### PR TITLE
Add detect.py --hide-conf --hide-labels --line-thickness options

### PR DESCRIPTION
**Pull request by Ashafix**
Three minor changes

- command line argument for specifying line thickness of bounding boxes, if not set defaults to 3 (the previous value)
- option to hide class labels (defaults to False)
- option to hide confidence values (defaults to False)

If none of the new parameters are set, nothing changes.

**Use case**
I have small images where only one class is detected. The labels and bounding boxes occlude most of the image making it hard to visually evaluate the results.
See also #2550

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced customization for object detection visual outputs in YOLOv5.

### 📊 Key Changes
- Added flexibility to hide labels and confidences on detection outputs.
- Introduced argument to adjust bounding box line thickness.

### 🎯 Purpose & Impact
- **Purpose**: Allows users to control how detection results are visualized, making it easier to produce cleaner images for presentations or to respect privacy constraints.
- **Impact**: Users gain finer control over the visualization aspect of object detection, possibly improving the user experience for both developers presenting results and end users consuming those results. 🎨

### CODE REVIEW

**Comment by zxsitu** [comment]
@Ashafix Can you add one more option: show only the prediction labels and do not show the predicted values?

**Comment by Ashafix** [comment]
@ilem777 : good idea! done

**Comment by zxsitu** [comment]
@Ashafix Many thanks, it's convenient that we don't have to modify the code statements in the main program.

**Comment by glenn-jocher** [comment]
@Ashafix not a bad idea. I've cleaned it up a bit to reduce code. 

Thank you for your contributions to YOLOv5 🚀!

**Comment by glenn-jocher** [comment]
@Ashafix @ilem777 results are below. This reminds me, we need to migrate detect.py to the standard color_list() in plots.py.

## default
```
python detect.py
```
zidane


## --hide-conf
```
python detect.py --hide-conf
```
zidane


## --hide-labels
```
python detect.py --hide-labels
```
zidane

**Pull request merged**
