### PR TITLE
`np.fromfile()` Chinese image paths fix

### PR DESCRIPTION
**Pull request by yeshanliu**
use "cv2.imdecode(np.fromfile(f, np.uint8), cv2.IMREAD_COLOR)" instead of "cv2.imread(f)" for Chinese image path.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced compatibility for non-ASCII filenames in YOLOv5.

### 📊 Key Changes
- Remapped `cv2.imread` function to handle Chinese characters in filenames using `cv2.imdecode` and `np.fromfile` across different modules.

### 🎯 Purpose & Impact
- **Purpose:** The purpose of this change is to ensure that images with filenames containing non-ASCII characters, particularly Chinese characters, can be properly loaded for processing without errors.
- **Impact:** Users working with datasets containing images with Chinese or other non-ASCII characters in their filenames will benefit from improved functionality, as YOLOv5 will now be able to handle these files seamlessly. This enhancement promotes broader usability of YOLOv5 across different languages and regions. 🌏🤖

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@yeshanliu thanks for the PR! This has been proposed previously but rejected because of the speed impacts of applying this to every image. Maybe a hybrid approach would be best, where we analyze each filename string and then apply this PR loader only when required. 

Can you please share an example Chinese font image file that the current dataloader is not working correctly on?

**Comment by yeshanliu** [comment]
> @yeshanliu thanks for the PR! This has been proposed previously but rejected because of the speed impacts of applying this to every image. Maybe a hybrid approach would be best, where we analyze each filename string and then apply this PR loader only when required.
> 
> Can you please share an example Chinese font image file that the current dataloader is not working correctly on?

Sorry for this  proposed PR.  There are few images with Chinese names in my dataset，such as '巴士.jpg' instead of 'bus.jpg', and these images were corruput when loading. Maybe you are right about using hybrid approach. But I test with each method for 1000 times, it seems like 'cv2.imdecode()' is not slower than 'cv2.imread()' and even faster (0.01684 VS 0.01706).

**Comment by CCRcmcpe** [comment]
You should change `imread()` in `utils\loggers\__init__.py` too, or paths with unicode characters will still mess up wandb functions.

**Comment by CCRcmcpe** [comment]
@glenn-jocher There's no impact at all. Actually `imdecode` is a little bit faster.
```py
import time
import cv2
import numpy as np

start_time = time.time()
for i in range(1, 100):
    cv2.imread('sample.jpg', cv2.IMREAD_COLOR)
print((time.time() - start_time) / 100, "second")

start_time = time.time()
for i in range(1, 100):
    cv2.imdecode(np.fromfile('sample.jpg', np.uint8), cv2.IMREAD_COLOR)
print((time.time() - start_time) / 100, "second")
```
`sample.jpg : JPEG 8192x8192 8-bit sRGB 11.077MiB`
Shows me:
```
0.8286143565177917 second
0.827539222240448 second
```
Such a hybrid approach is not needed.

**Comment by glenn-jocher** [comment]
@CCRcmcpe yes it looks like you are right, there's no speed impact. I get similar results:

```python
import time
import cv2
import numpy as np

start_time = time.time()
for i in range(1, 1000):
    cv2.imread('data/images/bus.jpg', cv2.IMREAD_COLOR)
print((time.time() - start_time) / 1000, "second")

start_time = time.time()
for i in range(1, 1000):
    cv2.imdecode(np.fromfile('data/images/bus.jpg', np.uint8), cv2.IMREAD_COLOR)
print((time.time() - start_time) / 1000, "second")

# 0.009527110815048218 second
# 0.009436187267303466 second
```

**Comment by glenn-jocher** [comment]
@CCRcmcpe @yeshanliu speed results look good. I propose instead of the existing implementation though we simply remap cv2.imread after importing cv2, i.e.:

```python
import cv2

cv2.imread = lambda x: cv2.imdecode(np.fromfile(x, np.uint8), cv2.IMREAD_COLOR)
```

Seems to be just as fast:

```
import time
import cv2
cv2.imread2 = lambda x: cv2.imdecode(np.fromfile(x, np.uint8), cv2.IMREAD_COLOR)
import numpy as np
start_time = time.time()
for i in range(1, 1000):
    cv2.imread('data/images/zidane.jpg', cv2.IMREAD_COLOR)
print((time.time() - start_time) / 1000, "second")
start_time = time.time()
for i in range(1, 1000):
    cv2.imread2('data/images/zidane.jpg')
print((time.time() - start_time) / 1000, "second")

0.006971234798431396 second
0.006953163146972656 second
```

**Comment by glenn-jocher** [comment]
Passes test:

```python
import numpy as np

np.allclose(cv2.imread('data/images/zidane.jpg'), cv2.imread2('data/images/zidane.jpg'))
```

**Comment by CCRcmcpe** [comment]
> You should change `imread()` in `utils\loggers\__init__.py` too, or paths with unicode characters will still mess up wandb functions.

@glenn-jocher I don't have the permission to do that, you may consider change that file too.

**Comment by glenn-jocher** [comment]
@CCRcmcpe changed in utils\loggers\__init__.py also now.

**Review by glenn-jocher — APPROVED** [review]

**Comment by yeshanliu** [comment]
> @CCRcmcpe @yeshanliu speed results look good. I propose instead of the existing implementation though we simply remap cv2.imread after importing cv2, i.e.:
> 
> ```python
> import cv2
> 
> cv2.imread = lambda x: cv2.imdecode(np.fromfile(x, np.uint8), cv2.IMREAD_COLOR)
> ```
> 
> Seems to be just as fast:
> 
> ```
> import time
> import cv2
> cv2.imread2 = lambda x: cv2.imdecode(np.fromfile(x, np.uint8), cv2.IMREAD_COLOR)
> import numpy as np
> start_time = time.time()
> for i in range(1, 1000):
>     cv2.imread('data/images/zidane.jpg', cv2.IMREAD_COLOR)
> print((time.time() - start_time) / 1000, "second")
> start_time = time.time()
> for i in range(1, 1000):
>     cv2.imread2('data/images/zidane.jpg')
> print((time.time() - start_time) / 1000, "second")
> 
> 0.006971234798431396 second
> 0.006953163146972656 second
> ```



> @CCRcmcpe @yeshanliu speed results look good. I propose instead of the existing implementation though we simply remap cv2.imread after importing cv2, i.e.:
> 
> ```python
> import cv2
> 
> cv2.imread = lambda x: cv2.imdecode(np.fromfile(x, np.uint8), cv2.IMREAD_COLOR)
> ```
> 
> Seems to be just as fast:
> 
> ```
> import time
> import cv2
> cv2.imread2 = lambda x: cv2.imdecode(np.fromfile(x, np.uint8), cv2.IMREAD_COLOR)
> import numpy as np
> start_time = time.time()
> for i in range(1, 1000):
>     cv2.imread('data/images/zidane.jpg', cv2.IMREAD_COLOR)
> print((time.time() - start_time) / 1000, "second")
> start_time = time.time()
> for i in range(1, 1000):
>     cv2.imread2('data/images/zidane.jpg')
> print((time.time() - start_time) / 1000, "second")
> 
> 0.006971234798431396 second
> 0.006953163146972656 second
> ```

**Comment by CCRcmcpe** [comment]
@yeshanliu What? Why you even close it? 如果你关闭了这个PR那就没法合并了

**Comment by yeshanliu** [comment]
> @yeshanliu What? Why you even close it? 如果你关闭了这个PR那就没法合并了

Just by accident...

**Comment by CCRcmcpe** [comment]
🤣

**Comment by glenn-jocher** [comment]
> > @yeshanliu What? Why you even close it? 如果你关闭了这个PR那就没法合并了
> 
> Just by accident...

haha. I think this is all good to go now.

**Comment by glenn-jocher** [comment]
@yeshanliu @CCRcmcpe PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

Final test results here:
```python
import time
import cv2
import numpy as np

cv2.imread2 = lambda x: cv2.imdecode(np.fromfile(x, np.uint8), cv2.IMREAD_COLOR)

im = 'data/images/zidane.jpg'
print(np.allclose(cv2.imread(im), cv2.imread2(im)))

start_time = time.time()
for i in range(1, 1000):
    cv2.imread(im)
print((time.time() - start_time) / 1000, "second")

start_time = time.time()
for i in range(1, 1000):
    cv2.imread2(im)
print((time.time() - start_time) / 1000, "second")

# True
# 0.01213301420211792 second
# 0.011982528448104858 second
```

**Pull request merged**
