### PR TITLE
Support extensive shape for functions related to bounding box localization

### PR DESCRIPTION
**Pull request by developer0hye**
This PR will make us play with bounding boxes more easily.

Signed-off-by: Yonghye Kwon <developer.0hye@gmail.com>

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of bounding box coordinate transformations to support higher dimensional tensors.

### 📊 Key Changes
- Implemented the use of ellipsis (`...`) in array indexing for box conversion functions (e.g., `xyxy2xywh`, `xywh2xyxy`, etc.), which allows these functions to operate on inputs with arbitrary number of dimensions.
- The changes apply to both PyTorch tensor and NumPy array operations, maintaining functionality across different object types.
- Adjusted `clip_boxes` function to support clipping for higher-dimensional tensors utilizing the same ellipsis indexing pattern.

### 🎯 Purpose & Impact
- **Flexibility**: The modifications introduce flexibility in handling bounding boxes, enabling batch processing and multi-dimensional data, leading to cleaner code when dealing with datasets that contain multiple images or annotations.
- **Performance**: Batch operations can improve performance, allowing more efficient computations when processing images or video sequences in a machine learning context, specifically within object detection tasks.
- **Consistency**: All related functions now follow the same indexing pattern, increasing the maintainability of the codebase.
- **Impact**: This will be particularly beneficial for users and developers working on applications involving a high volume of data, such as video analysis or large-scale image processing, ultimately enhancing the YOLOv5's usability in complex machine learning pipelines. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@developer0hye PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by developer0hye** [comment]
@glenn-jocher 

Hi Jocher!
Is there way to talk with you on a messenger?

**Comment by glenn-jocher** [comment]
@developer0hye yes, you can message me on LinkedIn at https://www.linkedin.com/in/glenn-jocher/ or WhatsApp at +13012376695

**Comment by developer0hye** [comment]
@glenn-jocher Okay, thanks!

**Comment by glenn-jocher** [comment]
@developer0hye you're welcome! If you have any more questions or need assistance, feel free to ask here on GitHub. We're always happy to help 😊

**Pull request merged**
