### PR TITLE
Fix Chinese README

### PR DESCRIPTION
**Pull request by Nioolek**
Hello, `YOLOv5` has been very popular among Chinese users. However, I found some incomprehensible and mistranslated points in the Chinese document. I will refine this document as much as possible.

I haven't finished all the work yet. Please do not merge this PR.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update to translation workflow and enhancements in YOLOv5 documentation and segmentation models.

### 📊 Key Changes
- Translation workflow now triggers on pushes to `translate_readme` branch rather than `main` or `master`.
- Updated video link in README files to a new tutorial or demo video.
- Enhanced segmentation model details with the inclusion of `YOLOv5m-seg` and `YOLOv5l-seg` models.
- Various sections in the README have been tidied up, including Inference, Install, Training, and Tutorials.

### 🎯 Purpose & Impact
- 🚀 The workflow change allows for controlled translation updates, likely for testing.
- 📹 Providing current video content improves user experience and aids in understanding YOLOv5 usage.
- 💡 Additional segmentation model details offer users more options and information for their computer vision tasks.
- 📚 Improved documentation structure enhances readability and user navigation, facilitating a smoother onboarding experience for new users.

### CODE REVIEW

**Comment by AyushExel** [comment]
@Nioolek thanks for helping out on this.

**Comment by Nioolek** [comment]
> @Nioolek thanks for helping out on this.

Hello, I have finished modifying the document. You can review this PR.

**Comment by glenn-jocher** [comment]
@Nioolek thanks! 

@Laughing-q could you take a look and let me know if this is good to merge? Thanks!

**Comment by Laughing-q** [comment]
@Nioolek 
`Ultralytics Live Session Ep。 2 将在 欧洲中部时间 12 月 13 日星期二的 19:00 ，通过 Joseph Nelson 的 Roboflow 直播` 这里应该改成`Ultralytics Live Session EP. 2将与Roboflow的Joseph Nelson在欧洲中部时间12月13日星期二的19:00直播`
Thanks!

@glenn-jocher generally look good! expect there's a tiny issue in the live info part which I point above. It's ready to merge after this part fixed.

**Comment by Nioolek** [comment]
> 与Roboflow的Joseph Nel

@glenn-jocher @Laughing-q
Hello, I have fixed thie part.

**Comment by Laughing-q** [comment]
@Nioolek thanks!
then it's ready to merge. :) @glenn-jocher

**Comment by glenn-jocher** [comment]
@Nioolek @Laughing-q PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
