### PR TITLE
Replace `openvino-dev` with OpenVINO Runtime inference

### PR DESCRIPTION
**Pull request by GabrielDornelles**
One of OpenVINO use cases is to run it on Raspberry devices. I'm proposing to make the inference using openvino.runtime, which is installable at raspberry and is available at latest openvino package (tested with openvino==2022.1.0).

The previous inference using openvino-dev was not usable at devices where the dev package is not available.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved OpenVINO integration in YOLOv5's model loading and inference.

### 📊 Key Changes
- Updated OpenVINO package requirement from `openvino-dev` to `openvino`.
- Switched to newer OpenVINO Python API usage with `Core` instead of `IECore`.
- Simplified OpenVINO network reading and compiling processes.
- Streamlined OpenVINO inference code to reduce verbosity and complexity.

### 🎯 Purpose & Impact
- **Purpose**: The update ensures compatibility with the latest OpenVINO version and takes advantage of the more user-friendly API.
- **Impact**: Users leveraging OpenVINO for model inference will experience a more straightforward setup with potentially enhanced stability and performance improvements. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@GabrielDornelles thanks for the PR! Is there a way to use the openvino package for export also instead of openvino-dev?

https://github.com/ultralytics/yolov5/blob/2b64b45cd8f05ae9499b19fe8e94677bb4ffb408/export.py#L171-L187

**Comment by GabrielDornelles** [comment]
> @GabrielDornelles thanks for the PR! Is there a way to use the openvino package for export also instead of openvino-dev?
> 
> https://github.com/ultralytics/yolov5/blob/2b64b45cd8f05ae9499b19fe8e94677bb4ffb408/export.py#L171-L187

I believe yes, I uninstalled dev package and the command works the same way in the non-dev package. The only thing is that it doesn't have a ``` __version__``` method, but it has a get_version that will display the following:

image

**Comment by glenn-jocher** [comment]
@GabrielDornelles looking at these two it seems that we still need openvino-dev for export:
https://pypi.org/project/openvino/
https://pypi.org/project/openvino-dev/

I'll take a closer look

**Comment by glenn-jocher** [comment]
@GabrielDornelles PR is merged. I validated PR and master exported OpenVINO models and saw same mAP. Also openvino-dev install provides for import openvino, so no changes needed by default for existing users.

Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
