### PR TITLE
Log hyperparameters in tensorboard

### PR DESCRIPTION
**Pull request by jancio**
Log both hyperparameters and command line options in tensorboard.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced TensorBoard logging with hyperparameter tracking in YOLOv5 training.

### 📊 Key Changes
- Added recording of hyperparameters to TensorBoard during the training process.

### 🎯 Purpose & Impact
- **Purpose:** To allow users to track and visualize the hyperparameters used during the model training in TensorBoard.
- **Impact:** Provides better experiment tracking and facilitates the comparison of different training runs, which can lead to more informed decisions and improvements in model performance. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@jancio good idea!

img-size is not height and width though, it is train and test sizes. Can you fix this?

**Comment by jancio** [comment]
Oh, ok, thanks for pointing this out. I will fix that.

**Comment by glenn-jocher** [comment]
@jancio the hyp to tensorboard update is having some strange effects. Each run is showing up on tensorboard twice. For example exp3 and exp4 are single runs below, but they show up with this additional garbage string folder in them when the hyps are added. I think I'm going to comment this out for now until there's a fix. Do you know why this is happening and what we can do to resolve?

Screen Shot 2020-07-15 at 10 35 29 AM

**Comment by jancio** [comment]
I have tried couple of things but didn’t help. Do you think it is a tensorboard issue?

**Comment by glenn-jocher** [comment]
@jancio yeah I think it's just a tensorboard issue, you might want to raise an issue on the pytorch or tensorboard repos. In any case the hyps are saved in the run directory as hyp.yaml.

**Pull request merged**
