### PR TITLE
Print hyperparameters to evolve yaml file correctly

### PR DESCRIPTION
**Pull request by iker-lluvia**
When training segmentation with evolve, the corresponding hyperparameters yaml file is created without considering the correct number of metrics. Thus the data is stored in the following way:
```
# YOLOv5 Hyperparameter Evolution Results
# Best generation: 1
# Last generation: 4
# metrics/precision(B),    metrics/recall(B),   metrics/mAP_0.5(B), metrics/mAP_0.5:0.95(B), metrics/precision(M),    metrics/recall(M),   metrics/mAP_0.5(M)
#             0.063966,              0.44075,             0.055458,             0.012713,             0.030348,              0.22661,             0.019414

metrics/mAP_0.5:0.95(M): 0.003792
val/box_loss: 0.12199
val/obj_loss: 0.15555
val/cls_loss: 0.63032
val/seg_loss: 0.0
lr0: 0.00935
lrf: 0.01246
...
```

This PR fixes this error, storing the data in the following format:
```
# YOLOv5 Hyperparameter Evolution Results
# Best generation: 1
# Last generation: 1
# metrics/precision(B),    metrics/recall(B),   metrics/mAP_0.5(B), metrics/mAP_0.5:0.95(B)
#             0.066667,              0.54054,             0.062136,             0.014717
# metrics/precision(M),    metrics/recall(M),   metrics/mAP_0.5(M), metrics/mAP_0.5:0.95(M)
#             0.035128,              0.28482,             0.024308,            0.0048832
#         val/box_loss,         val/obj_loss,         val/cls_loss,         val/seg_loss
#              0.11127,              0.13789,              0.59428,                    0

lr0: 0.01
lrf: 0.01021
...
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to YOLOv5's segmentation and hyperparameter evolution logging.

### 📊 Key Changes
- Removed `print_mutation` from `segment/train.py` and added it to `utils/segment/general.py`.
- Introduced a new `LOGGING_NAME` variable and emoji compatible logging for Windows.
- `print_mutation` function expanded with additional features for evolution results handling.
- Evolve results now save to both CSV and YAML formats, supporting better data management and readability.

### 🎯 Purpose & Impact
- 🚀 By shifting `print_mutation`, segmentation training code gets cleaner, promoting better codebase maintenance.
- 💻 Windows users will now see emoji-safe messages for an enhanced user experience.
- 📈 Enhanced evolution results logging provides a more comprehensive overview of model performance over generations, helping users to better track and understand hyperparameter evolution outcomes.
- 🗂️ The dual-format saving of evolve results in both CSV and YAML formats offers versatility in data analysis and sharing, potentially benefiting users who perform many evolutions to fine-tune their models.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@iker-lluvia thanks for the PR, but something doesn't seem right here. You're duplicating code that already exists within YOLOv5 into other parts of the repo, why not just import these functions where you need them?

**Comment by iker-lluvia** [comment]
> @iker-lluvia thanks for the PR, but something doesn't seem right here. You're duplicating code that already exists within YOLOv5 into other parts of the repo, why not just import these functions where you need them?

You are right, sorry. I copied those functions as well because I expected to make modifications to them as well, but in the end I did not.

338c0c03e65415b1f74431f93f0f556bb4f5217e still corrects the problem presented above, but it does not duplicate _set_logging_ and _colorstr_ functions.

_print_mutation_ is duplicated as the general implementation has values corresponding to the number of keys hard coded, and this number is different for segmentation.

**Comment by iker-lluvia** [comment]
@glenn-jocher is another modification needed for merging? If so, please, let me know and I'll try to add it. Thanks.

**Comment by glenn-jocher** [comment]
@iker-lluvia you're already on the right track, and I appreciate your diligence in addressing this. The current modification looks good to me. Thanks for your efforts!

**Pull request closed without merging**
