### PR TITLE
Classification Tutorial Notebook

### LINKED ISSUE #8999: Do we need a tutorial notebook for classification?
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
As we add more tasks, we will need to provide executable examples for each. Adding these tasks in the main detection colab will make it too long. My suggestion is that we add a `tutorial.ipynb` inside `classify/`. This way we can provide a dedicated classification tutorial without messing with the existing files.

What do folks think? 

### Additional

_No response_

### PR DESCRIPTION
**Pull request by paulguerrie**
Added a tutorial notebook for classification. Closes #8999 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Tutorial on how to use YOLOv5 for image classification tasks.

### 📊 Key Changes
- Added a new Jupyter notebook tutorial for image classification using YOLOv5.
- Detailed guidance on how to perform inference with pre-trained ImageNet models using YOLOv5.
- Instructions on how to train YOLOv5 on custom datasets using the Roboflow service for dataset preparation.
- Explanation on how to validate the performance of the trained model on the ImageNet or custom dataset.
- Provided methods to improve model performance using active learning by programmatically uploading failure cases back to Roboflow for retraining.
- Demonstrated various input methods for prediction using YOLOv5, such as webcam, images, videos, directories, and online sources like YouTube.

### 🎯 Purpose & Impact
- **Educational Resource**: The tutorial aims to serve as a comprehensive guide for users who wish to apply YOLOv5 to classification tasks, which could attract more users to the project by showcasing its versatility beyond object detection.
- **Ease of Use**: By providing easy-to-follow instructions for using out-of-the-box models and training custom models, the tutorial lowers the entry barriers for new users and researchers.
- **Model Improvement**: Active learning instructions can lead to improved model performance over time, benefiting users looking for more accurate classification in their applications.
- **Versatility**: The various input methods for prediction show the adaptability of YOLOv5 for a range of use cases, potentially increasing the user base.

By simplifying the use of YOLOv5 for classification tasks, this PR could greatly assist those working on image classification projects and foster a larger, more engaged user community. 🚀✨

### CODE REVIEW

**Comment by paulguerrie** [comment]
Hey @AyushExel! We put the finishing touches on the notebook today. Anything else we need to do before this PR can be merged?

**Comment by AyushExel** [comment]
@paulguerrie hey, there's probably one more change that we'll make in the classifier - we might add support for webcam and video and show result in realtime with labels inside frames. We'll discuss that today and once that is done, we'll finalize this colab

**Comment by paulguerrie** [comment]
Hey @AyushExel , Just wanted to let you know we added a section at the end of the tutorial to point out the various methods of input that `classify/predict.py` accepts (including some working examples for directories and a youtube video). Let me know if you think the notebook needs anything else, happy to edit.

**Comment by AyushExel** [comment]
@paulguerrie thanks! We're too busy before the yolo-vision event. Will prioritize this after that.

**Comment by paulguerrie** [comment]
Hey @AyushExel Congrats on a great YOLO Vision Conference! Let me know if there's anything else needed on this (or the segmentation tutorial) PR.

**Comment by glenn-jocher** [comment]
@paulguerrie hi! Could you update this classification notebook PR like you did with the segmentation PR? That one looks great I think. Thanks!

**Comment by glenn-jocher** [comment]
@paulguerrie closing as we now have a classification notebook. Thank you for your contributions!

**Pull request closed without merging**
