### PR TITLE
Add GradCAM integration - Make YOLOv5 Interpretable

### PR DESCRIPTION
**Pull request by pourmand1376**
## Why this PR?
This PR will adapt `GradCAM` library to `YOLOv5`. This is required since black box models are not always acceptable. We need to know why a certain prediction was made. This is completely different from `feature visualization` which is already implemented. This explains the model results on a per image basis. For example, we want to know why the model has detected this Person. What pixels are mostly responsible for this prediction? This will result in a heatmap like this. 

EigenCAM layer -2:
image

EigenCAM layer -3:
image

## Current State
Currently, I've implemented EigenCAM and it works perfectly. Still, I have to write documentation to understand how it works. 

## Related Issues and Links
This is a long-requested feature. 
YOLOv5 Related issues: 
- #8717 
- #5863 
- #4575 
- #2065
- #5863

Related Issues in other repositories:
- https://github.com/jacobgil/pytorch-grad-cam/issues/364
- https://github.com/jacobgil/pytorch-grad-cam/issues/359
- https://github.com/jacobgil/pytorch-grad-cam/issues/242

Useful Links:
- https://github.com/pooya-mohammadi/yolov5-gradcam: This one is actually fine but it is too old. Also, It doesn't add this functionality to YOLO in a way that it works with later versions. It implements YOLO from scratch. 
- [Tutorial: Class Activation Maps for Object Detection with Faster RCNN — Advanced AI explainability with pytorch-gradcam](https://jacobgil.github.io/pytorch-gradcam-book/Class%20Activation%20Maps%20for%20Object%20Detection%20With%20Faster%20RCNN.html)
- [EigenCAM for YOLO5 — Advanced AI explainability with pytorch-gradcam](https://jacobgil.github.io/pytorch-gradcam-book/EigenCAM%20for%20YOLO5.html)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

**WARNING ⚠️** this PR is very large, summary may not cover all changes.

### 🌟 Summary
This PR introduces new Makefile options and Jupyter notebook improvements for interpretability demos.

### 📊 Key Changes
- Added `run_interpretability` and `run_interpretability_old` commands to Makefile for running interpretability scripts.
- Included a demo Jupyter notebook with detailed code execution steps and outputs for interpretability methods.
- Updated `.pre-commit-config.yaml` to exclude the demo notebook from the codespell check.

### 🎯 Purpose & Impact
- Provides users with Makefile shortcuts for executing interpretability code, streamlining the process.
- Offers a clear, demonstrable notebook that guides users through using GradCAM and other interpretability tools in a practical setting.
- Enhances code quality by bypassing irrelevant spell checks on a demonstration notebook without affecting the rest of the codebase.

### CODE REVIEW

**Comment by pourmand1376** [comment]
This feature is now complete. I have also written a blog post for it. 

https://amirpourmand.ir/posts/2023/yolov5-interpretability-gradcam/

I'm eager to see your comments and suggestion if there is any. @glenn-jocher

**Comment by glenn-jocher** [comment]
@pourmand1376 great job on implementing this feature and writing the blog post! It's always helpful to have more interpretability tools for deep learning models, and your implementation of EigenCAM for YOLOv5 looks promising. I appreciate the effort you put into providing documentation and links for reference. Overall, it looks like a very useful addition to YOLOv5. Nice work!

**Comment by Fyw1988** [comment]
Hello, is this function successfully implemented now? Does it still apply to my own modified YOLOv5 network?

**Comment by pourmand1376** [comment]
> Hello, is this function successfully implemented now? Does it still apply to my own modified YOLOv5 network?

Yes. It is final on my side. 

Just copy the `explain/explainer.py' into your own repository and use it as explained in the blog. 

My implementation doesn't depend on any specific architecture. So, if you have architectural (or loss) changes, it would work properly. 

But if you change input output structure of YOLO, it won't work.

**Comment by glenn-jocher** [comment]
@Fyw1988 thank you for the confirmation that the function is successfully implemented and can be applied to modified YOLOv5 networks. I appreciate the advice on copying the `explainer.py` file and the information that architectural or loss changes should not affect the implementation. Thank you for your work on this feature!

**Comment by engrjav** [comment]
Well thanks for the great work

I have tried implementing your way however i get the error "TypeError: run() got an unexpected keyword argument 'iou_thres'"
can you please guide

**Comment by glenn-jocher** [comment]
@engrjav thank you for using our YOLOv5 repository and for your positive feedback! I'm sorry to hear that you're encountering an unexpected error. 

From the error message you provided, it seems that the `run()` function is being called with an unexpected keyword argument of `iou_thres`. Can you please confirm which version of the code you're using and provide more information about how you're calling the `run()` function?  It could be that `iou_thres` was not defined in the `run()` function in the version you're using. 

If you're still encountering the issue after checking the code version and how you're calling the function, please provide more details such as the complete error stack trace and any relevant code snippets so we can further investigate the issue and support you in finding a solution.

**Comment by pourmand1376** [comment]
> Well thanks for the great work
> 
> I have tried implementing your way however i get the error "TypeError: run() got an unexpected keyword argument 'iou_thres'" can you please guide

Currently, `iou_thres` is not supported by my function. I will add it in case anyone needs it.

**Comment by engrjav** [comment]
@glenn-jocher  thank you for responding and guiding me. I have tried using the explianer.py with the version of yolov5 downloaded today , made changes in detect.py and ran explainer. py  with the command stated in blog post and code i.e  python explainer.py --source data/images/bus.jpg --verbose but still get the error.

Traceback (most recent call last):
  File "D:\JCodeExp\yolov5-masterapril23\yolov5-master\explainer.py", line 399, in <module>
    main(opt)
  File "D:\JCodeExp\yolov5-masterapril23\yolov5-master\explainer.py", line 394, in main
    run(**vars(opt))
TypeError: run() got an unexpected keyword argument 'iou_thres'


@pourmand1376  thanks for the work. I am currently following your blog.  I have stated the error above. I would appreciate your input

**Comment by pourmand1376** [comment]
@engrjav 

Thanks for pointing out the issue. The issue is now fixed. The commandline version of my command was not matched well with the function version. 

You can use it like this:
```
!python explainer.py --source data/images/bus.jpg --verbose
```
and it will save the result in `explainer/output.jpg`. 

I hope it helps.

**Comment by glenn-jocher** [comment]
@pourmand1376, thanks for bringing this error to our attention. We apologize for any inconvenience this may have caused. 

As mentioned by @pourmand1376, the issue has been fixed, and you can use the following command to run the explainer:

```
!python explainer.py --source data/images/bus.jpg --verbose
```

This command will save the resulting image in `explainer/output.jpg`. Please let us know if you have any further questions or issues. We appreciate your interest in YOLOv5 and hope you find it helpful.

**Comment by engrjav** [comment]
Hey thanks @glenn-jocher  and @pourmand1376 

I have rerun the code using : python explainer.py --source data/images/bus.jpg --weights runs/yolov5s.pt --verbose

and now encountering this error

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape...
Traceback (most recent call last):
  File "D:\JCodeExp\YOLOv5\YOLOv5final\yolov5-masterapril23\explainer.py", line 405, in <module>
    main(opt)
  File "D:\JCodeExp\YOLOv5\YOLOv5final\yolov5-masterapril23\explainer.py", line 400, in main
    run(**vars(opt))
  File "D:\JCodeExp\YOLOv5\YOLOv5final\yolov5-masterapril23\explainer.py", line 362, in run
    cam_image = explain(method=method,
  File "D:\JCodeExp\YOLOv5\YOLOv5final\yolov5-masterapril23\explainer.py", line 273, in explain
    cam_image = extract_CAM(method_obj,
  File "D:\JCodeExp\YOLOv5\YOLOv5final\yolov5-masterapril23\explainer.py", line 224, in extract_CAM
    fixed_image = np.array(image[0]).transpose(1, 2, 0)
  File "C:\Users\Microwave Lab\.conda\envs\yolo\lib\site-packages\torch\_tensor.py", line 678, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Can you please confirm if this is some issue with my execution or a fix is required in explainer.py

**Comment by engrjav** [comment]
If i run in older version (downloaded on feb , 2022) and even list the names in coco128.yaml, sttill get this error 


 File "D:\JCodeExp\YOLOv5\YOLOv5final\yolov5\explainer.py", line 405, in <module>
    main(opt)
  File "D:\JCodeExp\YOLOv5\YOLOv5final\yolov5\explainer.py", line 400, in main
    run(**vars(opt))
  File "D:\JCodeExp\YOLOv5\YOLOv5final\yolov5\explainer.py", line 344, in run
    model_classes = {v: k for k, v in model.names.items()}
**AttributeError: 'list' object has no attribute 'items'**
(yolo)

**Comment by glenn-jocher** [comment]
@engrjav hello, it seems like you're encountering an issue with the `explainer.py` script while running it on an older version of YOLOv5 from February 2022. Specifically, you're getting an `AttributeError` related to its use of the `model.names` attribute. 

It's worth noting that the current version of the script is designed to work with the latest version of YOLOv5. It's possible that in the older version you're working with, the `model.names` attribute was different or not yet implemented, leading to this error. 

To get a better understanding of what's causing this error specifically, could you provide more information about how you're calling the script and what other changes you made in the older version of YOLOv5, if any? 

Alternatively, we highly recommend updating YOLOv5 to the latest version (which includes bug fixes and new features) and using the latest version of the `explainer.py` script to avoid any compatibility issues. Thank you.

**Comment by pourmand1376** [comment]
@engrjav 
Thanks for reporting.

You can see [this colab](https://colab.research.google.com/drive/13izqOOnt1Z9k77sPppgDxFsxqpbnKo5-) demo which is working very well.  
However, I have to investigate more for your issue. I think it could be solved by calling `.cpu()` for `image[0]`. Something like:

```
fixed_image = np.array(image[0].cpu()).transpose(1, 2, 0)
```
I will do an analysis about this problem soon.

**Comment by glenn-jocher** [comment]
Hello @pourmand1376,

Thank you for raising this issue related to the YOLOv5 explainer on GitHub.

In regards to your issue, it seems that calling `.cpu()` for `image[0]` could resolve the problem.  You can try something like this:

```
fixed_image = np.array(image[0].cpu()).transpose(1, 2, 0)
```

Alternatively, you can also try using the YOLOv5 explainer on the latest version of YOLOv5 which includes a bug fix for the issue you encountered.

I appreciate your patience as we work to resolve this issue. Feel free to reach out if you have any further questions or concerns.

Thanks and Have a great day!

**Comment by engrjav** [comment]
thank you @glenn-jocher and @pourmand1376 
I dealt with the error by using cpu only instead of cuda. Also used latest version of YOLOv5.

I get the results for "eigen cam' method using command 
python explainer.py --source data/images/selected/103.jpg --weights runs/proposed/best.pt --verbose --device cpu --imgsz 416 

However, upon using method 'eigengradcam', using

python explainer.py --source data/images/selected/103.jpg --weights runs/proposed/best.pt --verbose --device cpu --imgsz 416 --method EigenGradCAM


this error occurs
Fusing layers...
Model summary: 290 layers, 20974164 parameters, 0 gradients, 48.2 GFLOPs
Fusing layers...
Model summary: 290 layers, 20974164 parameters, 0 gradients, 48.2 GFLOPs
Adding AutoShape...
D:\JCodeExp\YOLOv5\YOLOv5final\yolov5-master11may\yolov5-master\explainer.py:222: RuntimeWarning: invalid value encountered in true_divide
  final_cam = final_cam / final_cam.max()

**Comment by glenn-jocher** [comment]
@engrjav thanks for your feedback on the YOLOv5 explainer. I'm glad to hear that you were able to resolve the previous issue. 

Regarding the new error you are encountering, the warning message you received suggests that division by zero or another invalid value may have occurred. This could happen if the CAM values that you are generating become too small or are NaN. Without more information, it's difficult to say exactly what could be causing this issue. 

To investigate further, I would suggest trying to run the `EigenGradCAM` method with some other images and see if the error persists. Additionally, you could try changing the hyperparameters of the method (such as the threshold or sigma values) to see if that affects the output in any way. 

Thank you for using YOLOv5 and the explainer, and please let us know if you have any further issues or questions.

**Comment by pourmand1376** [comment]
> thank you @glenn-jocher and @pourmand1376 I dealt with the error by using cpu only instead of cuda. Also used latest version of YOLOv5.
> 
> I get the results for "eigen cam' method using command python explainer.py --source data/images/selected/103.jpg --weights runs/proposed/best.pt --verbose --device cpu --imgsz 416
> 
> However, upon using method 'eigengradcam', using
> 
> python explainer.py --source data/images/selected/103.jpg --weights runs/proposed/best.pt --verbose --device cpu --imgsz 416 --method EigenGradCAM
> 
> this error occurs Fusing layers... Model summary: 290 layers, 20974164 parameters, 0 gradients, 48.2 GFLOPs Fusing layers... Model summary: 290 layers, 20974164 parameters, 0 gradients, 48.2 GFLOPs Adding AutoShape... D:\JCodeExp\YOLOv5\YOLOv5final\yolov5-master11may\yolov5-master\explainer.py:222: RuntimeWarning: invalid value encountered in true_divide final_cam = final_cam / final_cam.max()

This happens when final cam predictions are all zero. I could add a check here if it helps.

**Comment by pourmand1376** [comment]
Hi @AyushExel, What is your idea of all this? 

I think this can be easily added to YOLOv8 as well (with little modifications).

**Comment by glenn-jocher** [comment]
Hello @pourmand1376, 

Thank you for your comment on the YOLOv5 GitHub issue. It's great to hear that you're interested in adding this functionality to YOLOv8. The YOLOv5 team is always looking for ways to improve the model and its explainer, so any suggestions or contributions are welcome.

If you have any specific ideas or recommendations for implementing this feature in YOLOv8, please feel free to share them with the YOLOv8 team. They will greatly appreciate your input.

Thanks!

**Comment by AyushExel** [comment]
Well I haven't seen the entire thing but is this a generalized solution applicable to all models( n to x) and all model types( detect, segment etc) ?

**Comment by pourmand1376** [comment]
> Well I haven't seen the entire thing but is this a generalized solution applicable to all models( n to x) and all model types( detect, segment etc) ?

Yes, This is applicable to all model sizes and all architectures. Actually, I haven't tested all of them but it should work just fine. 

In regard to model types, I have just focused on detection. I think classification and segmentation models would be much easier to adapt. 

The problem with detection is NMS module which is inherently non-differentiable. I have written a blog post about it [here](https://amirpourmand.ir/posts/2023/yolov5-interpretability-gradcam/) and I explained how I adapted it to YOLO. 

I will add some more pictures for better understanding soon. But I think you will understand what I've done quite easily.

**Comment by glenn-jocher** [comment]
@pourmand1376 hello,

Thank you for your question regarding the applicability of the explainer to different model sizes and architectures. Yes, the explainer should be applicable to all model sizes and architectures, though we have primarily focused on detection models so far.

Regarding the different model types, we believe that classification and segmentation models would be easier to adapt than detection models. The main challenge with detection models is the non-differentiable nature of the NMS module. However, we have developed a solution to this problem specific to YOLO, which you can read about in this [blog post](https://amirpourmand.ir/posts/2023/yolov5-interpretability-gradcam/).

We hope this information is helpful. Please feel free to ask any additional questions you may have. Thank you for your interest in the YOLOv5 explainer.

**Comment by hlmhlr** [comment]
Hi @pourmand1376, your efforts towards making yolov5 interpretable are appreciable!! 
Can you please share your code that you used to implement EigenCAM with YOLOV5 which worked perfectly?
Many thanks in advance!

> ## Why this PR?
> 
> This PR will adapt `GradCAM` library to `YOLOv5`. This is required since black box models are not always acceptable. We need to know why a certain prediction was made. This is completely different from `feature visualization` which is already implemented. This explains the model results on a per image basis. For example, we want to know why the model has detected this Person. What pixels are mostly responsible for this prediction? This will result in a heatmap like this.
> 
> EigenCAM layer -2: image
> 
> EigenCAM layer -3: image
> ## Current State
> 
> Currently, I've implemented EigenCAM and it works perfectly. Still, I have to write documentation to understand how it works.
> ## Related Issues and Links
> 
> This is a long-requested feature. YOLOv5 Related issues:
> 
>     * [Visualize Features in Yolov5 #8717](https://github.com/ultralytics/yolov5/issues/8717)
> 
>     * [Grad-Cam for yolov5-5.0 #5863](https://github.com/ultralytics/yolov5/issues/5863)
> 
>     * [How would I call individual layers of the network? yolov5 #4575](https://github.com/ultralytics/yolov5/issues/4575)
> 
>     * [Interpreting model YoloV5 by Grad-cam #2065](https://github.com/ultralytics/yolov5/issues/2065)
> 
>     * [Grad-Cam for yolov5-5.0 #5863](https://github.com/ultralytics/yolov5/issues/5863)
> 
> 
> Related Issues in other repositories:
> 
>     * [Possibly inverted heatmaps for Score-CAM for YOLOv5 jacobgil/pytorch-grad-cam#364](https://github.com/jacobgil/pytorch-grad-cam/issues/364)
> 
>     * [[question] Support Grad-CAM in MMYOLO's yolov5 jacobgil/pytorch-grad-cam#359](https://github.com/jacobgil/pytorch-grad-cam/issues/359)
> 
>     * [YOLOv5 and ScoreCAM jacobgil/pytorch-grad-cam#242](https://github.com/jacobgil/pytorch-grad-cam/issues/242)
> 
> 
> Useful Links:
> 
>     * https://github.com/pooya-mohammadi/yolov5-gradcam: This one is actually fine but it is too old. Also, It doesn't add this functionality to YOLO in a way that it works with later versions. It implements YOLO from scratch.
> 
>     * [Tutorial: Class Activation Maps for Object Detection with Faster RCNN — Advanced AI explainability with pytorch-gradcam](https://jacobgil.github.io/pytorch-gradcam-book/Class%20Activation%20Maps%20for%20Object%20Detection%20With%20Faster%20RCNN.html)
> 
>     * [EigenCAM for YOLO5 — Advanced AI explainability with pytorch-gradcam](https://jacobgil.github.io/pytorch-gradcam-book/EigenCAM%20for%20YOLO5.html)

**Comment by glenn-jocher** [comment]
Hi @hlmhlr,

Thank you for your efforts in implementing EigenCAM with YOLOv5. We appreciate your dedication to making YOLOv5 interpretable. 

The community is looking forward to seeing the code you used to implement EigenCAM and its perfect functioning. It would be great if you could share the code with us. 

Your contribution will add value to YOLOv5 and help users understand the reasoning behind model predictions on a per-image basis. The heatmap examples you shared look promising and will greatly enhance interpretability.

We understand that you are still working on documenting the implementation. It would be helpful if you can complete the documentation to provide a better understanding of how EigenCAM works with YOLOv5.

Thank you once again for your efforts, and we look forward to your code contribution.

**Comment by pourmand1376** [comment]
Hi @hlmhlr,
Just use [this link](https://colab.research.google.com/github/pourmand1376/yolov5/blob/add_gradcam/explainer/demo.ipynb) and Change GradCAM to EigenCAM. It will work perfectly.

**Comment by glenn-jocher** [comment]
Hi @pourmand1376,

You can use [this link](https://colab.research.google.com/github/pourmand1376/yolov5/blob/add_gradcam/explainer/demo.ipynb) and simply change the GradCAM implementation to EigenCAM. This should allow you to use EigenCAM with YOLOv5 and achieve the desired results.

Please let me know if you have any further questions or need any additional assistance.

Best,

**Comment by hlmhlr** [comment]
Hi @glenn-jocher and @pourmand1376,  I gone through the code to the link that you shared, its working fine. Many thanks for your input.

Further, I have slightly modified the code of @pourmand1376 `explainer.py` from the [link](https://github.com/pourmand1376/yolov5/blob/add_gradcam/explainer/explainer.py) to make it more robust regarding Cam output visualization by taking the idea from this [link](https://jacobgil.github.io/pytorch-gradcam-book/EigenCAM%20for%20YOLO5.html). Mainly the following changes are made: 

- Concerning object detection,  removing heatmap data outside of the bounding boxes and scaling the heatmaps within each box.
- Drawing the bounding boxes for specific class(es) if mentioned via argument otherwise for all classes.
- Showcasing or hiding the class labels. For example, if there is aerial image with large number of objects, then visualizing the labels would resist to analyze the heatmaps optimistically.  Hiding might be preferable in that case. 
- Concatenating the images together (original image, cam image, cam image with boxes). 

I am attaching the snapshots below:

- With single class bus:





- With single class person:







- Both classes together





 

I believe, the changes are significant and beneficial to the YOLOv5 project as a whole, they should be integrated along with the pull request of @pourmand1376. Further, @glenn-jocher and @pourmand1376, please suggest how to proceed?

Many thanks and kind regards,

**Comment by pourmand1376** [comment]
Hi, The changes you made are interesting. It am flattered that someone continued what I've done. 

I think, maybe, it is better to sync these changes to YOLOv7 as YOLOv5 is not maintained anymore, I assume.

**Comment by hlmhlr** [comment]
> Hi, The changes you made are interesting. It am flattered that someone continued what I've done.
> 
> I think, maybe, it is better to sync these changes to YOLOv7 as YOLOv5 is not maintained anymore, I assume.

Dear @pourmand1376, 

I have created the pull request [here](https://github.com/ultralytics/yolov5/pull/11825) along with your contribution. You can check the details. 

Sure, we can do it for the YOLOv7, however, the maintenance of YOLOv5 and merging of the pull request in that may be confirmed by the @glenn-jocher.

**Comment by nyj-ocean** [comment]
@pourmand1376 
I use your code https://github.com/pourmand1376/yolov5/tree/add_gradcam
when the method=='`EigenCAM`', it can run no problem
but when the method=='`GradCAM`'  or  method=='`GradCAM++`' , it will meet the problem like following
```
Adding AutoShape...
unsupported operand type(s) for ** or pow(): 'NoneType' and 'int'
Traceback (most recent call last):
  File "explainer/explainer.py", line 491, in <module>
    main(opt)
  File "explainer/explainer.py", line 486, in main
    run(**vars(opt))
  File "explainer/explainer.py", line 432, in run
    cv2.imwrite(save_path, cam_image)
TypeError: Expected Ptr<cv::UMat> for argument 'img'
```

**Comment by glenn-jocher** [comment]
@nyj-ocean the error you encountered seems to be related to an unsupported operand type when using the `GradCAM` or `GradCAM++` method. Specifically, the error mentions an issue with the `cv2.imwrite` function. 

To investigate further, could you please provide more details about the input data and the specific steps you took when running the code? This will help us identify the root cause of the issue and provide a suitable solution.

In the meantime, please ensure that you have the necessary dependencies installed and that your input data is in the correct format for the `GradCAM` or `GradCAM++` method.

Looking forward to your response so that we can assist you further.

**Pull request closed without merging**
