### PR TITLE
Make it easier to do transfer learning by adding --freeze as an option

### PR DESCRIPTION
**Pull request by timstokman**
I've been doing some experiments with transfer learning. This small tweak makes it little easier to do transfer learning. It supports the most common use-case for freezing layers: freezing layers up to a point. It's still possible to manually edit the freeze array if more control is required over what exactly to freeze.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improving layer freezing options in YOLOv5 training.

### 📊 Key Changes
- `--freeze` argument added to `parse_opt()`, allowing users to specify the last layer number to freeze during training.
- Model parameter freezing logic updated in `train()` to handle the new `--freeze` option.
- Logging enhancement to display which model layers are being frozen or not during initialization.

### 🎯 Purpose & Impact
- **Purpose**: This change allows for more precise control over which layers of the model are frozen, which can be beneficial for transfer learning or fine-tuning models where certain layers' weights are desired to remain unchanged.
- **Impact**: Users now have the flexibility to easily freeze a specific range of layers by providing a layer number, potentially improving training times and preserving pre-trained feature detection capabilities in earlier layers. This can be especially useful when working with limited computational resources or wanting to maintain certain aspects of a pre-trained model.

### CODE REVIEW

**Review by Kubi94 — DISMISSED** [review]

**Comment by timstokman** [comment]
Had some merge conflicts, so I fixed those

**Comment by IneovaAI** [comment]
Hi please have a look at my implementation and tell me what you think. IneovaAI:patch-1 https://github.com/ultralytics/yolov5/pull/4238

**Comment by glenn-jocher** [comment]
@timstokman @IneovaAI closing this PR and merging `--freeze` PR #4238. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request closed without merging**
