### PR TITLE
W&B refactor, handle exceptions, CI example

### PR DESCRIPTION
**Pull request by AyushExel**
This PR:
* Adds exception handler when calling `wandb.log` as that is most likely to error out. We can expand the same to other parts based on feedback
* Adds some useful messages in place
* Attempts a CI test with a dummy wandb account only meant for CI

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced error handling and informative logging for W&B integration.

### 📊 Key Changes
- Commented out the direct W&B login command in CI configuration, highlighting a move towards a safer login practice.
- Added user guidance to install `wandb` for dataset logging in `create_dataset_artifact`.
- Improved the logging experience by replacing direct `print` statements with `LOGGER.info` throughout W&B utility functions for more consistent and informative messaging.
- Implemented error handling during logging to W&B to prevent training disruption and automatically finish the W&B run if errors occur.

### 🎯 Purpose & Impact
- 🔒 **Increased Security**: Obscuring sensitive W&B login details promotes better security practices.
- 🚀 **User Convenience**: By prompting users to install `wandb`, users are more informed about how to enable certain features.
- 📈 **Consistent Logging**: Integration of the LOGGER improves the consistency of how information is presented to users.
- 🛡️ **Robustness**: The added error handling ensures that training is not halted by logging issues, providing a more resilient training process for users.

### CODE REVIEW

**Comment by AyushExel** [comment]
@glenn-jocher can you have a look at this CI test solution. I've created a dummy wandb account and used its API key to log in to wandb from CI workflows. You can replace it with your own CI account if you want to. This is just a demonstration

**Comment by glenn-jocher** [comment]
@AyushExel thanks! Looks interesting. I'm going to try to figure out why pre-commit is failing.

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@AyushExel looks good, I've commented the CI to leave as an example for future work, probably in a separate, more in depth CI to come. Is this good to merge?

**Comment by AyushExel** [comment]
@glenn-jocher yes it's good to go for now. We've added a test on wandb side as well so we don't release any update which breaks yolov5. So, a similar test on yolov5's side should be all we need to be foolproof.

**Comment by glenn-jocher** [comment]
@AyushExel PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
