### PR TITLE
Add `timeout()` class

### PR DESCRIPTION
**Pull request by glenn-jocher**
@AyushExel @KalenMike @SkalskiP I'm adding a `timeout()` class to utils.general since we are dealing with wandb login-options timeout issues as well as `check_github()` timeout issues. Example usage:

### Python decorator usage:
```python
from time import sleep
from utils.general import timeout

@timeout(3)
def test_timeout():
    sleep(10)

test_timeout()
```

### Python context manager usage:
```python
from time import sleep
from utils.general import timeout

with timeout(3):
    sleep(10)
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing a new timeout feature and fixing a typo in utility functions.

### 📊 Key Changes
- Added `contextlib` and `signal` modules to support new functionality.
- Created a `timeout` class, which can be used both as a decorator and context manager to add time constraints for block execution.
- Fixed a typo from 'accesability' to 'accessibility' in the `check_online()` function.

### 🎯 Purpose & Impact
- 🛠 The new `timeout` class allows developers to set time limits on specific blocks of code, improving robustness by preventing processes from hanging indefinitely.
- 🐞 The typo correction in `check_online()` is minor but contributes to overall code quality.
- ⏱ For users, the timeout feature can enhance the user experience by preventing long waits and potential freezes, especially in network-dependent features.

### CODE REVIEW

**Comment by AyushExel** [comment]
@glenn-jocher Okay great I'll wrap the `wandb.init` calls in this context manager. Just one question though, let's say a new user chooses to signup to create a new account, how do we then decide the upper limit on the time the user takes to sign up and copy their API key?

**Comment by glenn-jocher** [comment]
@AyushExel I'm not sure, maybe 10 seconds. Perhaps you could put the timeout only on the 1, 2, 3 selection action and not on the API key paste action?

**Comment by glenn-jocher** [comment]
@AyushExel I think the intended effect is limited, only that the 1,2,3 selection defaults to 3 after 10 seconds. Everything else would ideally be the same.

**Comment by AyushExel** [comment]
@glenn-jocher I think this use case will need CLI modifications. I'll speak with the team about this today. 
Just to confirm, do you want this timeout across all environments or currently only intended for docker?

**Comment by glenn-jocher** [comment]
@AyushExel probably beneficial in all environments. i.e. CI tests can't run now either with `wandb` installed due to the same hang on 1,2,3.
https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml

**Comment by glenn-jocher** [comment]
@AyushExel though of course you'd want to add it to the function as an optional argument so it doesn't impact any other W&B workflows (for other integrations).

**Pull request merged**
