### PR TITLE
Edge TPU inference fix

### LINKED ISSUE #6684: EdgeTPU unassigned variable y running a detection
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Detection on _edgetpu_ model returns the following error:
`File "yolov5/models/common.py", line 449, in forward
    y[..., :4] *= [w, h, w, h]  # xywh normalized to pixels
UnboundLocalError: local variable 'y' referenced before assignment
`

I believe that the error from is caused by `self.tflite` not being set in the if/else branches in the forward method  when edgetpu is true (common.py line 438). That should be cause by `tflite &= not edgetpu  # *.tflite` in the `model_type` method.
```python3
@staticmethod
    def model_type(p='path/to/model.pt'):
        # Return model type from model path, i.e. path='path/to/model.onnx' -> type=onnx
        from export import export_formats
        suffixes = list(export_formats().Suffix) + ['.xml']  # export suffixes
        check_suffix(p, suffixes)  # checks
        p = Path(p).name  # eliminate trailing separators
        pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, xml2 = (s in p for s in suffixes)
        xml |= xml2  # *_openvino_model or *.xml
        tflite &= not edgetpu  # *.tflite
        return pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs
```
`tflite &= not edgetpu` sets `tflite` to true only if `tflite` is true and `edgetpu` is false, it is set to false otherwise.

### Environment

- OS: Ubuntu 20.04
-  Python 3.8.10

### Minimal Reproducible Example

I have exported the YoloV5s model to _edgetpu_ using:
`python export.py  --weights yolov5s.pt --include edgetpu --img 320 --data data/coco128.yaml`

Then run the detection with `python detect.py --weights yolov5s-int8_edgetpu.tflite --img 320 --data data/coco128.yaml`

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by RaffaeleGalliera**
Refers to #6684 

### Changes
- Remove `flite &= not edgetpu  # *.tflite` from `model_type` allowing tflite to be true when edgetpu is;
- Minor refactor using edgetpu flags and removing eventual `tflite or edgetpu` as if edgetpu is true also `tflite` should be following the current logic.

### BUG Report
Detection on _edgetpu_ model returns the following error:
`File "yolov5/models/common.py", line 449, in forward
    y[..., :4] *= [w, h, w, h]  # xywh normalized to pixels
UnboundLocalError: local variable 'y' referenced before assignment
`

I believe that the error from is caused by `self.tflite` not being set in the if/else branches in the forward method  when edgetpu is true (common.py line 438). That should be cause by `tflite &= not edgetpu  # *.tflite` in the `model_type` method.
```python3
@staticmethod
    def model_type(p='path/to/model.pt'):
        # Return model type from model path, i.e. path='path/to/model.onnx' -> type=onnx
        from export import export_formats
        suffixes = list(export_formats().Suffix) + ['.xml']  # export suffixes
        check_suffix(p, suffixes)  # checks
        p = Path(p).name  # eliminate trailing separators
        pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, xml2 = (s in p for s in suffixes)
        xml |= xml2  # *_openvino_model or *.xml
        tflite &= not edgetpu  # *.tflite
        return pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs
```
`tflite &= not edgetpu` sets `tflite` to true only if `tflite` is true and `edgetpu` is false, it is set to false otherwise.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved model compatibility and code clarity in YOLOv5's multi-backend inference support.

### 📊 Key Changes
- 🧹 Cleaned up comments listing supported model formats to reflect the actual code functionality more clearly.
- 🔍 Simplified TensorFlow GraphDef loading process with cleaner variable names and a more straightforward implementation.
- 🚫 Added an exception to explicitly state that TensorFlow.js (TF.js) inference is not supported.
- 🔄 Refined TensorFlow Lite and Edge TPU loading logic, with the inclusion of an Edge TPU-specific code path.

### 🎯 Purpose & Impact
- ⚙️ The reorganization and update of comments and code improve the readability and maintainability of the multi-backend inference system.
- 📈 By making the code more intuitive, developers can more easily understand the underlying mechanisms and potentially contribute improvements or fixes.
- 🤖 Users gain clearer information on which formats are compatible with YOLOv5, leading to less confusion and more efficient model deployment across various platforms.
- 🚀 These changes enhance the foundation for future expansions of supported backends and inference optimizations, ensuring the community benefits from a robust and versatile object detection model.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RaffaeleGalliera edge tpu export requires tflite export as a prerequisite. Otherwise this line will have nothing to work with:
https://github.com/RaffaeleGalliera/yolov5/blob/ad76f73b25bdd989a8d00d2b38de49b8145da365/export.py#L352

**Comment by glenn-jocher** [comment]
@RaffaeleGalliera PR fails simple export of Edge TPU models. Please verify export and inference on your PR.

Screenshot 2022-02-18 at 14 25 04

**Comment by RaffaeleGalliera** [comment]
@glenn-jocher Sorry,  I haven't realized that those flags were not referring to the same logic as in common.py and something went wrong while testing them :facepalm:  

I have removed the change in export.py and just tested export and inference for both edgetpu and tflite models, should be good now!

**Comment by glenn-jocher** [comment]
@RaffaeleGalliera thanks for the fixes! I agree with the L382 change (nice catch).

On L472 though, the desired effect for edgetpu models is that `tflite=False`, `edgetpu=True`. Is this correctly doing that?

**Comment by glenn-jocher** [comment]
@RaffaeleGalliera PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
