### PR TITLE
Use pathlib instead of low-level module

### PR DESCRIPTION
**Pull request by khiemdoan**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactor file I/O operations from `os` to `pathlib` for enhanced code simplicity and readability.

### 📊 Key Changes
- 🛠 Replaced `os.makedirs` with `Path.mkdir`, using the `pathlib` module for directory creation.
- 🔗 Changed file path concatenation to use `pathlib`'s `/` operator instead of `os.path.join`.
- ✂️ Removed `import os` statements, since `os` module functions are replaced by `pathlib`.
- 🌐 Ensured case-insensitive comparison for URL schemes (http/https) in `detect.py`.
- 📁 Used `.exists()` and `.isnumeric()` methods from `pathlib` for checking file existence and name formats.
- 🎨 Modified how project names are passed to WandB (from basename to stem) in `train.py`.

### 🎯 Purpose & Impact
- 📈 **Code Maintainability:** By using `pathlib`, the code is more Pythonic, readable, and maintainable.
- 🧑‍💻 **Developer Experience:** Simplifies the process of working with file paths for developers, making code contributions and understanding easier.
- 🚀 **Potential User Impact:** As these changes are internal code improvements, end-users will experience no direct impact, but may benefit indirectly from increased code reliability and future enhancements.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@khiemdoan thanks for the PR! I'm a fan of pathlib.Path() myself also actually :)

**Comment by glenn-jocher** [comment]
@khiemdoan PR is merged. Thank you for your contributions!

**Comment by carloslopezjoya** [comment]
@glenn-jocher thanks for your work. How to get bounding box coordinates in YOLO object detection and store them in variable?

**Comment by glenn-jocher** [comment]
@carloslopezjoya 

## Load YOLOv5 From PyTorch Hub

To load YOLOv5 from PyTorch Hub for inference with PIL, OpenCV, Numpy or PyTorch inputs:
```python
import cv2
import torch
from PIL import Image, ImageDraw

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True).fuse().eval()  # yolov5s.pt
model = model.autoshape()  # for autoshaping of PIL/cv2/np inputs and NMS

# Images
for f in ['zidane.jpg', 'bus.jpg']:  # download 2 images
    torch.hub.download_url_to_file('https://github.com/ultralytics/yolov5/releases/download/v1.0/' + f, f)
img1 = Image.open('zidane.jpg')  # PIL image
img2 = cv2.imread('bus.jpg')[:, :, ::-1]  # OpenCV image (BGR to RGB)
imgs = [img1, img2]  # batched list of images

# Inference
with torch.no_grad():
    prediction = model(imgs, size=640)  # includes NMS

print(prediction[0])  # print img1 predictions
#          x1 (pixels)  y1 (pixels)  x2 (pixels)  y2 (pixels)   confidence        class
# tensor([[7.47613e+02, 4.01168e+01, 1.14978e+03, 7.12016e+02, 8.71210e-01, 0.00000e+00],
#         [1.17464e+02, 1.96875e+02, 1.00145e+03, 7.11802e+02, 8.08795e-01, 0.00000e+00],
#         [4.23969e+02, 4.30401e+02, 5.16833e+02, 7.20000e+02, 7.77376e-01, 2.70000e+01],
#         [9.81310e+02, 3.10712e+02, 1.03111e+03, 4.19273e+02, 2.86850e-01, 2.70000e+01]])
```

To print/plot results:
```python
# Plot
for i, (img, pred) in enumerate(zip(imgs, prediction)):
    str = 'Image %g/%g: %gx%g ' % (i + 1, len(imgs), *img.shape[:2])
    img = Image.fromarray(img.astype(np.uint8)) if isinstance(img, np.ndarray) else img  # from np
    if pred is not None:
        for c in pred[:, -1].unique():
            n = (pred[:, -1] == c).sum()  # detections per class
            str += '%g %ss, ' % (n, model.names[int(c)])  # add to string
        for *box, conf, cls in pred:  # xyxy, confidence, class
            label = model.names[int(cls)] if hasattr(model, 'names') else 'class_%g' % cls
            # str += '%s %.2f, ' % (label, conf)  # label
            ImageDraw.Draw(img).rectangle(box, width=3)  # plot
    img.save('results%g.jpg' % i)  # save
    print(str + 'Done.')
```

**Comment by carloslopezjoya** [comment]
thanks for your answer, in my case I train the model with a single class, I use detection.py somehow I need to ram the coordinates of the objects in a variable to create a script and count the detected objects

**Comment by glenn-jocher** [comment]
@carloslopezjoya detect.py already counts objects. You might want to start with the notebook and review the tutorials:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
https://docs.ultralytics.com/yolov5

**Pull request merged**
