### PR TITLE
Edit comment for reshaping tensor in Detect Layer

### PR DESCRIPTION
**Pull request by developer0hye**
Edit comment for reshaping tensor in Detect Layer

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced code readability and maintainability in YOLOv5 model forward pass.

### 📊 Key Changes
- Split a complex line of code into two, separating a comment from the code logic.

### 🎯 Purpose & Impact
- **Purpose:** Improve code clarity without changing functionality.
- **Impact:** Makes the code easier to understand for developers, aiding future maintenance and development. No direct impact on end-users, as there is no change in model behavior or performance. 🛠️

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@developer0hye thanks for the PR, but this exceeds the 120 character line-length limit we have (PyCharm formatter).

**Comment by developer0hye** [comment]
@glenn-jocher 

I updated the position of the comment. How about this?

https://github.com/ultralytics/yolov5/blob/42fc32257a31a3e5587bdc795d0d3ce926999c20/models/yolo.py#L51-L55

**Comment by glenn-jocher** [comment]
@developer0hye sorry but this will add lines, which we want to avoid. I think in this case the current implementation may be the best compromise.

**Comment by developer0hye** [comment]
@glenn-jocher Yes! Thanks for your review!

**Pull request closed without merging**
