### PR TITLE
Prefer `tflite_runtime` for TFLite inference if installed

### PR DESCRIPTION
**Pull request by motokimura**
This PR imports the `tflite_runtime` package if `tensorflow` is not installed when running the .tflite model.
This is useful when running .tflite models on edge devices such as RPi, which have small disk space and cannot have large tensorflow library.

https://www.tensorflow.org/lite/guide/python?hl=en

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced TensorFlow Lite (TFLite) model loading with better package management and Edge TPU support.

### 📊 Key Changes
- Unified import statements for TensorFlow Lite (TFLite) to gracefully handle when `tflite_runtime` package is available.
- Simplified importing TFLite Edge TPU support with platform-specific dynamic loading of the appropriate delegate library.
- Cleaned up the code by removing redundant imports and comments.

### 🎯 Purpose & Impact
- 🚀 **Purpose**: The update aims to improve the compatibility with TensorFlow Lite on systems where `tflite_runtime` is installed, and streamline the process of running models on the Edge TPU.
- ⚙️ **Impact**: Users will experience a more reliable and flexible inference process for TFLite and Edge TPU models, potentially resulting in faster setup times and broader device support.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@motokimura the `tflite` variable name is already defined here as a boolean that indicates that the model is a TFLite model:
https://github.com/ultralytics/yolov5/blob/8efe97719c9b3b77c9db9b5c8592e051b7f0c9a7/models/common.py#L300

And all of the variables are assigned to `self` at the end of the init method, so `self.tflite` is already defined in the forward method and should not be redefined:
https://github.com/ultralytics/yolov5/blob/8efe97719c9b3b77c9db9b5c8592e051b7f0c9a7/models/common.py#L391

**Comment by motokimura** [comment]
@glenn-jocher thanks for the review. I've fixed it. Could you check again?

**Comment by glenn-jocher** [comment]
@motokimura I've moved the try except statement to apply to all TFLite inference and to prefer tflite_runtime if both are installed. 

PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
