### PR TITLE
Fix pylint: do not use bare 'except'

### PR DESCRIPTION
**Pull request by zhiqwang**
Hi @glenn-jocher , I'm fixing the lint in this PR, as `flake8` will raise

```bash
E722 do not use bare 'except'
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refinement of exception handling and cleanup in YOLOv5 codebase.

### 📊 Key Changes
- Specific exception handling using `except NameError` instead of a general exception clause.
- Removal of an unnecessary `import` statement from `train.py`.
- Enhancement in the `print_mutation` function for better readability in hyperparameter evolution results documentation.

### 🎯 Purpose & Impact
- 🛠️ **Better Error Handling**: Catching specific exceptions improves code reliability and maintainability, making it easier to debug issues.
- 🧹 **Code Cleanup**: Removing unused imports declutters the code, which may lead to slight performance improvements and better understanding for developers.
- ✏️ **Improved Documentation**: Formatting changes in `print_mutation` function result in cleaner and more professional representation of hyperparameter evolution results.
- 📦 **Overall**: These changes are likely to enhance the YOLOv5 experience for developers by making it more robust and user-friendly. Non-expert users benefit indirectly through a more stable and polished tool.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@zhiqwang thanks for the PR! Is this ready to review?

**Comment by zhiqwang** [comment]
> Is this ready to review?

Hi @glenn-jocher , Yep, is ready!

**Comment by glenn-jocher** [comment]
@zhiqwang ok I think some of these are good, but some may cause issues. Some of the Try except statements are really meant to handle a variety of possible errors. 

For example the cache try-except on datasets L412, multiple things could go wrong that are all currently handled by the bare try-except statement. 1) The file might not be found, the 2) file might just be corrupt and not load correctly, the asserts might fail if 3) the cache version is incorrect or 4) if the cache hash is different than the dataset hash. These are the known failure modes, but there may be other unknown failure modes that I'm not aware of right now. All of these failure modes (known and unknown) are intended to be caught by the existing bare try-except statement and trigger a new re-caching.

So while it might be nice to more explicitly create a tuple of errors above, it also makes the code more brittle and less robust  in practice since we are only including what we know might go wrong.

`thop` is another similar case. sometimes thop fails on certain models/environments, so the try except is not just in place to catch import errors but also any possible `thop` error, which is out of our control.

Let's do this. Can you remove all try-except updates except for the very simple cases where there is only 1 possible error to be caught: tf.py, yolo.py, general.py. Also please revert plots.py L311, as the y output is meant to be used on L312 to color the class histogram once the matplotlib issue is resolved. Thank you!

**Comment by zhiqwang** [comment]
Hi @glenn-jocher 

Thanks for the detailed explanation, and I have applied the changes you suggested.

**Comment by glenn-jocher** [comment]
@zhiqwang changes look good!

PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
