### PR TITLE
Handle input sources with multi-level child subfolders

### PR DESCRIPTION
**Pull request by DrSnowbird**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to YOLOv5 output directory structure and a test script for detection.

### 📊 Key Changes
- 👨‍💻 Modified the handling of output paths in `detect.py`, ensuring outputs are organized in `images` and `labels` subdirectories.
- 🌲 `detect.py` now respects the relative directory structure of the input source when saving outputs.
- 🏗️ Added `mkdir` commands to create necessary nested directories for saving images and labels.
- 🧪 Introduced `test-detect.py`, a simple script to perform model inference and print the results.
- 💾 Updated `utils/dataloaders.py` to properly load all files recursively when a directory is specified.

### 🎯 Purpose & Impact
- 📁 The changes to directory handling in `detect.py` allow for better organization of outputs, especially when dealing with nested input directories, enhancing usability for users with complex datasets.
- 🗂️ Maintaining the input's directory structure in outputs makes post-processing tasks like dataset analysis and file navigation more intuitive.
- ✨ The new `test-detect.py` script offers a straightforward way for users to test model inference, improving the initial user experience and providing a quick way to validate installations and models.
- ➕ Recursive file loading ensures that all images in nested folders are used for inference, eliminating the chance of missing data due to directory depth, which can be crucial for thorough dataset evaluation.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@DrSnowbird recursive subfolder inference is already available with glob commands, i.e.
https://stackoverflow.com/questions/2186525/how-to-use-glob-to-find-files-recursively

```
python detect.py --source 'path/**/*.jpg'
```

**Comment by glenn-jocher** [comment]
@DrSnowbird I noticed the README example lacked quotes so I fixed the glob examples in https://github.com/ultralytics/yolov5/pull/8927

**Comment by DrSnowbird** [comment]
[Thanks for comment](https://github.com/ultralytics/yolov5/pull/8924#issuecomment-1211186866)
The usage is for the example below so all the (including recursive children folders's) files (jpg, mp4, etc also non images will be scanned if process-able by yolov5). My users just did not like the "special requular expression setup since are are non-tech users since the burden is on them to know or setup up correctly". So, I tried to make it dumb-and-simple with whatever they provide (files, directory (plain OS dir name), or regex (if power users)) with the intelligence of processing leaving to the codes. I think we have different use casee (or design philosophy)! I though maybe yolov5 user community can benefit from my similar users' use cases. If not aligning with you guys' design principle, it's fine and I will continue to provide overwrite impelementations of you guys' upstream implementation using my forking github to shadow you guys' upstream. Thanks!

python detect.py --source './images'

**Comment by glenn-jocher** [comment]
@DrSnowbird the command for recursive inference for all images and videos is very simple. The dataloader automatically ignores any non-viable files.
```bash
python detect.py --source 'path/**/*'
```

**Comment by DrSnowbird** [comment]
@glenn-jocher - thanks for information.
I think we have two different kinds of users and design goals. As tech person, I know exactly what you said and glob ("**/*.*") does. But, I don't want train or require my users to specify or learn the syntax.
I will close the pull request since it is not aligning with each other goals design principles. 
thanks anyway.

**Comment by glenn-jocher** [comment]
Understood, @DrSnowbird! We appreciate your efforts and dedication to simplifying the user experience. The YOLOv5 community benefits greatly from diverse perspectives and contributions. If you have any further ideas or feedback, we're always open to discussion. Thank you for your understanding and support.

**Pull request closed without merging**
