### PR TITLE
build a classification network with a yaml file

### PR DESCRIPTION
**Pull request by yang-0201**
The previous question is #9734 
I have implemented a yaml file to build a classification network, using yolov5-cls.yaml as an example, and have implemented training.

I would like to use this function to get the pre-trained backbone network in the imagenet classification task and use it in the detection task by migration learning. The overhead is much smaller than retraining the coco detection network to get the whole pre-trained weights.

The code must have some small problems and need to be optimized, hope to make suggestions.

Thank you for considering my PR!
### Usage
`--cfg classify/models/yolov5l-cls.yaml`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Expansion of YOLOv5 classification capabilities with new model configuration and training script improvements.

### 📊 Key Changes
- Added a new model configuration file `yolov5l-cls.yaml` for a YOLOv5 large classification model.
- Updated `train.py` to allow building classification models from a YAML configuration file with `--cfg`.
- Enhanced `ClassificationModel` in `yolo.py` with the option to load from the YAML config and to visualize features during forward passes.
- Altered `parse_model` function to accommodate both detection and classification tasks by adding a `task` parameter.

### 🎯 Purpose & Impact
- Allows users to define and train classification models more flexibly using custom YAML configuration files, enhancing model customization. ⚙️
- The new feature visualization during the forward pass aids in understanding and debugging the model's feature extraction process. 🖼️
- Supports extending YOLOv5 beyond object detection to classification tasks, broadening the applications of the model. 🔍

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@yang-0201 thanks for the PR! Can you try to merge parse_model() with your new parse_model_class()? We don't want to duplicate code unless absolutely necessary, it increases maintenance and may lead to problems in the future.

**Comment by yang-0201** [comment]
@glenn-jocher Thanks for your reply and suggestion, I have modified this. I tried to build the code for the classification network by using the code in parse_model(), but I encountered some problems and would like to ask your opinion.

My current solution is to keep the information in the original yolov5 detection yaml file, but there are some redundant information such as anchor and the head module in the yaml file that cannot be removed, which makes the yolov5-cls.yaml file for building the classification network not elegant enough.

Or can I add a parameter to the parse_model() function to confirm whether I am building a detection model or a classification model, and then use the judgment to remove the redundant information.

**Comment by glenn-jocher** [comment]
@yang-0201 got it! I'd do with option 2. 

We run into this issue a lot, i.e. when we added segmentation we initially created a completely separate NMS function, but then added a few if-else statements to the current NMS function to allow it to handle both detection and segmentation. This is preferable as it reduces the amount of code that needs to be maintained and reduces duplication.

**Comment by glenn-jocher** [comment]
@yang-0201 That sounds like a solid approach! I'll take a look and let you know if I see any potential issues. Thanks for your continued work and dedication to improving the YOLOv5 repository!

**Pull request closed without merging**
