### PR TITLE
Add OpenVINO inference

### LINKED ISSUE #1193: Openvino Usage
## Additional context
I converted yolov5 to ONNX using export.py, then I cloned the OpenVINO toolkit and installed an inference engine. Then I got the IR files by using mo.py in the cloned OpenVINO toolkit. I managed to run the IR model somehow by using sample codes in OpenVINO. However, now I do not know how to decode the output of the model. Is the procedure the same as in samples of yolov3? Does someone have a script in c++? If yes, I would be more than happy for clues.

### LINKED ISSUE #5195: OpenVINO inference on ONNX model fail  (yolov5 6.0)
## ❔Question
I try to deploy the exported onnx model with openvino , but failed in ReadNetwork(). Is there any problem in exporting method or else?

### LINKED ISSUE #5533: Convert Yolov5 to IR Model in Openvino
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher et all,

Has anyone ever done the conversion of yolov5 models to IR models in openvino? maybe there is a tutorial i can learn? I want to try deploying yolov5 on Intel NCS2/VPU hardware devices.
thanks

### Additional

_No response_

### PR DESCRIPTION
**Pull request by glenn-jocher**
Add support for YOLOv5 Intel OpenVINO inference following https://github.com/ultralytics/yolov5/pull/6057 for OpenVINO export. Usage examples:

```python
!python export.py --weights yolov5s.pt --include openvino  # export
!python detect.py --weights yolov5s_openvino_model/yolov5s.xml  # inference
!python val.py --weights yolov5s_openvino_model/yolov5s.xml --data ...  # validation
```

YOLOv5 OpenVINO PyTorch Hub inference:
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/yolov5s.xml')  # OpenVINO *.xml file

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```

Inference is super fast, about 3X faster than PyTorch on Intel CPU. Have not benchmarked on AMD or M1 yet.
Screen Shot 2022-01-03 at 3 27 57 PM

EDIT: Credit to Daniel Merrick for this tutorial I followed in this PR: https://medium.com/analytics-vidhya/tutorial-on-how-to-run-inference-with-openvino-in-2021-a96e5e7c99f8

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced support for OpenVINO inference with new `.xml` extension.

### 📊 Key Changes
- Renamed OpenVINO model file extension from `_openvino_model` to `.xml` in `detect.py`, `export.py`, and `val.py`.
- Added OpenVINO as an official backend option alongside PyTorch, TorchScript, and others in `models/common.py`.
- Implemented the ability to perform inference with OpenVINO in `models/common.py`.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: These changes integrate OpenVINO more seamlessly into the YOLOv5 ecosystem, providing an additional pathway for running inference.
- 🚀 **Impact**: Users can now use OpenVINO XML models directly for inference, potentially offering performance gains on certain Intel hardware. This broadens the deployment options and optimizes workflows for environments where OpenVINO is preferred.

### CODE REVIEW

**Comment by kotomiDu** [comment]
@glenn-jocher  Is there c++ sample code for yolov5 OpenVINO?

**Comment by glenn-jocher** [comment]
@kotomiDu we don't have OpenVINO examples with C++ but we have ONNX examples here:

## C++ Inference

YOLOv5 OpenCV DNN C++ inference on exported ONNX model examples:

- https://github.com/Hexmagic/ONNX-yolov5/blob/master/src/test.cpp
- https://github.com/doleron/yolov5-opencv-cpp-python

YOLOv5 OpenVINO C++ inference examples:

- https://github.com/dacquaviva/yolov5-openvino-cpp-python

**Comment by dacquaviva** [comment]
@kotomiDu you can check it here [https://github.com/dacquaviva/yolov5-openvino-cpp-python](https://github.com/dacquaviva/yolov5-openvino-cpp-python)

@glenn-jocher would it be possible to add it here [https://docs.ultralytics.com/yolov5/tutorials/model_export](https://docs.ultralytics.com/yolov5/tutorials/model_export) like it is done for OpenCV DNN C++?

**Comment by glenn-jocher** [comment]
@dacquaviva thanks for the suggestion. I'd request a few updates first:

- Add the python and C++ examples to the main README (i.e. in different subsections) so that users see it immediately upon arrival. 
- YOLOv5 is an acronym for "You Only Look Once" and should be capitalized wherever it appears in text.

**Comment by dacquaviva** [comment]
@glenn-jocher thanks for the feedback. I updated the repo. Let me know if it is ok or if you think I should change something else, thanks!

**Comment by glenn-jocher** [comment]
@dacquaviva great thanks! I've updated our export tutorial with your additional examples. Please make sure you maintain the repository and test it periodically (CI actions could be useful to automate this).

**Pull request merged**
