### PR TITLE
Shadow `eval` fix

### PR DESCRIPTION
**Pull request by NaelsonDouglas**
**The problem**
There was a built-in name shadowing pitfall on eval.py where the name eval, which is a Python built-in method, was being used as a variable.;

If for any reason the method gets called within that context, it would cause a  hard to detect bug because **eval(arg)** would not be a method being called, but a variable being called as a method.

**Solution**
Changed the variable name to evaluation

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements and bug fixes for YOLOv5 workflows.

### 📊 Key Changes
- 📝 Improved the clarity of the feature request template.
- 🔄 Added automated weekly checks for GitHub Actions with Dependabot.
- 🔧 Updated various workflow actions to newer versions.
- 💅 Introduced a new workflow for code formatting checks.
- 🛠️ Various small fixes in GitHub Actions workflows, including a new workflow file for automatic code formatting (code-format.yml).
- 📃 New files introduced such as `.pre-commit-config.yaml` and `setup.cfg` to aid in code quality.
- 🗂️ Changed numbering in `CONTRIBUTING.md`.
- 🚀 Streamlined dataset downloading in Jupyter Notebooks and scripts.
- 👌 Autobatching improvements for efficient GPU utilization in `train.py`.

### 🎯 Purpose & Impact
- These updates aim to keep the project's dependencies up to date, ensuring security and reliability.
- The new workflow for automatic code formatting will improve code quality across the project.
- Users can expect more consistent performance and improved automation for development processes, potentially resulting in fewer bugs and better code maintainability.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
/rebase experiment after #5255 adding Organization secret ACTIONS_TOKEN

**Comment by glenn-jocher** [comment]
@NaelsonDouglas I need you to merge master into your fork before I can merge this PR. Please run the following commands:
```bash
git remote add upstream https://github.com/ultralytics/yolov5.git
git fetch upstream
git merge upstream/master
git push -u origin -f
```

**Comment by NaelsonDouglas** [comment]
> @NaelsonDouglas I need you to merge master into your fork before I can merge this PR. Please run the following commands:
> 
> ```shell
> git remote add upstream https://github.com/ultralytics/yolov5.git
> git fetch upstream
> git merge upstream/master
> git push -u origin -f
> ```

There were some errors, looks like I didnt manage to make it. :(

**Comment by glenn-jocher** [comment]
@NaelsonDouglas I will close this PR, please submit a new one from the latest master then, thank you!

**Pull request closed without merging**
