### PR TITLE
CVPR 2021 Argoverse-HD dataset autodownload support

### PR DESCRIPTION
**Pull request by karthiksharma98**
This PR allows auto-download of the Argoverse-HD Dataset to allow easy experimentation with yolov5. The dataset is described on the project webpage here: http://www.cs.cmu.edu/~mengtial/proj/streaming/

Discussion on CVPR 2021 - Streaming Perception Challenge is open in https://github.com/ultralytics/yolov5/discussions/2402

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of the Argoverse-HD dataset into YOLOv5 for advanced object detection in high-definition street scenes.

### 📊 Key Changes
- Added `argoverse_hd.yaml` configuration file to support the new Argoverse-HD dataset.
- Created a new Bash script `get_argoverse_hd.sh` to automate the downloading and setting up the dataset.
- Established image paths for training, validation, and testing data directories.
- Defined 8 object classes for detection within the dataset, including people, bikes, and various vehicle types.
- Wrote a Python script segment within the Bash script to convert Argoverse-HD annotations to YOLOv5 format.

### 🎯 Purpose & Impact
- Enables users to train YOLOv5 models on the Argoverse-HD dataset, which can improve object detection in autonomous driving applications.
- The automated setup script simplifies the process of preparing the dataset for training, making it more accessible to both researchers and practitioners.
- With the inclusion of Argoverse-HD, YOLOv5 demonstrates versatility and adaptability to high-definition sensor data, potentially improving detection accuracy and model robustness.
- Direct benefit to developers working on computer vision problems in autonomous driving and related areas.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@karthiksharma98 thanks for submitting this PR for the CVPR 2021 - Streaming Perception Challenge! Have you tested this for successful dataset autodownload and training?

Looking at the PR, commands to start training YOLOv5 on the Argoverse-HD dataset might be here below (for 16 GB GPUs). Note these should trigger a dataset autodownload if the dataset is not found locally.
```bash
$ python train.py --data argoverse_hd.yaml.yaml --weights yolov5s.pt --batch-size 64 --img 640
                                                          yolov5m                 40
                                                          yolov5l                 24
                                                          yolov5x                 16
```

**Comment by glenn-jocher** [comment]
@karthiksharma98 I'm testing out this PR. Dataset autodownloads correctly and training starts with no problems. Two images had issues with duplicate labels and are automatically removed from training, but this is not uncommon in large datasets.

```bash
train: WARNING: Ignoring corrupted image and/or label ../argoverse/Argoverse-1.1/images/train/d60558d2-d1aa-34ee-a902-e061e346e02a/ring_front_center/ring_front_center_315971355822961712.jpg: duplicate labels
val: WARNING: Ignoring corrupted image and/or label ../argoverse/Argoverse-1.1/images/val/1d676737-4110-3f7e-bec0-0c90f74c248f/ring_front_center/ring_front_center_315984819687787736.jpg: duplicate labels
```

Complete output when first running dataset:
```
train: Scanning '../argoverse/Argoverse-1.1/labels/train/02cf0ce1-699a-373b-86c0-eb6fd5f4697a/ring_front_center' for images and labels... 32870 found, 12 missing, 0 empty, 0 corrupted:  83%|▊| 32882/39384 [00:09<00:01,train: WARNING: Ignoring corrupted image and/or label ../argoverse/Argoverse-1.1/images/train/d60558d2-d1aa-34ee-a902-e061e346e02a/ring_front_center/ring_front_center_315971355822961712.jpg: duplicate labels
train: Scanning '../argoverse/Argoverse-1.1/labels/train/02cf0ce1-699a-373b-86c0-eb6fd5f4697a/ring_front_center' for images and labels... 39372 found, 12 missing, 0 empty, 1 corrupted: 100%|█| 39384/39384 [00:11<00:00,
train: New cache created: ../argoverse/Argoverse-1.1/labels/train/02cf0ce1-699a-373b-86c0-eb6fd5f4697a/ring_front_center.cache

val: Scanning '../argoverse/Argoverse-1.1/labels/val/00c561b9-2057-358d-82c6-5b06d76cebcf/ring_front_center' for images and labels... 2101 found, 0 missing, 0 empty, 0 corrupted:  14%|▏| 2101/15062 [00:00<00:03, 3359.2val: WARNING: Ignoring corrupted image and/or label ../argoverse/Argoverse-1.1/images/val/1d676737-4110-3f7e-bec0-0c90f74c248f/ring_front_center/ring_front_center_315984819687787736.jpg: duplicate labels
val: Scanning '../argoverse/Argoverse-1.1/labels/val/00c561b9-2057-358d-82c6-5b06d76cebcf/ring_front_center' for images and labels... 15055 found, 7 missing, 0 empty, 1 corrupted: 100%|█| 15062/15062 [00:04<00:00, 3238
val: New cache created: ../argoverse/Argoverse-1.1/labels/val/00c561b9-2057-358d-82c6-5b06d76cebcf/ring_front_center.cache
```

Overall everything looks good. I've cleaned up the PR in a couple places, and everything seems good to merge to me.

**Comment by karthiksharma98** [comment]
@glenn-jocher I was able to download and train on the dataset successfully, and ran into the corrupted label warning as well. Other than that I think everything else looks fine.

Thanks a lot for taking a look on your end! I think you have write access, you may go ahead and merge it :)

**Comment by glenn-jocher** [comment]
@karthiksharma98 PR is merged! Thank you for your contributions, and good luck with the competition.

**Comment by glenn-jocher** [comment]
@karthiksharma98 just noticed that we have a bug in the labels I think. The training mosaics look like this below. The width and height values look good, but the centers are offset by half-width and half-height. 

EDIT: solution would be to add `x += w/2`, `y += h/2` I think.

image

Label statistics look very interesting BTW (no problems there). The point trails may be from objects tracked across multiple video frames.
image

**Comment by glenn-jocher** [comment]
@karthiksharma98 testing potential fix in https://github.com/ultralytics/yolov5/pull/2418.

**Pull request merged**
