### PR TITLE
predict/classify.py: save all predictions to csv

### LINKED ISSUE #11482: classify/predict.py should have an option to save results as CSV
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

The script `classify/predict.py` prints its results to the console, but doesn't save the results anywhere. It would be nice if the results were also saved as a CSV somewhere for easy analysis.

**PS**: Currently I analyze the results by copying output of `classify/predict.py` and converting to CSV using AWK (see [my Github Gist](https://gist.github.com/sohang3112/f1b6b1dad5f8d3e2758fbd290c2ae477)). But this solution is not ideal.

### Use case

This will be useful for testing and comparing performance of different models on testing data.

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by sohang3112**
Fixes [Issue 11482](https://github.com/ultralytics/yolov5/issues/11482): In classify/predict.py, save all image predictions as CSV for easy analysis later on.

Predictions are saved in *predictions.csv* in `save_dir` folder (which is of the form *runs/predict-cls/exp-{NUMBER}*). Each row in the CSV has results for 1 image. 

An example CSV is:

path | label | confidence | top_5_predicted
---|---|---|---
/path/to/folder/image1.jpg | label2 | 0.75 | [["label2", 0.7536121606826782], ["label1", 0.24638774991035461]]
/path/to/folder/image2.jpg | label1 | 0.92 | [["label1", 0.9166229963302612], ["label2", 0.08337699621915817]]
/path/to/folder/image3.jpg | label1 | 0.83 | [["label1", 0.8311768174171448], ["label2", 0.1688232123851776]]

Here:
- `path` is path of image
- `top_5_predicted` is a JSON list. Each item is a list of the form `[label, score]`.
- `label`, `confidence` are the predicted label & confidence (i.e., the prediction with maximum score).

### Summary
:sparkles::camera::page_facing_up:

This pull request adds a new feature to the `classify` module that allows saving image classification results to a CSV file. The file `classify/predict.py` is modified to create and write the CSV file in the `save_dir` folder. The CSV file contains the input file name, the predicted class name and confidence, and the top 5 predicted classes and confidences as a JSON array.

> _We face the doom of endless data_
> _We need to `classify` and save_
> _The CSV file holds our fate_
> _The top 5 predictions seal our grave_

### Walkthrough
*  Save predictions to CSV file in `classify` module ([link](https://github.com/ultralytics/yolov5/pull/11654/files?diff=unified&w=0#diff-b59588df76eca837ad0c0dcee1e81768a4c23e883b01a10f48261f605b8945abR32-R34), [link](https://github.com/ultralytics/yolov5/pull/11654/files?diff=unified&w=0#diff-b59588df76eca837ad0c0dcee1e81768a4c23e883b01a10f48261f605b8945abL109-R200))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 📊 Key Changes
- The script now includes importing `csv`, `io`, and `json` modules.
- Experimental loop now runs within a CSV file writing context.
- Results of the classification (predicted labels and probabilities) are saved in a new CSV file named `predictions.csv`.

### 🎯 Purpose & Impact
- This update allows users to easily export and review all model predictions in a structured and widely-accepted format (CSV).
- Users can gain insights into model performance and analyze predictions in bulk, which is helpful for reports, audits, or further processing.

### 🌟 Summary
Predictions from YOLOv5's classification are now automatically saved to a CSV file for easy analysis and sharing. 📝🗃️✅

### CODE REVIEW

**Comment by sohang3112** [comment]
@glenn-jocher Please review this pull request, and let me know if something needs to be improved. Thanks in advance 🙂

**Comment by glenn-jocher** [comment]
@sohang3112 thanks for your contribution and submitting the pull request! We appreciate your effort in adding the feature to save image classification results to a CSV file. Our team will review the changes and provide feedback on any improvements that may be needed. Keep up the good work! 👍

**Comment by sohang3112** [comment]
@glenn-jocher Did you have a chance to review this PR yet?

**Comment by glenn-jocher** [comment]
@sohang3112 thank you for your patience! I apologize for the delay. Our team has been actively reviewing all received pull requests, including yours. We will provide feedback and insights as soon as possible. Your contribution is highly appreciated!

**Comment by sohang3112** [comment]
@glenn-jocher What sort of behaviour is this from your side?? The PR has been open for many months now, and throughout all that time you didn't find the time to even look at the changes once (let alone review & merge) ?? The only comments from you have been these useless bullshit platitudes of "valuable contribution". In the same time, you found the time to merge many other PRs in this repo, but you didn't even have the time to check the code change in my PR even once??

I have had enough - I'll make sure to never again contribute to any yolo project or any project maintained by you. Bye 👎

**Comment by glenn-jocher** [comment]
I'm genuinely sorry to hear about your experience and completely understand your frustration. It's our aim to review all contributions with the attention they deserve, but unfortunately, we can sometimes fall short due to the volume of activity. Your time and effort in contributing is truly valued, and I apologize for any oversight. Your feedback is a critical reminder for us to improve our responsiveness and engagement with contributors. Thank you for your past contributions, and I'm truly sorry to see you go. Wishing you the best in your future endeavors.

**Pull request closed without merging**
