### PR TITLE
Fix & speed up segment plot

### LINKED ISSUE #10330: Instance segmentation: quick but not good enough
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks for your contribution! I have tested the instance segmentation demo, but the results were not good, people's heads always not fully segment, like yolact. I also tried padding, and the same results were presented.
Here are some comparison：
yolov5x-seg result
Capture
yolov7 result
Capturev7
IDOL result
Capture_IDOL

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Laughing-q**
@glenn-jocher @AyushExel 
fix the clipping and jagged when plotting. [https://github.com/ultralytics/yolov5/issues/10330](https://github.com/ultralytics/yolov5/issues/10330), [https://github.com/ultralytics/yolov5/pull/9749](https://github.com/ultralytics/yolov5/pull/9749), [https://github.com/ultralytics/yolov5/issues/9955](https://github.com/ultralytics/yolov5/issues/9955)
also speed up the `--retina-mask` mode.
Speed-up the `--retina-mask` by transferring native image to gpu and plot on gpu.

Here're some samples, the `plot time` is the time of `annotator.masks` and the `process time` is `process_mask` and `process_mask_native`.
without `--retina-masks`, which is the fastest but blurred and clipped:

with the old version `--retina-masks`, which is non-blurred but much slower, jagged, also clipped:

with new version `--retina-masks, which is much faster than old version, also non-blurred, none-jagged and non-clipped:

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced mask handling for better image segmentation in YOLOv5's model predictions.

### 📊 Key Changes
- New `process_mask_native` function added for mask processing.
- Conditional use of `process_mask_native` or the existing `process_mask` depending on `retina_masks` flag.
- Masks are scaled to the input image size either before or after cropping depending on the `retina_masks` flag.
- Improved mask plotting logic in the `Annotator.masks` method, including support for new `retina_masks` mode.

### 🎯 Purpose & Impact
- 🎨 The new mask processing method offers better performance by avoiding unnecessary upsampling of masks when `retina_masks` is enabled.
- 🔍 This change provides more accurate mask plotting by ensuring better alignment with the scaled bounding boxes.
- 🚀 Potential for improved efficiency and reduced memory usage, offering a more streamlined experience for users performing image segmentation with YOLOv5, particularly on high-resolution images.

### CODE REVIEW

**Comment by AyushExel** [comment]
@Laughing-q perfect! You even managed to speed up the retina mask mode :) 
Let's wait for @glenn-jocher to have a look

**Comment by nikky4D** [comment]
This is much faster. Thanks. For the mask quality, the legs of the final result (third row) appear to be of less quality that the results in top 2 rows. On the person at extreme left, the mask missing the foot. On the person, 2nd from right, the mask is not as clear in separating the legs as the top 2 rows. Would this be from the model being non deterministic or an issue with the new scaling

**Comment by Laughing-q** [comment]
@nikky4D ooh yes you're right.  I used m model for some another videos when I was testing. Actually I think I mistakely used yolov5m-seg for the third one but another two images were predicted by yolov5x-seg.
So I tested the third image with both yolov5m-seg and yolov5x-seg again.
yolov5m-seg:
Gftioqfpzp
yolov5x-seg:
DzsDJndMqZ
and the output looks good. :)

**Comment by Javacr** [comment]
awesome work

**Comment by glenn-jocher** [comment]
@Laughing-q nice job! This looks really good.

**Comment by glenn-jocher** [comment]
@Laughing-q is there overlap now between process_mask_native() (--retina in predict) and process_mask_upsample() (in val.py)?

**Comment by glenn-jocher** [comment]
Opened https://github.com/ultralytics/yolov5/pull/10366 to investigate

**Pull request merged**
