### PR TITLE
Slightly modify CLI execution

### PR DESCRIPTION
**Pull request by lb-desupervised**
This simple change makes it easier to run the primary functions of this
repo (train/detect/test) from within Python. An object which represents
`opt` can be constructed and fed to the `main` function of each of these
modules, rather than having to call the lower level functions directly,
or run the module as a script.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactoring entry points for better maintainability and structure in YOLOv5 scripts.

### 📊 Key Changes
- Split the script execution into two functions: `parse_opt()` and `main(opt)` for `detect.py`, `export.py`, `test.py`, and `train.py`.
- The `if __name__ == '__main__':` block now calls `parse_opt()` followed by `main(opt)`, separating argument parsing from script execution.

### 🎯 Purpose & Impact
- **Purpose:** Enhance code readability and organization; facilitate the potential reusability of code components.
- **Impact:** Users will have a clearer understanding of the flow of the program. Developers can more easily use parts of the script in other contexts or build upon them, which might lead to community contributions and integrations. No direct impact on the functionality from the user perspective.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@lb-desupervised thanks for the PR! Can you add models/export.py to the PR please?

@fcakyon this would allow for better out of the box pip functionality you mentioned before right?

**Comment by lb-desupervised** [comment]
No problem @glenn-jocher :)

I've added the corresponding updates to models/export.py now.

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@lb-desupervised PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by fcakyon** [comment]
@glenn-jocher this is definitely a useful update!

**Comment by glenn-jocher** [comment]
@fcakyon @lb-desupervised yes this looks pretty useful. Now you can call detect() directly with any non-default arguments you have, or you can call main() if you have an existing arguments class (which you can get from parse_opt()).

**Pull request merged**
