### PR TITLE
Add export and detection for TensorFlow saved_model, graph_def and TFLite

### PR DESCRIPTION
**Pull request by zldrobit**
This PR add models/tf.py to export TensorFlow saved_model, graph_def and TFLite models.
This script support both yolov5 v2 (LeakyReLU activations) and v3 (Hardswish activations) models.

Export TensorFlow and TFLite models using:
```
PYTHONPATH=. python models/tf.py --weights weights/yolov5s.pt --cfg models/yolov5s.yaml --img 640
```
and use one of the following command to detect objects:
```
python detect.py --weights weights/yolov5s_saved_model --img 640
python detect.py --weights weights/yolov5s.pb --img 640
python detect.py --weights weights/yolov5s.tflite --img 640
```

This PR is tested sucessfully with PyTorchc 1.6, TensorFlow 1.15.3/2.3.0.
However, TFLite export is only supported under TensorFlow 2.3.0.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
The PR introduces support for the Android platform to the YOLOv5 model, focusing on setting up the necessary Android project structure.

### 📊 Key Changes
- Added Android app project structure and configuration files.
- Included resources such as layouts and vector icons for the Android application interface.
- Provided Gradle build scripts and properties for the Android project build automation.
- Implemented Java/Kotlin classes for activities, custom views, TensorFlow Lite integration, and utilities specific to Android.

### 🎯 Purpose & Impact
- The integration of YOLOv5 into an Android app allows for on-device object detection, which can benefit various applications such as real-time image analysis, augmented reality, and surveillance.
- Users can leverage the power of YOLOv5 directly from their mobile devices without the need for server-side processing, leading to faster and privacy-compliant applications.
- This update potentially opens the project to a wider community of mobile developers interested in deploying machine learning models on Android.

### CODE REVIEW

**Comment by bartvollebregt** [comment]
Very nice! 

Do you have a way to perform the detection with Java / Android already? This is where the TFLite formats will probably be used the most.

**Comment by lei522** [comment]
@zldrobit ,thank you for your pr, i have exported TFLite models successfully. but how can i use the letterbox function in tflite project ?

**Comment by zldrobit** [comment]
@bartvollebregt Thanks :D I am cleaning my Android project code, and I am going to push that code soon.
@lei522 No thanks :D Please wait for me to upload the Android demo code. TFLite model runs directly in the demo.

**Comment by BernardinD** [comment]
@zldrobit Do you also plan to look into an edgetpu implementation? I am having issue with int8 quantization of the keras model

**Comment by Guilhen** [comment]
Some operations used in the model such as resize_nearest_neighbor are not compatible with the edge TPU

**Comment by zldrobit** [comment]
@BernardinD I have never used an Edge TPU and I found it has 4T FLOPs computation power today.
I will try to buy one, but it takes a long time for shipping.

@Guilhen yes, resize_nearest_neighbor has [3D input/output limitations](https://coral.ai/docs/edgetpu/models-intro/#supported-operations).

**Comment by zldrobit** [comment]
@bartvollebregt @lei522 I updated the TF conversion script for GPU delegate compatibility and uploaded Android TFLite demo.
Please use
```
PYTHONPATH=. python3 models/tf.py --weights weights/yolov5s.pt --cfg models/yolov5s.yaml --no-tfl-detect
```
to generate `yolov5s.tflite`, and copy it to the Android _asset_ folder.
Then, build and run the Android TFLite demo.

I have tested yolov5s batch-size 1 run time on Android devices:
~~Snapdragon 820: 2.1s on CPU (4threads) and 1.5s on GPU~~
~~Snapdragon 845: 1.2s on CPU (4threads) and 0.7s on GPU~~

Snapdragon 820: 1.9s on CPU (4threads) and 1.3s on GPU
Snapdragon 845: 1.1s on CPU (4threads) and 0.6s on GPU

**Comment by lei522** [comment]
@zldrobit i can run the tflite model, but when i run  the model with hybrid quantization model or float16 quantization, i get the ValueError:Input array not provided for operation 'reshape'.

**Comment by zldrobit** [comment]
@lei522 I added fp16 and int8 TFLite model export.
Plz try again with 
```
PYTHONPATH=. python3  models/tf.py --weight weights/yolov5s.pt --cfg models/yolov5s.yaml --no-tfl-detect --tfl-int8 --source /dataset/coco/coco2017/train2017 --ncalib 100
```
This will generate `yolov5s-fp16.tflite` and `yolov5s-int8.tflite`.
You can use them in the new Android project.

@BernardinD @Guilhen The updated code supports full integer quantization (with --tfl-int8), which can be compiled to Edge TPU format. I have tested int8 quantization model on Android devices. 

The inference time of fp16 model (batch-size 1) is:
Snapdragon 820: 1.9s on CPU (4threads) and 1.3s on GPU
Snapdragon 845: 1.1s on CPU (4threads) and 0.6s on GPU
The inference time agrees with fp32's, due to the default fp16 precision of TFLite.

The inference time of int8 model (batch-size 1) is:
Snapdragon 820: 1.7s on CPU (4threads)
Snapdragon 845: 1.0s on CPU (4threads)
CPU inference time reduction is around 10% from fp32 precision to int8 precision.

**Comment by BernardinD** [comment]
Thanks @zldrobit, I was able to run the edgetpu compilation with your current conversion. Although when I try to run the outputted graph I'm given the error `ValueError: Found too many dimensions in the input array of operation 'reshape'.`

Any suggestions? The compilation also only gets 1 operation to get mapped

**Comment by zldrobit** [comment]
@BernardinD plz check your representative image forlder.
Have you provided enough images (defualt --ncalib is 100)?
If so, you may encounter a bug to be fixed in edge TPU, see https://github.com/google-coral/edgetpu/issues/74.
People disscussed in that issue, and @Namburger helped to convert tflite model to edge TPU format manually to avoid the *reshape* problem.
BTW, could you share your edgetpu_compiler output log? I am curious about why other operations are not mapped.

**Comment by BernardinD** [comment]
> @BernardinD plz check your representative image forlder.
> Have you provided enough images (defualt --ncalib is 100)?
> If so, you may encounter a bug to be fixed in edge TPU, see [google-coral/edgetpu#74](https://github.com/google-coral/edgetpu/issues/74).
> People disscussed in that issue, and @Namburger helped to convert tflite model to edge TPU format manually to avoid the _reshape_ problem.
> BTW, could you share your edgetpu_compiler output log? I am curious about why other operations are not mapped.

Sure no problem. Here's the log file:
[best_yolov5s_results-int8_edgetpu.log](https://github.com/ultralytics/yolov5/files/5293871/best_yolov5s_results-int8_edgetpu.log)

And I used the default 100 ncalib out of a folder of 1000 pictures. That should be fine, correct?

**Comment by minthawzin1995** [comment]
I managed to convert to int8 model with no issue. However, may i know if the same inference code (detect.py) could still be used to inference the int8 tflite model. I tried changing the input type to uint8 and the results seem to be wrong. 

Thank you and really appreciate it for the conversion scripts.

**Comment by idenc** [comment]
The android demo does not seem to be runnable. A bunch of the drawables are missing, and the env package is missing

**Comment by glenn-jocher** [comment]
@zldrobit hi, thanks for this PR! Export to *.tflite is an amazing contribution, I know a lot of people have been asking for this functionality. 

I think originally this PR featured only the export code (first 3 or 4 commits), and the accompanying android app was later added in commit 5. 

For us to merge this into the repo we'd ideally want to strip this down to the minimum export functionality required as you had originally, as supporting and maintaining an android app is beyond the scope of the repo (even though it's an amazing contribution in and of itself).

EDIT: maybe the best way to move forward is to submit a new PR featuring only the export, or to reset the head to an earlier commit on the branch, whatever is easiest for you, let me know, thanks!

**Comment by zldrobit** [comment]
@BernardinD sorry for this late reply, I was on vocation.
That should be good enough to use 100 out of 1000 pictures.

**Comment by zldrobit** [comment]
@minthawzin1995 int8 quantization does not support some ops in Detect module, some code needs to be added in detect.py .

**Comment by zldrobit** [comment]
@idenc I'll check the android code again, thx for reporting.

**Comment by zldrobit** [comment]
@glenn-jocher I am planning to submit a new PR.
I think I should leave detect.py untouched and just add models/tf.py and other code for *.tflite export.
Do we need the detection code for *.tflite in the new PR?

**Comment by glenn-jocher** [comment]
@zldrobit yes, please submit a new PR with tf.py and associated export code, but without detect.py integration and without the /android folder. This will help us minimize keep code maintenance going forward.

**Comment by zldrobit** [comment]
Export and Detection (/w TFLite int8 inference) functionality and Android project has been integrated in a new branch https://github.com/zldrobit/yolov5/tree/tf-android

@minthawzin1995 Plz try the new branch and int8 inference with:
```
python3 detect.py --weights weights/yolov5s-int8.tflite --tfl-detect --tfl-int8
```
inference time is around 18s on CPU.

@idenc Sorry for my unfamiliar with Android Studio. I have added necessary files in the Android  project.
Plz try the new branch.

**Comment by minthawzin1995** [comment]
> Export and Detection (/w TFLite int8 inference) functionality and Android project has been integrated in a new branch https://github.com/zldrobit/yolov5/tree/tf-android
> 
> @minthawzin1995 Plz try the new branch and int8 inference with:
> 
> ```
> python3 detect.py --weights weights/yolov5s-int8.tflite --tfl-detect --tfl-int8
> ```
> 
> inference time is around 18s on CPU.
> 
> @idenc Sorry for my unfamiliar with Android Studio. I have added necessary files in the Android project.
> Plz try the new branch.

@zldrobit Thank you for the fast response, I have tested the new update and the detection works perfectly now for the int-8 model.

**Comment by Hpero4** [comment]
> Export and Detection (/w TFLite int8 inference) functionality and Android project has been integrated in a new branch https://github.com/zldrobit/yolov5/tree/tf-android
> 
> @minthawzin1995 Plz try the new branch and int8 inference with:
> 
> ```
> python3 detect.py --weights weights/yolov5s-int8.tflite --tfl-detect --tfl-int8
> ```
> 
> inference time is around 18s on CPU.
> 
> @idenc Sorry for my unfamiliar with Android Studio. I have added necessary files in the Android project.
> Plz try the new branch.

@zldrobit Hey, thank you for providing the android demo, very helpful for me. but when i test the code found "org.tensorflow.lite.examples.detection.tflite.YoloV5Classifier.convertBitmapToByteBuffer" no adaptation uint8 model?  It always return 4 bytes buffer. Can you tell me how to improve it? I will be very grateful.

Edit ---------------------------------------------------

I tried to modify it like this:
```java
protected ByteBuffer convertBitmapToByteBuffer(Bitmap bitmap) {
//        ByteBuffer byteBuffer = ByteBuffer.allocateDirect(4 * BATCH_SIZE * INPUT_SIZE * INPUT_SIZE * PIXEL_SIZE);
        ByteBuffer byteBuffer = ByteBuffer.allocateDirect(BATCH_SIZE * INPUT_SIZE * INPUT_SIZE * PIXEL_SIZE);
        byteBuffer.order(ByteOrder.nativeOrder());
        int[] intValues = new int[INPUT_SIZE * INPUT_SIZE];
        bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
        int pixel = 0;
        for (int i = 0; i < INPUT_SIZE; ++i) {
            for (int j = 0; j < INPUT_SIZE; ++j) {
                final int val = intValues[pixel++];
//                byteBuffer.putFloat(((val >> 16) & 0xFF) / 255.0f);
//                byteBuffer.putFloat(((val >> 8) & 0xFF) / 255.0f);
//                byteBuffer.putFloat((val & 0xFF) / 255.0f);
                byteBuffer.put((byte)((val >> 16) & 0xFF));
                byteBuffer.put((byte)((val >> 8) & 0xFF));
                byteBuffer.put((byte)(val & 0xFF));
            }
        }
        return byteBuffer;
    }
```

But got a new error: 
`java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite tensor with type UINT8 and a Java object of type [[[F (which is compatible with the TensorFlowLite type FLOAT32).`

**Comment by zldrobit** [comment]
@Hpero4 The code you quote seems good,
and that's why I changed output variable type from `float` 
https://github.com/ultralytics/yolov5/blob/eb626a611aba0a83535ff72e9581014be8402a59/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/YoloV5Classifier.java#L355-L356
to `ByteBuffer`
https://github.com/ultralytics/yolov5/blob/eb626a611aba0a83535ff72e9581014be8402a59/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/YoloV5ClassifierDetect.java#L135-L139

**Comment by Hpero4** [comment]
> @Hpero4 The code you quote seems good,
> and that's why I changed output variable type from `float`
> https://github.com/ultralytics/yolov5/blob/eb626a611aba0a83535ff72e9581014be8402a59/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/YoloV5Classifier.java#L355-L356
> 
> 
> to `ByteBuffer`
> https://github.com/ultralytics/yolov5/blob/eb626a611aba0a83535ff72e9581014be8402a59/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/YoloV5ClassifierDetect.java#L135-L139

@zldrobit Thank you for your reply. After reading the relevant code, I tried to use "YoloV5ClassifierDetect" again and succeeded.

**Comment by bluemix** [comment]
hello there 👋🏼
i hope this pull will be merged soon.
thanks in advance.

**Comment by Sergey-sib** [comment]
Hello! after converting, I get int8 file size of about 8 mb. 
This is more than I expected. Could it be the number of classes? I have 326 classes.

**Comment by BernardinD** [comment]
@zldrobit Any update on the edgetpu compatibility?

**Comment by RSWAIN1486** [comment]
@zldrobit - Thanks for this excellent contribution. I am able to convert my custom model to both fp16 and int8 models.

fp16 works fine. But getting an issue when deploying int8 tflite to android. I get the below error. I have tried setting TF_OD_API_IS_QUANTIZED to both true and false. But the result is the same. Could you please help with what could be going wrong. 


```
2020-10-31 11:49:31.660 25862-27252/org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 25862
    java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (input_1) with 1228800 bytes from a Java Buffer with 4915200 bytes.
        at org.tensorflow.lite.Tensor.throwIfSrcShapeIsIncompatible(Tensor.java:423)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:189)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
        at org.tensorflow.lite.examples.detection.tflite.YoloV5ClassifierDetect.recognizeImage(YoloV5ClassifierDetect.java:388)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:246)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by zldrobit** [comment]
@RSWAIN1486 
```
java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (input_1) with 1228800 bytes from a Java Buffer with 4915200 bytes.
```
indicates `tensor (input_1)` input tensor has a different shape than you specified.
Plz check your input tensor shape again.
Have you set `isQuantized = true` for int8 inference in `DetectorFactory.java`?

**Comment by RSWAIN1486** [comment]
> @zldrobit 
> 
> ```
> java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (input_1) with 1228800 bytes from a Java Buffer with 4915200 bytes.
> ```
> 
> indicates `tensor (input_1)` input tensor has a different shape than you specified.
> Plz check your input tensor shape again.
> Have you set `isQuantized = true` for int8 inference in `DetectorFactory.java`?



@zldrobit - Thanks a lot. That works great. I wasn't aware about the DetectorFactory.java file as I am new to this. I think it would be helpful if we have some limited documentation on the android integration in the readme file for this branch.

One thing I observed is that in the GPU mode the int-8 model takes 3x time (1000ms) for inference than the fp-16 (300ms) model . Is that expected? Could it be improved?

**Comment by zldrobit** [comment]
@RSWAIN1486 That requires a new branch, since the current branch is for pull request.
I'll make a readme file after adding some necessary functions.

According to https://www.tensorflow.org/lite/performance/post_training_quantization, int8 TFLite model does not support GPU acceleration. 
It is mainly used in devices without GPU or specific devices like Edge TPU and Hexagon DSP.

**Comment by RSWAIN1486** [comment]
> @RSWAIN1486 That requires a new branch, since the current branch is for pull request.
> I'll make a readme file after adding some necessary functions.
> 
> According to https://www.tensorflow.org/lite/performance/post_training_quantization, int8 TFLite model does not support GPU acceleration.
> It is mainly used in devices without GPU or specific devices like Edge TPU and Hexagon DSP.

@zldrobit - That's right. Thanks again for the quick replies.

**Comment by RSWAIN1486** [comment]
@zldrobit - Let me know if you could help with this. When I export the models with size 640, the predictions work fine. But when exported with 416 or 320 as input size and then changing the `TF_OD_API_INPUT_SIZE` variable in `MainActivity.java` and `inputSize` in `DetectorFactory.java` to one of these new sizes, the bounding box predictions seem off from the object and also multiple boxes at random locations pop up. Any idea or have seen a similar issue? 

The `anchors `in `DetectorActivity.java` remain the same.

**Comment by zac-franklin** [comment]
> @zldrobit - Let me know if you could help with this. When I export the models with size 640, the predictions work fine. But when exported with 416 or 320 as input size and then changing the `TF_OD_API_INPUT_SIZE` variable in `MainActivity.java` and `inputSize` in `DetectorFactory.java` to one of these new sizes, the bounding box predictions seem off from the object and also multiple boxes at random locations pop up. Any idea or have seen a similar issue?
> 
> The `anchors `in `DetectorActivity.java` remain the same.

Similar issue here. Changing the `output_width` variable in `DetectorFactory.java` by the image conversion factor helped me.

**Comment by zldrobit** [comment]
@RSWAIN1486 you could change 
https://github.com/ultralytics/yolov5/blob/02c6003714fc473122b0131ea42d2f33efbba876/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/DetectorFactory.java#L32-L33
to
```
 inputSize = 320; 
 output_width = new int[]{40, 20, 10};  
```
according to the size scale factor.

**Comment by RSWAIN1486** [comment]
@zldrobit & @zacfpearson - It works great. Thank you!!

**Comment by zldrobit** [comment]
@BernardinD I use `-a` with `edgetpu_compiler` and I got 133 ops run on Edge TPU.
image
By the way, I am using the newest version of `edgetpu_compiler`.
I am about to get an Edge TPU, but now I am unable to do a speed test.

**Comment by BernardinD** [comment]
@zldrobit Thanks. I was able to convert it finally, thanks to your `-a` suggestion. But do you know why the activations you replaced in the keras model still appear in the tflite model? They stop more of the model from being mapped to the TPU

**Comment by zldrobit** [comment]
@BernardinD I guess the reason is TFLite converter compiles

https://github.com/ultralytics/yolov5/blob/1f8499c047126d678f631b8ee73681c913c64995/models/tf.py#L82-L83

to `HardSwish` op.

As pointed out in https://github.com/ultralytics/yolov5/pull/1127#issuecomment-730530894 and https://github.com/ultralytics/yolov5/pull/1127#issuecomment-730804893,
we may replace Leaky Relu and HardSwish with Relu for opertor support on edgetpu, but the accuracy may also be poor.

**Comment by gdebrecz** [comment]
Hi !

First of all thanks for this effort , it is really nice !

I've tried to covert a trained yolov5s model to tflite and to tflite.edgetpu. The conversion went fine, however the majority of the layers will be executed on the CPU. I've used the following procedure:

To convert the trained model to quantized tflite:
`
PYTHONPATH=. python3 models/tf.py --weights ../yolov5/runs/train/exp2/weights/best.pt --cfg models/yolov5s.yaml --img-size 512 --no-tfl-detect --tfl-int8 --source ../p7/images/train/ --ncalib 100`


To compile it with edgetpu compiler;

`user@hpegpu:/data/user/yv5-tf$ edgetpu_compiler -o /tmp/a ../yolov5/runs/train/exp2/weights/best-int8.tflite`

Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 88 ms.

Input model: ../yolov5/runs/train/exp2/weights/best-int8.tflite
Input size: 7.46MiB
Output model: /tmp/a/best-int8_edgetpu.tflite
Output size: 7.39MiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 8.07MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 205
Operation log: /tmp/a/best-int8_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 1
Number of operations that will run on CPU: 204
See the operation log file for individual operation details.



Am I doing something wrong ? What should I do in order to have more layers executed on the EdgeTPU ?
thanks  a lot in advance,
g

**Comment by BernardinD** [comment]
> @BernardinD I use `-a` with `edgetpu_compiler` and I got 133 ops run on Edge TPU.
> image
> By the way, I am using the newest version of `edgetpu_compiler`.
> I am about to get an Edge TPU, but now I am unable to do a speed test.

@gdebrecz I had the same issue earlier. Refer to the comment above

**Comment by gdebrecz** [comment]
Hi ! 
Thanks for the prompt reply and sorry for overlooking the -a switch ! Now, I've tried and got:
```

Number of operations that will run on Edge TPU: 133
Number of operations that will run on CPU: 72
See the operation log file for individual operation details.
```

Which is much better, indeed ! Thanks !

Two more question:
Do you seen any more possibility for the remaining operations to be ported to EdgeTPU ?
Do you have a link or simple example script for executing the edgetpu compiled version of the model on the device included in the repository ? 

Cheers,
G

**Comment by gdebrecz** [comment]
With the above version the model runs over 700 ms on the EdgeTPU.  I'd like to find further ways to optimize it !

**Comment by PINTO0309** [comment]
I have discussed this in my repository issues.
**https://github.com/PINTO0309/PINTO_model_zoo/issues/53**

I haven't tried it yet to see if it works properly.
100876665-0887ab80-34eb-11eb-83e7-a5e072528e41

**Comment by wwdok** [comment]
Hi,@zldrobit, i have a question, that is inside the function `representative_dataset_gen()` in `tf.py`, why do we need `input = np.transpose(img, [1, 2, 0])`, from my inference, this line of code is doing `CHW -> HWC`, is that right ?

**Comment by zldrobit** [comment]
@wwdok That's right.
`input = np.transpose(img, [1, 2, 0])` is for int8 TFLite calibration since TensorFlow's channel order is `HWC` while Pytorch's is `CHW`.

**Comment by wwdok** [comment]
> @wwdok That's right.
> `input = np.transpose(img, [1, 2, 0])` is for int8 TFLite calibration since TensorFlow's channel order is `HWC` while Pytorch's is `CHW`.

I asked this question is because i found in `utils/datasets.py`, there is a line of code `img = img[:, :, ::-1].transpose(2, 0, 1)` which is doing `HWC -> CHW `, If at the beginning, the order of channel is already `HWC`, does it mean the additional intermediate step （HWC -> CHW ->HWC ）is unneccessary ?

**Comment by zldrobit** [comment]
@wwdok If the images can be read directly with opencv, it is unnecessary.
However, `models/tf.py` reuse the PyTorch `LoadImages` pipeline with `CHW` channel order.
After loading images, We have to convert `CHW` back to `HWC` for TensorFlow.

**Comment by wwdok** [comment]
> @wwdok If the images can be read directly with opencv, it is unnecessary.
> However, `models/tf.py` reuse the PyTorch `LoadImages` pipeline with `CHW` channel order.
> After loading images, We have to convert `CHW` back to `HWC` for TensorFlow.

Got it, that is what i concerned about, thank you for your confirmation ! 
I am coding the `def representative_dataset_gen()`, my case is more simpler, there is no Pytorch `LoadImages` pipeline with `CHW`, so i think i can directly use the results the opencv return.

**Comment by zldrobit** [comment]
@BernardinD @Guilhen @gdebrecz I found a way to get yolov5s running fast on Edge TPU (70-100ms).
Plz refer to https://github.com/google-coral/edgetpu/issues/272#issuecomment-752905864 and use [tf-android-tfl-detect](https://github.com/zldrobit/yolov5/tree/tf-android-tfl-detect) branch to detect with Edge TPU.

**Comment by jsn5** [comment]
Hi @zldrobit, I'm getting different results on the android app compared to detect.py.

 I converted yolov5s model to fp16 using the following command:

 PYTHONPATH=. python models/tf.py --weights models/yolov5s.pt --cfg models/yolov5s.yaml --img 320

I setup the android app with the fp-16 model but on the app the results are much worse compared to when running inference using detect.py like this:

python detect.py --weights models/yolov5s-fp16.tflite --img-size 320

I've verified that the masks and output shapes are correct.  I set SAVE_PREVIEW_BITMAP as true and got the images going to inference on the phone and tried them with detect.py and it works well. I've tried with the default coco model as well as a custom model. For the custom model, the results are much worse from the android app. Here are the results on the coco model:

Using android app:

Screenshot_20210118-154149_TFL Detect
Screenshot_20210118-154205_TFL Detect


Using detect.py:

preview_31487
preview_19668

Am I missing something?

**Comment by zldrobit** [comment]
@jsn5 I notice that there are difference between above and below pictures.
The below pictures have higher brightness and contrast.
Try changing light conditions while comparing, you'll get a more comprehensive result.

**Comment by jsn5** [comment]
> @jsn5 I notice that there are difference between above and below pictures.
> The below pictures have higher brightness and contrast.
> Try changing light conditions while comparing, you'll get a more comprehensive result.

The pics look different because for the phone results I had to take a screenshot of the app. Regardless of lighting and contrast, the results seem very different overall. For a custom dataset that I trained yolov5s on, the detection on phone would miss many of the objects while taking the same preview image and running using detect.py is able to detect most of the objects in the scene.

I'll try to do some more tests and share it with you.

**Comment by glenn-jocher** [comment]
@jsn5 @zldrobit the differences may also be due to image transforms in Android. In iOS, there are a few options for how the camera image is transformed into the model input shape. iDetection iOS app currently uses scaleFill, which distorts the aspect ratio slightly, so we have a TODO item to move to scaleFit (same as YOLOv5 PyTorch dataloader), but this is not as simple as it sounds because the bounding box reconstruction is dependent on the exact input transforms, so modifications at the input must be accompanied by modification of the box reconstruction code as well.

Screen Shot 2021-01-18 at 8 50 43 PM

**Comment by zldrobit** [comment]
Since this PR is closed, any further questions about TensorFlow/TFLite export may be addressed in https://github.com/ultralytics/yolov5/pull/1127.

**Comment by glenn-jocher** [comment]
@zldrobit I just saw that the bot closed the PR, I'll reopen it again. Is the Android app here maintained and working correctly with models exported from #1127?

**Comment by zldrobit** [comment]
@glenn-jocher This PR is out-of-date, and its Android project is not compatible with the models exported from https://github.com/ultralytics/yolov5/pull/1127.
https://github.com/ultralytics/yolov5/pull/1127 has downstream branches `tf-android` and `tf-android-tfl-detect`.
They have Android project in them and are described in the first comment of https://github.com/ultralytics/yolov5/pull/1127.
The only advantage of this PR is to use TensorFlow 1.X.
Otherwise, we could close this PR and move on to https://github.com/ultralytics/yolov5/pull/1127.

**Comment by glenn-jocher** [comment]
@zldrobit ok makes sense! Will close.

**Comment by NandhiniN85** [comment]
> > @BernardinD I use `-a` with `edgetpu_compiler` and I got 133 ops run on Edge TPU.
> > image
> > By the way, I am using the newest version of `edgetpu_compiler`.
> > I am about to get an Edge TPU, but now I am unable to do a speed test.
> 
> @gdebrecz I had the same issue earlier. Refer to the comment above

@BernardinD We were able to compile the quantized model without -a and got TPU ops as 1. But when we used -a, got "Internal compiler error. Aborting!". Any suggestion to resolve it?. Thanks!

**Comment by NandhiniN85** [comment]
> > > @BernardinD I use `-a` with `edgetpu_compiler` and I got 133 ops run on Edge TPU.
> > > image
> > > By the way, I am using the newest version of `edgetpu_compiler`.
> > > I am about to get an Edge TPU, but now I am unable to do a speed test.
> > 
> > 
> > @gdebrecz I had the same issue earlier. Refer to the comment above
> 
> @BernardinD We were able to compile the quantized model without -a and got TPU ops as 1. But when we used -a, got "Internal compiler error. Aborting!". Any suggestion to resolve it?. Thanks!

here is the screenshot of the logfile,
image

**Comment by zldrobit** [comment]
@NandhiniN85 Could you share more information to inspect the problem, such as the model size, the number of classes, and the network structure (any change to yolov5*.yaml)?

**Comment by NandhiniN85** [comment]
> @NandhiniN85 Could you share more information to inspect the problem, such as the model size, the number of classes, and the network structure (any change to yolov5*.yaml)?

@zldrobit I have used yolov5s and the number of classes is 1. The only modification made to the config file is the nc=1. The input resolution is 640 x 640. Every image frame has around 100 objects at least, the size of the objects are very small (for the same reason used 640 x 640). Altogether the model has been trained on with 250k objects.

**Comment by zldrobit** [comment]
@NandhiniN85 640x640 may be too large for YOLOv5 EdgeTPU model.
Could you try exporting a smaller EdgeTPU model, e.g. with 320x320 resolution?

**Comment by NandhiniN85** [comment]
> @NandhiniN85 640x640 may be too large for YOLOv5 EdgeTPU model.
> Could you try exporting a smaller EdgeTPU model, e.g. with 320x320 resolution?

@zldrobit Thanks for the details! I will try with a smaller resolution and check out the accuracy. Thanks!

**Comment by ziyuwzf** [comment]
After i converted .pt to .tflite successfully,i runed the command as below:
D:/PycharmProjects/yolov5-tf-android/detect.py --weights models/yolov5s-fp16.tflite --img 320 --save-crop
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, hide_conf=False, hide_labels=False, img_size=[320, 320], iou_thres=0.45, line_thickness=3, max_det=1000, name='exp', nosave=False, project='runs/detect', save_conf=False, save_crop=True, save_txt=False, source='data/images', tfl_int8=False, update=False, view_img=False, weights=['models/yolov5s-fp16.tflite'])
YOLOv5  2021-6-17 torch 1.8.0+cpu CPU

image 1/2 D:\PycharmProjects\yolov5-tf-android\data\images\bus.jpg: 320x320 4 persons, 1 bus, Done. (18.252s)
image 2/2 D:\PycharmProjects\yolov5-tf-android\data\images\zidane.jpg: 320x320 3 persons, 2 ties, Done. (18.273s)
Results saved to runs\detect\exp5
Done. (36.643s)

Process finished with exit code 0
why .tflite runs so slower than .pt?i missed something?

**Comment by zldrobit** [comment]
@ziyuwzf If you run detection on a PC, TFLite could not use GPU. So it runs slower than PyTorch. You could also run your detection on Google Colab to confirm the performance issue. I ran detection with a 20-thread Intel i9-9820X CPU, and the results are
image
On what device you ran the detection?

**Comment by rashmi-learning** [comment]
While exporting the weights getting error:

File "models/tf.py", line 453, in <module>
    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
NameError: name 'keras_model' is not defined

**Comment by glenn-jocher** [comment]
@rashmi-learning exports are consolidated in export.py now. For TFLite:
```
python export.py --weights yolov5s.pt --include tflite
```

**Pull request closed without merging**
