### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by alho01**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of Data Version Control (DVC) and removal of GitHub community health files.

### 📊 Key Changes
- 🛠️ Addition of DVC for data and pipeline versioning.
- 👨‍💻 Configuration for AWS S3 as remote storage.
- 🚮 Deletion of GitHub community health files such as `CODE_OF_CONDUCT.md`, issue templates, etc.

### 🎯 Purpose & Impact
- 🤖 **DVC Integration**: Enables better data management practices and reproducibility of ML experiments.
- 🚀 **AWS S3 Configuration**: Facilitates storing and tracking of large datasets.
- 🧹 **Removal of Community Files**: May indicate a shift of community engagement strategies or relocation of those resources outside of GitHub.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@alho01 MLFlow updates in this PR could be suitable for master, though these should be placed directly in loggers/__init__.py rather than inlined:
https://github.com/ultralytics/yolov5/blob/master/utils/loggers/__init__.py

**Comment by alho01** [comment]
> @alho01 MLFlow updates in this PR could be suitable for master, though these should be placed directly in loggers/**init**.py rather than inlined: https://github.com/ultralytics/yolov5/blob/master/utils/loggers/__init__.py

The logger is accepting strings and while mlflow is loggin artifacts, params and metrics. I either had to seperate mlfow from logger, change how the logger is called or parse the incomming string for mlflow. are these what you are suggesting ?

**Comment by glenn-jocher** [comment]
@alho01 you can see example metrics/loss logging here for each of the 3 loggers (CSV, TensorBoard, W&B):
https://github.com/ultralytics/yolov5/blob/d29df68299a216abb3254752bbf85e28fc92e737/utils/loggers/__init__.py#L132-L153

On_model_save callback is here for uploading models:
https://github.com/ultralytics/yolov5/blob/d29df68299a216abb3254752bbf85e28fc92e737/utils/loggers/__init__.py#L154-L159

**Comment by alho01** [comment]
Dear @glenn-jocher, this PR was sent by a mistake, would you please remove this PR ?

**Comment by glenn-jocher** [comment]
@alho01 only branches can be deleted. Pull requests can be opened and closed but not deleted.

**Comment by alho01** [comment]
@glenn-jocher I have contacted Github and they said they will forward the request to you.

**Comment by glenn-jocher** [comment]
@alho01 I appreciate the heads-up. I will keep an eye out for any communication from GitHub regarding this matter. Thank you for reaching out.

**Pull request closed without merging**
