### PR TITLE
Flask REST API Example

### PR DESCRIPTION
**Pull request by robmarkcole**
Adds an example app providing a rest API to address https://github.com/ultralytics/yolov5/issues/2662

I chose to add this in a new directory rather than place it in the google_app_engine folder since it is independent of that platform

Note I also have an example web app at https://github.com/robmarkcole/yolov5-flask

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing a Flask REST API for the YOLOv5 object detection model!

### 📊 Key Changes
- A new `README.md` was added, explaining how to set up and run a REST API using Flask to interact with the YOLOv5 model.
- An `example_request.py` script was created to demonstrate how to send an image and receive detection results from the API.
- The `restapi.py` script launches a Flask app that defines an endpoint for posting images and getting detection results using the YOLOv5 model.

### 🎯 Purpose & Impact
- **Developer Convenience:** Provides developers with a simple way to integrate YOLOv5 into applications via HTTP requests.
- **Accessibility:** Allows easier access to YOLOv5 model inference for a variety of client-side languages and tools that can handle HTTP requests.
- **Expandability:** Opens the door for YOLOv5's object detection to be included in more complex systems or cloud environments.
🚀 Boosts applicability by facilitating model serving for real-world applications and user interfaces!

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@robmarkcole I merged master and applied a few small updates. I think this is good to merge on our side. Is everything good on your side to merge? Thanks!

**Comment by robmarkcole** [comment]
Looks good to me!

**Comment by glenn-jocher** [comment]
@robmarkcole thank you for your contributions!

**Comment by Adarsh474532** [comment]
How can we use flask rest api for video live streaming

**Pull request merged**
