### PR TITLE
Add Hub results.pandas() method

### LINKED ISSUE #2703: Return predictions as json
## 🚀 Feature
For creating API around models it would be very useful to add a `to_json()` method for inference results on `class Detections`.

## Motivation
Creating a flask app to expose inferencing, will need to implement a `to_json()` method but preferable to wrap around a standardised result.

## Pitch
Ideally something like:
```
detections = model(img, size=640)
return jsonify({"detections": detections.to_json()})
```

## Additional context
Can be used in https://github.com/ultralytics/yolov5/issues/2662

### LINKED ISSUE #2722: Can feed tensor the model
Why does `model(img)` works but `model(torch.Tensor(img))` does not, despite having the same shape resulting in the following error?
```
RuntimeError: Sizes of tensors must match except in dimension 2. Got 1 and 2 (The offending index is 0)
```
`img` is of shape `(720, 1280, 3)` and of type `int`.
Thanks

### PR DESCRIPTION
**Pull request by glenn-jocher**
New method converts results from torch tensors to pandas DataFrames with column names.

This PR may partially resolve issue https://github.com/ultralytics/yolov5/issues/2703

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()

image 1/2: 720x1280 2 persons, 1 tie
image 2/2: 1080x810 4 persons, 1 bus
Speed: 110.3ms pre-process, 7.0ms inference, 1.1ms NMS per image at shape (2, 3, 640, 640)

print(results.pandas().xyxy[0])  # print pandas 
    xcenter   ycenter     width    height  confidence  class    name
0  0.746094  0.522222  0.318750  0.923611    0.817871      0  person
1  0.445898  0.637326  0.745703  0.697569    0.577637      0  person
2  0.367578  0.795833  0.071875  0.400000    0.569336     27     tie
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to YOLOv5 inference and data presentation, improving usability and performance.

### 📊 Key Changes
- Minor cleanup in `hubconf.py`, correcting code format for model state dict loading.
- Introduction of `pandas` for data handling and `copy` for object duplication in `models/common.py`.
- Modified forward inference function to support automatic mixed precision and changed example image sizes in function docstring.
- Simplified inference code by removing redundant context managers and improved tensor data type handling.
- Added a new `pandas` method to the Detections class, enabling the conversion of detections to pandas DataFrames for easier analysis and manipulation.
- General code simplification in `utils/general.py` by adding pandas display option.

### 🎯 Purpose & Impact
- The changes aim to simplify the codebase, which may result in a modest performance improvement, especially in inference operations due to automatic mixed precision use.
- The introduction of pandas DataFrames for detections will make it easier for users to interact with, analyze, and visualize inference results.
- These updates will primarily impact end-users and developers who work with YOLOv5 inference, offering more streamlined data processing and possibly better integration into data-driven pipelines.

### CODE REVIEW

**Comment by lonnylundsten** [comment]
Is there any way to export to pandas or pickle from detect.py, in addition to --save-txt?

**Comment by glenn-jocher** [comment]
@lonnylundsten I'm not sure what you mean, as pandas objects are returned in the workspace here, but detect.py --save-txt is saving files to your hard drive.

**Comment by lonnylundsten** [comment]
I suppose rather than a specific exported format, what I noticed above is that the pandas df is more concise, informative, and useable than the --save-text. 

I would really like the save text (or maybe a --save-csv) function to give something similar to what I've pasted below, instead of getting a separate file for each image or frame. In addition, if the frame or image number could be added as a column that would be excellent. 

Something like this:
    xcenter,   ycenter,     width,    height,  confidence,  class,    name,    image
0,  0.746094,  0.522222,  0.318750,  0.923611,    0.817871,      0,  person,  image_001
1,  0.445898,  0.637326,  0.745703,  0.697569,    0.577637,      0,  person, image_002
2, 0.367578,  0.795833,  0.071875,  0.400000,   0.569336,     27,     tie,  image_003

**Comment by glenn-jocher** [comment]
@lonnylundsten hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Pull request merged**
