### PR TITLE
Set `TORCH_CPP_LOG_LEVEL=ERROR` for reduced verbosity

### PR DESCRIPTION
**Pull request by inisis**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced Logging Control in YOLOv5 Export Script ✨

### 📊 Key Changes
- Added a line to set the environment variable `TORCH_CPP_LOG_LEVEL` to `"ERROR"` in `export.py`.

### 🎯 Purpose & Impact
- **Purpose:** To reduce the verbosity of log messages from the PyTorch C++ backend during the export process. This change specifically filters out messages less severe than errors, making significant messages more noticeable.
- **Impact:** Users exporting models will experience a cleaner console output, making it easier to spot and address actual errors. This can lead to a more user-friendly experience during model export, particularly for those troubleshooting export issues. 🚀

### CODE REVIEW

**Comment by inisis** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@inisis thanks for the PR! What type of output are you seeing that will help suppress?

BTW we have an issue with `ultralytics` that we'd like to switch to PyTorch's built-in profiler but we have a similar problem that it is too verbose. Do you have any idea how we can silence these logging messages?

If we can figure out how to quiet the native FLOPs function down then we could migrate to it and ditch `thop` alltogether (would be awesome to eliminate an unmaintained dependency). The too-verbose output looks like this:

Screenshot 2024-05-05 at 19 35 54

**Comment by inisis** [comment]
@glenn-jocher for you first question, here are the screen shot.
image
and my pr can help fix it.

and for your second question, we can add export KINETO_LOG_LEVEL=5 to supress it,
image
I can help pr it.

**Comment by glenn-jocher** [comment]
Thanks for the screenshots, @inisis! Your PR looks promising for addressing the log issue in the first screenshot. 😊 For suppressing verbose output from PyTorch's built-in profiler as indicated in the second screenshot, setting `KINETO_LOG_LEVEL=5` sounds like a great approach. It would be fantastic if you could submit a PR for that as well! 🚀

**Comment by inisis** [comment]
@glenn-jocher can you cc me in that issue in **ultralytics** ,  i searched but didn't find it. and I think this pr can be merged and closed.

**Comment by glenn-jocher** [comment]
Hi @inisis! I'll make sure to mention you in the relevant issue on **ultralytics** once it's up for easier tracking. Regarding this PR, we'll review it shortly and merge if everything checks out. Thanks for your contributions! 😊👍

**Pull request merged**
