### PR TITLE
add base support for neptune.ai logger

### LINKED ISSUE #3164: support neptune.ai logger
## 🚀 Feature
support for neptune.ai logging

## Motivation

We need to keep track of our trainings over neptune.ai instead of wandb.

## Pitch

There may be an optional argument in train.py for logging the results to neptune.ai

## Additional context

Refer to my pr: https://github.com/ultralytics/yolov5/pull/3114

### PR DESCRIPTION
**Pull request by fcakyon**
this pr contains base logging functions for neptune.ai, after this pr its coverage can be increased similar to wandb logger

fixes https://github.com/ultralytics/yolov5/issues/3164

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of Neptune.ai logging for enhanced tracking in YOLOv5 training.

### 📊 Key Changes
- Added NeptuneLogger class to handle Neptune.ai logging.
- Setup Neptune.ai logging alongside existing WandbLogger in `train.py`.
- Included additional command-line arguments for Neptune.ai API token and project specification.
- Incorporated logic to log metrics, epoch results, and finalize the logger state at the end of the training or upon training completion.
- Added condition to save Neptune.ai logs and run ID into the model checkpoint dictionary.

### 🎯 Purpose & Impact
- Provides users with the option to use Neptune.ai for experiment tracking, which is an alternative to Weights & Biases (wandb).
- Enables detailed logging and visualization of training metrics, hyperparameters, and outputs, potentially improving experiment management and reproducibility.
- Offers better organization and tracking capabilities for users who prefer or are already using Neptune.ai in their workflows.

### CODE REVIEW

**Comment by fcakyon** [comment]
@glenn-jocher what do you think about this pr?

**Comment by fcakyon** [comment]
@glenn-jocher what do you think about this pr?

**Comment by fcakyon** [comment]
@glenn-jocher what do you think about this pr?

**Comment by fcakyon** [comment]
@glenn-jocher would you mind explaining why did you close this pr?

**Comment by glenn-jocher** [comment]
@fcakyon closed upon accidental `develop` branch deletion.

**Comment by fcakyon** [comment]
@glenn-jocher why wont you accept neptune support mate :D

**Pull request closed without merging**
