### PR TITLE
Feat/azure job integration

### PR DESCRIPTION
**Pull request by pathikg**
Changes for directly submitting a training job to azureml 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of YOLOv5 with Azure Machine Learning to enable automated training jobs.

### 📊 Key Changes
- Added a new `config.yaml` file to contain configuration parameters for training.
- Introduced a new `data/lossrun-ca.yaml` for class and path configurations.
- Implemented a new `job.py` script to set up and run training jobs on Azure ML.
- Added Azure ML dependencies to `requirements.txt`.
- Modified `train.py` to accept parameters from `config.yaml`.

### 🎯 Purpose & Impact
- **Purpose**: To streamline the setup and execution of training YOLOv5 models on Azure, utilizing configurations that can be easily adjusted.
- **Impact**: 
  - Automates the model training process, saving time and reducing the propensity for human error.
  - Facilitates scale-up and reproducibility, allowing for more efficiency in utilizing cloud GPU resources.
  - Provides a foundation for users to customize their training jobs in a cloud environment with a simple config file adjustment. 🚀

### CODE REVIEW

**Comment by pathikg** [comment]
Hey @glenn-jocher, while working on the azure-ml job integration we accidentally uploaded our PR to the master branch with our azure credentials 
So kindly requesting you to delete this PR as it exposed our private info, if possible.
We'll make sure such things won't happen in the future 
Thank you

**Comment by glenn-jocher** [comment]
@pathikg hi there! Thank you for bringing this issue to our attention. We understand the concern regarding the accidental exposure of private information in the PR. We apologize for any inconvenience caused.

Rest assured, your PR will be reviewed, and we'll take the necessary steps to address this. We appreciate your dedication to ensuring the security of your credentials.

If you have any other questions or concerns, please feel free to let us know. We're here to help!

Thank you for your understanding and for your contributions to YOLOv5.

Kind regards,
Glenn Jocher

**Comment by pathikg** [comment]
@glenn-jocher 
I appreciate you bringing this issue to light. 
Since it is crucial to our side, kindly review and delete the same as soon as you can. 
Regards

**Comment by glenn-jocher** [comment]
@pathikg thank you for reaching out to us and bringing this issue to our attention. We understand the importance of promptly addressing and resolving this matter. Rest assured, we will review and delete the mentioned PR as soon as possible. 

If you have any further concerns or questions, please feel free to let us know. We're here to assist you.

Thank you,
Glenn Jocher

**Comment by pathikg** [comment]
Hey @glenn-jocher 
Any update on the same?

**Comment by glenn-jocher** [comment]
@pathikg hi there!

Thank you for reaching out. Could you please provide some more information about the specific issue or question you are referring to? This will help me understand and address your concern more effectively.

Looking forward to assisting you further.

Glenn Jocher

**Comment by pathikg** [comment]
hey @glenn-jocher 
I wanted to remind you about deleting this PR since it exposed some of or azure credentials and its been more than a week

**Comment by glenn-jocher** [comment]
@pathikg hi there!

Thank you for reminding us about the need to delete the PR that exposed your Azure credentials. We apologize for any delay in taking action on this matter. We understand the importance of promptly addressing and resolving security concerns.

We will ensure that the PR is reviewed and removed as soon as possible. Once again, we apologize for any inconvenience caused and appreciate your understanding.

Kind regards,
Glenn Jocher

**Comment by pathikg** [comment]
Any update? @glenn-jocher 
Two weeks have passed with no update.

**Comment by glenn-jocher** [comment]
@pathikg hi there! Thank you for your patience. I apologize for the delay in providing an update. We understand the importance of timely responses and we're working diligently to address all outstanding issues. Your issue is important to us and we'll provide an update as soon as we have more information. Thank you for your understanding.

**Pull request closed without merging**
