### PR TITLE
Windows Python 3.7 .isfile() fix

### PR DESCRIPTION
**Pull request by SSTato**
Signed-off-by: SSTato <1210546396@qq.com>

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved file existence checks in Ultralytics dataloaders and utility functions.

### 📊 Key Changes
- Modified the method of checking if a file exists from using `Path.is_file()` to `os.path.isfile()`.
- Clarified and standardized the file existence validation across different parts of the code.

### 🎯 Purpose & Impact
- **Consistency:** Standardizing file checks makes the codebase more uniform and easier to maintain.
- **Compatibility:** The `os` module's file check methods are widely accepted, ensuring better compatibility across different operating systems.
- **Reliability:** These changes could increase the reliability of file handling within the toolkit, which benefits users in smoother data loading and processing.

### CODE REVIEW

**Comment by SSTato** [comment]
Resolve Issue # 9866

**Comment by glenn-jocher** [comment]
@SSTato I added Windows URL download test to CI in https://github.com/ultralytics/yolov5/blob/eef90572bf11602b17816a1721980cdb07a95eb2/detect.py#L252 and observed no problems in Windows. 

See https://github.com/glenn-jocher/yolov5/pull/2

Screenshot 2022-10-21 at 21 29 11

**Comment by SSTato** [comment]
I replaced my computer with a new one and downloaded the latest yolov5-master. He had no problem checking the pictures.


However, when I check the URL, I still make mistakes. The problem is still the line of code.


It does have problems with Windows 10, and I've tried it many times.
My new computer configuration is:
Windows 10 Python-3.7.10 torch-1.8.1+cu111 CUDA:0 (GeForce RTX 3060 Ti, 8192MiB)

**Comment by SSTato** [comment]
The problem is that the code 'Path(sources).is_file()' cannot run correctly on my computer. Replacing it with 'os.path.isfile(sources)' can solve this problem.

**Comment by glenn-jocher** [comment]
@SSTato I wonder if it's a Python 3.7 issue with Windows. I'll update the CI to 3.7 to see what happens.

**Comment by SSTato** [comment]
> @SSTato I wonder if it's a Python 3.7 issue with Windows. I'll update the CI to 3.7 to see what happens.

Python 3.8 has the same problem

**Comment by glenn-jocher** [comment]
Ok yes I see that 3.7 Pathlib usage might not allow for .is_file()

I wonder if we can replace it with .exists()

Screenshot 2022-10-22 at 15 47 28

**Comment by glenn-jocher** [comment]
@SSTato ok I've updated based on fixes in https://github.com/glenn-jocher/yolov5/pull/2 that pass Windows 3.7, 3.8 CI.

**Comment by SSTato** [comment]
> @SSTato ok I've updated based on fixes in [glenn-jocher#2](https://github.com/glenn-jocher/yolov5/pull/2) that pass Windows 3.7, 3.8 CI. Can you try the PR now and let me know if this resolves your issue?

I tested https://github.com/glenn-jocher/yolov5/pull/2, which can be used in python 3.7. For ' python detect py --source https://ultralytics.com/images/zidane.jpg 'No problem



but when I' python detect py --source rtsp://admin:abc12345 @192.168.1.71/Streaming/Channels/1 ', it still has errors, and' dataloaders. py 'needs to be modified. After that, it has no errors.

**Comment by SSTato** [comment]
I can correctly run the code before the change on python 3.9, so it can be determined that the problem is the python version. There is no problem when the yolov5-master is above python 3.9, but there are problems I raised with python 3.7 and 3.8.

**Comment by glenn-jocher** [comment]
@SSTato PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
