### PR TITLE
Bug fix mAP0.5-0.95

### PR DESCRIPTION
**Pull request by lebedevdes**
Two changes provided
1. Added limit on the maximum number of detections for each image likewise pycocotools
2. Rework process_batch function

Changes #2 solved issue #4251
I also independently encountered the problem described in issue #4251 that the values for the same thresholds do not match when changing the limits in the torch.linspace function.
These changes solve this problem.

Currently during validation yolov5x.pt model the following results were obtained:
from yolov5 validation
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 157/157 [01:07<00:00,  2.33it/s]
                 all       5000      36335      0.743      0.626      0.682      0.506
from pycocotools
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.505
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.685

These results are very close, although not completely pass the competition issue #2258.
I think it's problem with false positive bboxes matched ignored criteria, but this is not actual for custom datasets and does not require an additional solution.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to type conversions and matching criteria in YOLOv5 validation code.

### 📊 Key Changes
- Updated numpy type conversions from `.astype('int32')` and `.astype(np.int16)` to `.astype(int)`.
- Refactored matching logic in `process_batch` to iterate over different IoU (Intersection over Union) thresholds.
- Changed tensor indexing to use `.astype(int)` in `val.py`, ensuring compatibility across data types.

### 🎯 Purpose & Impact
- The type conversion change ensures more general integer representation for better compatibility across platforms.
- The improved matching logic allows for more precise performance evaluation at different IoU thresholds, likely leading to more accurate model validation results.
- These updates may provide a slight performance increase and ensure more consistent behavior in different environments, benefiting both developers working with the code and users relying on the model's accuracy.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@lebedevdes resolved conflicts and updated PR. I will take a look at this, I don't know why it's been left open so long.

**Comment by glenn-jocher** [comment]
@lebedevdes it seems like the pred = pred[:100] line is reducing the pycocotools mAP. If I remove it pycocotools mAP remains unchanged while YOLOv5 mAP slightly reduces as well, which is probably the preferred solution as it still represents a big improvement over current.

**Comment by glenn-jocher** [comment]
@lebedevdes PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by lebedevdes** [comment]
@glenn-jocher Glad to help, thanks for your great project)

**Comment by glenn-jocher** [comment]
@lebedevdes thanks for your kind words, but the real credit goes to the YOLO community and the Ultralytics team. We greatly appreciate your contributions! If you have any more ideas or feedback, feel free to share them with us.

**Pull request merged**
