### PR TITLE
Added different attension mechanism 

### PR DESCRIPTION
**Pull request by akashAD98**
I have added an attention mechanism to train model

image

image

#you can use any attension mechanism to add this in yolov5
if this feature is helpful please let me know . then ill add detailed steps for what things we need to change

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Seems like we've hit a hiccup – this PR contains no actual code changes!

### 📊 Key Changes
- None, as the PR diff is empty.

### 🎯 Purpose & Impact
- There is no direct impact or benefit from this PR as it stands, since it doesn't modify the codebase. It might be a placeholder or an error. 🤷‍♂️

### CODE REVIEW

**Comment by AyushExel** [comment]
@akashAD98 just curious, have you trained any of these yolov5-attention models? Have you got some benchmarks?

**Comment by akashAD98** [comment]
@AyushExel i haven’t trained for large no of steps ,due to limited resources, but I’ll do it in future,if anybody wants to do they can train & share the benchmark here .Thanks

**Comment by akashAD98** [comment]
@AyushExel  @glenn-jocher  i trained the model for 250 epochs  using siam_module attention
here are the results


image


#Train YOLOv5s on COCO128 250 steps
``` !python train.py --img 640  --batch 16 --epochs 250 --data coco128.yaml --weights yolov5s.pt --cache --cfg /content/yolov5/models/yolov5s.yaml ```

claawise map : [map_coc128.txt](https://github.com/ultralytics/yolov5/files/9753041/map_coc128.txt)

**Comment by glenn-jocher** [comment]
@akashAD98 thanks for the PR! I'm reviewing it and I see there are many different modules. I'm trying to understand which attention modules are the most important, i.e. are there any that are no longer relevant that we can remove from the PR to reduce it?

Have you experimented with the different bottlenecks? i.e.:

- C3SE
- C3CA
- C3ECA
- C3CBAM

**Comment by akashAD98** [comment]
i trained model using C3SE , 

image

command i used 
```!python train.py --img 640 --batch 16 --cfg /content/yolov5/models/yolov5s.yaml --epochs 250 --data coco128.yaml --weights yolov5s.pt --cache```



image


[C3SE_attention_map.txt](https://github.com/ultralytics/yolov5/files/9793594/C3SE_attention_map.txt)

**Comment by akashAD98** [comment]
For C3CBAM im getting this error https://github.com/pytorch/pytorch/issues/87029

**Comment by glenn-jocher** [comment]
@akashAD98 so C3SE produced the best results out of the 4 above? Why only use it in one place rather than throughout the whole model?

**Comment by akashAD98** [comment]
@glenn-jocher i was doing experiments,I’ll test it & let you know

**Comment by akashAD98** [comment]
this is comparison of all models,  @glenn-jocher 

image

from this model C3SE is good, but I added only at the last laer of backbone ,you can see the result.


for CBAM &  C3CA model I'm getting this error


```RuntimeError: adaptive_max_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation```

image

**Comment by akashAD98** [comment]
> init_seeds(opt.seed + 1 + RANK, deterministic=True)

@glenn-jocher yes 0.09% only. but (if you can check c3se attention in applied at 1 layer ) P - 1%, Recall - 3 % higher than base yolov5s.cfg,

**Comment by akashAD98** [comment]
> > appears that base YOLO without attention presents
> 
> May I ask how to add this attention module into the current YOLO program? Thank you so much. I just add one layer in module forward, is it correct? Hope to get more details.

yes you need to add attention code in common.py , & modify files yolo.py & cfg

**Comment by frabob2017** [comment]
> > > appears that base YOLO without attention presents
> > 
> > 
> > May I ask how to add this attention module into the current YOLO program? Thank you so much. I just add one layer in module forward, is it correct? Hope to get more details.
> 
> yes you need to add attention code in common.py , & modify files yolo.py & cfg

Thank you so much. My purpose is to reinforce the detection accuracy in the continuous slices. If a lesion is detected in one slice with high confidence, the chance to detect it in the next slice is also very high. I want to use this information as an attention for the next slice to improve the detection accuracy, based on my understanding, the attention network will work in this scenario. Is my understanding correct?  I will study your common.py file. Thank you so much.

**Comment by akashAD98** [comment]
@frabob2017 exactly

**Comment by frabob2017** [comment]
Hello I check your code. I found my theoretic knowledge is not enough to understand your code.  Do you have a paper to recommend to read to understand your code? Based on my understanding of the code,  It looks like that you get the weights along dim=1, then  torch.mult(x,out);  but I want to reinforce the weight from the bounding box and applied to the next slices. Do these codes solve this requirements?   Thank you so much.  Frank Cai

avg_out=torch.mean(x,dim=1,keepdim=True)
max_out, _ = torch.max(x,dim=1,keepdim=True)

If I only want to add more weight to the 

class SpatialAttention(nn.Module):
  def __init__(self,kernel_size=7):
    super(SpatilAttenion,self).__init__()

    assert kerel_size in (3,7),'kernal size must be 3 or 7'
    padding =3 if kernel_size ==7 else 1

    self.conv =nn.Conv2d(2,1,kernel_size,padding=padding,bias=False)
    self.sigmoid =nn.Sigmoid()
  def forward(self,x):
    avg_out=torch.mean(x,dim=1,keepdim=True)
    max_out, _ = torch.max(x,dim=1,keepdim=True)
    out = torch.cat([avg_out,max_out],dim=1)
    out =self.sigmoid(self.conv(out))
    return torch.mult(x,out)

**Comment by frabob2017** [comment]
Hello Akash,  Where can I find your URL so I can git clone your code directly for use?. At this stage, I feel some difficult to integrate your code into YOLOv5 code.   I check your https://github.com/akashAD98

But I do not find there is URL for for Git clone it.

image

**Comment by ExtReMLapin** [comment]
Comparing metrics on custom dataset : 
Nano6 model
```txt
                 from  n    params  module                                  arguments
  0                -1  1      1760  models.common.Conv                      [3, 16, 6, 2, 2]
  1                -1  1      4672  models.common.Conv                      [16, 32, 3, 2]
  2                -1  1      4800  models.common.C3                        [32, 32, 1]
  3                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  4                -1  2     29184  models.common.C3                        [64, 64, 2]
  5                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  6                -1  3    156928  models.common.C3                        [128, 128, 3]
  7                -1  1    221568  models.common.Conv                      [128, 192, 3, 2]
  8                -1  1    167040  models.common.C3                        [192, 192, 1]
  9                -1  1    442880  models.common.Conv                      [192, 256, 3, 2]
 10                -1  1    296448  models.common.C3                        [256, 256, 1]
 11                -1  1    164608  models.common.SPPF                      [256, 256, 5]
 12                -1  1     49536  models.common.Conv                      [256, 192, 1, 1]
 13                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 14           [-1, 8]  1         0  models.common.Concat                    [1]
 15                -1  1    203904  models.common.C3                        [384, 192, 1, False]
 16                -1  1     24832  models.common.Conv                      [192, 128, 1, 1]
 17                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 18           [-1, 6]  1         0  models.common.Concat                    [1]
 19                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 20                -1  1      8320  models.common.Conv                      [128, 64, 1, 1]
 21                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 22           [-1, 4]  1         0  models.common.Concat                    [1]
 23                -1  1     22912  models.common.C3                        [128, 64, 1, False]
 24                -1  1     36992  models.common.Conv                      [64, 64, 3, 2]
 25          [-1, 20]  1         0  models.common.Concat                    [1]
 26                -1  1     74496  models.common.C3                        [128, 128, 1, False]
 27                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 28          [-1, 16]  1         0  models.common.Concat                    [1]
 29                -1  1    179328  models.common.C3                        [256, 192, 1, False]
 30                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]
 31          [-1, 12]  1         0  models.common.Concat                    [1]
 32                -1  1    329216  models.common.C3                        [384, 256, 1, False]
 33  [23, 26, 29, 32]  1     11592  models.yolo.Detect                      [1, [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], [64, 128, 192, 256]]
```

Nano6 model with SPP and CBAM +  C3->C3TR

**Comment by akashAD98** [comment]
> Hello Akash, Where can I find your URL so I can git clone your code directly for use?. At this stage, I feel some difficult to integrate your code into YOLOv5 code. I check your https://github.com/akashAD98 click pull request.
> 
> But I do not find there is URL for for Git clone it.
> 
> image

you can use this  @frabob2017  https://github.com/akashAD98/yolov5

**Comment by frabob2017** [comment]
Thank you so much.  I will study of it.  If time is allowed, I will compare the detection accuracy in my datasets between yours and standard YOLOv5.

**Comment by urbaneman** [comment]
> this is comparison of all models, @glenn-jocher
> 
> image
> 
> from this model C3SE is good, but I added only at the before SPPF layer of backbone ,you can check the results
> 
> for CBAM & C3CA model I'm getting this error
> 
> `RuntimeError: adaptive_max_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation`
> 
> image
> 
> can you help me to solve this issue? so ill train other models also
> 
> thanks

I meet the same `RuntimeError`, How did you solved it?

**Comment by alkhalisy** [comment]
Dear akashAD98 when I try to add CBAM module as your said in the previous post the error message bellow happen, can you explain what the error and how can we solve it, I used your updated file. 
Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
  0% 0/275 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/yolov5/train.py", line 642, in <module>
    main(opt)
  File "/content/yolov5/train.py", line 531, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/yolov5/train.py", line 320, in train
    scaler.scale(loss).backward()
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
**RuntimeError: adaptive_max_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.**

**Comment by glenn-jocher** [comment]
@alkhalisy you're welcome! I hope you find my code helpful. I would be interested in hearing about your results and any feedback you have. Don't hesitate to reach out if you have any questions or issues.

**Comment by Malikanhar** [comment]
Hi @akashAD98 thank you for such a great implementation for the attention module in Yolov5, I would like to ask regarding the arguments of the `CBAM` `__init()__` function.

```
class CBAM(nn.Module):
    # CSP Bottleneck with 3 convolutions
    def __init__(self, c1, c2, ratio=16, kernel_size=7):  # ch_in, ch_out, number, shortcut, groups, expansion
        super().__init__()
        self.channel_attention = ChannelAttention(c1, ratio)
        self.spatial_attention = SpatialAttention(kernel_size)

    def forward(self, x):
        out = self.channel_attention(x) * x
        # c*h*w
        # c*h*w * 1*h*w
        out = self.spatial_attention(out) * out
        return out
```

What is exactly the use of `c2`? Thanks

**Comment by glenn-jocher** [comment]
Hello @Malikanhar, thank you for your feedback and question. The `c2` argument is not used in the `CBAM` `__init__` function. It is not necessary for this implementation and can be ignored. The only necessary arguments are `c1`, `ratio`, and `kernel_size`. I hope this helps clarify things for you. Let me know if you have any further questions or concerns.

**Comment by Malikanhar** [comment]
@glenn-jocher but if I remove the `c2` argument, it will cause an errror

```
[/content/ultralytics/ultralytics/nn/modules/conv.py](https://localhost:8080/#) in __init__(self, kernel_size)
    262         """Initialize Spatial-attention module with kernel size argument."""
    263         super().__init__()
--> 264         assert kernel_size in (3, 7), 'kernel size must be 3 or 7, found {}'.format(kernel_size)
    265         padding = 3 if kernel_size == 7 else 1
    266         self.cv1 = nn.Conv2d(2, 1, kernel_size, padding=padding, bias=False)

AssertionError: kernel size must be 3 or 7, found 64
```

**Comment by Malikanhar** [comment]
@glenn-jocher and I found that CBAM [implementation](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/conv.py#L277) on Yolov8 not using the `c2` argument and it cause an error when I'm trying to use it. But if I add the `c2` argument the error just disappeared. Maybe someone should look closer to this implementation

**Comment by glenn-jocher** [comment]
@Malikanhar thank you for bringing this to our attention. We apologize for any confusion or inconvenience this may have caused. We appreciate your feedback and will investigate this issue further to ensure that our implementation of the CBAM module in YOLOv8 is as accurate and efficient as possible. In the meantime, we suggest adding the `c2` argument to avoid any errors. Please let us know if you have any further questions or concerns.

**Comment by zeobec** [comment]
> @glenn-jocher sir did you accept this pr? Those who want to train their models with an attention mechanism can try this. also, I think lots of new attention are coming & so we can't ignore this.
> 
> c3se is best compared to other attention mechanism from this experiment image

may I know if attention module C3SE works for YOLOv8 as well?

**Comment by glenn-jocher** [comment]
@zeobec the attention mechanisms like C3SE are designed to be modular and can potentially be integrated into different versions of YOLO, including YOLOv8, provided that the necessary modifications are made to accommodate the architecture differences. However, each YOLO version may have specific design choices and optimizations, so the integration and performance of C3SE or any other attention mechanism would need to be carefully evaluated and tested within the context of YOLOv8. If you're interested in trying out C3SE with YOLOv8, you would need to adapt the code accordingly and ensure compatibility with the YOLOv8 architecture.

**Pull request closed without merging**
