### PR TITLE
Added MSCOCO API installation command to requirements.txt

### PR DESCRIPTION
**Pull request by sowndappan5**
Added the MSCOCO API installation command to the requirements.txt for better detection performance

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update dependencies to include Cython and cocoapi for improved functionality.

### 📊 Key Changes
- Added `Cython>=0.29.36` to `requirements.txt`.
- Included `cocoapi` from GitHub for MSCOCO support.

### 🎯 Purpose & Impact
- 🛠 **Enhanced Functionality**: Cython and cocoapi enable more efficient handling of COCO datasets.
- 📈 **Improved COCO Support**: Facilitates better integration and performance when working with COCO annotations.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @sowndappan5, thank you for submitting an `ultralytics/yolov5` 🚀 PR! This is an automated response to guide you through our contribution process. An Ultralytics engineer will review your submission shortly. Meanwhile, please ensure your PR aligns with the checklist below:

- ✅ **Purpose Clarification**: Clearly define the purpose of adding the MSCOCO API installation command in the PR description, and link any [relevant issues](https://github.com/ultralytics/yolov5/issues) you may be addressing.
- ✅ **Branch Synchronization**: Confirm your PR is up-to-date with the `main` branch. If updates are needed, click 'Update branch' or run `git pull` and `git merge main` locally.
- ✅ **CI Checks**: Ensure all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks pass. Address any that fail.
- ✅ **Documentation Updates**: If your changes affect usage, update the [documentation](https://docs.ultralytics.com) accordingly.
- ✅ **Tests**: Add or update tests to verify your changes and confirm all tests pass.
- ✅ **Contributor License Agreement**: Make sure you’ve signed our [CLA](https://docs.ultralytics.com/help/CLA/) by stating "I have read the CLA Document and I sign the CLA" in a comment if this is your first contribution.
- ✅ **Minimal Changes**: Keep your changes minimal and focused on the intended feature or fix. Remember, _"It is not daily increase but daily decrease, hack away the unessential."_  — Bruce Lee

For further details, see our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to ask questions or request assistance as needed. Your work helps make Ultralytics better! 👍

**Comment by sowndappan5** [comment]
I have read the CLA Document and I sign the CLA

**Comment by sowndappan5** [comment]
recheck

**Comment by sowndappan5** [comment]
> All Contributors have signed the CLA. ✅Posted by the **CLA Assistant Lite bot**.

**Comment by pderrenger** [comment]
@sowndappan5 thank you for confirming the CLA. If you have any questions or need further assistance, feel free to ask!

**Pull request closed without merging**
