### PR TITLE
Fix `cv2.imwrite` on non-ASCII paths

### PR DESCRIPTION
**Pull request by CCRcmcpe**
Previous PR https://github.com/ultralytics/yolov5/pull/6979 fixed `imread`. But I discovered `imwrite` is also broken: when saving a image, Unicode characters in the path are converted to meaningless characters, or it does not save the image at all.
Also moved the custom `imread` to `utils.general`.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactoring OpenCV image read/write functions for compatibility with non-latin filenames.

### 📊 Key Changes
- Removed direct `import cv2` statements from multiple files (`detect.py`, `hubconf.py`, and `datasets.py`).
- Re-defined `cv2.imread` and `cv2.imwrite` functions with custom Chinese-friendly versions in `utils/general.py`.
- Replaced original OpenCV image read/write calls with new custom functions across different modules.

### 🎯 Purpose & Impact
- 👨‍💻 **Developers**: Simplifies codebase by centralizing custom OpenCV functions, reducing direct imports, and remapping functions in a single location.
- 🌍 **Global Users**: Enhances functionality for users with non-latin filenames, offering broader international support for image file operations.
- 🚀 **Performance**: Streamlined interoperability with OpenCV without altering performance or functionality for existing users with latin-based filenames.

### CODE REVIEW

**Comment by CCRcmcpe** [comment]
image
image

**Comment by glenn-jocher** [comment]
@CCRcmcpe ok got it. What we should do then is this. Create the two functions in general.py and then assign them to cv2:

```python
def imread(path):
    return cv2.imdecode(np.fromfile(path, np.uint8), cv2.IMREAD_COLOR)


def imwrite(path, img):
    try:
        cv2.imencode(Path(path).suffix, img)[1].tofile(path)
        return True
    except:
        return False


cv2.imread, cv2.imwrite = imread, imwrite
```

Then everywhere that imports cv2, change it to:

```python
from utils.general import cv2
```
And finally delete all other changes from https://github.com/ultralytics/yolov5/pull/6979 and this PR. Then everything should work well with a minimum of customizations to the code.

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@CCRcmcpe PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by CCRcmcpe** [comment]
> @CCRcmcpe ok got it. What we should do then is this. Create the two functions in general.py and then assign them to cv2:
> 
> ```python
> def imread(path):
>     return cv2.imdecode(np.fromfile(path, np.uint8), cv2.IMREAD_COLOR)
> 
> 
> def imwrite(path, img):
>     try:
>         cv2.imencode(Path(path).suffix, img)[1].tofile(path)
>         return True
>     except:
>         return False
> 
> 
> cv2.imread, cv2.imwrite = imread, imwrite
> ```
> 
> Then everywhere that imports cv2, change it to:
> 
> ```python
> from utils.general import cv2
> ```
> 
> And finally delete all other changes from #6979 and this PR. Then everything should work well with a minimum of customizations to the code.

Great! I'm relatively new to python so I don't know can actually import like this.

**Comment by glenn-jocher** [comment]
@CCRcmcpe it's a bit of an experimental approach, but yes you can overwrite imports, or most any other variable/method after they are defined.

**Pull request merged**
