### PR TITLE
Batch inference

### PR DESCRIPTION
**Pull request by gilbo123**
Thank you for submitting a YOLOv5 🚀 Pull Request! We want to make contributing to YOLOv5 as easy and transparent as possible. A few tips to get you started:

- Search existing YOLOv5 [PRs](https://github.com/ultralytics/yolov5/pull) to see if a similar PR already exists.
- None
- Link this PR to a YOLOv5 [issue](https://github.com/ultralytics/yolov5/issues) to help us understand what bug fix or feature is being implemented.
- https://github.com/ultralytics/yolov5/issues/604, https://github.com/ultralytics/yolov5/issues/764
- Provide before and after profiling/inference/training results to help us quantify the improvement your PR provides (if applicable).
- Text output is the only noticeable difference  

Please see our ✅ [Contributing Guide](https://github.com/ultralytics/yolov5/blob/master/CONTRIBUTING.md) for more details.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced `detect.py` with batch processing support for images and videos.

### 📊 Key Changes
- Added `batch_size` as an argument to the `run` function and within image processing workflow.
- Modified `LoadImages` in `utils/datasets.py` to handle multiple images concurrently.
- Updated logging and saving routines to accommodate batch processing.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: To enable batch processing of images and videos, allowing multiple files to be processed at once for improved efficiency.
- 💥 **Impact**: Users can now run inference on batches of images or videos, leading to faster processing times and more streamlined workflows.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@gilbo123 looks like you have a number of PEP8 updates required before this will pass CI. See https://results.pre-commit.ci/run/github/264818686/1646389265.7QQVhb0LRievAMnnvQ70HQ

**Comment by gilbo123** [comment]
I have corrected them and resubmitted. These PEP8 issues were inherited (I fixed my own originally, but not these because I didn't change any of the code they refer to).

**Comment by Spudi2007** [comment]
Hello, guys
I tried to run your code, however i got an error:
ValueError: could not broadcast input array from shape (3,640,480) into shape (3)
As far as I understand, it is due to the fact that Zidane and the bus have different sizes. If you take pictures with the same resolution, then everything works. Please tell me, is this the final version of the batch inference? If so, could you give me some advice on how to assemble a batch of images with different resolutions. Thank you! 
Thanks for the work you are doing.

**Comment by Spudi2007** [comment]
Hello, guys
I tried to run your code, however i got an error:
ValueError: could not broadcast input array from shape (3,640,480) into shape (3)
As far as I understand, it is due to the fact that Zidane and the bus have different sizes. If you take pictures with the same resolution, then everything works. Please tell me, is this the final version of the batch inference? If so, could you give me some advice on how to assemble a batch of images with different resolutions. Thank you! 
Thanks for the work you are doing.

**Comment by glenn-jocher** [comment]
@Spudi2007 👋 Hello! Thanks for asking about **handling inference results**. YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference (including batched inference) in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
```


See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by zxq309** [comment]
@gilbo123 The saved video's quality is blurry, is the frame rate too fast, or others?

**Comment by gilbo123** [comment]
> @gilbo123 The saved video's quality is blurry, is the frame rate too fast, or others?

Thankyou, now corrected. Please let me know of any other issues.

**Comment by zxq309** [comment]
> > @gilbo123 The saved video's quality is blurry, is the frame rate too fast, or others?
> 
> Thankyou, now corrected. Please let me know of any other issues.

image
thanks for you reply. I run detect.py, batch_size=1, all detect is correct, however，This error appears at the end of the run, what happened?
batch_size=4,8,16 are correct.

**Comment by gilbo123** [comment]
> thanks for you reply. I run detect.py, batch_size=1, all detect is correct, however，This error appears at the end of the run, what happened?
> batch_size=4,8,16 are correct.

StopIteration logic for batch-size 1 was incorrect. Thanks, should be corrected now.

**Comment by zxq309** [comment]
> > thanks for you reply. I run detect.py, batch_size=1, all detect is correct, however，This error appears at the end of the run, what happened?
> > batch_size=4,8,16 are correct.
> 
> StopIteration logic for batch-size 1 was incorrect. Thanks, should be corrected now.

everything is OK，Thank you.

**Comment by gilbo123** [comment]
> I tried to run your code, however i got an error:
> ValueError: could not broadcast input array from shape (3,640,480) into shape (3)
> As far as I understand, it is due to the fact that Zidane and the bus have different sizes. If you take pictures with the same resolution, then everything works. Please tell me, is this the final version of the batch inference? If so, could you give me some advice on how to assemble a batch of images with different resolutions. Thank you!

@Spudi2007. Unfortunately, the input tensor cannot be made up of tensors (images) with varying shapes - as is the case with the return of the letterbox() function. 

If you wanted to, you could pre-process a dataset by zero-padding the images or resizing, so that they are all the same shape, before running detect.py.

For now, I have added a check for image shape consistency for each batch so that the program reports the error and stops if sequential image shapes don't match.

**Comment by Vlad188-1** [comment]
> > I tried to run your code, however i got an error:
> > ValueError: could not broadcast input array from shape (3,640,480) into shape (3)
> > As far as I understand, it is due to the fact that Zidane and the bus have different sizes. If you take pictures with the same resolution, then everything works. Please tell me, is this the final version of the batch inference? If so, could you give me some advice on how to assemble a batch of images with different resolutions. Thank you!
> 
> @Spudi2007. Unfortunately, the input tensor cannot be made up of tensors (images) with varying shapes - as is the case with the return of the letterbox() function.
> 
> If you wanted to, you could pre-process a dataset by zero-padding the images or resizing, so that they are all the same shape, before running detect.py.
> 
> For now, I have added a check for image shape consistency for each batch so that the program reports the error and stops if sequential image shapes don't match.

Hello, @gilbo123! I have the questions for you. I have prepared data for batch inference (Images have the same size), then I did some experiments. Dataset contained 5000 images (animals). The size of images was 1280*960. I varied the batch size and timed the detector:

1. batch_size = 1, time = 3 minutes 30 seconds
2. batch_size = 4, time = 3 minutes 14 seconds
3. batch_size = 8, time = 3 minutes 12 seconds
4. batch_size = 16, time = 3 minutes 12 seconds
5. batch_size = 24, time = 3 minutes 15 seconds
6. batch_size = 32, time = 3 minutes 14 seconds

In my opinion, increasing of batch size doesn't give a significant increase in the speed of the detector. If you look at the difference in time between batch_size = 1 and batch_size = 4, we see a speed gain of around 7-8%. This is a fairly small increase in speed. Recently I did batch inference for efficientnet-v2 classifier and got a significant increase in the speed of the classiffication (about 50%). My questions are:

1) Have you done experiments like mine?
2) If the answer to the first question is yes,  then what speed increase did you get for the detector?

All experiments were carried out on RTX 3080.

**Comment by gilbo123** [comment]
> > > I tried to run your code, however i got an error:
> > > ValueError: could not broadcast input array from shape (3,640,480) into shape (3)
> > > As far as I understand, it is due to the fact that Zidane and the bus have different sizes. If you take pictures with the same resolution, then everything works. Please tell me, is this the final version of the batch inference? If so, could you give me some advice on how to assemble a batch of images with different resolutions. Thank you!
> > 
> > 
> > @Spudi2007. Unfortunately, the input tensor cannot be made up of tensors (images) with varying shapes - as is the case with the return of the letterbox() function.
> > If you wanted to, you could pre-process a dataset by zero-padding the images or resizing, so that they are all the same shape, before running detect.py.
> > For now, I have added a check for image shape consistency for each batch so that the program reports the error and stops if sequential image shapes don't match.
> 
> Hello, @gilbo123! I have the questions for you. I have prepared data for batch inference (Images have the same size), then I did some experiments. Dataset contained 5000 images (animals). The size of images was 1280*960. I varied the batch size and timed the detector:
> 
>     1. batch_size = 1, time = 3 minutes 30 seconds
> 
>     2. batch_size = 4, time = 3 minutes 14 seconds
> 
>     3. batch_size = 8, time = 3 minutes 12 seconds
> 
>     4. batch_size = 16, time = 3 minutes 12 seconds
> 
>     5. batch_size = 24, time = 3 minutes 15 seconds
> 
>     6. batch_size = 32, time = 3 minutes 14 seconds
> 
> 
> In my opinion, increasing of batch size doesn't give a significant increase in the speed of the detector. If you look at the difference in time between batch_size = 1 and batch_size = 4, we see a speed gain of around 7-8%. This is a fairly small increase in speed. Recently I did batch inference for efficientnet-v2 classifier and got a significant increase in the speed of the classiffication (about 50%). My questions are:
> 
>     1. Have you done experiments like mine?
> 
>     2. If the answer to the first question is yes,  then what speed increase did you get for the detector?
> 
> 
> All experiments were carried out on RTX 3080.

Hi @Vlad188-1. Yes, I have tested similarly to you and have the same results:

RTX 2080 Ti
1 - 6.7ms
8 - 4.7ms
16 - 4.7ms
32 - 4.9ms
64 - 4.9ms

RTX 3070
1 - 6.2ms
8 - 5.3ms
16 - 4.9ms
32 - 5.7ms
64 - 5.5ms


This is average time per image over 1000 images (imgsz=960). Not the results I was expecting, either...

**Comment by glenn-jocher** [comment]
@gilbo123 @Vlad188-1 see https://community.ultralytics.com/t/yolov5-study-batch-size-vs-speed

**Comment by gilbo123** [comment]
> @gilbo123 @Vlad188-1 see https://community.ultralytics.com/t/yolov5-study-batch-size-vs-speed

Thanks Glenn. I assume this study used torch.load() as opposed to detect.py? I get more consistent speed increases when batching with torch.load() as well. However, I still am confused given detect.py is designed to accept batches e.g: 
'''
if len(im.shape) == 3: 
    im = im[None]  # expand for batch dim) 
'''
Would you have expected a similar result as your study?

Thanks for your help.

**Comment by gilbo123** [comment]
Thanks Glenn. I assume this study used torch.load() as opposed to detect.py? I get more consistent speed increases when batching with torch.load() as well. However, I still am confused given detect.py is designed to accept batches e.g:
```if len(im.shape) == 3:
im = im[None] # expand for batch dim)```

Would you have expected a similar result as your study?

Thanks for your help.

**Comment by gilbo123** [comment]
Thanks Glenn. I assume this study used torch.load() as opposed to detect.py? I get more consistent speed increases when batching with torch.load() as well. However, I still am confused given detect.py is designed to accept batches e.g:
```
if len(im.shape) == 3:
im = im[None] # expand for batch dim)
```

Would you have expected a similar result as your study?

Thanks for your help.

**Comment by gilbo123** [comment]
Thanks @glenn-jocher . I assume this study used torch.load() as opposed to detect.py? I get more consistent speed increases when batching with torch.load() as well. However, I still am confused given detect.py is designed to accept batches e.g:
```
if len(im.shape) == 3:
    im = im[None] # expand for batch dim)
```

Would you have expected a similar result as your study?

Thanks for your help.

**Comment by glenn-jocher** [comment]
@gilbo123 yes results should be nearly identical as the inference engine is the same for both (YOLOv5 DetectMultiBackend class). The main difference is that our hub inference was built from the ground up with batched inference in mind, wheras detect.py was an earlier effort that assumed batch-size 1 for images and videos. 

detect.py streamloaders use batched inference though. The use case there is i.e. 16 web cameras passed for inference as `python detect.py --source streams.txt`, then the multithreaded streamloader will load all cameras in parallel and package them into a single 16x3x640x640 tensor for batched inference.

So detect.py itself is fully batched inference capable (as the current streamloader use case shows). The real work for batched inference would be a total rework of the dataloader to scan a directory on init and come up with a batched inference plan (i.e. sort images by aspect ratio like valloader and then come up with a plan to package them into similar aspect ratio batches), and then multithreaded (or multiple workers) image loading, and then a collate fcn that collates images into batches (like the trainloader).

**Pull request closed without merging**
