### PR TITLE
[Classifier]: Add metric logging 

### PR DESCRIPTION
**Pull request by AyushExel**
This PR adds metric logging support using a General purpose `GenericLogger` class which can be used by any task. Later we can expand this class to support media logging.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to the `yolov5` classifier logging with the addition of a general-purpose logger.

### 📊 Key Changes
- Imported `time` module in `classifier.py` to measure the training duration.
- Introduced `GenericLogger` class in `utils/loggers/__init__.py` for improved logging.
- Added logger initialization and logging of metrics (e.g., loss and accuracy) during training.
- Modified the final training completion message to include the total training time.

### 🎯 Purpose & Impact
- The primary goal is to provide better insight into model performance and training progress.
- Users can more easily track and understand changes in loss and accuracy as the model trains.
- The inclusion of total training time in the completion message helps users gauge the efficiency of their training sessions.

🕒💡 These changes aim to give users a more informative training experience and assist them in optimizing their machine learning workflows.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel pushed normalize()/denormalize() fix and updated this branch. Ready to merge?

BTW, we should either merge this branch into master or push this generic logger also to master to avoid potential conflicts with our upcoming July logger updates.

**Comment by glenn-jocher** [comment]
Looks good:

Screenshot 2022-06-27 at 20 18 32

**Comment by glenn-jocher** [comment]
@AyushExel PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by AyushExel** [comment]
> @AyushExel pushed normalize()/denormalize() fix and updated this branch. Ready to merge?
> 
> BTW, we should either merge this branch into master or push this generic logger also to master to avoid potential conflicts with our upcoming July logger updates.

@glenn-jocher Let's just push this branch to master by the end of this week? I think that's enough time to build DDP and inference support for classification, after which this branch should be usable

**Comment by glenn-jocher** [comment]
@AyushExel ok agreed, we'll aim for an end of week push to master.

**Pull request merged**
