### PR TITLE
W&B: refactor W&B tables

### PR DESCRIPTION
**Pull request by AyushExel**
This PR: 
* refactors table integration to include avg. conf. of each class detected.
* Allows the user to upload only validation split of the dataset
* Improves W&B readme

### Before:
Screenshot from 2021-11-21 17-35-12
### After:
users can now sort/filter using any class, which enables inspecting on which classes models performs best/worst

Screenshot from 2021-11-21 17-40-06

TODO:
* Format using Pycharm
* Run additional tests

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to Weights & Biases logging in YOLOv5 training script.

### 📊 Key Changes
- Updated the `--upload_dataset` argument to include an optional "val" value, allowing for more flexible dataset uploads.
- Added documentation on how to disable and enable Weights & Biases (wandb) logging.
- Introduced efficiency improvements by avoiding repeat image uploads when using evaluation tables.
- Adjusted the wandb logger to log average confidence per class during training rather than total confidence.
- Several internal code refinements within wandb_utils.py for better readability and maintainability.

### 🎯 Purpose & Impact
- The changes provide users with more control over dataset uploads to wandb and an option to disable logging if desired. 🎛️
- Enhanced evaluation tables now provide more detailed insights into model performance, potentially aiding in debugging and model improvement. 📈
- Streamlined usage and clarified documentation make it easier for both new and existing users to utilize wandb features with YOLOv5. 📚
- Overall, these updates aim to sharpen the development experience and provide richer datasets for those integrating YOLOv5 with wandb. 🔍

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel thanks for the PR! Please fix pre-commit errors here:
https://results.pre-commit.ci/run/github/264818686/1637496775.8WDi9EjUQA6h8x5dKIZVfQ

**Comment by AyushExel** [comment]
@glenn-jocher I've updated the README.md in wandb folder with a section on how to enable/disable. I've also made some updates to reflect the current updates.
Can you please copy the entire markdown form that files to the official Wandb Tutorial? This PR is ready to be merged

**Comment by glenn-jocher** [comment]
@AyushExel great! Can you provide the links of exactly what to copy to what? Thanks!

**Comment by AyushExel** [comment]
@glenn-jocher after merging this PR, copy the contents from this[ wand Readme.md ](https://github.com/AyushExel/yolov5/blob/tables/utils/loggers/wandb/README.md) to the[ yolov5 tutorial issue](https://github.com/ultralytics/yolov5/issues/1289)

**Comment by glenn-jocher** [comment]
@AyushExel got it! PR is merged and https://github.com/ultralytics/yolov5/issues/1289 is updated.

Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
