### PR TITLE
Training reproducibility improvements

### PR DESCRIPTION
**Pull request by AyushExel**
Followed suggestions from:
 https://github.com/pytorch/pytorch/issues/7068#issuecomment-484918113
https://www.mldawn.com/reproducibility-in-pytorch/

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduced a global training seed option for enhanced reproducibility.

### 📊 Key Changes
- Added a new `--seed` command-line argument to specify the global training seed.
- Modified `init_seeds` method to accept a `deterministic` parameter and implemented deterministic behavior when activated.
- Updated `init_seeds` to use PyTorch's `use_deterministic_algorithms()` and set the `CUBLAS_WORKSPACE_CONFIG` environment variable for PyTorch versions >= 1.12.0.

### 🎯 Purpose & Impact
- 👨‍🔬 **Enhanced Reproducibility**: The changes allow for more reproducible training results, which is particularly important for experiments and comparisons.
- 🧮 **Consistent Training Behaviour**: Users can expect consistent model performance when retraining with the same seed, reducing variability due to random processes.
- 🤖 **Developer Convenience**: By introducing a command-line argument for seeding, developers have an easier time setting and managing the seeds within their training scripts.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel thanks for the PR!

Can you please provide before and after results, i.e. 3 runs from master and 3 runs from PR? The scenario can be small, i.e. COCO128 YOLOv5s 30 epochs, but it's important to compare changes to the current baseline. Thanks!

**Comment by AyushExel** [comment]
Screenshot from 2022-06-15 16-21-47
@glenn-jocher 
* All red lines are master runs and blue are runs from this branch. 
* The metrics section shows similar variance for both as the scores are very small, only 3rd decimal places
* But for train and val metrics this branch shows much less variance than master.
Again, due to small scale of the dataset and small numerical values involved, this test needs to be verified using a larger dataset.
[Dashboard](https://wandb.ai/cayush/fix-yolo-repro?workspace=user-cayush)

**Comment by glenn-jocher** [comment]
@AyushExel got it, perfect!

I will check out this branch and run full YOLOv5s COCO trainings on the 8 GPUs today.

**Comment by glenn-jocher** [comment]
@AyushExel public at https://wandb.ai/glenn-jocher/test-reproduce-p

**Comment by AyushExel** [comment]
@glenn-jocher nice. You also have the same test for master branch already right?

**Comment by glenn-jocher** [comment]
@AyushExel yes, these are the differences between min and max mAP@0.5:0.95:

- Master (37.46-38.13@epoch300): https://wandb.ai/glenn-jocher/test-speed
- Master with `pip uninstall albumentations` (37.54-37.93@epoch300): https://wandb.ai/glenn-jocher/test-reproduce-noalbumentations
- This PR(21.63-22.11@epoch10): https://wandb.ai/glenn-jocher/test-reproduce-pr
- Master with `--workers 0` (TODO-TODO@epoch10): https://wandb.ai/glenn-jocher/test-reproduce-workers0

**Comment by glenn-jocher** [comment]
@AyushExel seems to show identical variation to master at epoch 8 (about 0.4%), so seems like no change in randomness.

What happened to the [torch.use_deterministic_algorithms()](https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms) that I sugested?

**Comment by glenn-jocher** [comment]
@AyushExel also your dataloader init function seems to be lacking python and torch seed inits as in this example: https://discuss.pytorch.org/t/reproducibility-with-all-the-bells-and-whistles/81097

**Comment by AyushExel** [comment]
@glenn-jocher The dataloader init_fn only requires np random seed as mentioned in official pytorch issues [here](https://discuss.pytorch.org/t/random-seed-initialization/7854/17) and [here](https://github.com/pytorch/pytorch/issues/7068#issuecomment-484918113)

The [torch.use_deterministic_algorithms()](https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms) is not exception safe. There are many operations that'll just throw runtime error when this is enabled. Also to work for CUDA 10.2 and above correctly some environ variables need to be set or it'll cause runtime exceptions. More details here in the last section https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms
Enabling this seems way too risky

**Comment by AyushExel** [comment]
@glenn-jocher Also after reading a lot of discussions on various platforms( github, kaggle, pytorch discourse) I haven't found anyone who has actually been able to accurately reproduce their large model experiments. All solutions are just there to reduce the variance
It might happen due to the numerical instability of due to the estimation of floating point gradients.

**Comment by glenn-jocher** [comment]
@AyushExel ok I'm going to cancel this training and try new experiments:

1. Train with workers=0
2. Train with AMP disabled (needs new branch)
3. We can try the additional python and torch seeds to see if they help (please update this PR's init_fcn for this)

**Comment by AyushExel** [comment]
@glenn-jocher I'll do the 3rd on this branch in some time.

**Comment by glenn-jocher** [comment]
@AyushExel ok got it! --workers 0 experiment started in new project, tracking results in same comment https://github.com/ultralytics/yolov5/pull/8213#issuecomment-1156370140. Each epoch there takes 30 min so we'll have the epoch 10 results in about 5 hours.

The good news is the randomness at epoch 10 is a great benchmark, no need to wait 300 epochs.

**Comment by AyushExel** [comment]
@glenn-jocher I was just testing torch.use_deterministic_alg on my branch. The training ran successfully but there's one operation post training that throws runtime error. I'll test more to see if its actually deterministic. If so, we can change the implementation of the operation that throws error. If not, let's leave it alone.
```
 File "/home/yolov5/utils/torch_utils.py", line 205, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.shape))
RuntimeError: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#cublasApi_reproducibility
```

**Comment by AyushExel** [comment]
@glenn-jocher keep an eye on https://wandb.ai/cayush/use_deter?workspace=user-cayush
Training yolov5n from scratch for 50 epochs with deteministic_alg enabled

**Comment by AyushExel** [comment]
Screenshot from 2022-06-15 20-33-04


@glenn-jocher Okay so I've set the `warn_only` flag of `torch.use_deterministic_alg` to True which means it won't throw error after training. But this also means that if something goes wrong with reproduciblity ,it'll fail silently. We'll need to keep that in mind when creating new operations. 
That aside, these are the best results that I've got. All metrics are coinciding perfectly
[Dash](https://wandb.ai/cayush/use_deter?workspace=user-cayush)

EDIT: It seems like additional seed inn dataloader init fn is not required. So leaving it as it is right now. It only affects DDP mode which I can't test locally

**Comment by AyushExel** [comment]
@glenn-jocher You'll need to run these tests:
* One same as yesterday. train 8 yolov5s on 8GPUs from this branch. These metrics should all perfectly match
* if the above is successful, also test reproducibility in DDP mode. train 4 models in DDP across 8 GPUs( 2 for each training)
The 2nd test will confirm if we need any changes in `init_fn` method of the dataloader. I've run tests on multiple devices and my results for single worker training is perfectly reproducible( to the 4th decimal place)

**Comment by glenn-jocher** [comment]
@AyushExel got it. Running 8 YOLOv5s now at https://wandb.ai/glenn-jocher/test-reproduce-pr2

**Comment by AyushExel** [comment]
@glenn-jocher  great. How long does 1 epoch usually take? From the benchmark runs you posted above:
* This master branch run take ~5min for each train epoch https://wandb.ai/glenn-jocher/test-speed/runs/skny7ifr/logs
* This again from master branch takes ~30mins per epoch https://wandb.ai/glenn-jocher/test-reproduce-workers0/runs/3gtrixbr/logs
Isn't that difference too large? They should take similar time right?

**Comment by AyushExel** [comment]
@glenn-jocher 
good thing:
* All metrics are matching perfectly.
Bad thing:
* The maps are 0, flat line
No idea why this is happening. [Asked a question on Pytorch forums](https://discuss.pytorch.org/t/getting-flat-curves-when-using-torch-use-deterministic-algorithms/154310)

**Comment by glenn-jocher** [comment]
@AyushExel yes I see this also. Losses are all identical but mAP is 0. Usually when mAP is 0 it's due to AMP/CUDA/Windows/Conda issues, but I've recently added AMP checks and these are passing for PR trainings in https://wandb.ai/glenn-jocher/test-reproduce-pr3

AMP checks run inference on pretrained model (or YOLOv5n downloaded model if not pretrained model) to verify that AMP inference and default inference produce similar results. This was added in #7917 and improved in #7937

**Comment by AyushExel** [comment]
@glenn-jocher No responses on the pytorch forum issue. I'm trying to  debug this using pdb. Hopefully the bug is occurring during the calculation of maps with deterministic algorithms. I'll verify if the model is actually learning anything or not by plotting results in each epoch.

**Comment by AyushExel** [comment]
@glenn-jocher The error is with calculation. I plotted BBoxDebugger for 1st epoch in VOC training and most objects are detected correctly so  map shouldn't be 0. https://wandb.ai/cayush/use_deter_s/
EDIT:
Okay found the issue. This line is always false when deterministic alg is set -> https://github.com/ultralytics/yolov5/blob/master/val.py#L265
This happens because stats[0].any() returns false. When not using deterministic alg, it returns true. So the bug is somewhere in the `process_batch` function. 
The iou values on the first epoch are very low when deterministic_alg is set. 
EDIT2:
Okay I tried a lot of tracebacks. No idea where things are going wrong

**Comment by glenn-jocher** [comment]
@AyushExel I overlaid a master run against current PR: train losses, val losses, learning rates are all identical, but all metrics are zero. Very strange. Obviously the latest commit 254d37943b00a7e1b70611bbb3b38326d4dcba6e caused this. Looking at the commit it has two changes, so let's try to isolate one change at a time to identify the cause. I'll comment out one line and retry a new training.

Screenshot 2022-06-17 at 13 42 00

**Comment by glenn-jocher** [comment]
> @glenn-jocher The error is with calculation. I plotted BBoxDebugger for 1st epoch in VOC training and most objects are detected correctly so map shouldn't be 0. https://wandb.ai/cayush/use_deter_s/ EDIT: Okay found the issue. This line is always false when deterministic alg is set -> https://github.com/ultralytics/yolov5/blob/master/val.py#L265 This happens because stats[0].any() returns false. When not using deterministic alg, it returns true. So the bug is somewhere in the `process_batch` function. The iou values on the first epoch are very low when deterministic_alg is set. EDIT2: Okay I tried a lot of tracebacks. No idea where things are going wrong

I see what you're saying here. So this is good news, it means the models are actually learning and are identical, it's just the validation that seems problematic. But the validation is always deterministic anyways, it never varies so maybe we can set flags to enable/disable deterministic mode in val.py as a quick fix.

**Comment by AyushExel** [comment]
@glenn-jocher I found the exact line that was not behaving with `torch.use_deterministic_algorithms` . It's this line https://github.com/AyushExel/yolov5/blob/init_seeds/val.py#L93
I manually reduced the scope of code from train to val.py running binary search manually over lines of code and finally converged on this line. I've enclosed this line like this:
```
torch.use_deterministic_alg(False)
correct[matches[:, 1].astype(int), i] = True
torch.use_deterministic_alg(True)
```
After this my local tests ran well in terms of reproducibility. I've also removed some redundant seeds like cudnn seeds and dataloader init_fn as my results on single GPU were reproducible without them. We can add them again if needed in DDP setting.
Can you verify this PR again by running training in coco with yolovn?

**Comment by glenn-jocher** [comment]
> @glenn-jocher I found the exact line that was not behaving with `torch.use_deterministic_algorithms` . It's this line https://github.com/AyushExel/yolov5/blob/init_seeds/val.py#L93 I manually reduced the scope of code from train to val.py running binary search manually over lines of code and finally converged on this line. I've enclosed this line like this:
> 
> ```
> torch.use_deterministic_alg(False)
> correct[matches[:, 1].astype(int), i] = True
> torch.use_deterministic_alg(True)
> ```
> 
> After this my local tests ran well in terms of reproducibility. I've also removed some redundant seeds like cudnn seeds and dataloader init_fn as my results on single GPU were reproducible without them. We can add them again if needed in DDP setting. Can you verify this PR again by running training in coco with yolovn?

@AyushExel strange. I think matches in a numpy array but correct may be a torch tensor, perhaps this is causing the issue. I'll take a look and start a larger COCO training.

**Comment by glenn-jocher** [comment]
@AyushExel I've updated process_batch in https://github.com/ultralytics/yolov5/pull/8254 and merged into this PR resolving that issue.

Everything is running error-free now, but something is very different between Colab training with this PR (0.2 mAP) vs master (0.7 mAP)
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

I've isolated the cause to just this one single line:
```python
    torch.use_deterministic_algorithms(True)
```

This additional line is needed for fusing the model, but is not the cause of the problem as val runs after each epoch with non-fused models also.
```python
    os.environ['CUBLAS_WORKSPACE_CONFIG'] = ':4096:8'
```

**Comment by AyushExel** [comment]
@glenn-jocher probably there's again an isolated operation that is getting bottlenecked due to that torch command. I'll run a  similar binary search starting with that same line tonight

**Comment by glenn-jocher** [comment]
@AyushExel I've updated our notebook outputs in https://github.com/ultralytics/yolov5/pull/8255, Colab updates automatically from [tutorial.ipynb](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb), Kaggle I updated manually at https://www.kaggle.com/code/glennjocherultralytics/yolo11/notebook.

Now we can see that we should be seeing this on running the default training cell. The problem is the PR mAPs are closer to 0.2. I don't know why, but this is bad because it means users will see reduced performance when training from pretrained models. We might need to train new models (i.e. v7.0) and introduce this PR at the same time as the new models if we can't resolve this.

Screenshot 2022-06-18 at 14 35 42

**Comment by glenn-jocher** [comment]
@AyushExel I wonder if just disabling it for all of val.py like we do with @torch.no_grad() might be a quick fix, i.e.:
https://github.com/ultralytics/yolov5/blob/1156a323f8fc221d5c1a36c700e72e129419d187/val.py#L96-L97

**Comment by AyushExel** [comment]
@glenn-jocher yes that works as I tested it yesterday but I haven't checked if doing that would preserve the reproducibility. 
Will check that today

**Comment by AyushExel** [comment]
@glenn-jocher Okay to isolating the val() operation from reproducibility seems to solve the problem of low mAPs. But I'll need to verify all trainings are reproducible in this setting. 
Screenshot 2022-06-18 at 6 33 36 PM

**Comment by glenn-jocher** [comment]
@AyushExel ok I think these two changes should work. This sets deterministic True at the beginning of each epoch and False at the beginning of val.py.

EDIT: testing at https://wandb.ai/glenn-jocher/test-reproduce-pr4

**Comment by AyushExel** [comment]
@glenn-jocher yeah this looks good. Are you running the training test to check for reproducibility again?

**Comment by AyushExel** [comment]
@glenn-jocher looks good so far. I'm noticing some GPUs are slow?

**Comment by glenn-jocher** [comment]
@AyushExel yes we've got a problem with device 5, need to raise this with Lambda support. 

We've got a big problem other than that though, it looks like the PR models are all identical but are all also falling below a master model:

https://wandb.ai/glenn-jocher/test-reproduce-pr4
Screen Shot 2022-06-19 at 5 58 27 PM

In the past we've had DDP issues with different RANKs using the same seeds and thus seeing 1/8th of the standard augmentation, I wonder if something similar may be happening here. We should try to strip this PR down to just the bare minimum and retrain.

**Comment by AyushExel** [comment]
@glenn-jocher yes. All things  remaining constant, changing the  seed WILL result in in different metrics for better or worse. 
Commenting out `torch.seed_all` should not affect single-gpu but will affect DDP case which we're not testing in the current test.

**Comment by glenn-jocher** [comment]
@AyushExel ok I reduced the PR to the bare minimum, which is just mainly the two lines here (and setting to False in val.py):
```python
    torch.use_deterministic_algorithms(True)
    os.environ['CUBLAS_WORKSPACE_CONFIG'] = ':4096:8'
```

I added the 7 new runs (left device 5 alone) to the same project, and they seem to be tracking the previous 8 runs identically.

I know the PR will change the mAP but this one seems to solidly track much lower than master. It seems unlikely to be just noise. But I can add a different seed for each run to see what the new mean looks like to compare to the master mean. I'll go ahead and do that now.

**Comment by AyushExel** [comment]
@glenn-jocher cool. I guess this line might also be redundant as setting torch.deterministic automatically sets cudnn to deterministic mode:
```
    cudnn.benchmark, cudnn.deterministic = (False, True) if seed == 0 else (True, False)
```

**Comment by glenn-jocher** [comment]
@AyushExel ok got it. I added a -seed argument and then started 7 new runs with different seeds in the same project. Hopefully these show similar mean and variance as master.

I reverted most changes just to try to isolate any possible causes of lower mAP. It looks like the current PR reproduces the full changes you had earlier (at least out to about 10 epochs before I cancelled that).

**Comment by AyushExel** [comment]
@glenn-jocher what's happening with this?

**Comment by glenn-jocher** [comment]
@AyushExel results are in and they are problematic. All new PR trainings are lower than current master:
Screen Shot 2022-06-21 at 6 16 50 PM

It's extremely unlikely that 7 new trainings would all be below a random master training. I wonder if perhaps setting `torch.use_deterministic_algorithms(True)` every epoch is accidentally resetting seeds (and causing less random augmentation).

**Comment by glenn-jocher** [comment]
@AyushExel if we can't discover the cause then maybe we could make this optional, i.e. `python train.py --deterministic` which we would switch on for relative comparisons when doing internal R&D, but then train the official models without it for best results.

**Comment by glenn-jocher** [comment]
@AyushExel @SergioSanchezMontesUAM new runs started in https://wandb.ai/glenn-jocher/test-reproduce-pr4 after applying some changes.

I saw that the final models validate correctly **in a new workspace** for COCO128 even if the val results during training are incorrect. Unfortunately now if we run val.py with the below lines set there are no errors, no warnings, only low mAP, so it's hard to figure out what to debug.

```python
torch.use_deterministic_algorithms(True)
os.environ['CUBLAS_WORKSPACE_CONFIG'] = ':4096:8'  # not required for val-during-training, only val-after-training with .fuse()
```

**Comment by AyushExel** [comment]
@glenn-jocher so I guess we're stuck again on the reproducibility front

**Comment by glenn-jocher** [comment]
@AyushExel I think we can convert this PR from using torch.use_deterministic_algorithms(True)
 by default to using it on argument, i.e. --deterministic. That way we can merge and close this PR and just add the --deterministic when doing ablation studies etc, but train official models without it.

**Comment by glenn-jocher** [comment]
@AyushExel it might be working this time, but it's too early to know for sure.

### Previous run at epoch 130
Screenshot 2022-06-28 at 11 40 54


### Current commit at epoch 130
Screenshot 2022-06-28 at 11 41 31

**Comment by AyushExel** [comment]
@glenn-jocher okay that's interesting. I'm a little confused here though. If the training is deterministic shoudn't the values at same epoch with the same seeds be the same? Or maybe you changed something in the code
EDIT: Oh I see that you pushed some commits.

**Comment by glenn-jocher** [comment]
@AyushExel yes that's a good question... we had a recent warmup fix https://github.com/ultralytics/yolov5/pull/8356 that's probably causing a change. 

Interestingly though master is simply lower now while the PR distribution remains similar. Not sure what that means.

**Comment by UnglvKitDe** [comment]
@AyushExel  @glenn-jocher I am also working on improving the reproducibility. I also had the problem with the 0 values in the validation. It looks like torch 1.12 solve the problem. I'm still testing right now, but it looks good so far.

**Comment by AyushExel** [comment]
@UnglvKitDe that's great news. Do you know what caused the 0 val problem? Maybe you can point us to pytorch's fix for this

**Comment by UnglvKitDe** [comment]
@AyushExel I am not quite sure. The only thing done in the method `torch.use_deterministic_algorithms(True)` that causes the problem is #https://github.com/pytorch/pytorch/pull/76220

**Comment by AyushExel** [comment]
@UnglvKitDe okay got it. Thanks for pointing out. Do let us know about your findings.
@glenn-jocher I think we need to run another test with torch 1.12, this time without resetting the deterministic operation after every epoch

**Comment by UnglvKitDe** [comment]
@AyushExel I just took a look in your code. We do the same thing in `init_seed(..)`. I just set the seed for the worker in the dataloader as described in the [reproducibility doc](https://pytorch.org/docs/stable/notes/randomness.html#avoiding-nondeterministic-algorithms). From what I understand above, you intentionally didn't put that in?

**Comment by AyushExel** [comment]
@UnglvKitDe yes we're trying to isolate all changes. setting `torch.use_deterministic_algorithms` did produce reproducible results but the val metrics were 0. So we didn't revisit the dataloader

**Comment by UnglvKitDe** [comment]
@AyushExel Ah I got it. Thx :)

**Comment by glenn-jocher** [comment]
> @UnglvKitDe okay got it. Thanks for pointing out. Do let us know about your findings. @glenn-jocher I think we need to run another test with torch 1.12, this time without resetting the deterministic operation after every epoch

@UnglvKitDe thanks for the feedback! I've made updates to only run the command once if torch 1.12 is installed. torch < 1.12 we'll leave alone.

EDIT: Will run a new training today with these settings.

**Comment by UnglvKitDe** [comment]
> > @UnglvKitDe okay got it. Thanks for pointing out. Do let us know about your findings. @glenn-jocher I think we need to run another test with torch 1.12, this time without resetting the deterministic operation after every epoch
> 
> @UnglvKitDe thanks for the feedback! I've made updates to only run the command once if torch 1.12 is installed. torch < 1.12 we'll leave alone.
> 
> EDIT: Will run a new training today with these settings.

@glenn-jocher @AyushExel  I did 5 run with coco128. In one of 5 runs I get the 0 results again. A similar picture on my custom data (1 of 8 has the 0 problem again). Very strange. I have set up a clean conda installation with torch 1.12 and cuda 11.6.
results

**Comment by glenn-jocher** [comment]
@UnglvKitDe this is not the zero mAP problem. zero mAP means zero mAP at all times. In your training your validation loses are unstable and increasing leading to logically low mAP.

**Comment by glenn-jocher** [comment]
Tested PR in Colab with 1.12. Looks good, all 3 identical and high mAP.

```python
!git clone https://github.com/AyushExel/yolov5 -b init_seeds  # clone
%cd yolov5
%pip install -qr requirements.txt torch==1.12 torchvision==0.13  # install

import torch
import utils
display = utils.notebook_init()  # checks

# Train YOLOv5s on COCO128 for 10 epochs
!python train.py --img 640 --batch 16 --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --seed 0
!python train.py --img 640 --batch 16 --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --seed 0
!python train.py --img 640 --batch 16 --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --seed 0
```

Screen Shot 2022-06-29 at 4 57 23 PM

**Comment by glenn-jocher** [comment]
Testing vs master on COCO in https://wandb.ai/glenn-jocher/test-reproduce-pr4

EDIT: Unable to test on Multi-GPU systems per torch 1.12 YOLOv5 bug in https://github.com/ultralytics/yolov5/issues/8395

**Comment by UnglvKitDe** [comment]
> @UnglvKitDe this is not the zero mAP problem. zero mAP means zero mAP at all times. In your training your validation loses are unstable and increasing leading to logically low mAP.

@glenn-jocher Then we talked about other issues. When I used `use_deterministic_algorithms`, I got the problem described above (AP 0 at the end).

**Comment by glenn-jocher** [comment]
W&B trainings have been cancelled because unable to test on Multi-GPU systems per torch 1.12 YOLOv5 bug in https://github.com/ultralytics/yolov5/issues/8395

**Comment by UnglvKitDe** [comment]
@AyushExel @glenn-jocher With torch 1.12 there is a issue with multi gpu training when I insert the reproducibility as described in the doc. For some reason, CUDA runs out of memory. On the master it works without problems (~5.1/12 GB VRAM).

**Comment by UnglvKitDe** [comment]
ok, so i tried debugging this today, but i don't understand why the problem occurs. if i use a different number of workers it works. unfortunately ( at the moment ) i can't recreate it with any public record.

> > > @UnglvKitDe okay got it. Thanks for pointing out. Do let us know about your findings. @glenn-jocher I think we need to run another test with torch 1.12, this time without resetting the deterministic operation after every epoch
> > 
> > 
> > @UnglvKitDe thanks for the feedback! I've made updates to only run the command once if torch 1.12 is installed. torch < 1.12 we'll leave alone.
> > EDIT: Will run a new training today with these settings.
> 
> @glenn-jocher @AyushExel I did 5 run with coco128. In one of 5 runs I get the 0 results again. A similar picture on my custom data (1 of 8 has the 0 problem again). Very strange. I have set up a clean conda installation with torch 1.12 and cuda 11.6. results

ok, so i tried debugging the above problem today, but i don't understand why the problem occurs. if i use a different number of workers it works. unfortunately (as of now) i can't recreate it with any public dataset. Very strange. @glenn-jocher Have you ever seen such a problem?

**Comment by glenn-jocher** [comment]
@UnglvKitDe it's not uncommon for gradient/training instabilities to lead to higher losses and diverged results. This is just a fact of life with nonlinear optimization problems.

The reproducibility part we are trying to work on with this PR of course though.

**Comment by glenn-jocher** [comment]
@AyushExel I think this PR is good to merge. I added a `deterministic=False` argument to init_seeds()

**Comment by glenn-jocher** [comment]
@AyushExel PR is merged! The new deterministic policy is that init_seeds() defaults to False but we pass true in train.py. 

```python
init_seeds(opt.seed + 1 + RANK, deterministic=True)
```

I also added init_seeds to classifier.py and observed deterministic behavior without having to set deterministic=True, but also test it with True and saw no errors (strange). Anyway I think we are done here and can move on to other things!

**Comment by lijiajun3029** [comment]
good job

**Comment by glenn-jocher** [comment]
@lijiajun3029 thank you! 🙏 This is a team effort and your valuable feedback and testing have been instrumental in improving YOLOv5. We're always here if you have more questions or need further assistance.

**Pull request merged**
