### PR TITLE
Re-open IP-camera videostream if disconnected

### PR DESCRIPTION
**Pull request by EgOrlukha**
Streaming from IP-cameras via rtsp was freezing when signal lost. I added an option to re-open cv2.Videocapture in case of video-stream disconnection.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced error handling for unresponsive video streams in YOLOv5.

### 📊 Key Changes
- The `update` function in `utils/datasets.py` now takes an additional `stream` parameter.
- Improved error reporting with a warning message if a video stream is unresponsive.
- Added functionality to attempt to re-open the video stream automatically if the connection is lost.

### 🎯 Purpose & Impact
- Helps users to debug issues with IP camera connections by printing a warning when a video feed is lost.
- Increases robustness by trying to reconnect to the video stream, potentially reducing interruptions during stream processing.
- Facilitates continuity in video frame capture for YOLOv5, which is crucial for applications that rely on consistent real-time video analysis. 💪📹🔄

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@EgOrlukha this seems really useful, thanks for the PR!

Have you been able to see some streams reconnect when they drop due to the PR code?

**Comment by glenn-jocher** [comment]
@EgOrlukha PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by EgOrlukha** [comment]
> @EgOrlukha this seems really useful, thanks for the PR!
> 
> Have you been able to see some streams reconnect when they drop due to the PR code?

@glenn-jocher Yes, I changed the code for my needs and it works stable even if a videostream is lost for some reason. These are OpenCV issues, I just re-open cv2.Videocapture() in case it was disconnected.

**Comment by glenn-jocher** [comment]
@EgOrlukha great, good to know!

**Pull request merged**
