### PR TITLE
Update requirements.txt to `ultralytics 8.0.145`

### PR DESCRIPTION
**Pull request by glenn-jocher**
### Summary
🔧🚚📦

Refactored the `ultralytics` package to make it more modular and reusable, and moved `utils/general.py` to `utils/__init__.py` to simplify imports.

> _`ultralytics` splits_
> _refactoring for reuse_
> _autumn of code_

### Walkthrough
*  Refactor `ultralytics` package to make it more modular and reusable across different projects ([link](https://github.com/ultralytics/yolov5/pull/11920/files?diff=unified&w=0#diff-6e982446d45d5ffa23213eb0cb66991fb02283df19b49da3bc8057ce1ab5094aL57-R57), [link](https://github.com/ultralytics/yolov5/pull/11920/files?diff=unified&w=0#diff-dd425673dc44b64697acc887bb7abefec7ca7d92cf434d7ac9a6d69a8268f47aL38-R38))
  - Move `utils/general.py` to `utils/__init__.py` and adjust imports accordingly ([link](https://github.com/ultralytics/yolov5/pull/11920/files?diff=unified&w=0#diff-dd425673dc44b64697acc887bb7abefec7ca7d92cf434d7ac9a6d69a8268f47aL38-R38))
  - Import `check_requirements` from `ultralytics.utils` instead of `ultralytics.yolo.utils` in `notebook_init` function ([link](https://github.com/ultralytics/yolov5/pull/11920/files?diff=unified&w=0#diff-6e982446d45d5ffa23213eb0cb66991fb02283df19b49da3bc8057ce1ab5094aL57-R57))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update to dependency management and internal import paths.

### 📊 Key Changes
- Updated the required version of the `ultralytics` package from `8.0.111` to `8.0.145` in `requirements.txt`.
- Changed import paths for `check_requirements` from `ultralytics.yolo.utils` to `ultralytics.utils` in `utils/__init__.py` and `utils/general.py`.

### 🎯 Purpose & Impact
- Ensuring compatibility with the latest `ultralytics` package by requiring a newer minimum version may incorporate bug fixes, performance improvements, or new features.
- Refactoring the import paths for `check_requirements` helps maintain cleaner and more consistent code organization, reflecting an internal restructuring of the Ultralytics library.
- These changes enhance the stability and maintainability of the YOLOv5 project, potentially resulting in a smoother experience for users.

### CODE REVIEW

**Comment by aminrabinia** [comment]
Resolved with rebuild docker container. 
----
File "/usr/src/app/./main.py", line 19, in <module>
    model = torch.hub.load(BASE_DIR, 'custom', path=MODEL_DIR, device='cpu', trust_repo=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 572, in _load_local
    model = entry(*args, **kwargs)
  File "/home/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/home/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "/home/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 28, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "/home/.cache/torch/hub/ultralytics_yolov5_master/utils/dataloaders.py", line 31, in <module>
    from utils.augmentations import (Albumentations, augment_hsv, classify_albumentations, classify_transforms, copy_paste,
  File "/home/.cache/torch/hub/ultralytics_yolov5_master/utils/augmentations.py", line 15, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box, xywhn2xyxy
  File "/home/.cache/torch/hub/ultralytics_yolov5_master/utils/general.py", line 38, in <module>
    from ultralytics.utils.checks import check_requirements
ModuleNotFoundError: No module named 'ultralytics.utils'"

**Comment by glenn-jocher** [comment]
@aminrabinia this issue seems to be caused by a missing module named 'ultralytics.utils'. One possible solution to resolve this error is to rebuild the Docker container. This can be done by running the necessary commands to recreate the container from the Dockerfile or using the appropriate tools or commands specific to the containerization platform being used.

Rebuilding the Docker container should ensure that all the required dependencies and modules are properly installed and accessible within the container environment. Once the container is rebuilt, the issue with the missing 'ultralytics.utils' module should be resolved.

Please try rebuilding the Docker container and let us know if the issue persists.

**Comment by aminrabinia** [comment]
Thanks. Rebuild fixed the error.

**Comment by glenn-jocher** [comment]
@aminrabinia great to hear that rebuilding the Docker container solved the issue! If you have any further questions or run into any other problems, please don't hesitate to ask. The YOLOv5 community and the Ultralytics team are always here to help. Happy coding!

**Comment by AtillaErdinc1** [comment]
@glenn-jocher 

Hi sir,
I'm a computer engineering student in Turkey. I allways prepare one page average python codes about object detection. There is my code's problem;

In this line;

model = torch.hub.load('ultralytics/yolov5', 'custom', path='best10.pt', force_reload=True)

And there is a error code;

  File ~/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py:33 in _create
    from models.common import AutoShape, DetectMultiBackend

  File ~/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:26 in <module>
    from ultralytics.utils.plotting import Annotator, colors, save_one_box

ModuleNotFoundError: No module named 'ultralytics.utils'

Using the last version before the update solved the problem. But I want ask you :) How can I solve this problem in one line in the current version?

Thanks for your help and sorry for my bad English (:

**Pull request merged**
