### PR TITLE
rename class autoShape -> AutoShape

### PR DESCRIPTION
**Pull request by developer0hye**
follow other classes' naming convention

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved naming convention in YOLOv5 codebase.

### 📊 Key Changes
- Renamed `autoShape` class to `AutoShape` for consistency in class naming.
- Updated constructor and relevant print statements from `autoShape` to `AutoShape`.

### 🎯 Purpose & Impact
- 💅 **Code Readability:** Harmonizes class naming conventions for better clarity, adhering to Python's CapWords convention.
- 🛠️ **Refactoring:** Reflects best practices in software development, but no changes in functionality.
- 🔍 **User Transparency:** Clearer logging messages to inform users when AutoShape is enabled.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@developer0hye thanks for the PR! This is not a bad idea to stay consistent with the pytorch camelcase module convention. It looks like there are 6 case-sensitive occurences of 'autoShape' in the repo, but the PR only includes 4 changes. Can you do the other two also please? Thanks!

Screenshot 2021-05-16 at 15 28 23

**Comment by developer0hye** [comment]
@glenn-jocher I modified them! Please check my commit~

**Comment by glenn-jocher** [comment]
@developer0hye looks good! Thank you for your contributions!

**Comment by developer0hye** [comment]
@glenn-jocher 

Hello, jocher.

I measured the execution time of 300 over imagenet pretrained backbone networks.

Refer to https://github.com/developer0hye/pytorch-backbone-benchmark

I hope it helps you to find more efficient backbone than current yolov5's backbone model!

image

**Comment by glenn-jocher** [comment]
@developer0hye wow, that's impressive! 

You should definitely plot your results a few different ways, maybe using plotly or an interactive dashboard so you can mouse over the best datapoints and get their model names etc.

top1 vs time
top1 vs params
params vs time

**Comment by developer0hye** [comment]
@glenn-jocher 

https://colab.research.google.com/drive/1NmkUIcA9Vt8U2WLXgZeIrIuY3yFW3Byx#scrollTo=9NyYQqA_iwzn

Look at this!

**Comment by glenn-jocher** [comment]
@developer0hye very nice!

**Pull request merged**
