### PR TITLE
:sparkles: Added possibility to save metric curves as csv files

### PR DESCRIPTION
**Pull request by lcombaldieu**
Signed-off-by: Louis Combaldieu <louis.combaldieu@auxilia-tech.com>

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Add CSV output support for model evaluation metrics in YOLOv5. 📈

### 📊 Key Changes
- Added a `--csv` flag option in train.py and val.py scripts to enable CSV file output.
- Updated `ap_per_class()` in utils/metrics.py to support CSV output for evaluation metrics.
- Enhanced `plot_pr_curve()` and `plot_mc_curve()` functions to save precision-recall and metric-confidence curves as CSV files.
- Created a new `save_curves()` function to perform the actual writing of CSV files containing the curves data.

### 🎯 Purpose & Impact
- **Purpose**: To provide users the option to export model evaluation metrics and curves (precision-recall, F1, etc.) in a CSV format, which can be useful for further analysis, reporting, or integration with other data-processing tools.
- **Impact**: Users can now save and analyze their model evaluation metrics more easily in tools like Excel, Google Sheets, or custom data analysis scripts. This update could significantly improve the workflow for researchers and practitioners who need to document and present their results in a more formal or detailed manner. 📊🔍

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@lcombaldieu thanks for the PR! This looks good, but would it make more sense to pass the csv flag to the plot commands and have them call the csv saving function? Then you wouldn't need to duplicate as much code I believe.

**Comment by glenn-jocher** [comment]
@lcombaldieu I think with this method you could also pass headers as an argument to save_csv to make the function more generic.

**Comment by lcombaldieu** [comment]
I have also changed `train.py` and `val.py` to add the option to the arg list but I'm unable to push them to this PR. I don't want to flood PR, is there a way for me to push the changes here ?

**Comment by lcombaldieu** [comment]
@glenn-jocher can you approve the PR ? 
This functionality is required for fine-grain reading of metric curves and would help other people too I think.
Thank you

**Comment by glenn-jocher** [comment]
@lcombaldieu thanks for the suggestion! I've passed it along to the team for review. It looks like a good addition to the functionality. Appreciate your contribution!

**Pull request closed without merging**
