### PR TITLE
PyTorch Hub `verbose=False` fix

### PR DESCRIPTION
**Pull request by glenn-jocher**
Attempt to define environment variable before utils.general loads.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refinement of logging and error messaging in YOLOv5's download and creation functions.

### 📊 Key Changes
- Introduced environment variable `YOLOv5_VERBOSE` to control verbosity.
- Changed certain `print` statements to `LOGGER.info` for better control over logging.
- Used the `LOGGER` variable within the download functions for consistent logging.
- Modified method signatures to use `_verbose` instead of `verbose` where appropriate.

### 🎯 Purpose & Impact
- 🔧 **Consistent Verbosity Control**: The use of the `YOLOv5_VERBOSE` environment variable provides unified verbosity control across different parts of the code.
- 📝 **Enhanced Logging**: Transitioning from `print` to `LOGGER.info` offers developers a more granular logging level, which can help with debugging.
- 🧰 **Developer Experience**: Improved error handling and messaging during the download process can make development and troubleshooting smoother for users working with YOLOv5’s codebase.
- 🔄 **Minimal User Impact**: Changes are largely under-the-hood; end users working with YOLOv5 models may notice more informative logging during installation or when errors occur, but overall functionality remains the same.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
Test code:

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5:update/verbose_hub', 'yolov5s', verbose=False)

# Images
dir = 'https://ultralytics.com/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
```

**Comment by glenn-jocher** [comment]
Test fails, all output still seen in console. Seems that our custom verbose argument conflicts with the default torch hub verbose argument. https://pytorch.org/docs/stable/hub.html#torch.hub.load

**Comment by Powercube7** [comment]
@glenn-jocher how about we rename our argument to yolo_verbose?

**Comment by glenn-jocher** [comment]
@Powercube7 I can try that!

**Comment by glenn-jocher** [comment]
Closing PR as replaced by PR #7550

**Comment by glenn-jocher** [comment]
@Powercube7 I've implemented your idea now in PR #7550 with `_verbose=False` Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request closed without merging**
