### PR TITLE
YOLOv5 PyTorch Hub results.save() method retains filenames

### PR DESCRIPTION
**Pull request by dan0nchik**
Save the original imgs list, so the results will be saved like `results_zidane.jpg, results_bus.jpg... etc.`
I didn't test that, just brought you idea :)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improve handling of image filenames during YOLOv5 inference

### 📊 Key Changes
- Filename tracking now added for each processed image.
- Filenames are retained or generated appropriately for display and save operations.
- The `save` method now ensures the save directory exists before saving images.
- Minor changes to facilitate showing the correct image name during visualization.

### 🎯 Purpose & Impact
- **Enhanced Traceability**: Attaching filenames to inference results helps users identify which results correspond to which input images.
- **Better Visualization**: When users choose to display results, the correct image name/title enhances the user experience.
- **Easy Result Management**: Creating save directories as needed prevents errors and streamlines the saving process.
- **Impact for Users**: Users have a smoother and more informative interaction with output images, making it easier to handle and organize inference results.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@dan0nchik thanks for the PR! This is in the right direction, but we need to robustly handle different image types. The YOLOv5 Hub models can actually input various different input types listed in the forward() method comments:
https://github.com/ultralytics/yolov5/blob/17ac94b7968703e708bfeb7274de755c4b2f1f43/models/common.py#L183-L192


I can update this later with a few fixes.

**Comment by glenn-jocher** [comment]
@dan0nchik PR is merged. Thank you for your contributions! Let us know if you run into any other issues.

**Comment by dan0nchik** [comment]
@glenn-jocher Thank you :)

**Comment by p9anand** [comment]
@glenn-jocher : getting following error when passing an PIL image. Below is the screenshot.
image
I applied some print statement......!!

image

After this i did some debugging and following results i got...

image

image

In files.append return None object.

**Comment by glenn-jocher** [comment]
@p9anand this bug was fixed in a recent PR. Please rerun your command with `force_reload=True` to cache the latest YOLOv5 hub code. See tutorial for details:

## Tutorials

* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW

**Comment by p9anand** [comment]
@glenn-jocher : i just tried that, still getting same error. I'm loading a custom model, using pytorch hub.

**Comment by glenn-jocher** [comment]
@p9anand rerun your command with force_reload=True to cache the latest YOLOv5 hub code. 

If you believe there is a reproducible error then please raise a new bug report issue using the bug report template and providing exact code to reproduce.

**Pull request merged**
