### PR TITLE
Small fixes to docstrings

### PR DESCRIPTION
**Pull request by zhiqwang**
Hi @glenn-jocher 

This PR does the following three things:
- Fix markdown formatting
- Use em dash to quote https://en.wikipedia.org/wiki/Dash#Types_of_dash
- Maybe we should up-to-date with the upstream/master?

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated contributor guidance and automated welcome message in the YOLOv5 repository.

### 📊 Key Changes
- Modified the GitHub greetings workflow to change the indentation of bash commands.
- Updated the CONTRIBUTING.md documentation, adjusting the indentation of a bash command snippet and removing a quote from Bruce Lee.

### 🎯 Purpose & Impact
- Ensure consistency and readability in documentation and automated messages, which benefits contributors when setting up their local environment for contributions.
- The removal of the quote streamlines the contributing guidelines, focusing the content on technical instructions only. This may help in reducing distractions and making the document more focused and concise for contributors.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@zhiqwang oh thanks for pointing out the discrepancy! Now that I look at it maybe it makes more sense to rename upstream to origin. In PyCharm it shows the remote github branches as `origin`. What do you think?
Screenshot 2021-10-24 at 12 59 03

**Comment by zhiqwang** [comment]
Hi @glenn-jocher 

> Now that I look at it maybe it makes more sense to rename upstream to `origin`. In PyCharm it shows the remote github branches as `origin`. What do you think?

Seems to be `origin` only for you, because you have permission to work directly on https://github.com/ultralytics/yolov5, but for third party developers it is `upstream`, like for me, the `origin` I am currently working on is https://github.com/zhiqwang/yolov5 .

**Comment by glenn-jocher** [comment]
@zhiqwang oh got it! `origin` is your fork, `upstream` is the repo that was forked. Yes you are right.

**Comment by glenn-jocher** [comment]
@zhiqwang PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
