### PR TITLE
Update to ONNX opset 17

### LINKED ISSUE #10505: ONNX dynamic shapes and opset
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi guys,

Thanks for the amazing work. I am wondering why width and height are dynamic and not fixed, ideally (if you fix to idk `640x640`) onnx can do more performance optimization

https://github.com/ultralytics/yolov5/blob/1752768fb3b3ff4f842eaaecf7eba4808ac124a9/export.py#L143

Moreover, I've noticed the opset is set to a quite old number (12), I think we are a 17. 

Do you think it'd be possible to pass these parameters from the cli?

Thanks :)

Cheers,

Fra

### Additional

_No response_

### PR DESCRIPTION
**Pull request by glenn-jocher**
Resolves https://github.com/ultralytics/yolov5/issues/10505

Signed-off-by: Glenn Jocher <glenn.jocher@ultralytics.com>

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated default ONNX opset version to 17 for model exporting in `yolov5`.

### 📊 Key Changes
- The default ONNX opset version has been upgraded from 12 to 17 in the `export.py` script.

### 🎯 Purpose & Impact
- 📈 **Purpose:** To align the exported YOLOv5 models with the latest ONNX standards, likely enabling improved performance and compatibility with modern ONNX-savvy tools and frameworks.
- 🚀 **Impact:** Users exporting their models to ONNX format will benefit from enhancements available in the newer opset, potentially leading to more efficient inference and broader support across various ONNX-compatible platforms.

### CODE REVIEW

**Comment by jelena2712** [comment]
The error after this merge iwhen I try to convert pt to onnx is:
Unsupported ONNX opset version: 17

**Comment by glenn-jocher** [comment]
@jelena2712 ah, you probably need to update onnx, i.e.:

```
pip install -U onnx
```

I suppose we should update requirements.txt to the min version supporting opset 17 now.

**Comment by glenn-jocher** [comment]
https://onnxruntime.ai/docs/reference/compatibility.html

**Comment by glenn-jocher** [comment]
@jelena2712 good news 😃! Your original issue may now be fixed ✅ in PR #10526. This PR updates onnx requirements to >=1.12.0

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://bit.ly/yolov5-paperspace-notebook">Run on Gradient</a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb">Open In Colab</a> <a href="https://www.kaggle.com/models/ultralytics/yolov5">Open In Kaggle</a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5">Docker Pulls</a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Pull request merged**
