### PR TITLE
GH: add PR template

### PR DESCRIPTION
**Pull request by Borda**
Just to have some structure on open PRs, but feel free to adjust it as you want :]

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Implementing a PR template and updating contribution guidelines for YOLOv5 repository.

### 📊 Key Changes
- Added a new Pull Request (PR) template to the repository.
- Updated the contributing guidelines with a revised code block for rebasing.

### 🎯 Purpose & Impact
- **PR Template:** Ensures contributors check for existing PRs and link their submissions to relevant issues. Plus, encourages sharing of results demonstrating the PR's effectiveness.
  - 🚀 **Benefit**: Streamlines the review process and contributes to better documentation of changes and their ramifications.
  - 🔍 **Impact**: Contributors can provide more detailed and organized information, aiding both maintainers and users in understanding the changes.
  
- **Contributing Guidelines:** Clarifies the /rebase command and provides a cleaner code snippet for rebasing.
  - 🛠️ **Benefit**: Simplifies the rebase process, making it more accessible to contributors.
  - ⚙️ **Impact**: Encourages keeping branches up to date with the base branch, which can result in fewer merge conflicts and smoother integrations.

### CODE REVIEW

**Comment by Borda** [comment]
@glenn-jocher if you have a bit of tame :rabbit: ^^

**Comment by Borda** [comment]
@glenn-jocher any comments? it is very simple but at least good stating point... :rabbit:

**Comment by glenn-jocher** [comment]
@Borda PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
