### PR TITLE
Confusion matrix native image-space fix

### LINKED ISSUE #1960: Inconsistent confusion matrix
## ❔Question

We are training with yolov5l.pt as a baseline with 20K+ training and 4K val datasets. There are 6 classes. 1st one shows a decent confusion matrix where I can see a high TP of 50-60%. However, with the latest epochs of new training, we are consistently seeing a high mAP (89-95%), high recall 90%+, high precision (70-80%) but the confusion matrix shows a weird matrix. As the training progresses and mAP gets better, we try the intermediate best.pt and we can detect variations of all 6 classes but over time, we only see 1-2 classes being predicted which are wrong. Background FP is 1.0. Now, for all our training, this is happening consistently.

We don't claim to get to the bottom of it and will appreciate any pointers. The img sizes are 2448x784 and we are using --rect and img 1024.
train.py --rect --img 1024 --batch 2 --epochs 50 --data coco128.yaml --weights yolov5l.pt

We will much appreciate some pointers.
confusion_matrix
confusion_matrix (1)

### PR DESCRIPTION
**Pull request by ramonhollands**
Make sure the labels and predictions are equally scaled on confusion_matrix.process_batch

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of prediction handling in test suite.

### 📊 Key Changes
- Modified the `confusion_matrix.process_batch` function call to input `predn` instead of `pred`.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: The change ensures that the predictions processed in the confusion matrix are the normalized versions, likely correcting a previous oversight.
- 🌍 **Impact**: Improves the accuracy of the confusion matrix output, which is critical for evaluating model performance. Users will benefit from more reliable metrics for their object detection tasks. 📈

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@ramonhollands thanks for the PR! It appears you may have caught a bug in the confusion matrix. Do you get better results after this fix?

**Comment by glenn-jocher** [comment]
I get these confusion matrices before and after the fix. It looks better!

BEFORE
confusion_matrix

AFTER
confusion_matrix

**Comment by glenn-jocher** [comment]
Problem seems to be that predictions `pred` were passed (`pred` in letterboxed image space) along with labels in native image space to confusion matrix. Your fix passes `predn`, which are the same predicitons expressed in native image space. I agree, this is the correct fix. Will merge.

@ramonhollands thank you for your contributions to YOLOv5!

**Comment by ramonhollands** [comment]
You're very welcome, I'm happy to contribute!

**Pull request merged**
