### PR TITLE
ClearML's set_report_period's time is defined in minutes not seconds.

### PR DESCRIPTION
**Pull request by HighMans**
https://clear.ml/docs/latest/docs/references/sdk/hpo_optimization_hyperparameteroptimizer/#set_report_period

set_report_period function takes in time in terms of minutes, not seconds.

Signed-off-by: HighMans <42877729+HighMans@users.noreply.github.com>

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Optimization reporting frequency adjustment for ClearML Hyperparameter Optimization (HPO)

### 📊 Key Changes
- Changed the report period in ClearML's hyperparameter optimization from 10 seconds to every 10/60 minutes (10 seconds).

### 🎯 Purpose & Impact
- The update reduces the reporting frequency to a more reasonable interval for real-world applications.
- This can lead to less network traffic and reduced logging overhead, potentially improving the performance and usability of the HPO process for users.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@HighMans thanks for the PR!

@thepycoder can you review please?

**Comment by thepycoder** [comment]
Hi @HighMans! Thanks for another PR.

I'm a bit confused by you change
```

**Comment by thepycoder** [comment]
Hi @HighMans ! Thanks again for another PR :)

@glenn-jocher, that change looks good to me!

In fact, it was copy-pasted from our own examples over at the ClearML github, so I've asked our devs to change it there as well!

**Comment by glenn-jocher** [comment]
@HighMans @thepycoder perfect! 

PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
