### PR TITLE
Fix segment evolution keys

### LINKED ISSUE #9730: utils/general.py print_mutation variable keys does not correspond to output of seg train/val
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

 File ".../yolov5-master/segment/train.py", line 674, in <module>
    main(opt)
  File ".../yolov5-master/segment/train.py", line 654, in main
    print_mutation(results, hyp.copy(), save_dir, opt.bucket)
  File ".../yolov5-master/utils/general.py", line 979, in print_mutation
f.write(s + ('%s,' * n % vals).rstrip(',') + '\n')
TypeError: not all arguments converted during string formatting

### Environment

- yolov5 v6.2
- torchvision 0.13.1
- torch 1.12.1
- Python 3.10.6
- Ubuntu 20.04.4 LTS

### Minimal Reproducible Example

 python .../segment/train.py --data coco128-seg.yaml --weights '' --cfg yolov5s-seg.yaml --img 640 --evolve --epochs 2 --batch-size 3

### Additional

Hi,

variable keys (see below) in print_mutation needs to be updated to correspond to the output of train in .../segment/train.py when --evolve is used. 

keys = ('metrics/precision', 'metrics/recall', 'metrics/mAP_0.5', 'metrics/mAP_0.5:0.95', 'val/box_loss',
            'val/obj_loss', 'val/cls_loss') + tuple(hyp.keys())  # [results + hyps]

thank you!

cheers,
Adrian

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refinement of mutation results reporting in training scripts.

### 📊 Key Changes
- Changed the argument structure of the `print_mutation` function to accept `keys` as a parameter.
- Updated `train.py` and `segment/train.py` to specify keys when calling `print_mutation`.
- Reduced redundancy by removing the hardcoded keys list from the `print_mutation` function in `utils/general.py`.

### 🎯 Purpose & Impact
- 🛠️ **Purpose**: Streamlines the process of recording evolution data during hyperparameter tuning by making the desired keys for reporting more explicit and adaptable.
- 📈 **Impact**: Enhances the flexibility and maintainability of the code, which can lead to easier modifications and clearer mutation results for users engaging in hyperparameter optimization.

### CODE REVIEW

**Comment by AdrianStkr** [comment]
Hi,
thanks for your fast response. However, the bug is unfortunately still happening in the updated version. 

python segments/train.py --data coco128-seg.yaml --weights yolov5s-seg.pt --img 640 --epochs 1 --batch-size 3 --evolve 

still produces this:

  File ".../PycharmProjects/yolo/segment/train.py", line 674, in <module>
    main(opt)
  File ".../PycharmProjects/yolo/segment/train.py", line 654, in main
    print_mutation(KEYS, results, hyp.copy(), save_dir, opt.bucket)
  File ".../PycharmProjects/yolo/utils/general.py", line 977, in print_mutation
    f.write(s + ('%20.5g,' * n % vals).rstrip(',') + '\n')
TypeError: not enough arguments for format string

Cheers,
Adrian

**Comment by glenn-jocher** [comment]
@AdrianStkr hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by AdrianStkr** [comment]
Hi,
I´d like to help you with a Pull Request implementing a fix to the bug. However, in order to do that I need some further info, which I have difficulties finding out myself. 
- Can you specify the four different losses returned by segment/val.run? Can you further specify in which order the losses are returned?
- Is it feasible to change the order of keys in utils/segment/metrics.py without messing up other scripts referring to the list of keys in .../metrics.py?

best wishes,
Adrian

**Comment by glenn-jocher** [comment]
@AdrianStkr you can see the segmentation losses here:
https://github.com/ultralytics/yolov5/blob/16f87bb38e76a5aa14ee93252042063b678ece86/utils/segment/loss.py#L104-L111

I'd recommend not modifying the order of the keys in utils/segment/metrics.py

**Comment by AdrianStkr** [comment]
@glenn-jocher  Thank you for the very fast response and the valuable information!

the correct set and order of keys used in print_mutation is: 
`keys = ('metrics/bbox_precision', 'metrics/bbox_recall', 'metrics/bbox_mAP_0.5', 'metrics/bbox_mAP_0.5:0.95',
            'metrics/mask_precision', 'metrics/mask_recall', 'metrics/bbox_mAP_0.5', 'metrics/bbox_mAP_0.5:0.95',
            'boxloss', 'objectloss', 'classloss', 'segmentloss')`

I´ll implement the solution in a PR.
best wishes,
Adrian

**Comment by glenn-jocher** [comment]
@AdrianStkr great, thanks!

**Comment by ahmadtulsi** [comment]
I would like to ask question. I still get the same error after training when i enable --evolve parameter.

1 epochs completed in 0.002 hours.
Traceback (most recent call last):
  File "segment/train.py", line 658, in <module>
    main(opt)
  File "segment/train.py", line 638, in main
    print_mutation(KEYS, results, hyp.copy(), save_dir, opt.bucket)
  File "/content/yolov5/utils/general.py", line 1035, in print_mutation
    f.write(s + ('%20.5g,' * n % vals).rstrip(',') + '\n')
TypeError: not enough arguments for format string

is there any solution for this?

**Comment by glenn-jocher** [comment]
@ahmadtulsi I've able to reproduce this with `python segment/train.py --epochs 1 --evolve`, but I don't have time to implement a fix. If you could work on a fix and submit a PR that would be very helpful. The area of the code for segmentation evolution is here:

https://github.com/ultralytics/yolov5/blob/443ef7f33e0943ccc5e5c8ff922c6fe7a0cb7053/segment/train.py#L556-L645

**Comment by iker-lluvia** [comment]
I have created a PR (#11109 ) that fixes this error.

**Comment by glenn-jocher** [comment]
@iker-lluvia That's fantastic! Thank you for your contribution. I'll review the PR as soon as possible. Your help is much appreciated!

**Pull request merged**
