### PR TITLE
fix compatibility for hyper config

### PR DESCRIPTION
**Pull request by Borda**
changes in #1120 renamed a parameter in hyper config which means that all past configs are failing and from the error it is not very clear, so this is adding explanation warning and if the new argument is missing it uses the old one...

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved compatibility and refactored device selection in YOLOv5 training script.

### 📊 Key Changes
- Moved `device` selection to support Distributed Data Parallel (DDP) mode more seamlessly.
- Added a warning to handle missing `"box"` hyperparameter in configs, providing backward compatibility.
- Reordered imports for code cleanliness and standards.
- Refactored parts of the code to enhance maintainability and readability.

### 🎯 Purpose & Impact
- 🔁 The refactoring around `device` selection is meant to better support DDP, allowing for more scalable and efficient training across multiple GPUs 🚀.
- ⚠️ Warning for missing `"box"` hyperparameter ensures that users with older configurations will get notified about the change, preventing potential training issues 😌.
- ✨ With the overall refactoring and import reordering, the code base becomes cleaner, which makes it easier for developers to navigate and contribute 🧹.
- These changes should not directly affect model performance but can improve the user experience and reduce bugs in future developments 🛠️.

### CODE REVIEW

**Comment by Borda** [comment]
@glenn-jocher can we merge this compatibility hotfix :rabbit:

**Comment by glenn-jocher** [comment]
@Borda that's a good idea. Do you think we should actually place this in train.py right after the hyp.yaml is loaded? This would allow us to specify the exact name of the hyp file as well, i.e. `'problem with %s' % opt.hyp`

**Comment by glenn-jocher** [comment]
Maybe this?

```python
if 'box' not in h:
        warn(f'Compatibility: {opt.hyp} missing "box" which was renamed from past "giou". See https://github.com/ultralytics/yolov5/pull/1120')
        h['box'] = h['giou']
        del h['giou']
```

**Comment by glenn-jocher** [comment]
Ah, actually this combines the renaming and deleting into a single line:

```python
if 'box' not in h:
        warn(f'Compatibility: {opt.hyp} missing "box" which was renamed from past "giou" in https://github.com/ultralytics/yolov5/pull/1120')
        h['box'] = h.pop('giou')
```

**Comment by Borda** [comment]
> @Borda that's a good idea. Do you think we should actually place this in train.py right after the hyp.yaml is loaded? This would allow us to specify the exact name of the hyp file as well, i.e. `'problem with %s' % opt.hyp`

is the Trainer the only place from where the hyper can come? if you then train would be better...

**Comment by glenn-jocher** [comment]
Ok, I've sent this to train.py right after hyps are loaded (its the only place they are loaded), and tested. Output shows this, training starts correctly.

```python
/Users/glennjocher/PycharmProjects/yolov5/train.py:448: UserWarning: Compatibility: data/hyp.scratch.yaml missing "box" which was renamed from "giou" in https://github.com/ultralytics/yolov5/pull/1120
  warn('Compatibility: %s missing "box" which was renamed from "giou" in %s' %
```

**Pull request merged**
