### PR TITLE
fix coreml export and inference

### PR DESCRIPTION
**Pull request by mareczech1982**
Hi guis, thank you for the nice library. It helped me a lot for understanding how coreML and yolov5 works. The coreML part for export and for inference was not complete - or at least it didn't work for me. Now it works. 

You can export a coreML model with 
` python export.py --include coreml`
 and than run inference with 
`python detect.py --weights yolov5s.mlmodel`

@glenn-jocher, it seems to be your work, please have a look at it 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved CoreML model export compatibility with metadata and inference alterations.

### 📊 Key Changes
- Switched model to `eval()` mode during CoreML export, which is the standard mode for inference.
- Added a new metadata field to the CoreML export containing model class names, aiding in model interpretation.
- Altered CoreML model loading logic to accommodate new metadata usage.
- Updated the CoreML inference method to return the last tensor output directly, optimizing the prediction pipeline.

### 🎯 Purpose & Impact
- 🔍 **Enhanced Clarity:** Encodes class names in the CoreML model, making it easier for developers and end-users to understand predictions.
- 🤖 **Model Accuracy:** The change from `model.train()` to `model.eval()` ensures that the model is in the correct state for inference, potentially improving prediction accuracy.
- 🚀 **Inference Efficiency:** Streamlining the inference code can lead to faster model predictions for CoreML, enhancing the user experience for real-time applications.

### CODE REVIEW

**Comment by mareczech1982** [comment]
Hi @glenn-jocher , I have fixed the workflow errors. There is just a review waiting from somebody. I guess you could review it since its your code.

**Comment by sandeepwadhwa-ai** [comment]
I am getting an error post exporting the coreml model. When you try and run it. The following errors pop up. Keyerror "coordinates".

Traceback (most recent call last):
  File "detect.py", line 243, in <module>
    main(opt)
  File "detect.py", line 238, in main
    run(**vars(opt))
  File "/Users/sandy/research/yolov5/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 114, in run
    pred = model(im, augment=augment, visualize=visualize)
  File "/Users/sandy/research/yolov5/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/sandy/research/yolov5/models/common.py", line 391, in forward
    box = xywh2xyxy(y['coordinates'] * [[w, h, w, h]])  # xyxy pixels
KeyError: 'coordinates'

**Comment by mareczech1982** [comment]
@sandeepwadhwa-ai yes, that would be description of the bug before my fix. I am pretty sure, you are not using this branch, which is fixing this issue, because the CoreML logic is between lines 361 and 368, it cannot go to line 391. Please try to check out this branch and try again. Maybe you can add then some review to make it merged.

**Comment by sandeepwadhwa-ai** [comment]
Yes. I followed the code changes in your branch. It is now working. These changes should become part of main code. Thanks.

**Pull request closed without merging**
