### PR TITLE
YOLOv5 + Albumentations integration

### LINKED ISSUE #209: Non-letterbox resizing degrades performance
I've realised playing with these models that performance is degraded when using regular resizing vs letterbox resizing.
I would suggest not training with letterbox resizing, and instead add some augmentation whereby images are stretched, rotated, cropped, etc during training.

### LINKED ISSUE #248: Correctness of flip formula
First of all thanks so much for making this Yolo V5! It's now the best model in Kaggle Wheat detection : https://www.kaggle.com/c/global-wheat-detection

Trying to modify TTA, I found you use the following lr-flip formula for bbox : 

In `models/yolo.py`
`y[1][..., 0] = img_size[1] - y[1][..., 0]  # flip lr ---- Equation (1)` 

I have checked on Yolo V3 and it's the same, so I am sure the formula is correct.

However, in my understanding we should change both `xmin` and `xmax `for lr-flip but the formula above only change `xmin`.
For examples, the famous albumentations formula is :

https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/functional.py
In `def bbox_hflip`
`new_xmin, new_ymin, new_xmax, new_ymax = 1 - x_max, y_min, 1 - x_min, y_max`

Or explained intuitively here :  https://blog.paperspace.com/data-augmentation-for-bounding-boxes/

So my question is how can the above equation (1) is correct ??
It should be

`y[1][..., 2] = img_size[1] - y[1][..., 0]  # flip lr new xmax` 
`y[1][..., 0] = img_size[1] - y[1][..., 2]  # flip lr new xmin` 

**EDIT** : I got it. Yolo use `xcenter, ycenter, w, h`, so it explains Equation (1) . Close the issue.

### LINKED ISSUE #746: Reducing YOLOv5 Overfitting on COCO from scratch
## 🚀 Feature
Andrej Karpathy lists overfitting as one of the main steps in a training pipeline, and a prerequisite to regularization and obtaining a best final result:

http://karpathy.github.io/2019/04/25/recipe/
> The approach I like to take to finding a good model has two stages: first get a model large enough that it can overfit (i.e. focus on training loss) and then regularize it appropriately (give up some training loss to improve the validation loss)

On that front, the larger models are overfitting well, while the smallest just about completes training with no overfitting.  Here you can observe overfitting in the validation losses (objectness in particular) across the 4 models. The progression of greater overfitting for larger models is observed, as expected.
results

I've noticed interestingly in the switch from nn.LeakyReLU(0.1) to nn.Hardswish() that the overfitting has increased. For example here is YOLOv5l v2.0 vs v3.0. Very interestingly, val Objectness actually performs worse with the Hardswish() activations, the mAP gain must originate from better box regressions and better classifications. I do not know why this is, but I see a similar pattern in v5x, with worse val Objectness loss there also.
results

Since we have a multi-component loss function, made up of 3 individual losses (box, obj, cls), we would ideally like to reduce overfitting on a loss component basis (starting with Objectness), but this is not common practice that I'm aware of. L1 and L2 regularization techniques that might help in this situation can be targeted to individual parameters by assigning parameter groupings to the optimizer, but I don't think there's a precedent for targeting loss components with different regularization techniques (anyone correct me if I'm wrong).

It may be possible to create separate optimizers for each loss component, and assign then different weight_decays, though I don't know if this would involve a hit to training speed or memory consumption.

In any case, these are my thoughts on the matter. Other things I've tried are increased augmentation, including rotation, mixup, scale and perspective, nn.Dropout2d(0.1), and increased weight_decay using the existing structure, but in all of these cases the training results (on COCO from scratch) become worse. **If anyone has any ideas for Objectness regularization, or other techniques to reduce overfitting, please us know!**

### LINKED ISSUE #779: How to visualize input Dataloader after Augmentation?
Hi! I have a question your Dataloader.
Your yolov5 is soo difficult to me to analyze.. 
How to visualize input Dataloader after Augmentation? 
Before I training, I wonder how images come out in the dataloader.

Thanks!

### LINKED ISSUE #1929: How to incorporate custom data augmentation during training?
## ❔Question
Hi Glenn,

Great work. I know in Kaggle for the wheat competition many months ago YoloV5 was a great hit. 

I'm wanting to use custom augmentation during training for my dataset. How can I do that? Is this the [training augmentation config file?](https://github.com/ultralytics/yolov5/blob/9c91aeae10679fece5220e27cea3b68da669be89/data/hyp.scratch.yaml)

I'm wanting to add: RandomContrast, RandomGamma, RandomBrightness, ElasticTransform, GridDistortion, OpticalDistortion, ShiftScaleRotate.

Thanks Glenn,

Here's my Kaggle Profile: [www.kaggle.com/bopengiowa](http://www.kaggle.com/bopengiowa)

### LINKED ISSUE #1954: Support for imgaug
## 🚀 Feature

imgaug is very popular and is easy to work with. I am wondering if I put in PR's which allowed use of imgaug, such as `BoundingBox` instances, to be used in parts of the program if it would be approved.

e.g. The `plot_one_box` function could accept then convert `BoundingBox` instances to the proper format (tensor) for easy plotting of bboxes.

Example:
```
def plot_one_box(x, img, color=None, label=None, line_thickness=None):
    # If bbox is instance of BoundingBox
    if isinstance(x, BoundingBox):
        # Convert to tensor
        x = torch.tensor([x.x1, x.y1, x.x2, x.y2])
```

## Motivation

I use imgaug, albumentations uses imgaug. It is very easy to use.

## Pitch

Add functionality which allows use of imgaug.

### LINKED ISSUE #3578: change bounding box label index to text
## ❔Question
Hi, thanks for your great research and sharing codes.

I am applying YOLOv5 to my custom dataset.

And during learning, the mosaic section on wandb.ai shows the figure below.

image

However, I want to change the bbox label index to text label, such as '118' changes to 'cheesecake'.

What should I fix in code? or do I have to change my annotation?

Currently the data folder are consists of 
data_folder/  
┣ images/  
┃ ┣ train/  
┃ ┣ valid/  
┣ labels/  
┃ ┣ train/  
┃ ┣ valid/ 
┣ data_config.yaml

### LINKED ISSUE #3699: More Augmentations
## ❔Question
How i can use more and more augmentations related to Image Enhancements.

### PR DESCRIPTION
**Pull request by glenn-jocher**
I'm super excited to announce our new [YOLOv5](https://github.com/ultralytics/yolov5) 🚀 + [Albumentations](https://github.com/albumentations-team/albumentations) integration!! Now you can train the world's best Vision AI models even better with custom Albumentations automatically applied 😃!

PR https://github.com/ultralytics/yolov5/pull/3882 implements this integration, which will automatically apply Albumentations transforms during YOLOv5 training if `albumentations>=1.0.3` is installed in your environment.

## Get Started

To use albumentations simply `pip install -U albumentations` and then update the augmentation pipeline as you see fit in the new `Albumentations` class in [`yolov5/utils/augmentations.py`](https://github.com/ultralytics/yolov5/blob/def7a0fd19c1629903c3b073b4df265407719a07/utils/augmentations.py#L16-L17). Note these Albumentations operations run **in addition to** the YOLOv5 **hyperparameter** augmentations, i.e. defined in [hyp.scratch.yaml](https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch.yaml).

Here's an example that applies Blur, MedianBlur and ToGray albumentations in addition to the YOLOv5 hyperparameter augmentations normally applied to your training mosaics :)

```python
class Albumentations:
    # YOLOv5 Albumentations class (optional, used if package is installed)
    def __init__(self):
        self.transform = None
        try:
            import albumentations as A
            check_version(A.__version__, '1.0.3')  # version requirement

            self.transform = A.Compose([
                A.Blur(blur_limit=50, p=0.1),
                A.MedianBlur(blur_limit=51, p=0.1),
                A.ToGray(p=0.3)],
                bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels']))

            logging.info(colorstr('albumentations: ') + ', '.join(f'{x}' for x in self.transform.transforms))
        except ImportError:  # package not installed, skip
            pass
        except Exception as e:
            logging.info(colorstr('albumentations: ') + f'{e}')

    def __call__(self, im, labels, p=1.0):
        if self.transform and random.random() < p:
            new = self.transform(image=im, bboxes=labels[:, 1:], class_labels=labels[:, 0])  # transformed
            im, labels = new['image'], np.array([[c, *b] for c, b in zip(new['class_labels'], new['bboxes'])])
        return im, labels
```

## Example Result

Example `train_batch0.jpg` on COCO128 dataset with Blur, MedianBlur and ToGray. See the YOLOv5 [Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) to reproduce: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb">Open In Colab</a> <a href="https://www.kaggle.com/ultralytics/yolov5">Open In Kaggle</a>

train_batch0

# Update

To receive this YOLOv5 update:

- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb">Open In Colab</a> <a href="https://www.kaggle.com/ultralytics/yolov5">Open In Kaggle</a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5">Docker Pulls</a>

Thank you for your feedback and let us know if this update works for you, and of course feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀 + Albumentations!

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced image augmentation with Albumentations integration in YOLOv5

### 📊 Key Changes
- 📦 Albumentations library added to `requirements.txt` as an optional dependency.
- ✨ New `Albumentations` class created in `augmentations.py` to handle advanced image augmentation techniques.
- 🖼️ Albumentations are now applied during training in `utils/datasets.py` if augmentations are enabled.
- 🧩 Added version check for Albumentations in `utils/general.py`.

### 🎯 Purpose & Impact
- 👁️‍🗨️ This PR introduces more complex and diverse image transformations during model training for improved robustness and potential accuracy enhancements.
- 🧠 The integration allows users to leverage a broader range of augmentation options, potentially leading to better model generalization and performance.
- 🔄 The change is optional and backwards compatible, ensuring current workflows are uninterrupted for users who do not wish to use this new feature.

### CODE REVIEW

**Comment by nichaom** [comment]
What's about the defining of the sample of images output?

**Comment by glenn-jocher** [comment]
@nichaom I don't understand your question.

**Comment by nichaom** [comment]
> @nichaom I don't understand your question.

Thank you for your answer, I mean the way to specify number of images I require after I had added an augmentation pipeline like a step3 in the link which I've attached.

https://augmentor.readthedocs.io/en/master/userguide/usage.html

**Comment by nichaom** [comment]
> > @nichaom I don't understand your question.
> 
> Thank you for your answer, I mean the way to specify number of images I require after I had added an augmentation pipeline like a step3 in the link which I've attached.
> 
> https://augmentor.readthedocs.io/en/master/userguide/usage.html

**Comment by nichaom** [comment]
I have an another question. After Yolov5 was training wi the image augmentation, is it split the image augmentation into validation dataset?

Ps. This is the first time in AI field for me, I'm looking forward to your reply. Thank you so much.

**Comment by nichaom** [comment]
Hi, I would like to write the result from detect.py in text format and reply in Line Application. But the label shows only one class in text format. (Actually, there are 3 classes in the image.) Do you have any suggestion for solving my problem? 
Thank you.

**This is the part of my codes.**

# Print results
                for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += f'{n} {names[int(c)]}s, '  # add to string

                # Write results
                for *xyxy, conf, cls in reversed(det):
                    if save_txt:  # Write to file
                        xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                        line = (cls, *xywh,conf) if save_conf else (cls, *xywh)  # label format


                    if save_img or view_img:  # Add bbox to image
                        percentage = "{:.0%}".format(conf)
                        label = f'{names[int(cls)]} ({percentage})'
                        plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3)

            # Save results (image with detections)
            if save_img:
                if dataset.mode == 'image':
                    cv2.imwrite(save_path, im0)

            # Print time (inference + NMS)
            print(f'{s}Done. ({t2 - t1:.3f}s)')

url = request.url_root + '/static/tmp/' + dist_name

    line_bot_api.reply_message(
        event.reply_token, [
            TextSendMessage(text='Object detection result:'),
            ImageSendMessage(url,url)
        ])

@app.route('/static/<path:path>')
def send_static_content(path):
    return send_from_directory('static', path)

# create tmp dir for download content
make_static_tmp_dir()

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, debug=True)

**Comment by nichaom** [comment]
Hi, I would like to write the result from detect.py in text format and reply in Line Application. But the label shows only one class in text format. (Actually, there are 3 classes in the image.) Do you have any suggestion for solving my problem? 
Thank you.

**This is the part of my codes.**

# Print results
                for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += f'{n} {names[int(c)]}s, '  # add to string

                # Write results
                for *xyxy, conf, cls in reversed(det):
                    if save_txt:  # Write to file
                        xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                        line = (cls, *xywh,conf) if save_conf else (cls, *xywh)  # label format


                    if save_img or view_img:  # Add bbox to image
                        percentage = "{:.0%}".format(conf)
                        label = f'{names[int(cls)]} ({percentage})'
                        plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3)

            # Save results (image with detections)
            if save_img:
                if dataset.mode == 'image':
                    cv2.imwrite(save_path, im0)

            # Print time (inference + NMS)
            print(f'{s}Done. ({t2 - t1:.3f}s)')

url = request.url_root + '/static/tmp/' + dist_name

  line_bot_api.reply_message(
            event.reply_token, [
                TextSendMessage(text='Object Detection Result: '),
                TextSendMessage(text=label),
                ImageSendMessage(url,url)
            ])

**Comment by glenn-jocher** [comment]
@nichaom your post is off topic for this PR.

**Comment by nichaom** [comment]
@glenn-jocher sorry, I've deleted the post.

**Comment by sayakpaul** [comment]
@glenn-jocher could you help me understand where in the yolov5 code should one incorporate the Albumentation augmentation you showed above?

**Comment by glenn-jocher** [comment]
@sayakpaul 

> To use albumentations simply `pip install -U albumentations` and then update the augmentation pipeline as you see fit in the new `Albumentations` class in [`yolov5/utils/augmentations.py`](https://github.com/ultralytics/yolov5/blob/def7a0fd19c1629903c3b073b4df265407719a07/utils/augmentations.py#L16-L17)

**Comment by sayakpaul** [comment]
So, if I don't update it, will the default augmentation pipeline contain the Albumentation ones (given I have it installed)?

**Comment by glenn-jocher** [comment]
@sayakpaul yes

**Comment by JosepBC** [comment]
Hello, if I just want the augmentations from albumentations, except for mosaic, I should set the probability of all augmentatios of hyp.scratch-high.yaml to 0.0?

**Comment by glenn-jocher** [comment]
@JosepBC yes

**Comment by JosepBC** [comment]
Something like this if I just want mosaic, right?
hsv_h: 0.0  # image HSV-Hue augmentation (fraction)
hsv_s: 0.0  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.0  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.0  # image translation (+/- fraction)
scale: 0.0  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.0  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)
copy_paste: 0.0  # segment copy-paste (probability)

**Comment by glenn-jocher** [comment]
yes

**Pull request merged**
