### PR TITLE
Add `yolov5s-ghost.yaml`

### LINKED ISSUE #3234: about ghost module
## ❔Question

l've recently changed  the yolov5s models with ghost modules.I used ghostconv to replace conv and replaced the bottleneck in C3 with ghostbottleneck. I train with the new model successfully and get only a very small drop in map,while  the new model costs about 8 GFlops which is half of the yolov5s model(16GFlops).But when l run the test.py and find that the time consume of testing is almost the same as the yolov5s model,sometime even longer.

### LINKED ISSUE #4410: add ghostbottleneck module to yolov5s.yaml
## ❔Question
when I add ghostbottleneck module to yolov5s.yaml
image

## Additional context
# parameters
nc: 2  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, GhostBottleneck, [128, 3, 1]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, GhostBottleneck, [256, 3, 1]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, GhostBottleneck, [512, 3, 1]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, GhostBottleneck, [1024, 3, 1]],  # 9
  ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2]],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, GhostBottleneck, [512, 3, 1]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2]],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, GhostBottleneck, [256, 3, 1]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, GhostBottleneck, [512, 3, 1]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, GhostBottleneck, [1024, 3, 1]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

### PR DESCRIPTION
**Pull request by glenn-jocher**
Adds C3Ghost() module and new `yolov5s-ghost.yaml` to master to help users seeking to reproduce or design Ghost-related models from https://github.com/huawei-noah/ghostnet.

YOLOv5s-ghost comparison here using 
```
python val.py --weights yolov5s-ghost.pt --data coco.yaml --img 640 --iou 0.65 --half
YOLOv5 🚀 v5.0-330-g18f6ba7 torch 1.9.0+cu102 CUDA:0 (Tesla T4, 15109.75MB)
```

Model |size<br><sup>(pixels) |mAP<sup>val<br>0.5:0.95 |mAP<sup>test<br>0.5:0.95 |mAP<sup>val<br>0.5 |Speed<br><sup>T4 (ms) | |params<br><sup>(M) |FLOPS<br><sup>640 (B)
---   |---  |---        |---         |---             |---                |---|---              |---
YOLOv5s                 |640  |**37.0**     |-    |**56.4**     |**4.7** | |7.3   |17.0
YOLOv5s-ghost    |640  |35.6   |-     |54.1     |4.9     | |**3.9**  |**8.8**

Training comparison in https://wandb.ai/glenn-jocher/ghost

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduction of Ghost Convolution and Bottleneck modules to the YOLOv5 architecture for improved efficiency.

### 📊 Key Changes
- **New `GhostConv` and `GhostBottleneck` modules**: These new modules optimize performance by reducing the number of computations and parameters.
- **New `C3Ghost` subclass**: Inherits from the standard `C3` class but uses the GhostBottleneck for internal computations.
- **Refactor of module definitions**: `GhostConv` and `GhostBottleneck` definitions moved from `experimental.py` to `common.py`.
- **Addition of `yolov5s-ghost.yaml` configuration**: New model configuration file that employs ghost modules in the YOLOv5 architecture.

### 🎯 Purpose & Impact
- **Efficiency**: The update aims to make the model lighter and faster by integrating efficient convolutional operations.
- **Potential performance boost**: These changes could lead to better real-time inference speeds without significant loss in accuracy.
- **New model variant**: The YOLOv5s-Ghost model offers an alternative for applications where computational resources are limited.

### CODE REVIEW

**Comment by Zigars** [comment]
Hi glenn, I test ghostnet some times ago, and My test results are similar to yours, although ghostnet have less param and flops, it has low mAP and high speed than yolov5, I don't know the reason for it.

**Comment by glenn-jocher** [comment]
@Zigars it is what it is, for this Ghost configuration at least.

**Comment by lijain** [comment]
I had the same question. I took a look at the code.  The convolution kernel in Ghostnet is 3, and yours is 5. I wonder if this is the reason?

**Comment by lijain** [comment]
Just had a closer look, another reason is not that part of our network is missing the SqueezeExcite module

**Comment by glenn-jocher** [comment]
@lijain hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by JNaranjo-Alcazar** [comment]
Hi community,

I am new to ghost networks... Are they supposed to be faster than conventional networks?

I mean, ghost-yolov5s will perform with lower inference time than yolov5s?

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar you can ask the GhostNet authors at https://github.com/huawei-noah/CV-Backbones

**Comment by JNaranjo-Alcazar** [comment]
Thanks for the answer @glenn-jocher. I wonder if the network yolov5s-ghost can be donwloaded in order to run a detection

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar I've uploaded your trained yolov5s-ghost.pt here:
https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s-ghost.pt

EDIT: this model is out of date and not loading properly, deleted. Fallback is train your own ghost model:
```
python train.py --weights yolov5s.pt --cfg yolov5s-ghost.yaml
```

**Comment by JNaranjo-Alcazar** [comment]
Thanks @glenn-jocher for the reply.
I cannot see the model in the link you have pasted.

However, as I understand, the model is not working properly and I should train a ghost model from scratch....

Is that right?

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar yes

**Comment by JNaranjo-Alcazar** [comment]
The ghost model is TFLite conversion supported?

**Comment by JNaranjo-Alcazar** [comment]
Hi again! Thanks for the new version! Amazing job!

Is the ghost model supported for TFLite conversion? Another question, is the new nano model available with Ghost modules, `yolov5n-ghost.yaml`?

**Comment by glenn-jocher** [comment]
@JNaranjo-Alcazar TF models are built from scratch during TF exports, which has advantages and disadvantages, one disadvantage being that custom models must be defined in TF. Ghost TF export is not currently supported as ghost modules do not have TF counterparts.

There is no yolov5n-ghost available, but you can create one yourself using the yolov5n scaling constants and backbone applying the 5s to 5s-ghost changes.

**Comment by JimmyW-11** [comment]
> Hi glenn, I test ghostnet some times ago, and My test results are similar to yours, although ghostnet have less param and flops, it has low mAP and high speed than yolov5, I don't know the reason for it.

bro, i also tested ghostnet with VOC, but i found the result of mAP dropped a lot(10%), i don't know how to imporve it. training command is all same except the config of the net.

**Pull request merged**
