### PR TITLE
update `detect.py` in order to support torch script

### PR DESCRIPTION
**Pull request by andreiionutdamian**
This change assumes the torchscrip file was previously saved with `export.py`.
Based on the issue #5070 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added TorchScript compatibility to model loading in `detect.py`.

### 📊 Key Changes
- `detect.py` now includes a conditional to check for 'torchscript' in the model file name.
- If 'torchscript' is found, the script uses `torch.jit.load()` to load the model; otherwise, it uses the existing `attempt_load()` method.

### 🎯 Purpose & Impact
- **Purpose**: This change enables the use of TorchScript models, which can offer better performance and easier deployments to different platforms.
- **Impact**: Users can now run inference with YOLOv5 using TorchScript format models, potentially increasing the use cases and environments where YOLOv5 can be applied. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@andreiionutdamian thanks for the PR! I think this covers model loading, but we need additions in a second, place, inference, right? Otherwise you are attempting to use a torchscript model for normal pytorch inference, which should not be possible (probably the source of the CI fails):
https://github.com/ultralytics/yolov5/blob/276b6745132f2da0641706124c466b69f21b670c/detect.py#L142-L145

**Comment by andreiionutdamian** [comment]
@glenn-jocher it should work just fine. The whole intuition is to have exactly the same functionality but in a more graph/serialized way. Tried this already on other models and it works quite nice. So basically what happens after `th.jit.load` or `th.load` (or `th.nn.Module` definition, `th.nn.Module` instance & param dict loading) should not matter...

And one more thing: thank you sir for all your replies and real hands-on involvement.

**Comment by glenn-jocher** [comment]
@andreiionutdamian oh, got it! Good to know.

Can you debug the updates then to resolve the CI failures? Then we should be all set. Thanks!

**Comment by andreiionutdamian** [comment]
> 
> 
> @andreiionutdamian oh, got it! Good to know.
> 
> Can you debug the updates then to resolve the CI failures? Then we should be all set. Thanks!

Sorry, forgot to merge the modifications of the sloppy code spacing done directly in GitHub editor.

**Pull request merged**
