### PR TITLE
`DEVICE_COUNT` instead of `WORLD_SIZE` to calculate `nw`

### PR DESCRIPTION
**Pull request by sitecao**
https://github.com/ultralytics/yolov5/issues/6298

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced data loader device compatibility in YOLOv5 🤖.

### 📊 Key Changes
- Changed `WORLD_SIZE` to `DEVICE_COUNT` to better reflect the number of available GPU devices.
- The `DEVICE_COUNT` now directly uses `torch.cuda.device_count()` to get the GPU count, ensuring at least one device is accounted for.

### 🎯 Purpose & Impact
- Ensures more accurate determination and utilization of CPU resources relative to the available GPU devices.
- Improves the data loader's performance and efficiency, potentially leading to faster training times and better support for systems with multiple GPUs. 🚀
- Users with different GPU configurations should experience more optimized data loading operations.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@sitecao would it be possible to simplify this by simply replacing:

```python
WORLD_SIZE = int(os.getenv('WORLD_SIZE', 1))  # DDP
# with
DEVICE_COUNT = torch.cuda.device_count()  # DDP
```

We want the device count rather than the requested device count in order to compute the threads better, i.e. if we train on 2 out of 8 GPUs we only want the dataloader to use 2/8=25% of the available threads in total.

**Comment by sitecao** [comment]
> @sitecao would it be possible to simplify this by simply replacing:
> 
> ```python
> WORLD_SIZE = int(os.getenv('WORLD_SIZE', 1))  # DDP
> # with
> DEVICE_COUNT = torch.cuda.device_count()  # DDP
> ```
> 
> We want the device count rather than the requested device count in order to compute the threads better, i.e. if we train on 2 out of 8 GPUs we only want the dataloader to use 2/8=25% of the available threads in total.

@glenn-jocher done! used max(torch.cuda.device_count(), 1) just in case user is running without GPUs :)

**Comment by glenn-jocher** [comment]
Looks good! /rebase

**Comment by glenn-jocher** [comment]
@sitecao PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
