### PR TITLE
Proto upsample experiments

### PR DESCRIPTION
**Pull request by glenn-jocher**
@AyushExel @Laughing-q @kingmacth @sctrueew PR for Proto upsampling updates to attempt a fix for https://github.com/ultralytics/yolov5/issues/9955

Signed-off-by: Glenn Jocher <glenn.jocher@ultralytics.com>

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing ConvTranspose layer for improved upsampling in YOLOv5 models.

### 📊 Key Changes
- ✨ Added `ConvTranspose` class as a new module for transposed 2D convolutions.
- 🔄 Replaced `nn.Upsample` with `ConvTranspose` in the `Proto` module for upsampling operations.

### 🎯 Purpose & Impact
- 📈 The ConvTranspose layer provides a learnable upsampling mechanism, which could potentially increase the model's ability to reconstruct fine details in tasks such as segmentation.
- 🚀 Users can expect enhanced feature learning at different scales due to the improved upsampling capability, potentially leading to better performance in certain scenarios.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
First problem, we can't use bilinear2d due to non-determinism :(

I'll explore bicubic
```
RuntimeError: upsample_bilinear2d_backward_out_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
```

**Comment by glenn-jocher** [comment]
We also have nn.ConvTranspose2d() as an option. I tested this on a small training and works with deterministic=True. Now that I'm looking at it I'm not sure if it might have benefits to treat it as a convolution, with a training BN and activation?

**Comment by glenn-jocher** [comment]
@AyushExel or maybe even simpler, just keep the existing models but use something like:
```python
mode = 'nearest' if self.training else 'bilinear'
```

**Comment by Laughing-q** [comment]
@glenn-jocher @AyushExel I'm not sure if `bilinear` matters in `Upsample` module. I've visualized some images from coco val set with our yolov5s-seg model and one yolact model, which the yolact model is trained with `bilinear` mode upsample and yolov5s-seg is with `nearest` mode.
I don't see much differences about the jagged edge.
If there're jagged edges, both of them got jagged edges:
yolov5s-seg:
2FJ3c1sDM6
yolact:
ezMkPgK351

And if there's no jagged edge then both of them don't have it.

**Comment by AyushExel** [comment]
@Laughing-q after reading your response on the other thread, I think it makes sense to conclude that the jagged edges might be due to the downsampling of images from 4000x3000 to 640x640 which is quite a lot.

**Pull request closed without merging**
