### PR TITLE
Comet ML Integration

### PR DESCRIPTION
**Pull request by DN6**
This PR:

1. Adds support for logging metrics, hyperparameters, model predictions, checkpoints, and datasets from the YOLOv5 `train.py` script. 
3. Adds supports for resuming a training run from an Existing Comet Experiment 
4. Adds support for downloading checkpoints from a Comet Experiment
5. Adds support for downloading a dataset from Comet Artifacts downloading  
6. Adds support for using the Comet Hyperparameter Optimizer with the YOLOv5 `train.py` script.
7. Adds the relevant section on how to use Comet with YOLOv5 to `tutorials.ipynb`
8. Adds a README guide for the integration under `utils/loggers/comet` to explain the features of the integration
9. Updates the main README file in the repo with a link to the Comet README     

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added Comet integration support to YOLOv5 for enhanced ML experiment logging and visualization.

### 📊 Key Changes
- Implemented Comet logger for tracking training progress, experimenting, and visualizing results.
- Added flexibility to log various user-defined metrics and artifacts.
- Provided option to run Comet in online or offline mode.
- Enabled logging model predictions and additional datasets as Comet artifacts.
- Integrated Comet hyperparameter sweeps with YOLOv5.

### 🎯 Purpose & Impact
- 📈 Enables better experiment management, tracking, and comparison across training runs.
- 🔍 Allows users to visualize metrics, model predictions, and dataset distributions effectively.
- ⚙️ Offers tools for hyperparameter tuning to improve model performance.
- 🔄 Supports resuming training and hyperparameter sweeps, providing robustness to the training process.
- 🚀 Enhances collaboration within teams by enabling easy sharing of experiment details and outcomes.

### CODE REVIEW

**Comment by AyushExel** [comment]
Hi @DN6 thanks for the PR! Can you please remove formatting changes? Those make it very difficult to review. YOLOv5 uses pycharm formatter. Maybe if you just run the repo through the formatter unnecessary changes will be reverted

**Comment by DN6** [comment]
Hi @AyushExel. Updated the formatting.

**Comment by glenn-jocher** [comment]
@DN6 thanks for the PR! You need to remove all external formatting from your files. YOLOv5 automatically applies YAPF formatting defined in setup.cfg befor which is already incorporated into master.
https://github.com/ultralytics/yolov5/blob/master/setup.cfg

If it's easier you might want to close this PR, create a new fork, apply your changes to the master code without formatting the master code, and then submit a PR from there. Otherwise please remove all formatting that's been applied in this PR.

**Comment by glenn-jocher** [comment]
Sounds good, @DN6. Thank you for your understanding and cooperation. Looking forward to your new PR! 🚀

**Pull request closed without merging**
