### PR TITLE
Explicit opt function arguments

### PR DESCRIPTION
**Pull request by fcakyon**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactor of `detect.py` and `test.py` to include an `opt` parameter in their functions.

### 📊 Key Changes
- Modified the `detect()` function definition in `detect.py` to accept an `opt` parameter.
- Updated internal calls to `detect()` within the same file to pass the `opt` parameter.
- In `test.py`, updated the `test()` function definition to accept an `opt` parameter.
- Adjusted calls to `test()` within `test.py` to include the new `opt` parameter.

### 🎯 Purpose & Impact
- **Purpose:** These changes integrate configuration options directly into the function calls, making the functions more modular and flexible with respect to different configurations. 
- **Impact:** Users can now pass different configurations when calling `detect()` and `test()`, allowing for better customization for specific use cases. Developers benefit from cleaner code and a more explicit display of dependencies.

### CODE REVIEW

**Comment by fcakyon** [comment]
what do you think about this update @glenn-jocher  ?

**Comment by glenn-jocher** [comment]
@fcakyon hey this doesn't look too bad. Will this change make life easier on the pip side of things?

I'm not sure you want to set a default value for opt though, since the detect() function won't run correctly with `def detect(opt=None):`

**Comment by fcakyon** [comment]
@glenn-jocher it will definitely make it easier :)

Removed default value in detect().

**Comment by glenn-jocher** [comment]
@fcakyon ok. Changes look good. Is this PR ready to merge?

**Comment by fcakyon** [comment]
@glenn-jocher yes it is ready to merge.

**Comment by glenn-jocher** [comment]
@fcakyon thank you for your contributions!

**Comment by fcakyon** [comment]
Thank you too :)

**Pull request merged**
