### PR TITLE
SavedModel TF Serve Fix

### LINKED ISSUE #7205: export to saved_model with --nms flag yields incorrect/incomplete results.
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Relates to two issues resulting from exporting exporting to saved_model with the `--nms` flag set.

1. Output from model has no data for classes and scores
2. 100 boxes are returned with `--nms` flag compared to 4 boxes (2 persons, 2 ties) without `--nms` flag 

After exporting with the command
```bash
python export.py --weights yolov5s.pt --include saved_model --nms
```
The output from `saved_model_cli` shows the following inputs/outputs
```bash
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['x'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 640, 640, 3)
        name: serving_default_x:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_0'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 100, 4)
        name: PartitionedCall:0
  Method name is: tensorflow/serving/predict
WARNING:absl:Importing a function (__inference_pruned_7064) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
```
This indicates that the output is a tensor of 100 rows of bbox data. Visualization of these output boxes shows:

```bash
python export.py --weights yolov5s.pt --include saved_model --nms
python test_serve.py  # Here test_serve uses the tensroflow serve restful API
```
image

I have confirmed that the export function works perfectly well with no nms when doing inference with `detect.py`

Output from model with no nms using:
```bash
python export.py --weights yolov5s.pt --include saved_model
python detect.py --weights yolov5s_saved_model/ --source data/images/zidane.jpg
```
image

### Environment

- YOLOv5 🚀 v6.1-74-gcf4f3c3 torch 1.11.0+cu113 CPU
- Ubuntu 18.04 LTS
- Python 3.8

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
Fix for https://github.com/ultralytics/yolov5/issues/7205 proposed by @tylertroy

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced TensorFlow SavedModel export functionality with NMS (Non-Max Suppression) support.

### 📊 Key Changes
- 📝 Rearranged the order of some lines of code for better readability.
- ✨ Modified the TensorFlow export code to support exporting models with NMS directly incorporated for TensorFlow SavedModels.

### 🎯 Purpose & Impact
- The main purpose of these changes is to improve the TensorFlow model export process by including NMS within the SavedModel itself.
- Users who rely on TensorFlow for deploying models will benefit from this, as it simplifies the deployment pipeline by embedding crucial post-processing steps (like NMS) into the model, reducing the need for additional code after loading the model.
- The impact of this change streamlines model deployment, potentially improving performance and stability since the model export is more aligned with TensorFlow's execution framework. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@tylertroy your proposed fix breaks existing workflows, i.e. SavedModel inference with detect.py:
```python
!git clone https://github.com/ultralytics/yolov5 -b fix/tf_serve
%cd yolov5

!python export.py --include saved_model
!python detect.py --weights yolov5s_saved_model
```

Screenshot 2022-03-31 at 16 34 52

EDIT: Since all TF exports rely on SavedModel as a prerequisite they are all probably also impacted. So this small change has knockon impacts down the export and inference workflows that would need to be resolved for before update could be considered for merging with master.

**Comment by tylertroy** [comment]
@glenn-jocher As I understand it, any time the `--nms` flag is applied, then the saved_model no longer works with `detect.py`. I understood my change to only effect output when `--nms` is applied. Not so?
 
 Edit: Now I understand the issue you describe. Perhaps an if statement can clear this up. 
 
 ```bash
 diff --git a/export.py b/export.py
index 7517dc4..0c44cc0 100644
--- a/export.py
+++ b/export.py
@@ -276,7 +276,7 @@ def export_saved_model(model, im, file, dynamic,
             m = m.get_concrete_function(spec)
             frozen_func = convert_variables_to_constants_v2(m)
             tfm = tf.Module()
-            tfm.__call__ = tf.function(lambda x: frozen_func(x)[0], [spec])
+            tfm.__call__ = tf.function(lambda x: frozen_func(x)[:4], [spec]) if tf_nms else tf.function(lambda x: frozen_func(x)[0], [spec])
             tfm.__call__(im)
             tf.saved_model.save(
                 tfm,
```

**Comment by glenn-jocher** [comment]
@tylertroy yes it's true that NMS models are no longer detect.py compatible. It seems like the proposed update (or at least my implementation here) affects SavedModels regardless of the --nms flag though.

Maybe the solution is an `if nms: ... else: ...` statement there to only apply the change to --nms exports?

**Comment by tylertroy** [comment]
@glenn-jocher 
Great idea, I also made this suggestion in my above comment as an edit. Probably should have just made a new message! See above.

**Review by tylertroy — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@tylertroy PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
