### PR TITLE
Handle edgetpu model inference

### PR DESCRIPTION
**Pull request by Namburger**
TESTED=python3 detect.py --source 0 --weights yolov5n-int8_edgetpu.tflite

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced TFLite model support for Edge TPU in `detect.py`.

### 📊 Key Changes
- Imported `platform` library in `detect.py`.
- Added Edge TPU compatibility logic in TFLite model loading section.

### 🎯 Purpose & Impact
- **Integration with Edge TPUs:** Allows users to utilize models optimized for Google's Edge TPUs, enhancing inference speed on supported hardware.
- **Cross-Platform Support:** Support for Linux, macOS, and Windows is included, ensuring a wide range of users can benefit from this update.
- **Ease of Use:** The PR simplifies the process of deploying models on various platforms with Edge TPU support, potentially expanding the user base and applicability of YOLOv5 in edge computing environments.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Namburger I've merged with master and cleaned this up a bit. I also renamed the tflite import to avoid conflict with the existing tflite boolean. Can you verify the PR still works correctly? Thanks!

**Comment by Namburger** [comment]
> @Namburger I've merged with master and cleaned this up a bit. I also renamed the tflite import to avoid conflict with the existing tflite boolean. Can you verify the PR still works correctly? Thanks!

Thanks for cleaning up the shadowing and it looks good!

**Comment by glenn-jocher** [comment]
@Namburger PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
