### PR TITLE
Keypoints

### PR DESCRIPTION
**Pull request by andreysher**
Hi @glenn-jocher, @AyushExel and @Laughing-q there is [ENOT Team](https://enot.ai/) keypoint implementation in YOLOv5!

Thank you for this project. It is very useful for us.

Hope that we can collaborate somehow in the future.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced YOLOv5 with keypoint detection capabilities and improved benchmarks.

### 📊 Key Changes
- Added keypoint detection task to benchmarks with COCO and hand datasets.
- Implemented keypoint detection loss calculation.
- Updated performance metrics to include keypoint analysis.
- Included keypoints in Non-Max Suppression (NMS) and inference outputs.
- Extended model configurations to support keypoint dimensions.
- Upgraded training scripts to handle keypoint data arrangement.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: The addition of keypoint detection allows for more versatile object detection models, capable of intricate tasks like pose estimation or object tracking.
- 💥 **Impact**: Users can now train models to detect not only objects but also specific points of interest within those objects, opening the door to more detailed and sophisticated computer vision applications.

### CODE REVIEW

**Comment by AyushExel** [comment]
@andreysher hey thanks for the PR. I'd like to proceed further on this for which a quick chat would be better. Can you send me mail at ayush@ultralytics.com ? I'll also loop in Glenn and Laughing-q in the thread.

**Comment by andreysher** [comment]
> @andreysher hey thanks for the PR. I'd like to proceed further on this for which a quick chat would be better. Can you send me mail at [ayush@ultralytics.com](mailto:ayush@ultralytics.com) ? I'll also loop in Glenn and Laughing-q in the thread.

Done

**Comment by glenn-jocher** [comment]
@AyushExel @andreysher awesome! Looking forward to chatting.

**Comment by AyushExel** [comment]
@andreysher sent you an email

**Pull request closed without merging**
