### PR TITLE
Detection cropping+saving feature addition for detect.py and PyTorch Hub

### PR DESCRIPTION
**Pull request by burhr2**
Added arg option save_obj to save the detected objects as separate images. These images will be saved in cropped dir inside the project/name/cropped dir.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to YOLOv5 detection and saving mechanisms, including cropped image saving.

### 📊 Key Changes
- **Detection Argument Changes**: Removed `save_img` parameter from `detect()` function; it’s now determined inside the function itself.
- **Saving Cropped Detections**: Added `--save-crop` option to save cropped predicted boxes.
- **Path Management**: Updated `increment_path` function to handle directory creation when incrementing paths.
- **Bug Fixes**: Ensured that mutable defaults are not used in function signatures to avoid potential issues with object mutability.
- **Code Cleanup**: Minor refactoring and clean-up, ensuring object copying for immutability and modifying logic when `show`, `save`, or `render` results.

### 🎯 Purpose & Impact
- 🖼 **Cropped Image Saving**: Users can now save cropped images of detections, which can be useful for datasets creation or further analysis.
- 🚀 **Improved Path Handling**: Simplified the process of path incrementing, avoiding conflicts, and ensuring necessary directories are created, which results in a more robust and user-friendly experience.
- 🐞 **Stability and Safety**: Changes ensure code stability and prevent potential bugs associated with the use of mutable defaults and object references.
- 🧹 **Refactoring**: Improves the readability and maintainability of the codebase, making it easier for developers to understand and contribute.

These updates enhance the utility and robustness of the YOLOv5 detection pipeline, making it more flexible and user-friendly for various applications.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Ab-Abdurrahman thanks buddy, looks better. Will review.

**Comment by glenn-jocher** [comment]
@Ab-Abdurrahman I've updated your PR a bit, creating a new function to handle directory management/creation, cropping and saving. These crops are now saved in the default classification dataset directory structure of 1 directory per class.

```python
def save_one_box(xyxy, im, file='crop.jpg', gain=1.02, pad=10, square=False):
    # save an image crop as filename.jpg (crop size multiplied by 'gain' and padded by 'pad' pixels)
    xyxy = torch.tensor(xyxy).view(-1, 4)
    b = xyxy2xywh(xyxy)  # boxes
    if square:
        b[:, 2:] = b[:, 2:].max(1)[0].unsqueeze(1)  # attempt rectangle to square
    b[:, 2:] = b[:, 2:] * gain + pad  # box wh * gain + pad
    xyxy = xywh2xyxy(b).long()
    clip_coords(xyxy, im.shape)
    crop = im[int(xyxy[0, 1]):int(xyxy[0, 3]), int(xyxy[0, 0]):int(xyxy[0, 2])]

    file = Path(increment_path(file)).with_suffix('.jpg')
    if not file.parent.exists():
        file.parent.mkdir(parents=True, exist_ok=True)  # make dir
    cv2.imwrite(str(file), crop)
```

Placing this feature mostly in a function will also allow easier access to the same cropping behavior for pytorch hub models with results.crop(). I'll work on that next and try to get this merged afterward.

**Comment by glenn-jocher** [comment]
@Ab-Abdurrahman PR is merged! Thank you for your contributions. 

Prediction box cropping is now available in YOLOv5 via PR https://github.com/ultralytics/yolov5/pull/2827! PyTorch Hub models can use `results.crop()` or detect.py can be called with the `--save-crop` argument. Example usage:
```
python detect.py --save-crop
```
Screenshot 2021-04-20 at 23 50 51

**Comment by burhr2** [comment]
Nice @glenn-jocher. Thank you

**Pull request merged**
