### PR TITLE
Replace ONNXSim with ONNXSlim

### PR DESCRIPTION
**Pull request by Kayzwer**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR replaces the ONNX model simplifier with a newer slim tool for better model optimization.

### 📊 Key Changes
- 📝 Replaced `onnx-simplifier` with `onnxslim` for model optimization.
- 📈 Updated the requirement checks for the `onnxslim` package.
- 🎉 Adjusted log messages to reflect the use of `onnxslim`.

### 🎯 Purpose & Impact
- ➕ **Purpose:** To use a more efficient and potentially more reliable tool (onnxslim) for optimizing ONNX models.
- 💼 **Impact:** Users may experience faster and more reliable model optimization, leading to better performance in deployments.

### CODE REVIEW

**Comment by Kayzwer** [comment]
@inisis done

**Comment by inisis** [comment]
@Kayzwer thank you bro

**Comment by inisis** [comment]
Hi @glenn-jocher , can this be merged, it' was tested in ultralytics

**Comment by glenn-jocher** [comment]
Hi @inisis,

Thank you for your contribution! It's great to hear that you've tested this in Ultralytics. Before we proceed with merging, could you please ensure that the changes are compatible with the latest versions of the dependencies and that all tests pass successfully? This helps us maintain stability and reliability for all users.

If everything checks out, we'll be happy to review and merge your PR. Thanks again for your efforts and for contributing to the YOLO community! 😊

**Comment by inisis** [comment]
@glenn-jocher I believe all the CI tests are passed 😊

**Comment by glenn-jocher** [comment]
Hi @inisis,

That's fantastic news! 🎉 Thank you for running the CI tests and confirming that they have passed. This is a crucial step in ensuring the stability and reliability of the changes.

We'll proceed with a final review of your PR. If everything looks good, we'll merge it shortly. Your contribution is greatly appreciated and will benefit the entire YOLO community.

Thanks again for your hard work and dedication!

**Comment by glenn-jocher** [comment]
@Kayzwer @inisis PR merged! Thank you for your contributions :)

**Pull request merged**
