### PR TITLE
Train from `--data path/to/dataset.zip` feature

### PR DESCRIPTION
**Pull request by glenn-jocher**
@KalenMike this PR enables training directly from dataset zips as discussed.

Usage example:
```
cd yolov5
python train.py --data https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128_with_yaml.zip
```

By default all zip files will extract like this:
```python
# parent
# ├── yolov5
# └── datasets
#     ├── coco128.zip  ← downloads here
#     └── coco128  ← extracts here
#         └── coco128.yaml
```

CONSTRAINT: abc.zip MUST unzip to abc/

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactor and enhancement of dataset handling and logging in YOLOv5 repository.

### 📊 Key Changes
- 🔁 Renamed `Argoverse_HD.yaml` to `Argoverse.yaml` to simplify naming convention.
- 💾 Moved download utility functions from `google_utils.py` to a more generic module named `downloads.py`.
- 🔄 Replaced raw file opening with `check_dataset()` method to ensure proper dataset checking and downloading if necessary.
- 🗑️ Removed redundant code and simplified dataset verification in `datasets.py`.
- 🎛️ Added `profile` and `hub` flags to `dataset_stats()` for profiling and better dataset integration with HUB.
- 📦 Renamed `google_utils.py` to `downloads.py` for a more accurate description of its functionality.
- ✨ Improved dataset check and download functions, with better handling of datasets provided in `.zip` format.

### 🎯 Purpose & Impact
- This PR aims to streamline dataset handling and simplify the code for maintainability. By consolidating dataset checks and download processes, users can expect a more reliable setup experience.
- The renaming and refactoring work could reduce confusion and improve readability, easing future contributions to the codebase.
- The integration with HUB and enhanced profiling can provide a more robust development and user experience when working with datasets.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel this may modify resuming from W&B artifacts, can you take a look at train.py L80-L111, the order of check_datasets() was swapped, and check_datasets() now handles data.yaml parsing. I updated the single usage of check_datasets() inside the wandb_utils I found in L302.

**Comment by AyushExel** [comment]
@glenn-jocher thanks for the heads up. This is not working with Tables and artifacts enabled but I think I know why, I'll push a fix

**Comment by AyushExel** [comment]
@glenn-jocher the problem I see here is that check_dataset will automatically download the dataset if it is not found in the local system, but in a case of resume, when data is present as artifact, WandbLogger will download it and set the `data_dict` to the downloaded dataset path. 
With the new order of dataset check, the dataset will be downloaded twice. I'd propose the previous structure like this:
```
# Load YAML
data_dict = load_yaml(opt.data)
loggers = loggers.init(data_dict)
if opt.resume and loggers.wandb:
     data_dict = loggers.wandb.data_dict
check_dataset(data_dict)
```
This will prevent any duplication of dataset but it'll not work for zip dataset.
So, the best solution might to split the `check_dataset` into 2 parts, one that just checks if it is present and the second that attempts to download it.

**Comment by glenn-jocher** [comment]
@AyushExel ya that's what I was worried about. Kalen and I are adding additional capabilities so the code is having to implement more possible tasks now. The new functionality allows direct train from data.zip (yaml inside dataset)  in addition to data.yaml. I uploaded an example coco128_with_yaml.zip to the release assets to verify, so you can now run this command. 

Usage example:
```
cd yolov5
python train.py --data https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128_with_yaml.zip
```

By default all zip files will extract like this and the new `path` field will be set dynamically at runtime.
```python
# parent
# ├── yolov5
# └── datasets
#     ├── coco128.zip  ← downloads here
#     └── coco128  ← extracts here
#         └── coco128.yaml
```

I'll take a look at this in some more detail to see how to accomodate all options:

```bash
python train.py --data data.yaml  # dataset exists
python train.py --data data.yaml  # download: key in yaml installs dataset
python train.py --data data.zip  # this PR
python train.py --data ...  # W&B artifact
```

**Comment by AyushExel** [comment]
@glenn-jocher I've been working on supporting all features with these changes. It'll require another refactoring of wandb_utils which I'm almost done with. The good news is that I think I have a solution. Just testing some use cases. I'll update shortly

**Pull request merged**
