### PR TITLE
update mask2segments and saving results

### LINKED ISSUE #9784: masks2segments function does not always work correctly
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

_No response_

### Bug

When i use `segment/predict.py --save-txt` to save segmentation results, sometimes i had an error. 

The reason for this was an empty mask (only zeros), which was passed to the input of the masks2segments function. In this regard, `c = cv2.findContours(x, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0]` produced an empty tuple(due to previous transformations over the mask) and then there was an error.

I made the following changes in 3 places to avoid this:

1. general.py
```
def masks2segments(masks, strategy='largest'):
    # Convert masks(n,160,160) into segments(n,xy)
    segments = []
    for x in masks.int().cpu().numpy().astype('uint8'):
        c = cv2.findContours(x, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0]
        if c:
            if strategy == 'concat':  # concatenate all segments
                c = np.concatenate([x.reshape(-1, 2) for x in c])
            elif strategy == 'largest':  # select largest segment
                c = np.array(c[np.array([len(x) for x in c]).argmax()]).reshape(-1, 2)
            segments.append(c.astype('float32'))
        else:
            segments.append(0)
    return segments
```

2. segment/predict.py
```
# Segments
if save_txt:
    segments = reversed(masks2segments(masks))
    segments = [scale_segments(im.shape[2:], x, im0.shape).round() if not isinstance(x, int) else 0 for x in segments]
```

3. segment/predict.py
```
# Write results
for j, (*xyxy, conf, cls) in enumerate(reversed(det[:, :6])):
    if save_txt:  # Write to file
        if not isinstance(segments[j], int):
            segj = segments[j].reshape(-1)  # (n,2) to (n*2)
            line = (cls, *segj, conf) if save_conf else (cls, *segj)  # label format
            with open(f'{txt_path}.txt', 'a') as f:
                f.write(('%g ' * len(line)).rstrip() % line + '\n')
        else:
            line = (cls, segments[j], conf) if save_conf else (cls, segments[j])  # label format
            with open(f'{txt_path}.txt', 'a') as f:
                f.write(('%g ' * len(line)).rstrip() % line + '\n')
```

It helps me to avoid an error. 
I understand that my changes are not perfect. The main goal was to point out the problem itself.

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by vladoossss**
PR for this issue: https://github.com/ultralytics/yolov5/issues/9784

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhances segmentation strategies in YOLOv5 by ensuring robust handling of images with no detectable segments.

### 📊 Key Changes
- Added a conditional check to handle scenarios where no contours are found during segment processing.
- Ensures that a zero-filled array is used as a fallback for images lacking any detectable segments.

### 🎯 Purpose & Impact
- **Purpose:** The update aims to prevent errors that occur when the model processes an image without detectable segments by properly handling an empty contour list.
- **Impact:** This change ensures greater stability for the segmentation functionality in YOLOv5, leading to a more reliable performance for developers and users working with diverse image datasets. 📈

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@vladoossss I'd like to minimize the code changes here. Are you saying that some detections produce no masks?

Is there a way I can reproduce the issue myself? I don't think it makes sense to add integers to a list of segment masks. Can you simply update masks2segments with an `if` and no `else`?

```python
def masks2segments(masks, strategy='largest'):
    # Convert masks(n,160,160) into segments(n,xy)
    segments = []
    for x in masks.int().cpu().numpy().astype('uint8'):
        c = cv2.findContours(x, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0]
        if c:
            if strategy == 'concat':  # concatenate all segments
                c = np.concatenate([x.reshape(-1, 2) for x in c])
            elif strategy == 'largest':  # select largest segment
                c = np.array(c[np.array([len(x) for x in c]).argmax()]).reshape(-1, 2)
            segments.append(c.astype('float32'))
    return segments
```

**Comment by glenn-jocher** [comment]
@vladoossss ok took another look. I see we need to keep the output array the same length as the input masks, how about creating an empty nparray when there is no segment of the same 2 columns. Can you try this new function with no other changes anywhere (i.e. use master segments/predict.py etc.)

```python
def masks2segments(masks, strategy='largest'):
    # Convert masks(n,160,160) into segments(n,xy)
    segments = []
    for x in masks.int().cpu().numpy().astype('uint8'):
        c = cv2.findContours(x, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0]
        if c:
            if strategy == 'concat':  # concatenate all segments
                c = np.concatenate([x.reshape(-1, 2) for x in c])
            elif strategy == 'largest':  # select largest segment
                c = np.array(c[np.array([len(x) for x in c]).argmax()]).reshape(-1, 2)
        else:
            c = np.zeros((0, 2))  # no segments found
        segments.append(c.astype('float32'))
    return segments
```

**Comment by vladoossss** [comment]
> @vladoossss ok took another look. I see we need to keep the output array the same length as the input masks, how about creating an empty nparray when there is no segment of the same 2 columns. Can you try this new function with no other changes anywhere (i.e. use master segments/predict.py etc.)
> 
> ```python
> def masks2segments(masks, strategy='largest'):
>     # Convert masks(n,160,160) into segments(n,xy)
>     segments = []
>     for x in masks.int().cpu().numpy().astype('uint8'):
>         c = cv2.findContours(x, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0]
>         if c:
>             if strategy == 'concat':  # concatenate all segments
>                 c = np.concatenate([x.reshape(-1, 2) for x in c])
>             elif strategy == 'largest':  # select largest segment
>                 c = np.array(c[np.array([len(x) for x in c]).argmax()]).reshape(-1, 2)
>         else:
>             c = np.zeros((0, 2))  # no segments found
>         segments.append(c.astype('float32'))
>     return segments
> ```

Yes, modifying just this one function also works fine!

**Comment by glenn-jocher** [comment]
@vladoossss great! PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
