### PR TITLE
ACON activation function

### LINKED ISSUE #2891: A new activation function ACON that is very simple and effective !!
## 🚀 Feature

There is a new activation function [ACON (CVPR 2021)](https://arxiv.org/pdf/2009.04759.pdf) that unifies ReLU and Swish. 
ACON is simple but very effective, code is here: https://github.com/nmaac/acon/blob/main/acon.py#L19

image

The improvements are very significant:
image

## Pitch

I would like to suggest replacing SiLU with ACON directly because SiLU (Swish) is used in your project, its general and effective form ACON may also show improvements.

## Alternatives

It also has an enhanced version meta-ACON that uses a small network to learn beta explicitly, which may influence the speed a bit.

## Additional context

[Code](https://github.com/nmaac/acon) and [paper](https://arxiv.org/pdf/2009.04759.pdf).

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🚀 Feature

There is a new activation function [ACON (CVPR 2021)](https://arxiv.org/pdf/2009.04759.pdf) that unifies ReLU and Swish. 
ACON is simple but very effective, code is here: https://github.com/nmaac/acon/blob/main/acon.py#L19

image

The improvements are very significant:
image

## Alternatives

It also has an enhanced version meta-ACON that uses a small network to learn beta explicitly, which may influence the speed a bit.

## Additional context

[Code](https://github.com/nmaac/acon) and [paper](https://arxiv.org/pdf/2009.04759.pdf).

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of activation functions with the addition of ACON variants and removal of MemoryEfficientSwish.

### 📊 Key Changes
- 🗑️ Removed `MemoryEfficientSwish` activation class.
- ➕ Added `AconC` activation class, which is a parameterized activation function.
- ➕ Introduced `MetaAconC` activation class with a dynamic beta parameter determined by a mini-network.

### 🎯 Purpose & Impact
- The removal of `MemoryEfficientSwish` could be for simplifying the codebase or because it's less relevant now.
- The new `AconC` activation provides a flexible activation mechanism which can potentially improve model performance by adapting to different inputs.
- `MetaAconC` further increases this adaptability by generating the beta parameter through a small neural network, potentially allowing for more complex representations and improved learning.
- These changes may lead to more efficient and powerful neural network models within the Ultralytics ecosystem. 🚀

### CODE REVIEW

**Comment by www516717402** [comment]
Have you compare with mish activate function in yolov5? @glenn-jocher

**Comment by glenn-jocher** [comment]
@www516717402 yes **Mish** is included in our activation study, and we are currently in the process of running **FReLU**, **SiLU(Beta*x)**, **AconC** and **MetaAconC**. Once all the tests are complete we will publish the study results, you can follow the results realtime at this link:
https://wandb.ai/glenn-jocher/activations

**Comment by www516717402** [comment]
Great help. Thank you.

**Pull request merged**
