### PR TITLE
Avoid redundant processing in minor loop

### PR DESCRIPTION
**Pull request by topiaruss**
Some of this processing is being unnecessarily repeated for each detection, when it should be frame/image oriented.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Streamlining `detect.py` for efficiency in the YOLOv5 application.

### 📊 Key Changes
- Refactored code to remove nested conditions within image detection and saving logic.
- Simplified output streaming and image/video saving processes.

### 🎯 Purpose & Impact
- Improves code readability and maintainability. 🛠️
- Potentially increases performance by reducing unnecessary checks within the main detection loop. ⚡
- End-users should experience a more concise codebase leading to easier modifications and potentially smoother operation, especially when saving detection results. 📈
- No direct impact on detection accuracy or output results, ensuring users get the same quality of detections with a streamlined code structure. 👌

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@topiaruss thanks for the PR. I like speeding up inference, but the operations you pointed out are already only running once per image, they can not be brought out of this loop any further.

**Comment by topiaruss** [comment]
Surely the unindented lines now are outside the loop starting on line 76, which executes per prediction?
        for i, det in enumerate(pred):  # detections per image
?

**Comment by glenn-jocher** [comment]
@topiaruss no, this code runs once per image.

**Comment by topiaruss** [comment]
OK. 
Sorry for the noise.

**Pull request closed without merging**
