### PR TITLE
Update requirements.txt

### LINKED ISSUE #414: TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
image

**Got this error while running the train.py file in Google Colab**

the full link of the notebook is - https://colab.research.google.com/drive/10J3_S3_pjpvh55ZwoBnjK3xyX0zTRSSq?usp=sharing

## To Reproduce (REQUIRED)

Input:
```
!python train.py --img 1024 --batch 32 --epochs 10 --data /content/wheat.yaml --cfg models/yolov5s.yaml --name wm --nosave --cache
```

Output:
```
Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
Namespace(batch_size=32, bucket='', cache_images=True, cfg='models/yolov5s.yaml', data='/content/wheat.yaml', device='', epochs=10, evolve=False, hyp='', img_size=[1024], multi_scale=False, name='wm', noautoanchor=False, nosave=True, notest=False, rect=False, resume=False, single_cls=False, weights='')
Using CUDA device0 _CudaDeviceProperties(name='Tesla K80', total_memory=11441MB)

2020-07-14 21:11:21.719560: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
Hyperparameters {'optimizer': 'SGD', 'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.58, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.014, 'hsv_s': 0.68, 'hsv_v': 0.36, 'degrees': 0.0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
Traceback (most recent call last):
  File "train.py", line 404, in <module>
    train(hyp)
  File "train.py", line 57, in train
    yaml.dump(hyp, f, sort_keys=False)
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
```

## Expected behavior
It should start training the model

## Environment
I was running it on google colab Gpu

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancing testing workflow and updating dependencies for YOLOv5 🚀

### 📊 Key Changes
- 🧪 Added a new line in CI testing workflow to run `hubconf.py`
- ✏️ Modified `custom` function in `hubconf.py` to save results instead of showing them
- 📦 Updated the minimum required version of PyYAML in `requirements.txt`

### 🎯 Purpose & Impact
- 📈 The addition of `hubconf.py` script execution to the testing workflow aims to ensure the hub interface remains reliable with updates, preventing integration issues.
- 🔄 The change from `results.show()` to `results.save()` in `hubconf.py` transitions from displaying results to storing them, which could streamline workflows that process image results programmatically.
- 💼 Lowering the PyYAML version requirement increases compatibility with environments where newer PyYAML versions are not available, broadening the user base that can run YOLOv5 without additional upgrades.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
Lower pyYAML requirement to current Colab version, eliminating need to install pyYAML on colab start. Saves about 1-2 seconds on every Colab start :)

Also hubconf.py now added to CI tests.

**Comment by glenn-jocher** [comment]
Just noticed, this PR is number 2021!! 

To optimism in this new year. Everyone keep their heads up, I'm sure good things are ahead of us :)

**Comment by killernay** [comment]
> Lower pyYAML requirement to current Colab version, eliminating need to install pyYAML on colab start. Saves about 1-2 seconds on every Colab start :)
> 
> Also hubconf.py now added to CI tests.

**I got error from colab just normal tutorial.ipynb.**

!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --nosave --cache

github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 v4.0-41-g9a3da79 torch 1.7.0+cu101 CUDA:0 (Tesla T4, 15079.75MB)

Namespace(adam=False, batch_size=16, bucket='', cache_images=True, cfg='', data='./data/coco128.yaml', device='', epochs=3, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], local_rank=-1, log_artifacts=False, log_imgs=16, multi_scale=False, name='exp', noautoanchor=False, nosave=True, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/exp', single_cls=False, sync_bn=False, total_batch_size=16, weights='yolov5s.pt', workers=8, world_size=1)
wandb: Install Weights & Biases for YOLOv5 logging with 'pip install wandb' (recommended)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
2021-01-24 08:00:37.646235: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0
Traceback (most recent call last):
  File "train.py", line 522, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 53, in train
    yaml.dump(hyp, f, sort_keys=False)
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'

**Comment by glenn-jocher** [comment]
@killernay understood. #414 is reopened on this issue, and I just created a PR to fix this in @#2030, so this should be resolved today.

**Pull request merged**
