### PR TITLE
fix: prevent logging config clobbering

### PR DESCRIPTION
**Pull request by rkechols**
Fix for issue: https://github.com/ultralytics/yolov5/issues/10132

- Previous behavior: loading this repository with `torch.hub.load` clobbers the existing logging configuration by modifying the root logger's configuration.
- New behavior: loading this repository with `torch.hub.load` only clobbers the logging configuration for logger `yolov5` and its descendants.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced logging initiation process with dynamic logger name setup in the YOLOv5 code.

### 📊 Key Changes
- Moved the "yolov5" logger name into a variable before initializing the logging.
- Called `set_logging()` with the new `logger_name` variable.

### 🎯 Purpose & Impact
- 🛠️ **Maintainability**: Defining the logger name as a variable makes the code more maintainable and clear.
- 🔍 **Clarity**: It's now easier to change the logger name in one place if needed in the future.
- 👥 **User Experience**: No direct impact on end users, but developers will appreciate the cleaner setup for logging.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Please what problem this line 129 and like 130 had??

**Review by ghost — COMMENTED** [review]
Oooh okay I get it now. You run before defining. Thank you. I was confused at first. 😂😂😂

**Comment by rkechols** [comment]
@Christiansarpong , the linked issue, #10132, has more details if needed.

**Comment by glenn-jocher** [comment]
@rkechols thanks for the PR! Can you please update your branch to master and then I'll merge?

**Comment by glenn-jocher** [comment]
@rkechols thanks, but for some reason GitHub is showing me an out of date message here. It's strange because usually there's a button to update. I think there may be something wrong with the PR. Can you please close this one and open a new one with your updates? I'll prioritize that and should be able to merge immediately. Thanks!

Screenshot 2022-11-15 at 19 07 48

**Comment by rkechols** [comment]
Yes, there was another button to update from main. It's running now.

**Comment by rkechols** [comment]
@glenn-jocher , ready for you

**Comment by glenn-jocher** [comment]
@rkechols PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
