### PR TITLE
Add `--source screen` for screenshot inference

### PR DESCRIPTION
**Pull request by zombob**
add SCREENSHOT as source ([isse link](https://github.com/ultralytics/yolov5/issues/2045#issuecomment-1253875724))
you can use it like:
```
python .\detect.py --source screen   # default full screen(0)
python .\detect.py --source "screen 2"   # 2nd screen only if you have multiple monitors, can specify screen number
python .\detect.py --source "screen 500 600 256 256"   # Specify top, left, width and height
python .\detect.py --source "screen 1 500 100 256 256"   # Specify screen nunmber, top, left, width and height
```
Position parameters(left,top) is relative to the "screen"'s left and top,
if you have multiple monitors, the left and top of the screen my be NOT (0,0) !
About the screen can refer to the [mss document](https://python-mss.readthedocs.io/examples.html#part-of-the-screen-of-the-2nd-monitor)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing screenshot detection to YOLOv5 with the new `screen` source option.

### 📊 Key Changes
- 🖥️ Added ability to take screenshots as input with `screen` source keyword.
- 🔎 Expanded input sources in `README.md`, notebook, and script help strings to include new screenshot functionality.
- 🧰 Integrated the `LoadScreenshots` class for fetching screen captures as a data source.
- ➕ Added a requirement for the `mss` library, which is necessary for screenshot functionality.

### 🎯 Purpose & Impact
- 🆕 The purpose of this change is to widen the input capabilities of YOLOv5 to include live screen captures, offering more flexibility for real-time applications.
- 📈 This will have a positive impact on users who wish to apply YOLOv5 object detection on their screen content without the need for pre-recorded media or additional hardware.
- 👨‍💻 Developers can now seamlessly integrate YOLOv5 into desktop applications that work with screen content, enhancing automation and monitoring solutions.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@zombob this looks good but we want to minimise changes to detect.py, as we’ll need to duplicate any code changes there to segment/predict.py and classify/predict.py. 

Can you pass the —source screen args to LoadScreenshots and parse args there?

**Comment by zombob** [comment]
> @zombob this looks good but we want to minimise changes to detect.py, as we’ll need to duplicate any code changes there to segment/predict.py and classify/predict.py.
> 
> Can you pass the —source screen args to LoadScreenshots and parse args there?

Fixed.
And change the name "LoadScreenshot" to "LoadScreenshots".

**Comment by zombob** [comment]
#

**Comment by zombob** [comment]
God!
New bug: if use "--view-img",  every screenshot show a new opencv windows

**Comment by zombob** [comment]
Fixed! Fixed! Fixed!
Take screenshots as streams:
"--view-img" to show one windows;
inference result save as "X.mp4" file. (X is screen number)

**Comment by glenn-jocher** [comment]
@zombob great to hear that the issue is fixed! Thank you for the update, and we appreciate your efforts in improving YOLOv5. If you have any further questions or need assistance with anything else, feel free to ask.

**Pull request merged**
