### PR TITLE
Update detect.py

### PR DESCRIPTION
**Pull request by hopesala**
update print info for relative path and absolute
otherwise the info below is misleading

Results saved to /workspace//output_path1  

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved file path display in detection results

### 📊 Key Changes
- Changed the way the output path is printed to the console after saving detection results.

### 🎯 Purpose & Impact
- 🛠️ **Purpose:** This change simplifies the code for displaying the saved file path and potentially fixes any cross-platform path display issues by using the `Path` object from Python's `pathlib`.
- 🚀 **Impact:** Users will see a cleaner and more consistent output path in their console, regardless of the operating system they are using. This enhances the user experience by making the results easier to locate and access.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@hopesala hi, thanks for the PR. Are you seeking a more absolute path? What OS are you on? Perhaps something like this would be more concise:
```python
    if save_txt or save_img:
        print('Results saved to %s' % Path(out).absolute())  # os-agnostic
        if platform == 'darwin' and not opt.update:  # MacOS
            os.system('open ' + save_path)
```

**Comment by hopesala** [comment]
Thanks for replying.
My OS is MacOS, I run the detect.py and if the output path  is passed in as "/output_path", it will generate the result in the root path /output_path rather in the workspace/output_path

**Comment by hopesala** [comment]
print('Results saved to %s' % Path(out).absolute())  # os-agnostic
this is much concise than mine!

**Comment by glenn-jocher** [comment]
@hopesala oh, but this line simply prints a path for the user to see on screen. The actual file each image is saved to is `save_path`. Maybe I'm not understanding though, can you supply a command to reproduce what you are seeing?

**Comment by hopesala** [comment]
the command is something like 
python3 detect.py --source '/input_path' --weights /workspace/last.pt --save-txt  --output '/output_path'

**Comment by glenn-jocher** [comment]
Oh I see, you are talking about specifying a custom output folder. We should probably simply pass opt.output through an os agnostic absolute path checker like above then right after the argparser.

**Comment by glenn-jocher** [comment]
@hopesala ok, I think I'll update the line to make it OS agnostic, this way it should display correctly in all 3 OS's. In regards to abs vs local, I did not find an easy fix that works across all 3 OS's. I think on MacOS you may always need to start a path with a period rather than a slash:

`python detect.py --output ./local_dir`

**Comment by hopesala** [comment]
OK，got it, and thank you very much!

**Pull request merged**
