### PR TITLE
TFDetect dynamic anchor count assignment fix

### PR DESCRIPTION
**Pull request by nrupatunga**
1. Currently the TFDetect layer is hardcoded to `3` anchors. change it to take care of a dynamic number of anchors in the model

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement to output tensor reshaping in TensorFlow model wrapper.

### 📊 Key Changes
- Modified the reshaping of the output tensor from `3 * ny * nx` to `self.na * ny * nx`.

### 🎯 Purpose & Impact
- **Purpose:** To fix the logic for reshaping the output tensor to correctly reflect the anchor boxes count (`self.na`) used in the object detection model.
- **Impact:** This change ensures accurate output dimensions, which is critical for proper functioning of object detection. It might affect downstream tasks such as object localization and classification performance. Users working with TensorFlow models will have more reliable output, potentially improving the model's overall predictions on image data.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@nrupatunga good catch! If we want to use the number of anchors though, we should use the Detect `na` attribute defined here:
https://github.com/ultralytics/yolov5/blob/e80a09bbfa1ddb1097fdc7164d84dedeb3d95388/models/tf.py#L207

**Comment by nrupatunga** [comment]
@glenn-jocher Oops! missed it altogether. That's a clean change to do. Fixed the changes.

**Comment by glenn-jocher** [comment]
@nrupatunga see https://github.com/ultralytics/yolov5/issues/5278#issuecomment-970171986, we can not add tensorrt specific packages to requirements.txt as the majority of users will not need these and do not want them.

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@nrupatunga PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
