### PR TITLE
HUB dataset_stats() error reporting

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancing dataset yaml loading robustness in `dataloaders.py`.

### 📊 Key Changes
- Wrapped yaml loading inside a `try` block.
- Added an `except` block to raise a specific exception on yaml loading failure.

### 🎯 Purpose & Impact
- **Purpose**: To provide a more clear and user-friendly error message if there are issues loading the dataset yaml file.
- **Impact**: Users will encounter a more descriptive error when yaml loading fails, making debugging easier and improving overall user experience. 🛠️

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@kalenmike how's this?

**Comment by kalenmike** [comment]
@glenn-jocher It will work great to check for YAML parse errors, but can we handle for the other errors as well? Like the paths don't exist for example.

**Comment by glenn-jocher** [comment]
@kalenmike hmm, most of the finer checks are run by the default YOLOv5 function here:
https://github.com/ultralytics/yolov5/blob/6a67594cbfe6599aab7006e33948f073e14246a8/utils/dataloaders.py#L1031

It looks like only the val path is specifically checked though. We could expand to all parts of the dataset: train, val, test:
i.e. L485 
https://github.com/ultralytics/yolov5/blob/6a67594cbfe6599aab7006e33948f073e14246a8/utils/general.py#L472-L487

**Comment by glenn-jocher** [comment]
@kalenmike PR merged to avoid letting it linger. Will update HUB tag to master and we can work on additional error reporting next week.

**Comment by awetzel-lionpower** [comment]
I am currently getting the generic "Failed: Processing Error". Wondering if the more detailed error reporting has been finished. My data works fine with yolov5.

**Comment by glenn-jocher** [comment]
@awetzel-lionpower glad your data works with YOLOv5! We've enhanced error reporting with the latest changes. Please update to the latest version and provide the specific error message if the issue persists. Always happy to help!

**Pull request merged**
