### PR TITLE
fix(utils): missing edge when resample segments

### PR DESCRIPTION
**Pull request by HRan2004**
One small problem.  When resample segments, missing an edge from the last point to the first.
Eg: https://github.com/HRan2004/Yolo-ArbV2/blob/main/data/images/debug01.png
When the polygon is cut, the missing edge will lead to the wrong position of the GT box.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement to segment resampling in the YOLOv5 codebase.

### 📊 Key Changes
- Added a line of code to ensure that the first point of a segment is repeated at the end, completing the loop before resampling.

### 🎯 Purpose & Impact
- Ensures that closed segments (like those forming polygons) properly connect by including the starting point at the end before interpolation.
- This small but critical update may improve the accuracy of geometric operations or analyses performed on these segments.
- Users dealing with polygonal data representations will benefit from more accurate resampling, impacting tasks such as object detection or segmentation in images. 🌐✨

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@HRan2004 thanks for the PR! Have you trained this successfully with a segmented dataset?

**Comment by HRan2004** [comment]
@glenn-jocher  I did not directly use yolov5 to train the segment dataset, but I successfully trained on the modified model and found the bug at this time. There are many modifications, and the GT box is not generated by segment, but predicted the segment directly.

Repos address (https://github.com/HRan2004/Yolo-ArbV2)

**Comment by glenn-jocher** [comment]
@HRan2004 got it, thank you! I will train a segmented dataset to verify.

**Comment by glenn-jocher** [comment]
Temp experiment tracking at https://wandb.ai/glenn-jocher/test-segmentfix

**Comment by glenn-jocher** [comment]
@HRan2004 PR shows improved results on segmentation dataset training:
Screenshot 2022-06-09 at 10 50 48

**Comment by glenn-jocher** [comment]
@HRan2004 PR is merged. It looks like you found and fixed a significant bug in segmentation training! Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
