### PR TITLE
added config files for much lighter yolov5 models

### PR DESCRIPTION
**Pull request by jere357**
mistake, let me redo this, this code was really weird for "legacy" reasons
this is the actual PR:
https://github.com/ultralytics/yolov5/pull/11813

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Optimizing and modularizing Ultralytics YOLOv5's codebase for maintainability and functionality.

### 📊 Key Changes
- 🔁 Refactored common utility functions into separate modules for checks (e.g., file size verification) and device selection.
- 🧹 Cleaned up code by removing redundant imports and consolidating utility functions.
- ✨ Introduced new lightweight model configuration files: `yolov5pico.yaml`, `yolov5micro.yaml`, and `yolov5femto.yaml`.
- 🔄 Replaced `attempt_load` with `attempt_load_weights` for model weight initialization across multiple scripts.

### 🎯 Purpose & Impact
- ✔️ Simplification makes the codebase more readable and easier to maintain.
- 📦 Modular architecture enhances code reusability.
- 📉 New lightweight models offer users more options for resource-constrained environments.
- 🚀 Centralized device selection should prevent inconsistencies and make GPU/CPU usage across modules more uniform.

### CODE REVIEW

**Comment by jere357** [comment]
mistake, let me redo this, this code was really weird for "legacy" reasons
this is the actual PR: 
https://github.com/ultralytics/yolov5/pull/11813

**Comment by glenn-jocher** [comment]
@jere357 thank you for bringing this to our attention. We appreciate your effort in providing the config files for lighter YOLOv5 models. 

Mistakes happen, and we understand the need to make corrections. We appreciate your honesty in acknowledging the issue with the code and taking the initiative to rectify it.

We will review the updated pull request (PR) you shared, and our team will carefully evaluate the changes made. We prioritize maintaining a robust and reliable codebase, so your contribution is valuable to us in improving the project.

Once again, thank you for your contribution and for being proactive in addressing the issue. We appreciate your understanding and support.

If you have any further questions or need assistance, please feel free to let us know.

Keep up the great work!

Ultralytics YOLOv5 Team

**Comment by jere357** [comment]
@glenn-jocher no problem, feel free to open a discussion in how to convert the other PR into an actual PR, i think we gotta figure out where to include it in documentation, whether there is a need to mention these configs in the COCO benchmark. Also transfer them to the other yolov8 repo as future work, that is something i can do but I'd like to see how we figure things out here first.
You and the team take your time, the PR is a bit weird but i feel many people will find that the lighter models are more than enough for simple object detection tasks.

**Comment by glenn-jocher** [comment]
@jere357 

Thank you for your understanding. We appreciate your willingness to discuss and collaborate on converting the previous pull request into an actual one. It is important to properly integrate the changes and consider their inclusion in the documentation, as well as decide whether to mention these configs in the COCO benchmark.

We also agree that transferring these configs to the other yolov8 repository as future work is a good idea. Once we have resolved the details here, we can proceed with that task.

We will take our time to carefully review and discuss the changes in order to ensure a smooth and effective integration. We fully acknowledge the value of lighter models for simple object detection tasks and are excited to work towards making them more accessible to the community.

Thank you once again for your contribution and patience. We look forward to collaborating with you on this matter.

Ultralytics YOLOv5 Team

**Pull request closed without merging**
