### PR TITLE
Allow detect.py to use video size for initial window size

### PR DESCRIPTION
**Pull request by NicholasZolton**
It appeared that there was a bug introduced in #8318 that caused the `detect.py` window to be opened with a smaller shape than the video content. 

I have talked to @RyanHir (author of #8318) and the change introduced in the previous PR was unexpected. In the discussion held in #8318 it was claimed that `namedWindow()` had to be called in the loop, but this does not appear to be the case and can instead be called once.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to visualization and efficiency in the YOLOv5 detection script.

### 📊 Key Changes
- Initialized an empty list `windows` to keep track of created OpenCV windows.
- Updated window creation logic to check if a window has already been created before initializing a new one.

### 🎯 Purpose & Impact
- **Avoid Redundancy:** Prevents the unnecessary creation of multiple windows for the same output stream, which can clutter the screen and consume more system resources.
- **Optimize Viewing Experience:** Ensures that each newly created OpenCV window is resized to match the dimensions of the output image, providing a more consistent and user-friendly display.
- **Impact to Users:** Users will have a cleaner interface when running detection in real-time with the view enabled, leading to better performance and a more intuitive display of detection results.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@NicholasZolton I can't test since neither this nor https://github.com/ultralytics/yolov5/pull/8318 have any effect on macOS. 

Does resizing the window to it's image size risk the possibility that the image is larger than the screen?

**Comment by RyanHir** [comment]
Hello, @NicholasZolton and I share a lab environment, and I am aware of the issue at hand.

Since we only develop on Ubuntu 20.04 systems, we have not tested if the issues we have are present on macOS or Windows. Before #8318, windows would open to show the full resolution image, but would not allow for resizing if the content was too big for the screen (Ubuntu). After the PR (#8318), all windows would open with a size similar to 300x300. This PR (#8330) is returning this functionality where the window will open to the "correct" size, but preserving the ability to resize.

**Comment by NicholasZolton** [comment]
To further add to this, I just tested it on Windows and it appears that, just like MacOS, Windows isn't affected by any of these changes, so this PR (#8330) fixes the bug on Ubuntu and does not affect other platforms from what I can gather.

**Comment by glenn-jocher** [comment]
@NicholasZolton @RyanHir got it, thanks guys!

**Comment by glenn-jocher** [comment]
@NicholasZolton PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
