### PR TITLE
Feature/classification tutorial refactor

### PR DESCRIPTION
**Pull request by paulguerrie**
Refactored the classification tutorial to match the main tutorial.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added a comprehensive tutorial notebook for YOLOv5 classification tasks.

### 📊 Key Changes
- 📁 New `tutorial.ipynb` notebook added for classification.
- 🚀 Includes setup, prediction, validation, and training guidelines.
- ✨ Features tensorboard integration for logging and visualization.
- 🎓 Instructions for active learning loop closure using Roboflow.
- 🧪 Comet and ClearML integration details provided.
- 🔒 Local logging with CSV and TensorBoard explained.
- 📚 Additional appendix content for further learning and execution.

### 🎯 Purpose & Impact
- 📖 Provides an end-to-end tutorial for users interested in YOLOv5 classification to follow along easily.
- 🛠️ Facilitates easier setup and use of YOLOv5's classification capabilities, potentially increasing adoption and user success.
- 🏋️‍♂️ Helps users understand and apply transfer learning for their custom classification tasks.
- 🌐 Enhances user experience by integrating with robust experiment tracking and dataset versioning systems.

### CODE REVIEW

**Comment by paulguerrie** [comment]
Here's the predict output image for you guys to host.

zidane

**Comment by glenn-jocher** [comment]
@paulguerrie thanks! I'll take a look. Did you run inference at --img 224 for zidane.jpg? Confidence seem pretty low.

**Comment by paulguerrie** [comment]
I don't think so.  I'm pretty sure the image I provided was the output of this command: `!python classify/predict.py --weights yolov5s-cls.pt --img 640 --source data/images`

**Comment by glenn-jocher** [comment]
> I don't think so. I'm pretty sure the image I provided was the output of this command: `!python classify/predict.py --weights yolov5s-cls.pt --img 640 --source data/images`

Ohh ok got it. That makes sense then. The ImageNet-trained classification models are all at --imgsz 224, so running them at 640 will cause poor results. Detection and Segmentation are all at 640 though :)

**Comment by glenn-jocher** [comment]
@paulguerrie hey I'm updating all notebooks now, just noticed there seems to be an image missing here. I think I'm going to merge this now, but if you can provide me the updated image URL I can fix this. This should probably be an image of Roboflow classification annotation, or just annotation in general.

Screenshot 2022-11-18 at 22 00 12

**Comment by glenn-jocher** [comment]
EDIT, I'll just use this one from the blog post :)

Screen-Shot-2022-08-19-at-3 52 11-PM

**Pull request merged**
