### PR TITLE
Update ci-testing.yml

### PR DESCRIPTION
**Pull request by YoniChechik**
add testing to saved_model and tflite conversion

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced export compatibility for YOLOv5 models in TensorFlow formats.

### 📊 Key Changes
- Added a new line in the CI (Continuous Integration) testing workflow to export YOLOv5 models to TensorFlow's `saved_model` and `tflite` formats.

### 🎯 Purpose & Impact
- 🎨 **Purpose**: This change ensures that automated tests now include the process of converting YOLOv5 models to additional TensorFlow formats, increasing the compatibility and usability of YOLOv5 in TensorFlow-based environments.
- ✅ **Impact**: Users benefit from enhanced support for model deployment across diverse platforms, which now includes TensorFlow Lite for mobile and IoT devices, broadening YOLOv5's applicability.

### CODE REVIEW

**Comment by YoniChechik** [comment]
Currently this fix is failing due to this bug: https://github.com/ultralytics/yolov5/issues/5147

**Comment by YoniChechik** [comment]
Once https://github.com/ultralytics/yolov5/pull/5153 is merged, the errors above will be eliminated.

**Comment by glenn-jocher** [comment]
@YoniChechik thanks for the PR! 

That's too bad that the CI checks did not catch the TF model issue with the SPPF layer, but I think the existing CI should suffice since it actually builds a new TF and Keras model already with this line. 

https://github.com/ultralytics/yolov5/blob/26784afd998937811dfff34392ccd83f87e1e41f/.github/workflows/ci-testing.yml#L80-L81

I'm a little confused about why the CI checks didn't report an error here, but I think the source of the problem was that it was loading models from the latest release, which at the time was v5.0. Since tf.py builds models from a *.pt file's internal yaml rather than directly from a yaml, it was pulling the v5.0 models and building them, and everything worked correctly there already of course.

So I think this PR may be unnecessary other than to evaluate full TFLite export. The reason we don't use TFLite export in the CI is that it is much slower than all the other tests, roughly doubling the CI check time when we earlier looked at this option.

**Comment by YoniChechik** [comment]
I understand. I've also figured this download v5 part while debugging. In this case I'll close this PR.

**Comment by glenn-jocher** [comment]
One possible solution might be to load the trained model instead of the official model. The trained model is built from the --cfg *.yaml:

```bash
          # Export
          python models/yolo.py --cfg ${{ matrix.model }}.yaml  # build PyTorch model
          python models/tf.py --weights runs/train/exp/weights/last.pt  # build TensorFlow model
``

**Pull request closed without merging**
