### PR TITLE
Add segmentation and classification support for ClearML

### PR DESCRIPTION
**Pull request by thepycoder**
This PR adds ClearML support to `GenericLogger` which is used by the instance segmentation and classification training scripts, also solves issue #10710 

The feature list proposed in PR #8620 has been loosely followed, depending on what I had access to through the `GenericLogger` interface:
- [x] Current YOLO5 segmentation Tensorboard scalar metrics that can be visualized in a graph with ClearML -> so losses and segmentation mAPs (AP50:95, AP50, etc). The ones YOLO5 logs into "results.csv" file
- [x] opt.yaml, the config of the run
- [ ] If possible, per class mAP metrics (we get those printed in the console when running inference, but not during training sadly)
- [x] Inference images on the test set (the one we get with YOLO automatically in the experiment folder)
- [x] Train batch images (the one we get with YOLO automatically in the experiment folder)
- [ ] (this will be probably too much, but prediction masks on the test set in the COCO format)

The 2 features that are not yet included, aren't because I cannot access them via the existing logging interface. @glenn-jocher does it make sense to extend the `GenericLogger` for this?

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to ClearML logging support in Ultralytics YOLOv5.

### 📊 Key Changes
- Added logging of label images and plots to ClearML during pretraining.
- Improved how scalars (like loss, mAP) are logged to ClearML by introducing a new method `log_scalars`.
- Enabled ClearML logging at the end of training to log a summary of results, all generated plots, and to differentiate between the best and last models.
- `ClearmlLogger` initialization is now more robust, with exceptions caught for failed setup, and the `project_name` logic was updated to default to 'YOLOv5' when `opt.project` starts with 'runs/'.
- Integrated matplotlib with ClearML to report plots directly.
- Expanded the logging capabilities to include model weights, final summary metrics, and custom plots.
- Code cleanup and removal of redundant or commented-out code blocks.

### 🎯 Purpose & Impact
- **Enhanced Monitoring**: Users now have a more comprehensive and granular visualization of their models' training progress in ClearML.
- **Simplified Integration**: Simplifying the codebase for ClearML integration makes maintenance easier and enhances user experience.
- **Better Experiment Tracking**: Improved logging features allow for better tracking and comparison of different training runs, leading to more informed decision-making for model improvements.
- **Increased Compatibility**: The upgrade ensures compatibility between YOLOv5 and the latest features offered by ClearML, facilitating a seamless workflow for those relying on this combination for their ML experiments.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@thepycoder thanks for the PR! We'll take a look at this.

@AyushExel

**Comment by Robotatron** [comment]
@thepycoder I've tested it and everything works great, thank you!

ps . Could be off topic here but would you know if I have to configure clearML or edit your logger to also log the best model under "artefacts"? I am new to ClearML so could be a stupid question :)

**Comment by pktiuk** [comment]
Is there any chance for merging this?

**Comment by pktiuk** [comment]
Will this pr be closed because nobody had time to look at this?

**Comment by glenn-jocher** [comment]
@pktiuk thanks for your contribution! We apologize for the delay in reviewing your pull request. Our team is working hard to review and address all incoming requests. We appreciate your patience in this matter. Rest assured, your pull request will be reviewed and evaluated soon. Thanks again for your contribution to YOLOv5!

**Comment by pktiuk** [comment]
@glenn-jocher I hope so

**Comment by glenn-jocher** [comment]
@pktiuk we greatly appreciate your understanding and patience. Thank you for your valuable contribution to the YOLOv5 repository! Your PR will be reviewed soon.

**Pull request merged**
