### PR TITLE
Add OpenVINO metadata to export

### PR DESCRIPTION
**Pull request by xylieong**
Write .yaml file automatically when exporting model to openvino to be used during inference

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved metadata handling for OpenVINO exports and model class name loading in YOLOv5.

### 📊 Key Changes
- 🔧 Added `yaml` import for metadata handling.
- ⚙️ Modified `export_openvino` function to include the model parameter.
- ✨ OpenVINO export now saves a `meta.yaml` file with model stride and class names.
- 🔍 The `__init__` method in `models/common.py` no longer loads class names from `data.yaml` directly.
- 📦 New `_load_metadata` method in `MultiBackend` class to load metadata from `meta.yaml`.
- 🛠️ Refactored code related to warmup to ensure GPU model warmup.

### 🎯 Purpose & Impact
- 🔄 The changes allow for better integration and metadata management when exporting models to OpenVINO format, enabling users to retain important information about the model such as stride and class names.
- 🧠 This improves the ease of use and compatibility of YOLOv5 models with the OpenVINO toolkit, potentially broadening the user base involved in deploying YOLOv5 on different platforms.
- 🏃‍♂️ Warmup refactoring ensures that the models are correctly primed for inference, particularly on GPU devices, leading to more efficient operations post-deployment.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@xylieong this is a great idea! This should be added to DetectMultiBackend() also to load these during inference.

**Comment by xylieong** [comment]
@glenn-jocher Sure! Besides, I saw your commit, but would it be better that the yaml file name is based on the model name instead of 'metadata'? There might be possibility that different models exist in the same Path with different metadatas.

**Comment by glenn-jocher** [comment]
@xylieong I've updated your PR and made the idea extensible to any other directory format like SavedModel and TF.js. If any of them have a meta.yaml in their directory it can now be loaded to retrieve stride and class names.

**Comment by glenn-jocher** [comment]
@xylieong PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by glenn-jocher** [comment]
> @glenn-jocher Sure! Besides, I saw your commit, but would it be better that the yaml file name is based on the model name instead of 'metadata'? There might be possibility that different models exist in the same Path with different metadatas.

Just saw this. Yes this is a good point. I'll make a new PR with this update.

**Comment by glenn-jocher** [comment]
@xylieong resolved in #7952

**Comment by xylieong** [comment]
Great!

**Comment by glenn-jocher** [comment]
@xylieong thank you! We really appreciate your feedback and suggestions.

**Pull request merged**
