### PR TITLE
Fix BGR->RGB Bug in albumentations #8641

### LINKED ISSUE #8641: Albumentations-Pipeline is applied to BGR not to RGB
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

_No response_

### Bug

As written [here ](https://albumentations.ai/docs/getting_started/image_augmentation/) in step 3, Albumentations internally uses the RGB format and not the BGR format of opencv.  However, the data is currently passed internally as BGR:
https://github.com/ultralytics/yolov5/blob/92e47b85d952274480c8c5efa5900e686241a96b/utils/dataloaders.py#L626-L628
https://github.com/ultralytics/yolov5/blob/92e47b85d952274480c8c5efa5900e686241a96b/utils/dataloaders.py#L654
 Or am I missing something?

### Environment

YOLOv5 torch 1.11 (cuda 11.3) and 1.12 (cuda 11.6)

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by UnglvKitDe**
@glenn-jocher First idea. Easy, but maybe not the fastest one...

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved image augmentation compatibility for BGR image inputs.

### 📊 Key Changes
- Augmentation now converts images from BGR to RGB before applying transformations.
- After transformations, images are converted back from RGB to BGR.

### 🎯 Purpose & Impact
- **Purpose:** Ensures image augmentations are applied correctly when the input images are in BGR format, which is common in OpenCV.
- **Impact:** Users can now expect consistent augmentation results even if their images start in BGR format, leading to potentially more accurate models when training with images processed by OpenCV. This change also streamlines preprocessing steps for users working with BGR images.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@UnglvKitDe yes this is probably the simplest fix but not a very good one. I think we need to convert the LoadImagesAndLabels dataloader to be fully RGB. I'll merge this now as a temp fix though so I don't forget.

**Comment by UnglvKitDe** [comment]
@glenn-jocher I looked at it. Think it might be worth adding it right after the image loading and rebuilding the other methods. Because we don't really have any opencv operations in the data loader anymore except in augmentations. Good point!

**Comment by glenn-jocher** [comment]
Caused bug in #8724

**Comment by glenn-jocher** [comment]
> @glenn-jocher I looked at it. Think it might be worth adding it right after the image loading and rebuilding the other methods. Because we don't really have any opencv operations in the data loader anymore except in augmentations. Good point!

Second fix attempt PR #8747, can you please review?

**Pull request merged**
