### PR TITLE
W&B: Allow changed in config variable

### LINKED ISSUE #3583: error around wandb_logger when using custom trained weight file as initial weights
experienced in the latest repo version.

## error info
- runs fine
`python train.py --img 640 --batch 8 --epochs 250 --data config.yaml --weights yolov5l --name my_train`

- encounts error prior to training
`python train.py --img 640 --batch 8 --epochs 250 --data config.yaml --weights ./runs/train/my_train/weights/best.pt --name transfer_learning_train`

```
File "train.py", line 543, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 72, in train
    wandb_logger = WandbLogger(opt, save_dir.stem, run_id, data_dict)
  File "/home2/synthetic_seeds/yolov5/utils/wandb_logging/wandb_utils.py", line 121, in __init__
    self.wandb_run.config.opt = vars(opt)
  File "/home/dl-box/anaconda3/envs/yolo5/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 139, in __setitem__
    key, val = self._sanitize(key, val)
  File "/home/dl-box/anaconda3/envs/yolo5/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 231, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "opt" from {'cfg': '', 'hyp': {'box': 0.05, 'cls': 0.5, 'lr0': 0.01, 'lrf': 0.2, 'obj': 1, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'iou_t': 0.2, 'mixup': 0, 'scale': 0.5, 'shear': 0, 'cls_pw': 1, 'fliplr': 0.5, 'flipud': 0, 'mosaic': 1, 'obj_pw': 1, 'degrees': 0, 'anchor_t': 4, 'fl_gamma': 0, 'momentum': 0.937, 'translate': 0.1, 'perspective': 0, 'weight_decay': 0.0005, 'warmup_epochs': 3, 'warmup_bias_lr': 0.1, 'warmup_momentum': 0.8}, 'adam': False, 'data': 'config.yaml', 'name': 'my_train', 'quad': False, 'rect': False, 'bucket': '', 'device': '', 'entity': None, 'epochs': 250, 'evolve': False, 'nosave': False, 'notest': False, 'resume': False, 'project': 'runs/train', 'sync_bn': False, 'weights': 'yolov5l.pt', 'workers': 8, 'exist_ok': False, 'img_size': [640, 640], 'save_dir': 'runs/train/my_train', 'linear_lr': False, 'batch_size': 8, 'local_rank': -1, 'single_cls': False, 'world_size': 1, 'global_rank': -1, 'multi_scale': False, 'save_period': -1, 'cache_images': False, 'noautoanchor': False, 'bbox_interval': -1, 'image_weights': False, 'artifact_alias': 'latest', 'upload_dataset': False, 'label_smoothing': 0, 'total_batch_size': 8} to {'weights': './runs/train/my_train/weights/best.pt', 'cfg': '', 'data': 'config.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}, 'epochs': 250, 'batch_size': 8, 'img_size': [640, 640], 'rect': False, 'resume': False, 'nosave': False, 'notest': False, 'noautoanchor': False, 'evolve': False, 'bucket': '', 'cache_images': False, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'adam': False, 'sync_bn': False, 'local_rank': -1, 'workers': 8, 'project': 'runs/train', 'entity': None, 'name': 'transfer_learning_train', 'exist_ok': False, 'quad': False, 'linear_lr': False, 'label_smoothing': 0.0, 'upload_dataset': False, 'bbox_interval': -1, 'save_period': -1, 'artifact_alias': 'latest', 'world_size': 1, 'global_rank': -1, 'save_dir': 'runs/train/transfer_learning_train', 'total_batch_size': 8}
If you really want to do this, pass allow_val_change=True to config.update()

```

## temporary workaround

train.py
```
#run_id = torch.load(weights).get('wandb_id') if weights.endswith('.pt') and os.path.isfile(weights) else None
run_id = None
```

## Note
Durring writing this issue, I noticed I have used the same config file name (config.yaml), although the content of the yaml is different between trains. Don't know whether that is the cause of the problem, so will try after my current train settles.

### PR DESCRIPTION
**Pull request by AyushExel**
Fix for #3583 
This issue has been reported 3 times, so I figured we should relax this sanity check

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved flexibility in logging with Weights & Biases (W&B) 📈

### 📊 Key Changes
- Added `allow_val_change=True` to `wandb.init()` calls.
- Ensured W&B run initiation handles parameter changes gracefully.

### 🎯 Purpose & Impact
- **Purpose**: To address issues with resuming W&B runs where hyperparameters may change, potentially causing conflicts without this option.
- **Impact**: Users can now resume W&B training runs with modified hyperparameters without encountering errors, leading to a smoother experiment tracking and hyperparameter tuning experience. 🔄

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐!

**Comment by PeterSenyszyn** [comment]
@glenn-jocher this update did not fix the issue. I still get the same error after confirming the latest code changes.

**Comment by AyushExel** [comment]
@PeterSenyszyn can you share your W&B run link that is facing this problem ?
Also, some more info about the platform and environment will be useful for reproduction of this issue.

**Comment by Andreluizfc** [comment]
@PeterSenyszyn @AyushExel Same problem here. I am running in a VM with Tesla T4.

Here is the log.

```
(yolov5) rdxuser@vm-ia-dev:~/nexa/reps/yolov5$ python train.py --data data/nexa.yaml --weights runs/train/exp13/weights/best.pt --img 1280 --batch-size 2 --epochs 200
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v5.0-188-g239a11c torch 1.8.1+cu102 CUDA:0 (Tesla T4, 15109.75MB)

Namespace(adam=False, artifact_alias='latest', batch_size=2, bbox_interval=-1, bucket='', cache_images=False, cfg='', data='data/nexa.yaml', device='', entity=None, epochs=200, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[1280, 1280], label_smoothing=0.0, linear_lr=False, local_rank=-1, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/exp14', save_period=-1, single_cls=False, sync_bn=False, total_batch_size=2, upload_dataset=False, weights='runs/train/exp13/weights/best.pt', workers=8, world_size=1)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0
wandb: Currently logged in as: andreluizfc (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.10.32
wandb: Resuming run exp14
wandb:  View project at https://wandb.ai/andreluizfc/YOLOv5
wandb:  View run at https://wandb.ai/andreluizfc/YOLOv5/runs/1388jt3h
wandb: Run data is saved locally in /home/rdxuser/nexa/reps/yolov5/wandb/run-20210614_150241-1388jt3h
wandb: Run `wandb offline` to turn off syncing.

wandb: ERROR Attempted to change value of key "opt" from {'cfg': '', 'hyp': {'box': 0.05, 'cls': 0.5, 'lr0': 0.01, 'lrf': 0.2, 'obj': 1, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'iou_t': 0.2, 'mixup': 0, 'scale': 0.5, 'shear': 0, 'cls_pw': 1, 'fliplr': 0.5, 'flipud': 0, 'mosaic': 1, 'obj_pw': 1, 'degrees': 0, 'anchor_t': 4, 'fl_gamma': 0, 'momentum': 0.937, 'translate': 0.1, 'perspective': 0, 'weight_decay': 0.0005, 'warmup_epochs': 3, 'warmup_bias_lr': 0.1, 'warmup_momentum': 0.8}, 'adam': False, 'data': 'data/nexa.yaml', 'name': 'exp', 'quad': False, 'rect': False, 'bucket': '', 'device': '', 'entity': None, 'epochs': 300, 'evolve': False, 'nosave': False, 'notest': False, 'resume': False, 'project': 'runs/train', 'sync_bn': False, 'weights': 'weights/yolov5l6.pt', 'workers': 8, 'exist_ok': False, 'img_size': [1280, 1280], 'save_dir': 'runs/train/exp13', 'linear_lr': False, 'batch_size': 2, 'local_rank': -1, 'single_cls': False, 'world_size': 1, 'global_rank': -1, 'multi_scale': False, 'save_period': -1, 'cache_images': False, 'noautoanchor': False, 'bbox_interval': -1, 'image_weights': False, 'artifact_alias': 'latest', 'upload_dataset': False, 'label_smoothing': 0, 'total_batch_size': 2} to {'weights': 'runs/train/exp13/weights/best.pt', 'cfg': '', 'data': 'data/nexa.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}, 'epochs': 200, 'batch_size': 2, 'img_size': [1280, 1280], 'rect': False, 'resume': False, 'nosave': False, 'notest': False, 'noautoanchor': False, 'evolve': False, 'bucket': '', 'cache_images': False, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'adam': False, 'sync_bn': False, 'local_rank': -1, 'workers': 8, 'project': 'runs/train', 'entity': None, 'name': 'exp', 'exist_ok': False, 'quad': False, 'linear_lr': False, 'label_smoothing': 0.0, 'upload_dataset': False, 'bbox_interval': -1, 'save_period': -1, 'artifact_alias': 'latest', 'world_size': 1, 'global_rank': -1, 'save_dir': 'runs/train/exp14', 'total_batch_size': 2}
wandb: ERROR If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "train.py", line 542, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 73, in train
    wandb_logger = WandbLogger(opt, save_dir.stem, run_id, data_dict)
  File "/home/rdxuser/nexa/reps/yolov5/utils/wandb_logging/wandb_utils.py", line 126, in __init__
    self.wandb_run.config.opt = vars(opt)
  File "/anaconda/envs/yolov5/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 139, in __setitem__
    key, val = self._sanitize(key, val)
  File "/anaconda/envs/yolov5/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 231, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "opt" from {'cfg': '', 'hyp': {'box': 0.05, 'cls': 0.5, 'lr0': 0.01, 'lrf': 0.2, 'obj': 1, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'iou_t': 0.2, 'mixup': 0, 'scale': 0.5, 'shear': 0, 'cls_pw': 1, 'fliplr': 0.5, 'flipud': 0, 'mosaic': 1, 'obj_pw': 1, 'degrees': 0, 'anchor_t': 4, 'fl_gamma': 0, 'momentum': 0.937, 'translate': 0.1, 'perspective': 0, 'weight_decay': 0.0005, 'warmup_epochs': 3, 'warmup_bias_lr': 0.1, 'warmup_momentum': 0.8}, 'adam': False, 'data': 'data/nexa.yaml', 'name': 'exp', 'quad': False, 'rect': False, 'bucket': '', 'device': '', 'entity': None, 'epochs': 300, 'evolve': False, 'nosave': False, 'notest': False, 'resume': False, 'project': 'runs/train', 'sync_bn': False, 'weights': 'weights/yolov5l6.pt', 'workers': 8, 'exist_ok': False, 'img_size': [1280, 1280], 'save_dir': 'runs/train/exp13', 'linear_lr': False, 'batch_size': 2, 'local_rank': -1, 'single_cls': False, 'world_size': 1, 'global_rank': -1, 'multi_scale': False, 'save_period': -1, 'cache_images': False, 'noautoanchor': False, 'bbox_interval': -1, 'image_weights': False, 'artifact_alias': 'latest', 'upload_dataset': False, 'label_smoothing': 0, 'total_batch_size': 2} to {'weights': 'runs/train/exp13/weights/best.pt', 'cfg': '', 'data': 'data/nexa.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}, 'epochs': 200, 'batch_size': 2, 'img_size': [1280, 1280], 'rect': False, 'resume': False, 'nosave': False, 'notest': False, 'noautoanchor': False, 'evolve': False, 'bucket': '', 'cache_images': False, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'adam': False, 'sync_bn': False, 'local_rank': -1, 'workers': 8, 'project': 'runs/train', 'entity': None, 'name': 'exp', 'exist_ok': False, 'quad': False, 'linear_lr': False, 'label_smoothing': 0.0, 'upload_dataset': False, 'bbox_interval': -1, 'save_period': -1, 'artifact_alias': 'latest', 'world_size': 1, 'global_rank': -1, 'save_dir': 'runs/train/exp14', 'total_batch_size': 2}
If you really want to do this, pass allow_val_change=True to config.update()

wandb: Waiting for W&B process to finish, PID 32192
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb:
wandb: Find user logs for this run at: /home/rdxuser/nexa/reps/yolov5/wandb/run-20210614_150241-1388jt3h/logs/debug.log
wandb: Find internal logs for this run at: /home/rdxuser/nexa/reps/yolov5/wandb/run-20210614_150241-1388jt3h/logs/debug-internal.log
wandb: Run summary:
wandb:                 train/cls_loss 0.00141
wandb:           metrics/mAP_0.5:0.95 0.56229
wandb:                       _runtime 20646
wandb:                   val/cls_loss 0.00123
wandb:                   val/obj_loss 0.01563
wandb:                 metrics/recall 0.71416
wandb:                 train/box_loss 0.02048
wandb:                          x/lr2 0.00933
wandb:                 train/obj_loss 0.01421
wandb:                     _timestamp 1623672746
wandb:                   val/box_loss 0.0151
wandb:              metrics/precision 0.85158
wandb:                          _step 57
wandb:                          x/lr0 0.00933
wandb:                          x/lr1 0.00933
wandb:                metrics/mAP_0.5 0.79422
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb:
wandb: Synced exp14: https://wandb.ai/andreluizfc/YOLOv5/runs/1388jt3h
```

**Comment by Andreluizfc** [comment]
@PeterSenyszyn @AyushExel 

I just used the ``--resume`` flag and it worked. 

https://github.com/ultralytics/yolov5/issues/3583#issuecomment-860558687

**Comment by AyushExel** [comment]
@Andreluizfc yes `--resume` is used for resuming a crashed run. `--weights` is used for transfer learning, which means you'll need a fully trained and stripped model in order to use `--weights`

**Pull request merged**
