### PR TITLE
Add yolov5/ to sys.path() for *.py subdir exec

### LINKED ISSUE #2898: Use of tensorboard in yolo.py
## ❔Question
When I uncomment Tensorboard，the following error occurred

## Additional context
Run 'tensorboard --logdir=models/runs' to view tensorboard at http://localhost:6006/
Traceback (most recent call last):
  File "/Users/leo/Desktop/yolov5/models/yolo.py", line 279, in <module>
    tb_writer.add_graph(model.model, img)  # add model to tensorboard
  File "/Users/leo/.virtualenvs/yolov5_3/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 724, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "/Users/leo/.virtualenvs/yolov5_3/lib/python3.7/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 286, in graph
    trace = torch.jit.trace(model, args)
  File "/Users/leo/.virtualenvs/yolov5_3/lib/python3.7/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/Users/leo/.virtualenvs/yolov5_3/lib/python3.7/site-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
  File "/Users/leo/.virtualenvs/yolov5_3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/Users/leo/.virtualenvs/yolov5_3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/Users/leo/.virtualenvs/yolov5_3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Users/leo/.virtualenvs/yolov5_3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/Users/leo/.virtualenvs/yolov5_3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/Users/leo/Desktop/yolov5/models/common.py", line 210, in forward
    return torch.cat(x, self.d)
TypeError: cat() received an invalid combination of arguments - got (Tensor, int), but expected one of:
 * (tuple of Tensors tensors, name dim, *, Tensor out)
 * (tuple of Tensors tensors, int dim, *, Tensor out)

### PR DESCRIPTION
**Pull request by glenn-jocher**
Allows yolo.py and export.py execution from any directory.

Solves https://github.com/ultralytics/yolov5/issues/2898#issuecomment-827631411.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvement of sys.path handling and minor code cleanup in Ultralytics YOLOv5.

### 📊 Key Changes
- Replaced `sys.path.append('./')` with `sys.path.append(Path(__file__).parent.parent.absolute().__str__())` for more reliable module imports.
- Minor code formatting adjustment (removed trailing spaces).

### 🎯 Purpose & Impact
- 🛠 **Reliable Execution**: Utilizing `pathlib` for dynamic path resolution enhances compatibility across different operating systems and execution environments.
- 👨‍💻 **Developer Experience**: This update should prevent potential issues with the Python path in different setups, leading to smoother development and operation processes across various platforms.
- 🔗 **Stability**: These changes will make the codebase more robust and maintainable, ensuring that relative imports work more consistently for users and developers of the YOLOv5 project.

### CODE REVIEW

**Comment by pravastacaraka** [comment]
Hello @glenn-jocher, I'm still getting error when I run python yolo.py from `yolov5/models/`.

image

**Comment by glenn-jocher** [comment]
@pravastacaraka hmm interesting, it looks like you are on windows. The windows CI checks are passing here:
https://github.com/ultralytics/yolov5/runs/2449196728?check_suite_focus=true

The command used to test yolo.py that passes the above tests is here:
https://github.com/ultralytics/yolov5/blob/4200674a136a5589972f352790f76d3f37e98dd6/.github/workflows/ci-testing.yml#L78

So if you simply run your command from the yolov5/ directory everything should work fine:
```
python models/yolo.py
```

**Comment by pravastacaraka** [comment]
@glenn-jocher Yeah, I'm working on windows. And yes, when I run this command:

```bash
python models/yolo.py
```

This works fine. But I have only tried the ones you stated to allow yolo.py and export.py execution from any directory.

EDIT: And I tried it on colab too, running with the same command !python yolo.py and producing the same error.

**Comment by jaskiratsingh2000** [comment]
@pravastacaraka @glenn-jocher When you run this same on Linux distro it is showing the model error as stated above in the referenced issue.

**Pull request merged**
