### PR TITLE
Update FLOPs description.

### LINKED ISSUE #3413: FLOPS result In the README
## ❔Question
I find that in the table of the pretraind result has a column named FLOPS. However, as my understanding, for algorithm, FLOPS is meanless; the real deal should be FlOPs. I wonder the 17.0 of YOLOv5s in the table of FLOPS, is this actually "FLOPs" or there is other specific calculation?

### PR DESCRIPTION
**Pull request by chocosaj**
Just update the FLOPS to FLOPs to validate the results.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated terminology for computing model complexity from 'FLOPS' to 'FLOPs'.

### 📊 Key Changes
- Changed all instances of 'GFLOPS' to 'GFLOPs' for consistency in term usage.
- Updated documentation (README.md, tutorial.ipynb) with the correct abbreviation 'GFLOPs'.
- Altered comments and logger messages in code files (models/yolo.py, utils/torch_utils.py) to reflect the updated abbreviation.

### 🎯 Purpose & Impact
- Ensures consistent and accurate use of terms across the project's documentation and code, thereby increasing clarity for developers and practitioners.
- Prevents confusion by standardizing on the widely accepted abbreviation for floating-point operations per second (FLOPs).
- Minor change with no impact on functionality but improves the project's professionalism and attention to detail.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@chocosaj thanks for the PR! It looks like the FLOPS term is used in quite a few places throughout YOLOv5, so we should update all of them within this PR. If you're using PyCharm this should be easy with the Edit > Find > Replace in Files.

Screenshot 2021-06-02 at 17 33 09

**Comment by chocosaj** [comment]
OK, working on it.

**Comment by chocosaj** [comment]
All done.

**Comment by glenn-jocher** [comment]
@chocosaj thank you for your contributions to YOLOv5 🚀!

**Pull request merged**
