### PR TITLE
Fix `select_device()` for Multi-GPU

### LINKED ISSUE #6431: the GPU devices number problem
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Multi-GPU

### Bug

First thank you for your great work!
In the latest verson, when i make the opt parameter device="0", it also use all GPUs.
 When I check the function select_device, I found that the potision of  'os.environ['CUDA_VISIBLE_DEVICES'] = device' has an effect on the results. When I put it on the first line of the 'elif device' section, then it works, I dont know why ?

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
Possible fix for https://github.com/ultralytics/yolov5/issues/6431

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced CUDA device detection in YOLOv5's utility functions.

### 📊 Key Changes
- Implemented a safer version of `torch.cuda.device_count()` named `device_count()`.
- Replaced the direct call to `torch.cuda.device_count()` with the new `device_count()` in `datasets.py` and `torch_utils.py`.
- Adjusted the order of operations in `select_device()` to set `CUDA_VISIBLE_DEVICES` before asserting CUDA availability.

### 🎯 Purpose & Impact
- The purpose of these changes is to provide a more robust way of counting CUDA devices that avoids potential exceptions.
- The impact for users is an improvement in the reliability of YOLOv5 when it initializes CUDA devices, especially in systems with complex setup or permission issues.
- The new `device_count()` function should make the tool more resilient to errors, leading to smoother setup and training processes for users with compatible CUDA devices. 🖥️🚀

### CODE REVIEW

**Comment by Ethan-niu** [comment]
I does not work yet. 
I have made several tests, it is not only with the line "nd = len(os.getenv('CUDA_VISIBLE_DEVICES', '').split(','))" but also " assert torch.cuda.is_available()", 'os.environ['CUDA_VISIBLE_DEVICES'] = device' must be in front of "assert torch.cuda.is_available()"
 elif device:  # non-cpu device requested
        # os.environ['CUDA_VISIBLE_DEVICES'] = device  # 当放在下面的时候不起作用
        # nd = torch.cuda.device_count()  # number of CUDA devices
        nd = len(os.getenv('CUDA_VISIBLE_DEVICES', '').split(','))
        # assert torch.cuda.is_available(), 'CUDA is not available, use `--device cpu` or do not pass a --device'
        assert nd > int(max(device.split(','))), f'Invalid `--device {device}` request, valid devices are 0 - {nd - 1}'
        os.environ['CUDA_VISIBLE_DEVICES'] = device  # set environment variable (must be after asserts)
        assert torch.cuda.is_available(), 'CUDA is not available, use `--device cpu` or do not pass a --device'
        print(torch.cuda.device_count())

**Comment by glenn-jocher** [comment]
@Ethan-niu like this?

```python
    elif device:  # non-cpu device requested
        nd = len(os.getenv('CUDA_VISIBLE_DEVICES', '').replace(',',''))  # number of CUDA devices
        os.environ['CUDA_VISIBLE_DEVICES'] = device  # set environment variable
        assert torch.cuda.is_available(), 'CUDA is not available, use `--device cpu` or do not pass a --device'
        assert nd > int(max(device.split(','))), f'Invalid `--device {device}` request, valid devices are 0 - {nd - 1}'
```

**Comment by Ethan-niu** [comment]
This will be ok!
And the follow will also be ok!
```python
elif device:  # non-cpu device requested
        nd = len(os.getenv('CUDA_VISIBLE_DEVICES', '').replace(',',''))  # number of CUDA devices
        assert nd > int(max(device.split(','))), f'Invalid `--device {device}` request, valid devices are 0 - {nd - 1}'
        os.environ['CUDA_VISIBLE_DEVICES'] = device  # set environment variable
        assert torch.cuda.is_available(), 'CUDA is not available, use `--device cpu` or do not pass a --device'
```

The order of 'assert nd' and 'os.environ['CUDA_VISIBLE_DEVICES']' has no effect, but 'os.environ['CUDA_VISIBLE_DEVICES']'  must be in front of 'assert torch.cuda.is_available()'. The previous version is :
        os.environ['CUDA_VISIBLE_DEVICES'] = device  # set environment variable
        assert torch.cuda.is_available(), 'CUDA is not available, use `--device cpu` or do not pass a --device'

I dont know why the order can affect the result.

**Comment by glenn-jocher** [comment]
@Ethan-niu I've updated the PR, can you verify that it works now?

**Comment by Ethan-niu** [comment]
@glenn-jocherI Yeah, and if you know the reason later, please tell me , I am so curious ^_^

**Comment by glenn-jocher** [comment]
@Ethan-niu I verified that Multi-GPU device selection works correctly in v6.0 release, and is now broken. I tried reverting select_device() to it's original v6.0 configuration but this does not solve the problem so the problem seems to actually be somewhere else.

Some commit between v6.0 and now seems to have broken Multi-GPU.

**Comment by glenn-jocher** [comment]
5814 works correctly
5991 works correctly
6223 works correctly
6285 works correctly
6290 is broken

**Comment by glenn-jocher** [comment]
@Ethan-niu Multi-GPU is now resolved for DP and DDP. Issue seems to be that calls to torch.cuda.is_available() and torch.cuda.device_count() (recent PR added this in datasets.py) seem to break the YOLOv5 device selection. 

I've created a new safe device_count() function and this has fixed the problem, as well as placing torch.cuda.is_available() calls after CUDA_VISIBLE_DEVICES is set.

**Comment by glenn-jocher** [comment]
Verification command:
```bash
python -m torch.distributed.run --nproc_per_node 2 --master_port 1 train.py --device 3,6
```

Screenshot 2022-01-26 at 23 42 07
Screenshot 2022-01-26 at 23 42 09

**Comment by yangrisheng** [comment]
Great job.I can't use multi GPU to train the model serveral days ago.Now,I will try to use it.
Thank you!

**Pull request merged**
