### PR TITLE
Fix `detect.py --view-img` for non-ASCII paths

### LINKED ISSUE #7075: About real-time display of video files
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

@glenn-jocher 
I ran this instruction to detect video:

```shell
python detect.py --weights ./yolov5s.pt --source ./video/
```

I found that this command can only get the detected video files. I would like to ask, can I detect the video files and display the video files in real time?

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Zengyf-CVer**
@glenn-jocher 
I found a solution to the problem mentioned in https://github.com/ultralytics/yolov5/issues/7075, the reason is that my yolov5 project path includes Chinese, so `cv2.imshow(str(p), im0) `This line of code cannot display the window, resulting in the inability to display pictures and videos, I will fix this bug.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved OpenCV functions for better Chinese character handling in file paths.

### 📊 Key Changes
- Added a wrapper function around `cv2.imshow` to prevent recursion errors.
- Extended functionality to encode file paths for proper handling of Chinese characters within the `imshow` function.
- Redefined `cv2.imread`, `cv2.imwrite`, and `cv2.imshow` to utilize the new, improved functions supporting Chinese character file paths.

### 🎯 Purpose & Impact
- 🚀 **Purpose**: The main goal is to enhance compatibility with Chinese characters in file paths when using OpenCV functions, mitigating issues faced by users with non-Latin alphabets in their file system.
- 🌍 **Impact**: This change makes the YOLOv5 more accessible and user-friendly for a global audience, particularly assisting Chinese-speaking developers and users in running image processing tasks without encountering errors related to file path encoding.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Zengyf-CVer thanks for the PR! I think we should use the strategy I raised in https://github.com/ultralytics/yolov5/pull/7139#issuecomment-1078889636 for this

**Comment by glenn-jocher** [comment]
@Zengyf-CVer looks like unicode escape is faster than is_chinese, so makes sense just to always apply it rather than to check first:

```python
p = 'acbadsfasdfasdfadslfkhadsfhjlasdfhljj.jpg'

%timeit p.encode('unicode_escape')
462 ns ± 3.47 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
%timeit is_chinese(p)
1.15 µs ± 11.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

**Comment by glenn-jocher** [comment]
@Zengyf-CVer ok I've updated per my recommendation and replaced

```diff
-    cv2.imshow(p.encode('unicode_escape').decode(), im)
+    cv2.imshow(p.encode().decode('utf-8', 'ignore'), im)
```

Does this work for your use case? If not can you send me the image or string that is causing the problem?

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Still can't display properly, here is my video path and result:
```shell
# video path:
/home/zyf/文档/yolov5/video/202202241928.mp4
# run:
python detect.py --weights ./yolov5s.pt --source ./video/ --view-img
```
ksnip_20220325-195704

**Comment by glenn-jocher** [comment]
@Zengyf-CVer here are my `--view-img` results on MacOS. I renamed zidane.jpg as 文档.jpg. Not sure what to do.
```python
path.encode('unicode_escape').decode()
```
Screenshot 2022-03-25 at 13 06 48


```python
path.encode('').decode('utf-8', 'ignore')
```
Screenshot 2022-03-25 at 13 08 20

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
My result is also like this, the code will convert Chinese to a specific encoding, but at least the picture can be displayed normally.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
This works fine on Ubuntu：
```python
imshow_(path.encode('unicode_escape').decode(), im)
```

But this doesn't show up:
```python
imshow_(path.encode().decode('utf-8', 'ignore'), im)
```

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@Zengyf-CVer got it. I've reverted to `imshow_(path.encode().decode('utf-8', 'ignore'), im)`. Should be good to merge once CI completes.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
