### PR TITLE
detect.py ONNX inference feature

### PR DESCRIPTION
**Pull request by glenn-jocher**
This PR allows for direct ONNX inference using detect.py:

```
python detect.py --weights yolov5s.onnx
```

Credit: PR #3844 by @aditya-dl

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved support and handling for different model formats in the YOLOv5 detection script.

### 📊 Key Changes
- 🧠 Refactored model loading to support `.pt` and `.onnx` formats with clearer logic.
- ⚡ Enabled model type inference (classification or detection) based on the model file extension.
- 📏 Adjusted the default stride and class name setup to assign sensible defaults before model loading.
- ✨ Added conditional half-precision (FP16) support when using PyTorch models on compatible CUDA devices.
- 🕵️‍♂️ Included optional second-stage classification only for PyTorch models when enabled.
- 🧼 Cleaned up image preprocessing and reshaping logic.
- 🚀 Improved inference time accounting by structuring it around model format type.
- 🔍 Made post-processing (NMS, classification) conditional on model format.

### 🎯 Purpose & Impact
- 📈 Enhances the usability of the YOLOv5 detector by clearly distinguishing between PyTorch and ONNX model handling.
- 🔄 Streamlines code by creating distinct blocks for each model type, simplifying future maintenance.
- 💻 Ensures that users can easily run inference with either `.pt` or `.onnx` YOLOv5 models without extra configuration steps.
- 🤖 Aids in optimizing performance by correctly enabling FP16 inference on suitable hardware.
- 😎 Provides a flexible base for potentially integrating more model formats and inference optimizations in the future.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
Note that image size constraints apply, i.e. if you export a 640x640 ONNX model you must pass it only 640x640 images! This PR really needs merging with TFLite PR by @zldrobit in order to bring multi-model inference to detect.py including TFLite models etc using the 'auto' flag in the dataloader.

**Comment by glenn-jocher** [comment]
After forcing bus.jpg into a 640x640 square shape ONNX inference works correctly:

**Comment by glenn-jocher** [comment]
@aditya-dl could you take a look at this PR to see if this meets your ONNX inference needs?

**Comment by glenn-jocher** [comment]
@aditya-dl ONNX inference PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by aditya-dl** [comment]
@glenn-jocher I am happy to contribute towards this repo as it is my favourite. I will looking forward to contribute more and I will be happy to help in anything else.

**Comment by glenn-jocher** [comment]
@aditya-dl it turns out that ONNX models exported with --dynamic axes can be used directly with detect.py for all shapes as they are resized just like the pytorch models.

ONNX inference seems to be about 30% faster on CPU also than PyTorch inference.

**Comment by glenn-jocher** [comment]
@batrlatom interesting competition development: this PR allows for ONNX exported models to run directly with detect.py, and these ONNX models typically run about 30% faster on CPU than their PyTorch counterparts.

**Comment by aditya-dl** [comment]
@glenn-jocher that's great to hear. We could optimise ONNX models further if possible and gain more speed.

**Comment by glenn-jocher** [comment]
@aditya-dl that would great. Do you know if FP16 quantization is possible with ONNX on CPU? The exported models are currently FP32.

Update here: I tried to profile both in Colab but there it seems the ONNX models are slower, so it seems to really depend on the hardware. I saw faster ONNX speeds earlier on my local iMac.

```python
!python export.py --include onnx --dynamic --simplify
!python detect.py --weights yolov5s.pt --device cpu
!python detect.py --weights yolov5s.onnx --device cpu

detect: weights=['yolov5s.pt'], source=data/images, imgsz=640, conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
YOLOv5 🚀 v5.0-313-g6e4358f torch 1.9.0+cu102 CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
image 1/2 /content/yolov5/data/images/bus.jpg: 640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.267s)
image 2/2 /content/yolov5/data/images/zidane.jpg: 384x640 2 persons, 2 ties, Done. (0.212s)
Results saved to runs/detect/exp9
Done. (0.560s)

detect: weights=['yolov5s.onnx'], source=data/images, imgsz=640, conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
YOLOv5 🚀 v5.0-313-g6e4358f torch 1.9.0+cu102 CPU

image 1/2 /content/yolov5/data/images/bus.jpg: 640x512 4 class0s, 1 class5, Done. (0.413s)
image 2/2 /content/yolov5/data/images/zidane.jpg: 384x640 2 class0s, 2 class27s, Done. (0.290s)
Results saved to runs/detect/exp10
Done. (0.786s)
```

**Comment by glenn-jocher** [comment]
@aditya-dl local iMac profile results show ONNX about twice as fast.

```python
(venv) (base) glennjocher@Glenns-iMac yolov5 % python detect.py --weights yolov5s.pt --device cpu
detect: weights=['yolov5s.pt'], source=data/images, imgsz=640, conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
YOLOv5 🚀 v5.0-313-g6e4358f torch 1.9.0 CPU

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
image 1/2 /Users/glennjocher/PycharmProjects/yolov5/data/images/bus.jpg: 640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.325s)
image 2/2 /Users/glennjocher/PycharmProjects/yolov5/data/images/zidane.jpg: 384x640 2 persons, 2 ties, Done. (0.323s)
Results saved to runs/detect/exp2
Done. (0.745s)


(venv) (base) glennjocher@Glenns-iMac yolov5 % python detect.py --weights yolov5s.onnx --device cpu
detect: weights=['yolov5s.onnx'], source=data/images, imgsz=640, conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False
YOLOv5 🚀 v5.0-313-g6e4358f torch 1.9.0 CPU

image 1/2 /Users/glennjocher/PycharmProjects/yolov5/data/images/bus.jpg: 640x512 4 class0s, 1 class5, Done. (0.187s)
image 2/2 /Users/glennjocher/PycharmProjects/yolov5/data/images/zidane.jpg: 384x640 2 class0s, 2 class27s, Done. (0.132s)
Results saved to runs/detect/exp3
Done. (0.384s)
```

**Comment by aditya-dl** [comment]
Maybe ONNX implementations differ for hardware as you mentioned. We would need to test more on which hardware it performs better. 

Also, there is a way using onnxmltools to convert the models to float16, however, I have never tried it. I will look into it to see if that works.

**Comment by aditya-dl** [comment]
@glenn-jocher onnxruntime also supports GPU, did you get a chance to profile those results?

**Comment by glenn-jocher** [comment]
@aditya-dl no I don't know how to do that. detect.py will use CPU backend now for all ONNX inference even if CUDA is available. Perhaps you could submit a PR to fix that?

**Comment by aditya-dl** [comment]
@glenn-jocher We can replace the package that is installed, i.e., instead of onnxruntime we install onnxruntime-gpu. However, I will test this out and let you know.

**Comment by batrlatom** [comment]
> @batrlatom interesting competition development: this PR allows for ONNX exported models to run directly with detect.py, and these ONNX models typically run about 30% faster on CPU than their PyTorch counterparts.

@glenn-jocher Thanks for letting me know, this is great feature!

**Comment by aditya-dl** [comment]
@glenn-jocher I tested the package and the model. Replacing onnxruntime with onnxruntime-gpu will make the model run on the GPU.

**Comment by aditya-dl** [comment]
@glenn-jocher so the onnxmltools method doesn't work to convert ONNX to float16. Plus, I didn't find any information that ONNX supports float16 on CPU.

**Comment by glenn-jocher** [comment]
@aditya-dl got it, thanks!

**Comment by henbucuoshanghai** [comment]
my onnx is slower 50% than the pt ???  yolo5s  on 1080 GPU   ,why?

**Comment by glenn-jocher** [comment]
@henbucuoshanghai I'm not sure what speed to expect or if ONNX inference even runs on GPU.

In general CPU inference runs at similar speed between torch and onnx.

**Pull request merged**
