### PR TITLE
Improved FLOPS computation

### PR DESCRIPTION
**Pull request by glenn-jocher**
This PR improves FLOPS computation, and allows passing an `img_size` argument for the first time (previous FLOPS computations were fixed at 640, 640 img-size.

To view model FLOPS, `pip install thop` and then run any normal command:
Screenshot 2020-11-14 at 14 25 24

Or call the model.info() method directly with an optional `img_size` argument:
```python
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

model.info()
model.info(img_size=320)
model.info(img_size=[320, 640])

# OUTPUT
# Model Summary: 232 layers, 7459581 parameters, 0 gradients, 17.5 GFLOPS
# Model Summary: 232 layers, 7459581 parameters, 0 gradients, 4.4 GFLOPS
# Model Summary: 232 layers, 7459581 parameters, 0 gradients, 8.7 GFLOPS
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated YOLOv5 model and utility functions to provide more detailed information including FLOPS based on varying image sizes.

### 📊 Key Changes
- The `info` method in `models/yolo.py` now takes an additional `img_size` argument.
- The `model_info` function in `utils/torch_utils.py` has been updated to:
    - Accept `img_size` as an argument, which can be an integer or a list.
    - Use `img_size` to calculate FLOPS correctly for different input image dimensions.
    - Compute FLOPS based on provided stride and image dimensions for greater accuracy.

### 🎯 Purpose & Impact
- **Purpose**: To offer users a more accurate calculation of FLOPS that reflects the model's complexity based on different input resolutions, rather than a fixed size.
- **Impact**: Users now can get precise model information pertinent to their specific use case, leading to better understanding of the model's computational demand for different image sizes. This could be particularly useful for optimizing performance or ensuring compatibility with hardware constraints. 🚀💡

### CODE REVIEW

**Comment by glenn-jocher** [comment]
PR is complete. Note thop package is incompatible with Google Colab, mental note to raise an issue there.

**Comment by glenn-jocher** [comment]
Google Colab - thop issue raised at https://github.com/Lyken17/pytorch-OpCounter/issues/113

**Comment by klyjm** [comment]
> Google Colab - thop issue raised at [Lyken17/pytorch-OpCounter#113](https://github.com/Lyken17/pytorch-OpCounter/issues/113)

When trying to compute the FLOPs, I have meet the same error ```RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _thnn_conv2d_forward``` in my own device. And I use TITAN V, python 3.8, pytorch 1.7, cudatoolkit 10.2. Maybe it is because of the environment?

**Comment by glenn-jocher** [comment]
@klyjm it may be possible that this is a CUDA issue and not a colab issue. Apparently initializing the model on CPU as we do and then trying to get a FLOPS count is causing it.

> `Expected object of device type cuda but got device type cpu for argument #1 `
> 
> Did you turn on GPU options in Colab? If you use GPU, then the input data should also be a GPU tensor.
> 
> _Originally posted by @Lyken17 in https://github.com/Lyken17/pytorch-OpCounter/issues/113#issuecomment-729086837_

**Pull request merged**
