### PR TITLE
save_txt() method added

### PR DESCRIPTION
**Pull request by SarperYurttas**
This function imitates exactly 'detect.py --save-txt' behavior. Reference issue: #6382

However, a problem occurred when using with save() method, therefore I added save_imgs parameter. 
Screenshot 2022-01-27 144430

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced image results processing with added text output and refined saving mechanisms.

### 📊 Key Changes
- Introduced `save_txt` flag for textual output of predictions.
- Revision of file and directory handling for saving cropped images and annotations.
- `save_dir` is now an instance variable, improving directory management.
- Text files for labels are now saved with image index included in their names.
- Simplified the file saving process without needing to increment path names unnecessarily.

### 🎯 Purpose & Impact
- 👩‍💻 Developers can more easily integrate YOLOv5 outputs with other systems due to the added text output feature.
- 📁 Users gain more organized and predictable file output, simplifying post-processing tasks.
- 🖼️ Enhanced saved images nomenclature and structure improve clarity, especially when processing multiple images or batches.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@SarperYurttas this looks good! The only issue seems to be that labels and images will get saved to different directories, i.e. exp7 and exp8 as in your example. I suppose we should only increment if a save_dir does not already exist for the results object.

**Comment by SarperYurttas** [comment]
I made some changes. I think old behavior didn't work well, I mean if you called the save method more than once it was creating different paths for the same object as you can see. I fixed that issue as well
old_save_method
new_save_method

**Comment by glenn-jocher** [comment]
@SarperYurttas thanks for the updates!

We want to use the single for loop that's already established here and which contains all the info we need and simply pass it flags for what actions to take, i.e. save_txt=True, otherwise there is too much duplication of loops and code.
https://github.com/ultralytics/yolov5/blob/c3e599cfda112455d69da0fea64faadfaeaedcf2/models/common.py#L571-L590

**Comment by SarperYurttas** [comment]
@glenn-jocher at the first, "display" and "save txt" seemed unrelated to me therefore I left them apart. If you say so, I'll change that the way you want

**Comment by glenn-jocher** [comment]
@SarperYurttas hmm maybe the `display` function needs renaming to indicate it handles results processing per image, like `loop` or `process`

**Comment by SarperYurttas** [comment]
Hi @glenn-jocher, I'm wondering, why are we iterate predictions reversed direction?
https://github.com/ultralytics/yolov5/blob/c3e599cfda112455d69da0fea64faadfaeaedcf2/models/common.py#L579
If I change it like this, would anything be affected? I tried the enumerated version and saw no problem, I'm asking to be sure.
```python
for j, (*box, conf, cls) in enumerate(pred):
```

**Comment by glenn-jocher** [comment]
@SarperYurttas reversed() is in place because NMS sorts results from max confidence to min confidence. We want to plot min conf first so the highest confidence results are on the top (plotted last).

**Comment by SarperYurttas** [comment]
@glenn-jocher Can you check my last update?

**Pull request closed without merging**
