### PR TITLE
Fix cutout bug

### PR DESCRIPTION
**Pull request by Oswells**
Signed-off-by: Junjie Zhang <46258221+Oswells@users.noreply.github.com>

When I use cutout, I find that even if the object is completely covered, its gt_label is still retained on the image.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refinement of cutout augmentation in data preprocessing to enhance object detection.

### 📊 Key Changes
- Imported `xywhn2xyxy` function within `augmentations.py`.
- Improved the `cutout` function by ensuring it considers the IOA (Intersection over Area) of bounding boxes in the image coordinate space.

### 🎯 Purpose & Impact
- The purpose of these changes is to increase the accuracy of the `cutout` data augmentation technique used during training.
- By converting labels to the correct coordinate format before calculating IOA, it ensures that the object detection model is trained on better quality data, potentially leading to improved model performance.
- Users can expect their models to handle partial occlusions in a more robust way, which can be particularly beneficial for real-world applications where objects are often partially obscured.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Oswells thanks for the PR! It looks like you are saying that the current box inputs are in the wrong format. Are you sure this is the case?

**Comment by Oswells** [comment]
I use this code to check and it works well on yolov5:v6.1, but it may not be compatible with yolov5: v6.2. When I test it on yolov5:v6.2, I use v6.1's plot_images.
```python
from utils.datasets import create_dataloader
from utils.general import colorstr,init_seeds
from utils.plots import plot_images
import yaml 

init_seeds(429)
hyp='data/hyps/hyp.scratch-low.yaml'
with open(hyp, errors='ignore') as f:
            hyp = yaml.safe_load(f)
dataloader, dataset = create_dataloader(  "test.txt",
                                            480,
                                            22 // 2,
                                            32,
                                            False,
                                            hyp=hyp,
                                            augment=True,
                                            cache="ram",
                                            rect=False,
                                            rank=-1,
                                            workers=4,
                                            image_weights=False,
                                            quad=False,
                                            prefix=colorstr('train: '),
                                            shuffle=False)
for imgs, targets, paths, _ in dataloader:
    plot_images(imgs,targets)
```
before：
QQ图片20220918112735

fixed：
QQ图片20220918112735

**Comment by glenn-jocher** [comment]
@Oswells I reviewed. You are absolutely right, the labels are in xywhn so the IoA computation is flawed.

Your fix looks good!

**Comment by glenn-jocher** [comment]
@Oswells PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
