### PR TITLE
Add Ultralytics HUB to README

### PR DESCRIPTION
**Pull request by glenn-jocher**
@pderrenger @kalenmike @AlanDimmer @AyushExel new Ultralytics HUB section in YOLOv5 README.

Signed-off-by: Glenn Jocher <glenn.jocher@ultralytics.com>

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved integration visuals and streamlined README documentation.

### 📊 Key Changes
- Updated the README files in both English and Chinese versions to include a new "Integrations" section with a more visually appealing and informative banner.
- Streamlined "Quick Start Examples" in the English README, combining sections for conciseness.
- Replaced integration partner images with a single, comprehensive integration loop image.
- Added a new "Ultralytics HUB" section with an illustrative banner.
- Removed outdated images and links, replacing them with updated material that improves user engagement.

### 🎯 Purpose & Impact
- Enhance the visual appeal of the Ultralytics integration sections, making it more engaging and informative for users.
- Simplify the README structure to make it easier for new users to get started with YOLOv5.
- Promote the Ultralytics HUB more prominently.
- Increase awareness of helpful integrations and tools among YOLOv5 users, potentially improving their workflows and project outcomes.🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
## <div align="center">Ultralytics HUB</div>

[Ultralytics HUB](https://ultralytics.com/hub) is our ⭐ **NEW** no-code solution to visualize datasets, train YOLOv5 🚀 models, and deploy to the real world in a seamless experience. Get started for **Free** now!

<a align="center" href="https://ultralytics.com/hub" target="_blank">
</a>

**Comment by kalenmike** [comment]
@glenn-jocher So we are not going to show the steps in the YOLOv5 readme?

**Comment by glenn-jocher** [comment]
> @glenn-jocher So we are not going to show the steps in the YOLOv5 readme?

Yes we need the updated banner from @AlanDimmer. We want the same exact graphics here and on signup page so users know they've arrived at the right place when they go there.

**Comment by glenn-jocher** [comment]
@kalenmike @AlanDimmer @pderrenger @AyushExel I'm merging this PR using current HUB banner just to get this into master faster. Once we settle on a new banner it's easy for me to update.

**Pull request merged**
