### PR TITLE
[x]W&B: Don't resume transfer learning runs

### PR DESCRIPTION
**Pull request by AyushExel**
Discussion here -> https://github.com/ultralytics/yolov5/issues/3583
wandb used to complain if users started transfer learning from partially trained models. This acted as a sanity check but we've seen this issue being raised multiple times. So, here's a fix that allows users to use checkpoints for transfer learning.

@glenn-jocher I don't think we should allow this. We can just point users to this if they really insist on using partially trained models to transfer learning

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved handling of run IDs and configuration options in Weights & Biases (wandb) integration.

### 📊 Key Changes
- Introduced an adjustment in `train.py` to ensure that a fresh Weights & Biases (wandb) run ID is created when transfer learning, rather than resuming from an existing run.
- Added `--entity` command-line argument to specify the Weights & Biases (wandb) entity in the `log_dataset.py` script.
- Streamlined the configuration update process within the `wandb_utils.py` script to allow value changes in the wandb run configuration.

### 🎯 Purpose & Impact
- The modifications in `train.py` ensure clarity in experiment tracking by preventing unintentional continuation of a previous run when starting transfer learning, leading to more accurate experiment tracking and easier understanding of each run's provenance.
- The new `--entity` argument in `log_dataset.py` gives users the ability to define the Weights & Biases entity, making it easier to organize projects and control access within teams or organizations.
- Changes to `wandb_utils.py` offer more flexible configuration management during run initialization, allowing for updates to run parameters even after they've been initially set, which can accommodate adjustments and corrections as needed.

Overall, these changes enhance the user experience with Weights & Biases by providing better control and clearer experiment tracking, benefiting both individual users and teams working on machine learning projects. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel thanks for your patience! Is this PR ready to merge?

**Comment by AyushExel** [comment]
@glenn-jocher Yes this is ready. But do you think we should allow this? Transfer learning from checkpoints isn't really recommended right?

**Comment by glenn-jocher** [comment]
@AyushExel well right now if a checkpoint with optimizer is loaded the only option should be to --resume training it to completion. If someone really wants to transfer learn from a checkpoint they can manually run strip_optimizer() on it first and then follow the default workflows.

**Comment by AyushExel** [comment]
@glenn-jocher  Okay, then this should be ready to get merged. I've merged master into this and added a minor bug fix in upload_dataset.py script.

**Comment by glenn-jocher** [comment]
@AyushExel PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
