### PR TITLE
Add force_reload=True when loading model using torch hub

### PR DESCRIPTION
**Pull request by developer0hye**
Signed-off-by: Yonghye Kwon <developer.0hye@gmail.com>

It is related to #6948.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced model reloading in YOLOv5 tutorial notebook.

### 📊 Key Changes
- The tutorial Jupyter notebook now includes a `force_reload` parameter when loading the YOLOv5 model with `torch.hub.load`.

### 🎯 Purpose & Impact
- **Purpose:** To ensure that the latest model is always downloaded and loaded, even if a cached version exists.
- **Impact:** Users will always run inference with the most updated version of YOLOv5, which is especially helpful for newcomers experimenting with the tutorial notebook or for those who need to test recent changes. This minor update promotes best practices in model loading. 🔄🆕

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@developer0hye we've left this off the notebook since notebook environments won't have existing caches, so they'll download new caches by default the first time this cell block is run.

**Comment by developer0hye** [comment]
@glenn-jocher 

Thanks for your feedback!

I faced a problem when I programmed code by referencing this colab code. So I made a PR.

Do you think that it is unnecessary?

**Comment by glenn-jocher** [comment]
@developer0hye ah ok, sure let's do it then.

**Comment by glenn-jocher** [comment]
@developer0hye PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
