### PR TITLE
Upgrade onnxsim to v0.4.1

### PR DESCRIPTION
**Pull request by daquexian**
I'm the author of onnx-simplifier. Recently I published onnxsim v0.4.1. In the latest version, dynamic input shapes are natively supported. Extra flags like `dynamic_input_shapes` and `input_shapes` are not needed anymore.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced ONNX export functionality and requirements adjustment for the YOLOv5 model.

### 📊 Key Changes
- Updated the ONNX simplification process in `export.py`, removing the need to specify dynamic input shapes directly.
- Modified conditional requirement to install either `onnxruntime-gpu` or `onnxruntime` based on CUDA availability for ONNX model simplification.
- Changed assertion in `export.py` to clarify that the optimization process requires the CPU device.
- Bumped minimum version requirement for `onnx-simplifier` in `requirements.txt` to `>=0.4.1`.

### 🎯 Purpose & Impact
- 🚀 Simplifies the ONNX export process, potentially leading to fewer user errors and smoother integration for those using ONNX models.
- 🌐 Allows for automatic selection of the appropriate ONNX runtime depending on the user's environment, potentially improving performance.
- 🛠️ Clarifies the need to use a CPU for model optimization to prevent user confusion and ensure compatibility.
- 📈 Ensures users have the necessary software versions for seamless functionality and compatibility with the improved export process.

These changes aim to streamline the process for users exporting YOLOv5 models to ONNX format, which may improve user experience and broaden the deployment possibilities of YOLOv5 in different environments and platforms.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@daquexian I get a failure in Colab when testing this PR. Something seems off about the `onnxruntime` installation:

Screen Shot 2022-07-19 at 6 32 25 PM

**Comment by glenn-jocher** [comment]
@daquexian I added onnxruntime install prior to the new onnxsim 0.4.1 install and this appears to resolve the issue. Not sure what the problem was.
Screen Shot 2022-07-19 at 6 51 05 PM

**Comment by glenn-jocher** [comment]
@daquexian PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by daquexian** [comment]
@glenn-jocher Thanks for your work!

**Comment by glenn-jocher** [comment]
@daquexian you're welcome! It's a team effort and we're grateful for all the support from the YOLO community and the Ultralytics team. If you have any more questions or suggestions, feel free to reach out anytime.

**Pull request merged**
