### PR TITLE
Add support for `*.pfm` images 

### LINKED ISSUE #9222: training with .pfm extension
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

how to train yolov5 with pfm files?

### Additional

_No response_

### PR DESCRIPTION
**Pull request by spacewalk01**
Solved the following issue:
https://github.com/ultralytics/yolov5/issues/9222#issue-1355398439

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Expanded image format support in YOLOv5 data loaders.

### 📊 Key Changes
- Added support for `.pfm` image format files.

### 🎯 Purpose & Impact
- **Enhanced Flexibility**: Users can now use `.pfm` (Portable Float Map) files for input, which is beneficial for depth maps or HDR images.
- **Broader Applicability**: The YOLOv5 model can be trained on a more diverse set of image data, potentially improving its utility in fields that use this format, like computer vision research or image processing.

### CODE REVIEW

**Comment by spacewalk01** [comment]
Tested 'pfm' extension with opencv imread:
image

**Comment by glenn-jocher** [comment]
@spacewalk01 thanks for the PR! Have you been able to train correctly with *.pfm images on this branch?

**Comment by glenn-jocher** [comment]
@spacewalk01 PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by spacewalk01** [comment]
Oh you merged, I was trying to test training model with pfm images. I will test it and fix if there is any problem.

**Comment by Yousef-Alhattab** [comment]
image

I could not train?? 

**AssertionError: train: No labels found in D:\rty\yolov5\datasets\coco128\labels\train2017.cache, can not start training. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data**

the labels are there when I change the images extension, it works well

I used [MiDaS](https://github.com/isl-org/MiDaS) to get the depth.
please help?
thanks a lot

**Comment by glenn-jocher** [comment]
@urbansound8K it seems that the issue might be related to the labels for the pfm images. We recommend verifying the label files and ensuring they are correctly formatted and in the expected directory. 📝 You can find guidelines for training custom data in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/tutorials/train_custom_data. Let us know if you need further assistance.

**Pull request merged**
