### PR TITLE
VisDrone2019-DET Dataset Auto-Download

### LINKED ISSUE #2840: wandb: Network error (ReadTimeout), entering retry loop. See wandb\debug-internal.log for full traceback.
- **Current repo**: yolov5-5.0 release version
 - **Common dataset**: VisDrone.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments

## 🐛 Bug
I try to use your rep to train yolov4's NET because yolov4(https://github.com/WongKinYiu/PyTorch_YOLOv4)'s code is outdate and do not maintain, it has many bugs.
 when I train my own yolov4-tiny.yaml, it comes this bug, I think this bug is because my network can not  connect to wandb's server? before today, I can train normally, and a few minute ago, I try many times to `python train.py `,but I still can not begin my train code.

## To Reproduce (REQUIRED)
 
`python train.py `

Output:
```
YOLOv5  2021-4-15 torch 1.7.1 CUDA:0 (GRID V100D-32Q, 32638.0MB)

Namespace(adam=False, artifact_alias='latest', batch_size=64, bbox_interval=-1, bucket='', cache_images=False, cfg='models/yolov4-tiny.yaml', data='datai/Visdrone.yaml', device='', entity=None, epochs=300, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[640, 640], label_smoothing=0.0, linear_lr=False, local_rank=-1, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs\\train\\exp8', save_period=-1, single_cls=False, sync_bn=False, total_batch_size=64, upload_dataset=False, weights='', workers=8, world_size=1)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0
wandb: Currently logged in as: zigar (use `wandb login --relogin` to force relogin)
wandb: Network error (ReadTimeout), entering retry loop. See wandb\debug-internal.log for full traceback.
```

## Environment

 - OS: [e.g. WIndows 10]
 - GPU [e.g. GRID V100D-32Q, 32638.0MB]

### PR DESCRIPTION
**Pull request by glenn-jocher**
This PR adds VisDrone2019-DET dataset https://github.com/VisDrone/VisDrone-Dataset to the YOLOv5 autodownload dataset list, and includes significant contributions from @Zigars.

- [x] [COCO](https://cocodataset.org/#home)
- [x] [COCO128](https://www.kaggle.com/ultralytics/coco128)
- [x] [VOC](http://host.robots.ox.ac.uk/pascal/VOC/)
- [x] [Argoverse-HD](http://www.cs.cmu.edu/~mengtial/proj/streaming/)
- [x] [VisDrone2019-DET](https://github.com/VisDrone/VisDrone-Dataset)
- [x] [GlobalWheat-2020](http://www.global-wheat.com/)
- [ ] [KITTI](https://www.kaggle.com/twaldo/kitti-object-detection)
- [ ] [SKU110](https://github.com/eg4000/SKU110K_CVPR19) (grocery store items)
- [ ] [CityScapes](https://www.cityscapes-dataset.com/)
- [ ] [Objects365](https://www.objects365.org/overview.html)
- [ ] [OpenImages](https://storage.googleapis.com/openimages/web/index.html)

```yaml
# VisDrone2019-DET dataset https://github.com/VisDrone/VisDrone-Dataset
# Train command: python train.py --data visdrone.yaml
# Default dataset location is next to YOLOv5:
#   /parent_folder
#     /VisDrone
#     /yolov5
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated dataset comments and streamlined VOC dataset preparation script in the YOLOv5 repo.

### 📊 Key Changes
- Modified comments to specify the default dataset location as "next to YOLOv5" for clarity.
- Added a new YAML file for the VisDrone2019-DET dataset, with support for auto-downloading and label conversion.
- Simplified and corrected dataset preparation script in `get_voc.sh`, including the handling of directories and image/label copying.
- Improved the `general.py` script with multi-threaded download support and a more graceful dataset check.

### 🎯 Purpose & Impact
- 🎨 Improves readability of dataset documentation.
- 💡 Offers better dataset management by supporting auto-download and processing for VisDrone, enhancing usability for those working with drone imagery.
- ✅ Enhances the setup process for the VOC dataset, reducing errors and improving efficiency.
- 🚀 Provides a faster way to download datasets with multi-threading, potentially speeding up dataset preparation times.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
## train_batch0.jpg
train_batch0

## train_batch1.jpg
train_batch1

## train_batch2.jpg
train_batch2

**Comment by glenn-jocher** [comment]
@Zigars I think this PR is ready to merge. If you submit your own PR against the visdrone branch then you should be counted as **a co-author on this PR**. You can do that by going to this link and clicking the edit icon below, make any change, i.e. update a comment however you want, and then click 'submit PR'.

https://github.com/ultralytics/yolov5/blob/visdrone/data/visdrone.yaml

Screenshot 2021-04-22 at 01 27 24

**Comment by Zigars** [comment]
@glenn-jocher Thank you so much! I also think this PR is ready to merge. I saw your code, it's pretty concise than mine! I'm glad to be a contributor for yolov5. And you are a great open source community contributor!

**Comment by Zigars** [comment]
@glenn-jocher  Hello, I saw your 5.0 release have the transformer block, I want to know the performance of transformer in yolov5, I saw many transformer paper in cvpr2021, but I still not familiar with transformer, will next version of YOLO would be transformer architecture? I'm looking forward to your reply!

**Comment by glenn-jocher** [comment]
@Zigars PR is merged, thank you for your contributions!

**Pull request merged**
