### PR TITLE
Default FP16 TensorRT export

### LINKED ISSUE #6777: Why is the TensorRT input binding set to FP16 for FP16 engines by default?
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

_No response_

### Bug

Right now, when exporting a model to TensorRT using `export.py` with the `--half` argument, the input binding is set to datatype "half" while the output is set to datatype "float":

```
TensorRT: Network Description:
TensorRT:	input "images" with shape (1, 3, 640, 640) and dtype DataType.HALF
TensorRT:	output "output" with shape (1, 25200, 6) and dtype DataType.FLOAT
```

However, this means that whenever the resulting engine is used, its inputs also need to be converted to FP16, as can be seen in `detect.py`:

https://github.com/ultralytics/yolov5/blob/cea994b3f62a55106c3b1404f36e8aa780f324e0/detect.py#L118

Now I was wondering: is this intentional? TensorRT can handle an input in FP32 without problem even if the remaining engine is in half precision. However, having TensorRT handle the conversion means less overhead for the developer, while most likely also being faster as the conversion can be handled by the GPU instead of CPU. The datatype of the input binding when creating a new engine can be easily changed with a single line of code:

`network.get_input(0).dtype = trt.DataType.FLOAT`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by DavidBaldsiefen**
Assert that the `--half` flag fits the precision of the TensorRT engine in `val.py` and `detect.py`.

In addition, make the default TensorRT export use FP16 precision (if available), and set input precision according to `--half` flag

EDIT: Adding justification for update. No mAP penalty and speed improvements:

YOLOv5 🚀 v6.1-13-g601dbb8 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)

```python
!pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com  # install

!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0  # export
%mv yolov5s.engine yolov5s_fp32.engine
!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0 --half  # export
%mv yolov5s.engine yolov5s_fp16.engine

!python val.py --weights yolov5s.pt --data coco.yaml --img 640 --iou 0.65 --device 0 --batch 1
!python val.py --weights yolov5s.pt --data coco.yaml --img 640 --iou 0.65 --device 0 --batch 1 --half

!python val.py --weights yolov5s_fp32.engine --data coco.yaml --img 640 --iou 0.65 --device 0 --batch 1
!python val.py --weights yolov5s_fp16.engine --data coco.yaml --img 640 --iou 0.65 --device 0 --batch 1 --half
```

YOLOv5s v6.1 |Inference time (ms)    | COCO mAP
---        |---          |---  
PyTorch FP32      |12.5   | 37.5
PyTorch FP16      |10.5  | 37.5
TensorRT FP32      |3.4   | 37.4
TensorRT FP16      |1.9  | 37.4

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved half-precision inference handling for TensorRT models.

### 📊 Key Changes
- Detection, validation, and export scripts now adjust the `half` (FP16) setting based on the model's capabilities when using TensorRT.
- The TensorRT model now has a boolean attribute to indicate if it requires FP16 input.
- Automatic notification and adjustment if the user-specified `half` setting doesn't match the model's TensorRT FP16 input requirement.
- Simplification of FP16 engine building logic in the export script, to rely strictly on the platform's fast FP16 support capability.

### 🎯 Purpose & Impact
- Ensures compatibility between the user's FP16 setting and the model's actual capabilities, avoiding potential errors.
- Provides clearer logging information to the user when an auto-adjustment occurs, improving the user experience.
- Users can expect better reliability and ease of use when exporting and running models with TensorRT, particularly on platforms that support fast FP16 inference. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@DavidBaldsiefen thanks for the updates! I'm confused about the --half incompatibility, I thought before you said with the addition of forcing an FP32 input layer TRT could determine and adapt both FP32 and FP16 inputs to the type of model (FP16 or FP32), so I thought all 4 combinations of export and inference would work, but this is not the case, even after removing the detect.py and val.py asserts:

```python
!pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com  # install

!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0  # export
%mv yolov5s.engine yolov5s_fp32.engine
!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0 --half  # export
%mv yolov5s.engine yolov5s_fp16.engine

!python detect.py --weights yolov5s_fp32.engine --imgsz 640 640 --device 0  # works
!python detect.py --weights yolov5s_fp32.engine --imgsz 640 640 --device 0 --half  # fails
!python detect.py --weights yolov5s_fp16.engine --imgsz 640 640 --device 0  # fails
!python detect.py --weights yolov5s_fp16.engine --imgsz 640 640 --device 0 --half  # works
```

Is there any way to make all 4 Usage examples work? I understand that user error will trigger the asserts on the fails, but it would be nice to make these two usage cases robust to user error if possible.

**Comment by DavidBaldsiefen** [comment]
@glenn-jocher Sorry for the misunderstanding, I have replaced the assert with a info and automatically adjusted the input precision. However I am on mobile right now so I cannot check the code (no GPU), can you?
Also, what happens when the `—half` flag is set but not `—device`? Right now this could lead to a problem in val.py where the input is changed to half again even on cpu devices. Does this cause a crash?

**Comment by glenn-jocher** [comment]
@DavidBaldsiefen thanks for the updates! --half will be disabled if device=cpu:
https://github.com/ultralytics/yolov5/blob/47288407450f83ccbdbd2e950bf339e30e67a181/detect.py#L96-L97

**Comment by glenn-jocher** [comment]
@DavidBaldsiefen tested and all for use cases now work correctly withy FP16 times:

```bash
detect: weights=['yolov5s_fp32.engine'], source=data/images, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-23-gfb64186 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)

Loading yolov5s_fp32.engine for TensorRT inference...
[03/06/2022-19:23:25] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 0, GPU 501 (MiB)
[03/06/2022-19:23:26] [TRT] [I] Loaded engine size: 16 MiB
[03/06/2022-19:23:26] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14, now: CPU 0, GPU 14 (MiB)
[03/06/2022-19:23:29] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +17, now: CPU 0, GPU 31 (MiB)
image 1/2 /content/yolov5/data/images/bus.jpg: 640x640 4 persons, 1 bus, Done. (0.002s)
image 2/2 /content/yolov5/data/images/zidane.jpg: 640x640 2 persons, 2 ties, Done. (0.002s)
Speed: 1.9ms pre-process, 1.9ms inference, 10.1ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp
detect: weights=['yolov5s_fp32.engine'], source=data/images, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=True, dnn=False
YOLOv5 🚀 v6.1-23-gfb64186 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)

Loading yolov5s_fp32.engine for TensorRT inference...
[03/06/2022-19:23:33] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 0, GPU 501 (MiB)
[03/06/2022-19:23:33] [TRT] [I] Loaded engine size: 16 MiB
[03/06/2022-19:23:33] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14, now: CPU 0, GPU 14 (MiB)
[03/06/2022-19:23:37] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +17, now: CPU 0, GPU 31 (MiB)
model incompatible with --half. Adjusting automatically.
image 1/2 /content/yolov5/data/images/bus.jpg: 640x640 4 persons, 1 bus, Done. (0.002s)
image 2/2 /content/yolov5/data/images/zidane.jpg: 640x640 2 persons, 2 ties, Done. (0.002s)
Speed: 1.8ms pre-process, 1.8ms inference, 1.5ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp2
detect: weights=['yolov5s_fp16.engine'], source=data/images, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-23-gfb64186 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)

Loading yolov5s_fp16.engine for TensorRT inference...
[03/06/2022-19:23:40] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 0, GPU 503 (MiB)
[03/06/2022-19:23:40] [TRT] [I] Loaded engine size: 16 MiB
[03/06/2022-19:23:40] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14, now: CPU 0, GPU 14 (MiB)
[03/06/2022-19:23:44] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +17, now: CPU 0, GPU 31 (MiB)
model requires --half. Adjusting automatically.
image 1/2 /content/yolov5/data/images/bus.jpg: 640x640 4 persons, 1 bus, Done. (0.002s)
image 2/2 /content/yolov5/data/images/zidane.jpg: 640x640 2 persons, 2 ties, Done. (0.002s)
Speed: 0.6ms pre-process, 1.9ms inference, 1.6ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp3
detect: weights=['yolov5s_fp16.engine'], source=data/images, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=True, dnn=False
YOLOv5 🚀 v6.1-23-gfb64186 torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)

Loading yolov5s_fp16.engine for TensorRT inference...
[03/06/2022-19:23:47] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 0, GPU 501 (MiB)
[03/06/2022-19:23:48] [TRT] [I] Loaded engine size: 16 MiB
[03/06/2022-19:23:48] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14, now: CPU 0, GPU 14 (MiB)
[03/06/2022-19:23:51] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +17, now: CPU 0, GPU 31 (MiB)
image 1/2 /content/yolov5/data/images/bus.jpg: 640x640 4 persons, 1 bus, Done. (0.002s)
image 2/2 /content/yolov5/data/images/zidane.jpg: 640x640 2 persons, 2 ties, Done. (0.002s)
Speed: 0.6ms pre-process, 1.9ms inference, 1.6ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp4
```

**Comment by glenn-jocher** [comment]
@DavidBaldsiefen PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
