### PR TITLE
blueberry model

### PR DESCRIPTION
**Pull request by chautrn**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Converted GitHub PR into a human-friendly summary.

### 📊 Key Changes
- Added TensorFlow support for exporting TFLite models via `export.py`.
- Introduced Android code to use TFLite models in the YOLOv5 repository.
- Updated relevant Python scripts to support TensorFlow and TFLite alongside PyTorch.

### 🎯 Purpose & Impact
- The changes allow users to export YOLOv5 models in TFLite format which can be used in mobile applications.
- Developers can now utilize YOLOv5's object detection capabilities within Android apps.
- The PR extends the usability of YOLOv5 to onboard new platforms like Android, broadening its applications.

### CODE REVIEW

**Comment by chautrn** [comment]
Sorry, completely misclicked.

**Comment by chautrn** [comment]
Maintainers, if you are reading this, could you please delete this PR?

**Comment by glenn-jocher** [comment]
@chautrn PR's can't be deleted, only opened, closed, merged etc.

**Comment by chautrn** [comment]
@glenn-jocher Gotcha, thanks. Sorry about this PR then.

**Pull request closed without merging**
