### PR TITLE
Make normalized confusion matrix more interpretable 

### PR DESCRIPTION
**Pull request by rbavery**
This solves https://github.com/ultralytics/yolov5/issues/2071, see it for an explanation of why the current implementation produces a confusion matrix with a misplaced background FP and background FN vectors. Switching their position before normalization means that columns are correctly normalized by the amount of groundtruth for each column.

It's worth noting that this implementation is based on 

https://github.com/kaanakan/object_detection_confusion_matrix/blob/master/confusion_matrix.py

which is based on 

https://github.com/svpino/tf_object_detection_cm

Both of which also implement the confusion matrix for object detection with the background FP and background FN misplaced. I'll link to this PR in each repo.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved label consistency in confusion matrix of YOLOv5.

### 📊 Key Changes
- Fixed an issue in the confusion matrix where false positives (FP) and false negatives (FN) were incorrectly labeled.
- Updated the confusion matrix plotting code to align the labels for FP and FN with standard practice.

### 🎯 Purpose & Impact
- 🎯 This change ensures that the confusion matrix correctly represents and labels the FP and FN, improving the interpretability of model performance for developers and users.
- 💡 The corrected labels will help users more accurately evaluate and tune their object detection models, potentially leading to better performance and fewer classification errors.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@rbavery one question: if we swap the plotted axes I think we should also swap the 'True' and 'Predicted' axes labels right?

Coincidentally this would align us with Google's automl confusion plots convention, which isn't a bad thing:
image

**Comment by rbavery** [comment]
We aren't swapping the plotted axes exactly, we are swapping the positions of the cells in the last column and last row. So the axes labels are correct as is, after swapping the last column and last row. If we swapped the axes labels with this PR's implementation of the CM, the labels would be backwards. The CM values could definitely be rotated so that the axes labels are switched, but I think it's fine as is.

**Comment by rbavery** [comment]
I think it might make sense to leave it for another PR to play with ways to format the Confusion Matrix. The purpose of this PR is primarily to fix a bug, where the matrix proportions do not mean what people think they mean when the matrix is normalized.

**Comment by rbavery** [comment]
any updates on this or blockers to merging?

**Comment by glenn-jocher** [comment]
@rbavery no blockers, just need to set aside some time to try out the changes, as the last time I looked the swaps seemed to be in line with transposing the matrix, but maybe I was confused. Added a TODO.

**Comment by glenn-jocher** [comment]
@rbavery ok reviewed this again. Matrix is plotted as detected class `dc` (y axis) vs ground-truth class `gc` (x axis). Array should increment then as `matrix[gc, dc] += 1` for each detection I think, which master seems to stick to.


In PR L148 remains the same, but L150 and 155 switch the convention. It is not switched entirely for the matrix though since L148 is unchanged, otherwise we could simply transpose everything. I think it must not be possible to insert data based on `dc` indexing axis zero though if axis zero corresponds to the truth indices `gc`, this doesn't seem correct.

I think maybe what you are trying to achieve could be done by transposing the array with the same column normalization, or perhaps simply normalizing rows instead of columns? I'm sorry if I'm just not understanding.

**Comment by glenn-jocher** [comment]
Running some tests here with this command:
`!python test.py --weights yolov5m.pt --data coco128.yaml --img 640 --iou 0.65`

## default master
image

## default PR
image

## master transposed
```
            self.matrix = self.matrix.transpose()
            array = self.matrix / (self.matrix.sum(0).reshape(1, self.nc + 1) + 1E-6)  # normalize cols
```
image


## master row normalize
```python
            # array = self.matrix / (self.matrix.sum(0).reshape(1, self.nc + 1) + 1E-6)  # normalize cols
            array = self.matrix / (self.matrix.sum(1).reshape(self.nc + 1, 1) + 1E-6)  # normalize rows
```
image


EDIT: can't really make sense of this, too many classes.

**Comment by rbavery** [comment]
To summarize again:

values within a column of the confusion matrix should count how many groundtruth samples were counted as the row class. The current confusion matrix on master does not do this, because the value at row class "background FP" and column "person" does not represent a count of # of "person" predicted as row class . 

Therefore normalizing along columns is invalid. You also can't normalize by row for the same reason, since the final column on master does not represent what was predicted by the row class, but instead that nothing was predicted and that groundtruth is the row class.

**Transposing the whole matrix or changing the axis of normalization does not fix the core issue that the FN and FP vectors are misplaced. This is a bug if the columns or rows are normalized, since the proportions do not mean what people think they mean. Example: If we normalize by column .6 for the person row and person column does not mean 60% of all groundtruth people were detected as people using the implementation on master**.

@glenn-jocher If it's still not making sense, I suggest reviewing the explanation in the github issue again. I think I laid the explanation out there and I'm confident this fix is correct. 
The issue has been fixed in this repo: https://github.com/kaanakan/object_detection_confusion_matrix/issues/8

**Comment by glenn-jocher** [comment]
@rbavery hmm ok thanks again. If @kaanakan accepts the fix, then we should change it here as well.

**Comment by glenn-jocher** [comment]
@rbavery PR is merged. Thank you for your contributions!

Updated comparison with VOC for easier viewing:
```
python test.py --weights VOC/yolov5s/weights/best.pt --data voc.yaml --img 512 --device 0
```

## Before 
image


## After 
image

**Pull request merged**
