### PR TITLE
Refactor/detect.py

### PR DESCRIPTION
**Pull request by sandstorm12**
Hi, I thought the detect script needs a refactor before adding multi-thread support for video processing.

## Changes:
- Broke long functions
- Broke long lines
- Did some refactor based on PEP8

## Future refactor suggestions:
- Use argument dict to simplify function signatures (reduce the number of arguments)

P.S. I have tested the detect.py on Colab on an image. Testing on other inputs is necessary.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactor `detect.py` for modularity and maintainability.

### 📊 Key Changes
- Refactored the `detect.py` script into smaller, more manageable functions.
- Simplified argument passing by initializing fields earlier in the process.
- Checked and loaded different types of models more systematically.
- Streamlined device initialization and model loading procedures.
- Refined pre-processing, inference, and prediction post-processing steps.
- Enhanced readability by organizing the code more logically and improving comments.

### 🎯 Purpose & Impact
- 🔍 **Increased Readability and Maintainability**: Breaking down a large function into smaller parts makes it easier to understand and update.
- 🚀 **Future Development**: With TODO comments in place, it's clear that the maintainers plan to further improve the code.
- ⚙️ **Systematic Approach**: Users can expect more consistent behavior when different parts of the code are standardized.
- ✅ **Potential Performance Improvements**: Streamlining the code may reduce errors and improve execution efficiency.

### CODE REVIEW

**Comment by sandstorm12** [comment]
@glenn-jocher 
Is there any progress on this PR? :)

**Comment by glenn-jocher** [comment]
@sandstorm12 thanks for the PR, I appreciate the initiative here! We strive to create the simplest and most concise implementation we can in YOLOv5. Keeping this in mind, I'm not sure that adding 300 extra lines (doubling the length of detect.py), with no additional features supported is what we want. To the contrary if it were possible to remove lines/code from detect.py I would jump at the chance.

Also the repository is on a 120 character line format, linting is handled by PyCharm formatter, though we are considering other solutions there like YAPF. In any case this would need to be applied repo-wide if we went that route.

**Comment by sandstorm12** [comment]
@glenn-jocher Hi,

Great, I would have your suggestions in mind.

Yet, I think single-purpose short functions (30 ~ 60 lines) are basic best practices. Halfing your script line count by having a function with ~230 lines seems obviously a bad practice. I suggest (doing it myself) breaking the detect.py into two or more scripts as shorter script files are also a best practice.

Regarding the character limit, my bad :) I would refactor it back to 120 characters limit.

Please tell me if the above suggestions are acceptable for you and I could eventually merge my PR. Otherwise, we could do something more productive :)))

**Comment by glenn-jocher** [comment]
@sandstorm12 I think one of the requirements we do have going forward is a more unified inference approach. We currently have detect.py, val.py and pytorch hub inference, all of which use different dataloaders and inference methods. We've had many requests for validation of exported models, but val.py currently only handles pytorch models.

I think if we want to update detect.py the modification would probably be part of a larger restructuring of the entire inference engine. But this is a rather large undertaking.

**Comment by sandstorm12** [comment]
@glenn-jocher I agree and that's ok. I'll consider this PR closed. Let me know if there was anything I could do :)

**Pull request closed without merging**
