### PR TITLE
Update models/hub *.yaml files for v2.0

### LINKED ISSUE #543: The old version model configuration file error caused by the new version.
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#reproduce-our-environment
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
From models/hub/*.yaml configure file all Invalidation. I think the reason for this is that you no longer output the `nn.Conv2d` function.

## To Reproduce (REQUIRED)

Input:
```
# command
python train.py --cfg models/hub/yolov3-spp.yaml --data data/coco.yaml
```

Output:
```
# report error message
Traceback (most recent call last):
  File "train.py", line 469, in <module>
    train(hyp, tb_writer, opt, device)
    ......
IndexError: index 0 is out of range
```

## Expected behavior
Run this program normally.

## Environment
 - OS: [Ubuntu18.04]
 - GPU [2080 Ti]

## Additional context
I have read your model configuration file, I think the new version of the configuration file should be filled out in accordance with it, I am also ready to submit a PR, looking forward to your reply.

**yolov3-spp.yaml**
```
# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# darknet53 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [32, 3, 1]],  # 0
   [-1, 1, Conv, [64, 3, 2]],  # 1-P1/2
   [-1, 1, Bottleneck, [64]],
   [-1, 1, Conv, [128, 3, 2]],  # 3-P2/4
   [-1, 2, Bottleneck, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 5-P3/8
   [-1, 8, Bottleneck, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 7-P4/16
   [-1, 8, Bottleneck, [512]],
   [-1, 1, Conv, [1024, 3, 2]], # 9-P5/32
   [-1, 4, Bottleneck, [1024]],  # 10
  ]

# YOLOv3-SPP head
head:
  [[-1, 1, Bottleneck, [1024, False]],
   [-1, 1, SPP, [512, [5, 9, 13]]],
   [-1, 1, Conv, [1024, 3, 1]],
   [-1, 1, Conv, [512, 1, 1]],
   [-1, 1, Conv, [1024, 3, 1]],  # 15

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 8], 1, Concat, [1]],  # cat backbone P4
   [-1, 1, Bottleneck, [512, False]],
   [-1, 1, Bottleneck, [512, False]],
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [512, 3, 1]],  # 22

   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P3
   [-1, 1, Bottleneck, [256, False]],
   [-1, 2, Bottleneck, [256, False]],  # 27

   [[27, 22, 15], 1, Detect, [nc, anchors]],   # Detect(P3, P4, P5)
  ]
```

### PR DESCRIPTION
**Pull request by Lornatang**
Update the configuration file under the hub model to yolov5—2.0 version.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvements to model configuration YAML files for YOLOv3-SPP, YOLOv5 FPN, and YOLOv5 PANet.

### 📊 Key Changes
- **Code Clean-up:** Removed redundant comments and lines for a cleaner configuration structure.
- **Layer References:** Updated negative indices to correct layer references for upsampling and concatenation operations.
- **Detect Layer References:** Specified explicit indices in the Detect layer to indicate which layers are used for detection.

### 🎯 Purpose & Impact
- **Readability:** The changes make the YAML configuration files more readable and maintainable. 📖
- **Correctness:** Adjustments in the layer references ensure that the models are constructed with the correct architecture, potentially fixing bugs related to incorrect layer connections. 🛠️
- **Detection Performance:** Modifying which layers are used in the Detect layer may enhance the detection capabilities of the models, leading to potentially better performance in object detection tasks. 🎯

The impact of these changes will likely be noticed by users in the form of more stable and reliable model performance, although the exact impact on metrics like accuracy or speed would need to be evaluated empirically.

### CODE REVIEW

**Comment by Lornatang** [comment]
See problem https://github.com/ultralytics/yolov5/issues/543#issue-667115718

**Comment by glenn-jocher** [comment]
Looks good! I added some output layer comments I accidentally deleted from the v2.0 yamls.

**Comment by lucasjinreal** [comment]
@Lornatang The fpn version can not parse?

```
/models/yolo.py", line 120, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/yolov5/models/yolo.py", line 27, in forward
    x[i] = self.m[i](x[i])  # conv
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 147, in __getitem__
    return self._modules[self._get_abs_string_index(idx)]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 137, in _get_abs_string_index
    raise IndexError('index {} is out of range'.format(idx))
IndexError: index 0 is out of range
```

**Comment by lucasjinreal** [comment]
actually PAN   also can not parse

**Comment by Lornatang** [comment]
@jinfagang 
*yolov5-panet.yaml*
```
# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [116,90, 156,198, 373,326]  # P5/32
  - [30,61, 62,45, 59,119]  # P4/16
  - [10,13, 16,30, 33,23]  # P3/8

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, BottleneckCSP, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]], # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, BottleneckCSP, [1024, False]],  # 9
  ]

# YOLOv5 PANet head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, BottleneckCSP, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [256, False]],  # 17

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, BottleneckCSP, [512, False]],  # 20

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, BottleneckCSP, [1024, False]],  # 23

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```
It is work.

**Comment by Lornatang** [comment]
@jinfagang 
*yolov5-fpn.yaml*
```
# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, Bottleneck, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]], # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 6, BottleneckCSP, [1024]],  # 9
  ]

# YOLOv5 FPN head
head:
  [[-1, 3, BottleneckCSP, [1024, False]],  # 10

   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 1, Conv, [512, 1, 1]],
   [-1, 3, BottleneckCSP, [512, False]],  # 14

   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 3, BottleneckCSP, [256, False]],  # 18

   [[18, 14, 10], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```
It is work.

**Comment by glenn-jocher** [comment]
All of the models currently parse correctly. You can test them directly from yolo.py:

```bash
$ export PYTHONPATH="$PWD" 
$ python models/yolo.py --cfg yolov5-fpn.yaml                               
Using CPU

                 from  n    params  module                                  arguments                     
  0                -1  1      7040  models.common.Focus                     [3, 64, 3]                    
  1                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  2                -1  3    246912  models.common.Bottleneck                [128, 128]                    
  3                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  4                -1  1   1627904  models.common.BottleneckCSP             [256, 256, 9]                 
  5                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  6                -1  1   6499840  models.common.BottleneckCSP             [512, 512, 9]                 
  7                -1  1   4720640  models.common.Conv                      [512, 1024, 3, 2]             
  8                -1  1   2624512  models.common.SPP                       [1024, 1024, [5, 9, 13]]      
  9                -1  1  18105344  models.common.BottleneckCSP             [1024, 1024, 6]               
 10                -1  1  10234880  models.common.BottleneckCSP             [1024, 1024, 3, False]        
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    787456  models.common.Conv                      [1536, 512, 1, 1]             
 14                -1  1   2561536  models.common.BottleneckCSP             [512, 512, 3, False]          
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1    197120  models.common.Conv                      [768, 256, 1, 1]              
 18                -1  1    641792  models.common.BottleneckCSP             [256, 256, 3, False]          
 19      [18, 14, 10]  1    457725  Detect                                  [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [256, 512, 1024]]
Model Summary: 309 layers, 5.02628e+07 parameters, 5.02628e+07 gradients, 118.7 GFLOPS
```

**Comment by Pluto1314** [comment]
@glenn-jocher Hi, what is the yolov5-FPN performance? (such as : AP)

**Comment by glenn-jocher** [comment]
@Pluto1314 instead of asking me why don't you read the readme, where it shows you the commit where PANet replaced FPN?

**Pull request merged**
