### PR TITLE
TorchScript `torch==1.7.0` Path support

### PR DESCRIPTION
**Pull request by miknyko**
#### thanks

### CODE REVIEW

**Comment by miknyko** [comment]
@glenn-jocher 
Hi, I modified several other places as well, in case there is an error as well, is that ok ?

**Comment by glenn-jocher** [comment]
@miknyko let's just fix this one issue, as the other packages have not had any bug reports yet. Thanks!

**Comment by glenn-jocher** [comment]
@miknyko PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Comment by miknyko** [comment]
@glenn-jocher 
Thanks. Great project by the way!

**Pull request merged**
