### PR TITLE
W&B: Restructure code to support the new dataset_check() feature

### PR DESCRIPTION
**Pull request by AyushExel**
@glenn-jocher I've tested this on most of the features and I'll continue some more testing to be sure.
Most of the changes are in wandb_utils.py but there is some restructuring in train.py:
* changes in train.py: Loggers are initialized before `dataset_check()` is called. This is essential for not re-downloading the same dataset
* changes in utils/loggers/init.py: there was a redundant wandb import check that I've removed. I think we can reduce some more import checks but it's a minor detail that I'll address in another PR. Getting the original behavior fixed is a bigger priority

@glenn-jocher This is an urgent fix. You might also have to re-format using pycharm. Sorry about that!

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved integration with Weights & Biases for better YOLOv5 training management and dataset logging.

### 📊 Key Changes
- Modified dataset checking logic to either use a default check or Weights & Biases dict when provided.
- Streamlined Weights & Biases (wandb) logger initialization and configuration update process.
- Simplified the logger start-up, especially when Weights & Biases is not installed.
- Updated the dataset artifact creation process in Weights & Biases logging.
- Minor refactoring and removal of redundant code to increase clarity and maintenance.

### 🎯 Purpose & Impact
- The changes aim to enhance user experience managing YOLOv5 training with Weights & Biases, and simplify the codebase, making it easier for developers to understand and contribute.
- Users can now expect a more robust and straightforward connection between YOLOv5 and Weights & Biases, improving tracking and management of machine learning experiments.
- The improvements could potentially lead to a more efficient development cycle and a better understanding of model performance for end users.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel I can't do the reformat myself:
Screenshot 2021-07-28 at 17 12 15

It's really easy for you to do, just open up your code in pycharm, select the loggers dir, right click and 'Reformat Code':
Screenshot 2021-07-28 at 17 13 55

**Comment by AyushExel** [comment]
@glenn-jocher done. I selected all available options.
Screenshot (16)

**Comment by glenn-jocher** [comment]
@AyushExel PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
