### PR TITLE
reducing time latency for long run live stream

### LINKED ISSUE #4465: Detection Latency with live streaming sources (RTMP)
## ❔Question

I am trying to detect objects in a live stream using the default `yolov5s.pt` model. However, I am seeing a latency in the detection output irrespective of the source of the stream. Tried the below ways

- OBS streaming to a local RTMP server
- Webapp sending camera feed to a server, encoded using `ffmpeg` and then to local RTMP server

In both the scenarios, I saw the latency to be increasing over time. Is this what everyone usually experiences with the detection script or is it something that I am doing wrong on the ingestion side?

I tried playing the OBS stream in a VLC player and the playback is almost realtime with may be 1-2 seconds latency.

If anyone tried live stream object detection using YoloV5, please let me know if you made any performance improvements for the script to not have the latency increase over time.

## Additional context

Thanks for this awesome detection library.

### PR DESCRIPTION
**Pull request by ashReal**
Hey, first congrats on building such a great model for object detection. Here I wanted to contribute a little. When we are running our model on live stream it takes a millisecond to execute but much of the time it keeps on executing some frames repeatedly because we were not able to fetch new frames due to fps. And when new frame arrives our model is busy in executing the old frame and this causes latency.. I ran my model on live stream it started giving significant latency after hours. As far as i can recall it was giving latency in 4-5 seconds. Hope you like the changes

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvements to real-time object detection with YOLOv5, including new latency optimizations and support for ONNX.

### 📊 Key Changes
- Added support for ONNX models in the streaming input pipeline to improve compatibility.
- Refined the frame processing in `detect.py` to reduce latency, especially for continuous live streams.
- Removed an unnecessary sleep call in `datasets.py` that was introducing delays during live streams.
- Integrated an early check to skip processing if consecutive frames are identical, reducing redundant computations.

### 🎯 Purpose & Impact
- Enhance the performance of YOLOv5 during long-running live stream object detection tasks. 
- Reduce the time-to-inference by skipping processing of identical frames and removing delays.
- Allow users to utilize ONNX models more effectively within the existing pipeline, increasing flexibility for deployment scenarios.

These changes aim to deliver a snappier, more efficient real-time detection experience to users, who may benefit from reduced computational overhead and support for a wider range of model formats. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@ashReal thank you for your contribution! LoadStreams() is a multithreaded dataloader that operates independent threads for each index in a batch. This provides multi-stream capability, i.e. stream 16 RTSP cameras and run inference on them simultaneously at batch-size 16. 

The current PR does not maintain current functionality for all other workflows, i.e. inference on images, directories, etc.

**Comment by ashReal** [comment]
@glenn-jocher ok ok I will look into that too, but the changes I made are very much required in the live stream, try to run once my push parallelly with the previous repo after 10 to 15 minutes you will start noticing a delay. I Will see for images and directories I totally missed that part.

**Comment by ashReal** [comment]
@glenn-jocher that test failed shouldn't happen I think. Can you tell me what could be the reason?

**Comment by Smalltarget108** [comment]
> @glenn-jocher that test failed shouldn't happen I think. Can you tell me what could be the reason?

Hello, @ashReal  I face this problem, after running your code, there is no delay but the stream frozen frequently，how do you push the stream? Many thanks.

**Comment by ashReal** [comment]
> > @glenn-jocher that test failed shouldn't happen I think. Can you tell me what could be the reason?
> 
> Hello, @ashReal I face this problem, after running your code, there is no delay but the stream frozen frequently，how do you push the stream? Many thanks.

Hello @Smalltarget108 which problem are you facing? and stream is frozen when it don't find any object for which we are doing detection but as soon as it find object it starts again. If I missed what you tried to say please explain a little bit. 

**Edit: Stream not freezing checked several times.**

**Comment by Smalltarget108** [comment]
> > > @glenn-jocher that test failed shouldn't happen I think. Can you tell me what could be the reason?
> > 
> > 
> > Hello, @ashReal I face this problem, after running your code, there is no delay but the stream frozen frequently，how do you push the stream? Many thanks.
> 
> Hello @Smalltarget108 which problem are you facing? and stream is frozen when it don't find any object for which we are doing detection but as soon as it find object it starts again. If I missed what you tried to say please explain a little bit.

Do you need to push the stream to another rtsp address? I find that the stream is frozen frequently after inference.

**Comment by ashReal** [comment]
> > > > @glenn-jocher that test failed shouldn't happen I think. Can you tell me what could be the reason?
> > > 
> > > 
> > > Hello, @ashReal I face this problem, after running your code, there is no delay but the stream frozen frequently，how do you push the stream? Many thanks.
> > 
> > 
> > Hello @Smalltarget108 which problem are you facing? and stream is frozen when it don't find any object for which we are doing detection but as soon as it find object it starts again. If I missed what you tried to say please explain a little bit.
> 
> Do you need to push the stream to another rtsp address? I find that the stream is frozen frequently after inference.

I am not doing anything like that and my stream is not pausing it's running smoothly. Can you help me reproduce the problem on my side?

**Comment by Smalltarget108** [comment]
> > > > Hello, @ashReal I face this problem, after running your code, there is no delay but the stream frozen frequently，how do you push the stream? Many thanks.
> > > 
> > > 
> > > Hello @Smalltarget108 which problem are you facing? and stream is frozen when it don't find any object for which we are doing detection but as soon as it find object it starts again. If I missed what you tried to say please explain a little bit.
> > 
> > 
> > Do you need to push the stream to another rtsp address? I find that the stream is frozen frequently after inference.
> 
> I am not doing anything like that and my stream is not pausing it's running smoothly. Can you help me reproduce the problem on my side?

You see your inference results via “cv2.imshow” on local machine, and there is no  pause and no delay after hours？

**Comment by ashReal** [comment]
> > > > > Hello, @ashReal I face this problem, after running your code, there is no delay but the stream frozen frequently，how do you push the stream? Many thanks.
> > > > 
> > > > 
> > > > Hello @Smalltarget108 which problem are you facing? and stream is frozen when it don't find any object for which we are doing detection but as soon as it find object it starts again. If I missed what you tried to say please explain a little bit.
> > > 
> > > 
> > > Do you need to push the stream to another rtsp address? I find that the stream is frozen frequently after inference.
> > 
> > 
> > I am not doing anything like that and my stream is not pausing it's running smoothly. Can you help me reproduce the problem on my side?
> 
> You see your inference results via “cv2.imshow” on local machine, and there is no pause and no delay after hours？

Yes, nothing happened like that till. But still, can you tell me how many hours you ran so I will run for the same hours and will update here?  I start running it again and will run for straight two to three hours exactly.

**Comment by Smalltarget108** [comment]
> > > > > > Hello, @ashReal I face this problem, after running your code, there is no delay but the stream frozen frequently，how do you push the stream? Many thanks.
> > > > > 
> > > > > 
> > > > > Hello @Smalltarget108 which problem are you facing? and stream is frozen when it don't find any object for which we are doing detection but as soon as it find object it starts again. If I missed what you tried to say please explain a little bit.
> > > > 
> > > > 
> > > > Do you need to push the stream to another rtsp address? I find that the stream is frozen frequently after inference.
> > > 
> > > 
> > > I am not doing anything like that and my stream is not pausing it's running smoothly. Can you help me reproduce the problem on my side?
> > 
> > 
> > You see your inference results via “cv2.imshow” on local machine, and there is no pause and no delay after hours？
> 
> Yes, nothing happened like that till. But still, can you tell me how many hours you ran so I will run for the same hours and will update here? I start running it again and will run for straight two to three hours exactly.

I think the problem maybe because  i need to push the result to another stream address on the server by the ffmpeg command below:     

command = ['ffmpeg',
    '-y',
    '-f', 'rawvideo',
    '-vcodec','rawvideo',
    '-pix_fmt', 'bgr24',
    '-s', "{}x{}".format(width, height),
    '-r', str(fps),
    '-i', '-',
    '-c:v', 'libx264',
    '-pix_fmt', 'yuv420p',
    '-preset', 'ultrafast',
    '-f', 'flv', 
    outstream]
    pipe = sp.Popen(command, stdin=sp.PIPE)
pipe.stdin.write(im0.tostring())

**Comment by ashReal** [comment]
> > > > > > > Hello, @ashReal I face this problem, after running your code, there is no delay but the stream frozen frequently，how do you push the stream? Many thanks.
> > > > > > 
> > > > > > 
> > > > > > Hello @Smalltarget108 which problem are you facing? and stream is frozen when it don't find any object for which we are doing detection but as soon as it find object it starts again. If I missed what you tried to say please explain a little bit.
> > > > > 
> > > > > 
> > > > > Do you need to push the stream to another rtsp address? I find that the stream is frozen frequently after inference.
> > > > 
> > > > 
> > > > I am not doing anything like that and my stream is not pausing it's running smoothly. Can you help me reproduce the problem on my side?
> > > 
> > > 
> > > You see your inference results via “cv2.imshow” on local machine, and there is no pause and no delay after hours？
> > 
> > 
> > Yes, nothing happened like that till. But still, can you tell me how many hours you ran so I will run for the same hours and will update here? I start running it again and will run for straight two to three hours exactly.
> 
> I think the problem maybe because i need to push the stream to another stream address on the server by the ffmpeg command below:
> 
> command = ['ffmpeg',
> '-y',
> '-f', 'rawvideo',
> '-vcodec','rawvideo',
> '-pix_fmt', 'bgr24',
> '-s', "{}x{}".format(width, height),
> '-r', str(fps),
> '-i', '-',
> '-c:v', 'libx264',
> '-pix_fmt', 'yuv420p',
> '-preset', 'ultrafast',
> '-f', 'flv',
> outstream]
> pipe = sp.Popen(command, stdin=sp.PIPE)
> pipe.stdin.write(im0.tostring())

It might be the cause, I can't tell anything about that, because I am using a stream from RTSP and it shows no delay what you saying might be because of server latency. But for my local stream no such lag and delay I noticed.

**Comment by ashReal** [comment]
@glenn-jocher how can I get this reviewed?

**Comment by glenn-jocher** [comment]
@ashReal sorry it's just that the problem is not clear to me. Can you provide code to reproduce the issue you are attempting to address in this PR please?

**Comment by nandukalidindi** [comment]
@ashReal, sorry if the question is a little out of context of the PR. When you said that the detection is showing latency after some hours, can I please know what setup you are using? I was using OBS to stream to a local rtmp server and I see latency of 3 seconds right from the start and it just keeps increasing as time goes. I also played the same rtmp stream in VLC and it's near close to the real time. Just wondering what your setup is.

Sample video for the setup https://github.com/ultralytics/yolov5/issues/4465#issuecomment-901582252

**Comment by ashReal** [comment]
> @ashReal, sorry if the question is a little out of context of the PR. When you said that the detection is showing latency after some hours, can I please know what setup you are using? I was using OBS to stream to a local rtmp server and I see latency of 3 seconds right from the start and it just keeps increasing as time goes. I also played the same rtmp stream in VLC and it's near close to the real time. Just wondering what your setup is.
> 
> Sample video for the setup [#4465 (comment)](https://github.com/ultralytics/yolov5/issues/4465#issuecomment-901582252)

@nandukalidindi @glenn-jocher  ya it can start with delay also my main point was as the time keep on increasing the latency we observe in beginning don't stay same but keeps on increasing with time because our for loop in detect.py keeps on doing inference for the last frame even if it has done inferencing on it. And as it was busy in doing inference on the same frame for which it has already given us results our model is still busy and the latest frame takes time to be sent to model. To remove this problem i had done PR.

@glenn-jocher  to reproduce the problem run the yolov5 on live stream for 1 hour and after that check the difference in real stream and stream after detection you will see latency, But with my PR there seems to be no latency. For videos it works pretty well because it already got all frame but in rtsp when it dont get any new frame it keep on running our model on last frame of img list. 

I have RTX 2080 ti.

**Comment by ashReal** [comment]
@nandukalidindi also check execution time it is taking 0.4sec to execute a frame so delay started at beginning is obvious.

**Comment by nandukalidindi** [comment]
@ashReal I assumed you weren't facing a latency issue at the start because you mentioned that the latency is significant after hours but seems like that is not the case. And your RTX will definitely cut down latency compared to mine, for me latency jumps to 10+ seconds within minutes. Thank you for clarifying, I will try to incorporate your changes locally and see how it performs for my use case.

**Comment by ashReal** [comment]
@nandukalidindi  yes and also try to run with lower img-size as it will run images much faster or use some better end hardware.

**Pull request closed without merging**
