### PR TITLE
W&B: Fix for 4360

### LINKED ISSUE #4360: AttributeError: 'NoneType' object has no attribute 'get'
## ❔Question
I am trying to resume training but unfortunately i am getting  error (see image).Please guide me about this
!python train.py --img 920 --batch 32  --epochs 500 --data customcoco.yaml  --resume /content/yolov5/runs/train/exp/weights/last.pt --save_period 1
## Additional context
Plese guide me about this how to solve it
Capture 2

### PR DESCRIPTION
**Pull request by AyushExel**
Fix for https://github.com/ultralytics/yolov5/issues/4360

@glenn-jocher is there a way to include offline resume tests in the CI tests workflow? It'll make sure that all of the default YOLO feature never break due to a change 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced integration with the Weights & Biases (WandB) tool in the YOLOv5 codebase.

### 📊 Key Changes
- Resolved an issue in `wandb_utils.py` where the `data_dict` was not properly initialized under certain conditions.
- Minor edit to the end of the file to fix formatting (newline at the end of the file).

### 🎯 Purpose & Impact
- **Purpose**: To ensure that the Weights & Biases logging utility always correctly initializes with the dataset information, preventing potential runtime errors.
- **Impact**: Users utilizing the Weights & Biases platform for tracking experiments will experience more reliable performance, especially when dealing with local YAML and ZIP file datasets. Overall stability and consistency in experiment tracking are improved. 📈🔍

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel that's a really interesting question. My instinct is to say it's not possible unless we build in a backdoor to force-crash the training at a given point, as fully trained models can't be --resumed currently, though I've been thinking of a way to allow that as the users seem to like using the --resume command.

**Comment by glenn-jocher** [comment]
@AyushExel is this PR ready to merge?

**Comment by AyushExel** [comment]
@glenn-jocher yes it is ready to merge.

How about we force crash a run by raising an exception one 1st epoch is completed? Then just resume for one more epoch

**Comment by glenn-jocher** [comment]
@AyushExel well that's what I was saying, this is only possible if we build a mechanism for this directly in train.py, this is not possible externally by updating the github CI actions.

**Comment by glenn-jocher** [comment]
@AyushExel PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
