### PR TITLE
Simplified YOLOv5 README

### PR DESCRIPTION
**Pull request by batrlatom**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Revamped YOLOv5 README for a cleaner, more informative user experience.

### 📊 Key Changes
- ✨ Introduced a new, streamlined visual layout for the project's README.
- 📸 Replaced outdated images with a fresh YOLOv5 logo and new badges.
- 🔗 Added quick access links to documentation, tutorials, and easy integration guides.
- 🚀 Announced an Ultralytics YOLOv5 competition with cash prizes.
- 🐳 Improved guidance on Docker usage.
- 🧠 Highlighted preprocessing improvements to the YOLOv5 models' performance statistics.

### 🎯 Purpose & Impact
- 🌐 Improves the first impression of the project for newcomers with a cleaner README layout.
- 📑 Enhances accessibility to information, making it easier to get started with YOLOv5.
- 👥 Engages the community with a competition to drive innovation and user interaction.
- 📈 Provides updated model performance metrics to help users choose the right model for their needs.

### CODE REVIEW

**Comment by batrlatom** [comment]
Need to correctly insert logo image, Kalen made it relative to the root directory, but we need it as usercontent .. https://github.com/KalenMike/yolov5-readme/raw/master/assets/img/yolov5-logo-s.png

**Comment by glenn-jocher** [comment]
@batrlatom thanks for the PR! I'll take a look at this today.

**Comment by batrlatom** [comment]
Kalen improved it much more, I think we can just skip this.

**Comment by glenn-jocher** [comment]
Ok got it.

**Pull request closed without merging**
