### PR TITLE
Gmt710 patch 2

### PR DESCRIPTION
**Pull request by gmt710**
Set s starting index for the videos.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced video processing in YOLOv5's data loader to start from custom frame index.

### 📊 Key Changes
- 🎬 Added `video_start_idx` parameter to `LoadImages` class initializer.
- 🐞 Fixed video reading loop to handle non-successful frame reads more robustly.
- ✨ Enabled skipping to a specific video frame index when initializing video processing.

### 🎯 Purpose & Impact
- 🎥 Provides users with the ability to start video inference from a specified frame, improving flexibility for video analysis tasks.
- 🛠️ Improves robustness in video reading, potentially reducing issues with corrupted frames or videos loading incorrectly.
- 📈 May benefit applications that require analysis of video segments rather than full videos, saving processing time and resources.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@gmt710 can you explain the use case behind this PR please? Thanks!

**Comment by gmt710** [comment]
@glenn-jocher Ok, you may add an Parameter in detect.py:
```
line 230
parser.add_argument('--start', default=0, help=' Your test video start index. If you want to test some videos, you can try it.')

line 64
start=0,

line 95 change :
dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt, video_start_idx=start)
```


```
Usage:
    $ python path/to/detect.py --weights yolov5s.pt --source  path/*.mp4 or avi  # directory
                                                 --start your_video_start_index 
```
your_video_start_index from 0, I've tested it many times.

For example, If I have 100 videos, I want start from 30. this may helps.
```
python path/to/detect.py --weights yolov5s.pt --source  path/*.mp4 or avi  # directory
                                                 --start 29
```

**Comment by gmt710** [comment]
@glenn-jocher Hello, Have you checked ?

**Comment by glenn-jocher** [comment]
@gmt710 thanks for the PR, but I don't think we want this feature in master. Instead we probably want a way to pass a list of individual files for detection, or point to a *.txt file that contains a list of files (moving streams to *.streams file).

**Pull request closed without merging**
