### PR TITLE
Add yolov5 namespace

### PR DESCRIPTION
**Pull request by sheromon**
The changes here to address #2481 move the yolov5 code into a yolov5 directory with an `__init__.py` file to make `yolov5` a Python package. When yolov5 is installed using pip, modules and functions can then be imported like `from yolov5.utils.autoanchor import check_anchors` with no need to add any directories to the Python path. This is a problem that many users have encountered in the past as in #134 and #353.

Adding `yolov5` to the import statement can also help to disambiguate in the event that a user has something else named `models` or `utils` in their Python path.

These changes are intentionally made to be consistent with changes made by @fcakyon in yolov5-pip and make the code in these two repos more similar.

A TODO item is updating the docs to reflect the new locations for various files. I thought about doing that but figured it made more sense to get some feedback on these changes first.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Reorganization of the YOLOv5 codebase with directory structure changes and updates to files for better modularity.

### 📊 Key Changes
- 📁 Refactored the project structure by moving most files into a new `yolov5` directory.
- 🧹 Cleaned up import statements to reflect the new directory structure.
- ✂️ Removed unnecessary sys.path.append calls due to the reorganization.
- ➕ Added `.vscode` to `.gitignore` to prevent committing Visual Studio Code-specific files.
- 🔄 Adjusted hard-coded paths in the `.gitignore` to match the new structure.

### 🎯 Purpose & Impact
- ⚙️ Enhances modularity: better organization makes it easier to maintain and navigate the project.
- 🔍 Improves clarity: clear separation of different components for developers working on the project.
- 🚀 Project scalability: sets a foundation for future expansions/extensions of the codebase.
- ✨ User experience: non-intrusive changes from a user perspective, but may require updates to custom import statements if working directly with the code.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@sheromon thanks for the PR! Users have made similar suggestions in the past, including @fcakyon and @Borda with an earlier PR. We'd like to strike a balance between exportability/deployability and training/development so we've avoided this so far, thinking it would complicate matters for many use-cases.

Is there a middle-ground that might work so that someone could clone yolov5 within their own project and then use the same import structure you have above? Perhaps if we made the imports relative rather than absolute?

**Comment by fcakyon** [comment]
@glenn-jocher im not 100% sure but relative imports might make it easier

**Comment by glenn-jocher** [comment]
@fcakyon @sheromon, I'm not really sure either. I understand of course that dropping everything into a subfolder would make packaging easier, but it would also create more hurdles and possible failure points when new users were trying to learn and reproduce the tutorials, i.e. the current command is hard to fail, even if no arguments are passed we've designed it to run correctly the first time, and there's no ambiguity really about where to run it from:
```bash
$ python train.py
```

But under the proposed PR there would be 4 possible cases and probably many more bug reports from confused users in the future (especially first-time uses, which we really focus on):
```bash
$ python train.py  # works from yolov5/ but fails from .
$ python yolov5/train.py  # works from . but fails from yolov5/
```

EDIT: if the git clone directory and package directory are identically named it might lead to further confusion also, i.e. user raises an issue saying "I ran this command from the yolov5/ directory and {bug here}" and we would not know what that meant.

**Comment by Borda** [comment]
Check make installable pip package #465

**Comment by sheromon** [comment]
@glenn-jocher, oh, I hadn't realized that this change had been proposed before.

Now that you mention it, I can see the concern about confusion about which directory to run from. It seemed pretty clear to me, but I guess I'm somewhat used to working with Python code that is set up to be a pip package now. It's true that I don't have experience maintaining code for a large number of users -- I mainly write code for myself and my teammates, so I recognize that you have the much more experienced perspective.

I feel like relative imports wouldn't work, because sometimes you'd need to include a parent directory in the import path, e.g. in `models/common.py`, there's this line: `from utils.datasets import letterbox`. A relative import would have to go up a level from models, so I think it would be `from ...utils.datasets import letterbox`, and that seems like it wouldn't work if you don't have the pip package installed, right?

Anyway, the motivation was to solve the import issues that I and some others had encountered. To fix my problem for just me, I could probably just work off of the yolov5-pip repo instead.

Update: Oh! Maybe if this repo mentioned yolov5-pip? I just saw the part in #465 where someone said they'd found yolov5-pip but weren't sure "how much (if at all) it was associated with this project". It seems like it would be helpful to at least some people if maybe the ultralytics/yolov5 repo mentioned yolov5-pip so the relationship would be a little bit clearer.

**Comment by sheromon** [comment]
@Borda, thanks for mentioning, but it looks like nothing's been going on with #465 since last November?

**Comment by sheromon** [comment]
I retract my request

**Pull request closed without merging**
