### PR TITLE
Add ONNX export metadata

### LINKED ISSUE #7351: Why is the default "stride" of common.DetectMultiBackend set to 64
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm trying to run `detect.py`  with my onnx model, while I find that the image size is changed from (416, 416) to (448,448) by the `check_img_size` function, since `model.stride=64`. However, my model is a **P5** model. Then, I find that the default `stride` is set to 64 in `DetectMultiBackend `as follows:
`stride, names = 64, [f'class{i}' for i in range(1000)]  # assign defaults`
If the input is a .pt model, the `stride` will be changed by 
`stride = max(int(model.stride.max()), 32)  # model stride`
while, if the input is a .onnx model, the `stride` will never be changed. Then, if I exported the onnx mdoel by `python export.py --device 0 --img 416`, during inference,  I got this error:
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 448 Expected: 416
 index: 3 Got: 448 Expected: 416
 Please fix either the inputs or the model.

Process finished with exit code 1
```

Of course, if I use `--dynamic` to export .onnx model, the `detect.py` will run without error, but the image size is still changed to (448,448) and the inference speed is lower. And the the output anchors will be misplaced. 
If I modify the default `stride` to 32, then all the outputs are correct.
So I'm confused about the default setting of stride. Is this a bug？ Or, is there a bug in my code?

Environment:
`Win11 + anaconda + cuda 11.0 + python 3.8 + pytorch 1.7.1 + yolov5-6.0
`

### Additional

_No response_

### PR DESCRIPTION
**Pull request by glenn-jocher**
Adds stride and names to ONNX export metadata for reading during inference. Resolves #7342, https://github.com/ultralytics/yolov5/issues/7351

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced ONNX model export with metadata and improved model loading with custom metadata handling.

### 📊 Key Changes
- 🏷️ Added custom metadata properties (such as 'stride' and 'names') to the ONNX model during export.
- 📚 ONNX models now store additional information within their metadata properties.
- 🧠 Updated the model loading code to parse and utilize the new metadata when models are loaded using ONNX runtime.

### 🎯 Purpose & Impact
- 🛠️ **Purpose**: The inclusion of metadata in the ONNX models allows for more information to be packaged with the model itself, improving model portability and ease of use.
- 🔍 **Impact**: Users can benefit from the additional model metadata, leading to more informed and potentially optimized model deployment, especially in environments where model parameters like stride are important for integration.
- 🔄 Users relying on ONNX models from YOLOv5 will notice more robust integration with external tools due to enriched model metadata.

### CODE REVIEW

**Comment by axzakari** [comment]
Hi,

metadata are saved in onnx file. This can be confirmed by using netron.
But, we can not actually retrieve the  metadata properties when using:
`meta = session.get_modelmeta().custom_metadata_map`, the value is always empty.

@glenn-jocher, have you checked that we can retrieve the metadata as expected ?

Thanks in advance ;-)

**Comment by axzakari** [comment]
> Hi,
> 
> metadata are saved in onnx file. This can be confirmed by using netron. But, we can not actually retrieve the metadata properties when using: `meta = session.get_modelmeta().custom_metadata_map`, the value is always empty.
> 
> @glenn-jocher, have you checked that we can retrieve the metadata as expected ?
> 
> Thanks in advance ;-)

Never mind, buggy installation !!
It works

**Comment by luizconrado** [comment]
I believe this same issue is happening in YOLO v8.
When I export a custom-trained model to .engine, once I try to use it with YOLO to predict something, the same error mentioned above:
In my case...
AssertionError: input size torch.Size([1, 3, 640, 640]) not equal to max model size (1, 3, 1920, 1920)

Do you think this could be the case?
Can you help me fix it?

Thank you.

**Comment by glenn-jocher** [comment]
@axzakari great to hear! If you have any other questions or issues, feel free to ask. We're here to help!

**Pull request merged**
