### PR TITLE
Save *.npy features on detect.py `--visualize`

### PR DESCRIPTION
**Pull request by Zengyf-CVer**
Add feature map to save npy files,export npy files with 32 feature maps per layer.
ksnip_20211117-215723

ksnip_20211117-215757

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements in feature visualization and data saving within YOLOv5.

### 📊 Key Changes
- 📁 Modified the path handling for saving feature visualization images, ensuring they are stored in the correct directory.
- 🖼️ Feature visualization now includes saving the features as `.npy` files for easier post-processing or analysis.

### 🎯 Purpose & Impact
- 🚀 The updated path handling prevents potential issues with saving files in unintended locations, improving the reliability of the feature visualization functionality.
- 🔍 Saving features as `.npy` files provides users with more flexibility, allowing them to more easily use the visualized data for further research or analysis.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Zengyf-CVer if you want to add numpy outputs, it probably makes sense to export a single multi-dimensional array npy file per image rather than many npy files. i.e. instead of exporting 30 10x10 arrays you could export a single 30x10x10 array, and then no new directories are needed.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much for your suggestion, I will look into it again. thanks.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
I merged the 32 feature maps of each layer into one npy file and removed the folder.
ksnip_20211120-125556

**Comment by glenn-jocher** [comment]
@Zengyf-CVer hey great!

**Comment by glenn-jocher** [comment]
@Zengyf-CVer I've cleaned this up so the PR only adds +1 lines of code to the repo.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer PR is merged. Thank you for your contributions to YOLOv5 🚀 and Vision AI ⭐

**Pull request merged**
