### PR TITLE
Add verbose option to pytorch hub models

### LINKED ISSUE #2862: Is there a way to hide/suppress any console output when loading and inferencing via PyTorch Hub?
## ❔Question
I would like to use YOLOv5 in a custom project, so I need to be in control of what will be printed to the console. Currently I am loading the model and using it like described in your wiki:

    model = torch.hub.load("ultralytics/yolov5", "custom", path_or_model=args.model)
    model.conf = args.confidence
    model.iou = args.iou
    img = Image.open(args,image)
    results = model(img, size=args.size, augment=True)
    preds = results.pandas().xyxy[0]

However, these line result in some console output (like network layout, autoShape info, etc.)
Is there any way to hide all these standad console output?

### PR DESCRIPTION
**Pull request by NanoCode012**
As discussed in #2862 , I tried an implementation by allowing a user to pass in `verbose` as a positional argument when calling the pytorch hub model.

Command test run: `python hubconf.py` (and change the verbose value inside the file itself)
Real command after merged : `model = torch.hub.load("ultralytics/yolov5", "yolov5s", verbose=False)`

Before:
```
               from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7276605 parameters, 7276605 gradients, 17.1 GFLOPS

Downloading https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt to yolov5s.pt...
100%|██████████████████████████████████████| 14.1M/14.1M [00:01<00:00, 7.96MB/s]

Adding autoShape... 
YOLOv5 🚀 2021-4-25 torch 1.7.1 CUDA:0 (Tesla V100-SXM2-32GB, 32510.5MB)

image 1/5: 720x1280 2 persons, 2 ties
image 2/5: 720x1280 2 persons, 2 ties
image 3/5: 1080x810 4 persons, 1 bus
image 4/5: 1080x810 4 persons, 1 bus
image 5/5: 320x640
Speed: 337.4ms pre-process, 92.8ms inference, 1.6ms NMS per image at shape (5, 3, 640, 640)
Saved zidane.jpg, zidane.jpg, image2.jpg, bus.jpg, image4.jpg to runs/hub/exp
```

After:
```
Downloading https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt to yolov5s.pt...
100%|██████████████████████████████████████| 14.1M/14.1M [00:02<00:00, 7.32MB/s]

image 1/5: 720x1280 2 persons, 2 ties
image 2/5: 720x1280 2 persons, 2 ties
image 3/5: 1080x810 4 persons, 1 bus
image 4/5: 1080x810 4 persons, 1 bus
image 5/5: 320x640
Speed: 307.3ms pre-process, 95.6ms inference, 1.6ms NMS per image at shape (5, 3, 640, 640)
Saved zidane.jpg, zidane.jpg, image2.jpg, bus.jpg, image4.jpg to runs/hub/exp
```

I'm not sure if this is enough stripping or should the `Speed` be removed too? That will need a bit more modification...

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced logging control in YOLOv5 models by adding verbosity settings.

### 📊 Key Changes
- 🛠 Added a new `verbose` parameter to control logging output.
- ✨ Modified functions (`create`, `custom`, `yolov5s`, `yolov5m`, `yolov5l`, `yolov5x`, `yolov5s6`, `yolov5m6`, `yolov5l6`, `yolov5x6`) to accept and utilize the `verbose` parameter.
- 🔄 Updated logging calls (`print` statements) to use `logger.info` for consistent logging behavior.
- 📝 Changed default logging level behavior to depend on the verbosity setting.

### 🎯 Purpose & Impact 
- 🎛 Provides users and developers with more control over log output, which can be particularly helpful with debugging or running YOLOv5 in production environments.
- 🔇 Allows suppression of logs when not needed, making the console output cleaner for users who prefer less verbosity.
- ⚙ Facilitates better integration with systems where log verbosity needs to be dynamically controlled.
- 📊 Potentially reduces distraction and clutter in log files, helping users focus on important messages.

### CODE REVIEW

**Comment by NanoCode012** [comment]
@haimat , could you please check if this was what you wanted?

**Comment by haimat** [comment]
@NanoCode012 Well, yes, partly. It would be great though to have an option "silent" or something that would completely remove *all* output ...

**Comment by NanoCode012** [comment]
I see! I understood you incorrectly. I thought you only wanted the network outputs and autoshape gone.

**Comment by glenn-jocher** [comment]
@NanoCode012 thanks for the PR! @haimat the implementation does appear to remove all output. The output shown is due to the .print() call, which would be called by a user by definition to print results to screen.

**Comment by haimat** [comment]
Ahh I see, thanks. When can this be tested via Hub?

**Comment by glenn-jocher** [comment]
@haimat after it's merged it would appear in hub (use `force_reload=True` to update your cache). Before merge you can test like this:
```shell
git clone https://github.com/NanoCode012/yolov5 -b hub-verbose
cd yolov5
python hubconf.py
```

One item that still prints in the .save() statement.

**Comment by glenn-jocher** [comment]
@NanoCode012 PR looks good! Tested and works well. Merging now.

Thank you for your contributions (again)!!

**Comment by glenn-jocher** [comment]
@NanoCode012 I tried the fix with PyTorch Hub, but unfortunately logging seems to not respond the verbose argument. It seems to behave differently when running hubconf.py directly than when loading up a hub model. I'm not sure what's causing this.

**Comment by NanoCode012** [comment]
Hi @glenn-jocher , I'll have to do some guessing in the next few days to see. It's harder since pytorch hub models can't be tested locally. I'll check out if this is a limitation of logging with the hub models or my code and (hopefully) find a fix.

**Comment by glenn-jocher** [comment]
@NanoCode012 I know, they can be hard to debug. Thanks for the effort though!

**Comment by haimat** [comment]
I just tried it - first I did a `force_reload=True` to reload the model from the hub, then I added a `verbose=False`. However, the output was the same, incl. model layout summary. Is this update even online in the hub? Moreover, I am using my own model checkpoint like this:

    torch.hub.load("ultralytics/yolov5", "custom", path_or_model=model_path, verbose=False)

Should this new verbose option work in this case as well?

**Comment by haimat** [comment]
Just tested it with newly updated model from the Hub - this is the new, reduced output with `verbose=True`:

```
Fusing layers... 
Model Summary: 606 layers, 141024988 parameters, 0 gradients
Adding autoShape... 
YOLOv5 🚀 2021-5-11 torch 1.8.1+cu102 CPU
```

**Comment by glenn-jocher** [comment]
@haimat yes I've updated PyTorch Hub model loading to avoid having to build each model from scratch if no changes are asked for, so this simplifies the loading process and reduces the printed lines to screen now under most conditions. 

If you request a modification to the model it is still created first and then weights transferred, i.e. `classes=10`, resulting in the full printout as before.

**This is not a solution to the `verbose=False` not working problem**, but it helps of course.

**Comment by NanoCode012** [comment]
Hello @haimat , I'm sorry for my lack of response. This month irl is hectic for me. I don't think I will be available to debug on this PR till early next month.

**Pull request merged**
