### PR TITLE
Adding polygon detection alongside bounding boxes

### PR DESCRIPTION
**Pull request by ahmad4633**
I would like to thank [XinzeLee](https://github.com/XinzeLee/PolygonObjectDetection)  for his amazing work, that inspired this pull request.

This PR adds 4 points polygon detection capability to this repo. Original bounding box detection is not modified. The new head will output 9 values (index x1 y1 x2 y2 x3 y3 x4 y4), the labels for training are of the same format as the mentioned output.

Also, for training we need to install polygon IoU Cuda to speed up the validation process and we need set "--polygon True", a full tutorial for training is provided in this notebook [Polygon Tutorial](https://colab.research.google.com/drive/1sfdz3iu5yvIL9gD_GQFiWre4tAcwCeQZ?usp=sharing).

image

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced support for polygon labels in YOLOv5.

### 📊 Key Changes
- Added polygon label plotting utilities.
- Improved polygon label support in training and logging functions.
- Integrated polygon-specific NMS (Non-Maximum Suppression).
- Developed CUDA extensions for polygon IOU (Intersection Over Union) computation.

### 🎯 Purpose & Impact
- These changes allow YOLOv5 to train and infer with polygon-shaped bounding boxes, which are more accurate for certain objects.
- The CUDA extensions improve performance by offloading complex IOU calculations to the GPU.
- Overall, this broadens the range of computer vision tasks YOLOv5 can handle effectively.

### CODE REVIEW

**Comment by iceisfun** [comment]
Does the training data set change to polys instead of rects?

**Comment by ahmad4633** [comment]
> Does the training data set change to polys instead of rects?

Yes, that's right.
It should be in this form 
index x1 y1 x2 y2 x3 y3 x4 y4

**Comment by GivanTsai** [comment]
@ahmad4633 Thanks for your great work.
I have some questions. In the tutorial, we can train the model on pretrained weight, `--weights '/path/to/polygon_yolov5s.pt'`, Where can I download this weight? Since my training dataset is very small, maybe only 100 polygon.
And if I train the model from the scratch using this small dataset, is it enough to get good model performance?

**Comment by ahmad4633** [comment]
> @ahmad4633 Thanks for your great work. I have some questions. In the tutorial, we can train the model on pretrained weight, `--weights '/path/to/polygon_yolov5s.pt'`, Where can I download this weight? Since my training dataset is very small, maybe only 100 polygon. And if I train the model from the scratch using this small dataset, is it enough to get good model performance?

Please refer to [XinzeLee/PolygonObjectDetection](https://github.com/ahmad4633/PolygonObjectDetection.git) , where he attached a pretrained model in his original repo.
As for your dataset, consider using open Image dataset it contains around 5k licence plate images

**Comment by GivanTsai** [comment]
> > @ahmad4633 Thanks for your great work. I have some questions. In the tutorial, we can train the model on pretrained weight, `--weights '/path/to/polygon_yolov5s.pt'`, Where can I download this weight? Since my training dataset is very small, maybe only 100 polygon. And if I train the model from the scratch using this small dataset, is it enough to get good model performance?
> 
> Please refer to [XinzeLee/PolygonObjectDetection](https://github.com/ahmad4633/PolygonObjectDetection.git) , where he attached a pretrained model in his original repo. As for your dataset, consider using open Image dataset it contains around 5k licence plate images

But my polygon image is difference from the licence plate. If I use licence plate image dataset to pretrain the model, is it useful? By the way, where can I find the licence plate image dataset with 8 points labels?

**Comment by ahmad4633** [comment]
> > > @ahmad4633 Thanks for your great work. I have some questions. In the tutorial, we can train the model on pretrained weight, `--weights '/path/to/polygon_yolov5s.pt'`, Where can I download this weight? Since my training dataset is very small, maybe only 100 polygon. And if I train the model from the scratch using this small dataset, is it enough to get good model performance?
> > 
> > 
> > Please refer to [XinzeLee/PolygonObjectDetection](https://github.com/ahmad4633/PolygonObjectDetection.git) , where he attached a pretrained model in his original repo. As for your dataset, consider using open Image dataset it contains around 5k licence plate images
> 
> But my polygon image is difference from the licence plate. If I use licence plate image dataset to pretrain the model, is it useful? By the way, where can I find the licence plate image dataset with 8 points labels?

Sorry i read your post earlier and thought you wanted to train a license plate detector.
You can try using [XinzeLee’s weights](https://github.com/XinzeLee/PolygonObjectDetection/blob/main/polygon-yolov5/polygon-yolov5s-ucas.pt) as pretrained weights and see if it helps for your problem. If it doesn’t work you’ll have to gather more data and consider training from scratch.

As for the 4 points datasets, i don’t know of any, i only know datasets with normal bounding boxes labels but you can take the downloaded images and label them yourself. Maybe you can find a labeller online.
Note: This repo only takes 4 points not more.

**Comment by GivanTsai** [comment]
Do we must install `iou_cuda` to run training or test code? It seems that the version of cuda needs to be larger than 11.2, but I don't want to upgrade the cuda for now since it will influence my other environments for executing tasks. @ahmad4633

**Comment by ahmad4633** [comment]
> Do we must install `iou_cuda` to run training or test code? It seems that the version of cuda needs to be larger than 11.2, but I don't want to upgrade the cuda for now since it will influence my other environments for executing tasks. @ahmad4633

Install `iou_cuda` to run the training faster or it will take ages, but for predicting you don't need to install it.

**Comment by UygarUsta99** [comment]
@ahmad4633 Thank you for your great work ! Do you know any labeling tools that I can use for training a model with your work ?

**Comment by ahmad4633** [comment]
> @ahmad4633 Thank you for your great work ! Do you know any labelling tools that I can use for training a model with your work ?

Sorry I don't know of any online labeller.

**Comment by sctrueew** [comment]
@ahmad4633 Hi,

I appreciate your work. Can I use it with TensorRt C++?

Thanks

**Comment by ahmad4633** [comment]
> @ahmad4633 Hi,
> 
> I appreciate your work. Can I use it with TensorRt C++?
> 
> Thanks

Yes you can.

**Comment by tujh2** [comment]
Hi! Thank you for this modification.

I have an issue with onnx model. I can not import polygon model via opencv after onnx export: i guess ScatterND operator is not implemented.
Model successfully exported into onnx: `python export.py --img 128 --weights runs/train/exp17/weights/polygon_best.pt --include onnx --simplify`

So when i import model via `dnn::readNetFromONNX()` i get this error:
```
[ERROR:0] global /home/buildozer/aports/community/opencv/src/opencv-4.5.4/modules/dnn/src/onnx/onnx_importer.cpp (718) handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [ScatterND]:(416)
terminate called after throwing an instance of 'cv::Exception'
what():  OpenCV(4.5.4) /home/buildozer/aports/community/opencv/src/opencv-4.5.4/modules/dnn/src/onnx/onnx_importer.cpp:739: error: (-2:Unspecified error) in function 'handleNode'
> Node [ScatterND]:(416) parse error: OpenCV(4.5.4) /home/buildozer/aports/community/opencv/src/opencv-4.5.4/modules/dnn/src/dnn.cpp:615: error: (-2:Unspecified error) Can't create layer "416" of type "ScatterND" in function 'getLayerInstance'
```
<details>

image

</details>

Also I guess there is a problem with Mul operator with constants "inside", cause without `--simplify` I get this err:
```
Node [Mul]:(371) parse error: OpenCV(4.5.4) /home/buildozer/aports/community/opencv/src/opencv-4.5.4/modules/dnn/src/onnx/onnx_importer.cpp:1591: error: (-213:The function/feature is not implemented) Different shapes case is not supported with constant inputs: Mul in function 'parseMul'
```
I think I should go with this errors to opencv/opencv, but... Maybe we can produce solution to replace this operators? Unfortunately, I don't understand how to solve this.

P.S. I've tested with your last commits
P.S.S. `--img 128` is OK, this is my custom model.

**Comment by sctrueew** [comment]
@ahmad4633 Hi,

 I'm using Yolov5 in Tensort c++. Is there a way to use it in C++?

I could generate polygon_yolov5s_ucas.wts but when I want to make an engine I get this error.

[E] [TRT] 3: [network.cpp::nvinfer1::Network::addScale::735] Error Code 3: Internal Error (Parameter check failed at: network.cpp::nvinfer1::Network::addScale::735, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)

Thanks

**Comment by RoudyES** [comment]
Hello @tujh2 , @sctrueew ! This is Roudy, Ahmad's Co-worker.

@tujh2 your problem is due to OpenCV's inference engine. It does not support all the operators that ONNX officially supports. OpenCV tries to unify several formats under 1 inference engine (such as OpenVINO, ONNX, Caffe....) so they try to support all the common operators that are shared across the libraries and frameworks. Also, the Mul problem is due to the same limitation.
Unfortunately, there is no direct fix from our end for this. To make it work, either OpenCV will have to add that operator in their next versions, or, we would have to re-work all the detection head to try and workaround this operator, which obviously isn't the best course of action here.
You can run the model using ONNX runtime though, pre-process and post-process normally like you do in an OpenCV inference scenario but you just have to change the actual inference code. It shouldn't be that much of a difference for you.

@sctrueew yes this model works with TensorRT. You have 2 options:

1. Export a model in this repo by using `python export.py --weights /Path/To/Weights.pt --imgsz ImageSize --device 'cpu' --simplify --include engine`. This will directly export a .engine file without going through wts first.
2. Export model to ONNX format and build the .engine file from there.

We didn't try running the models in TensorRT C++. However, we deploy our models using ONNX format with the TensorRT execution provider which automatically converts the ONNX model to .engine then runs inference on the .engine so I believe it should work normally in TensorRT C++ if ONNX can run it.

**Comment by UygarUsta99** [comment]
I keep getting load_image is not defined error even though it should be imported from utils/datasets ? Any help ? Also I have installed iou_cuda utils via setup.py but I am getting Warning: "polygon_inter_union_cuda" and "polygon_b_inter_union_cuda" are not installed errors ?

**Comment by ahmad4633** [comment]
> I keep getting load_image is not defined error even though it should be imported from utils/datasets ? Any help ? Also I have installed iou_cuda utils via setup.py but I am getting Warning: "polygon_inter_union_cuda" and "polygon_b_inter_union_cuda" are not installed errors ?

Merhaba Uygar, please refer to [Colab Tutorial](https://colab.research.google.com/drive/1sfdz3iu5yvIL9gD_GQFiWre4tAcwCeQZ?usp=sharing).

**Comment by tujh2** [comment]
Hi, @RoudyES
> Unfortunately, there is no direct fix from our end for this.

I figured out that you can just comment `y[..., 8:] = y[..., 8:].sigmoid()` line in `Polygon_Detect.forward(x)` in `models/yolo.py` and then OpenCV reads model successfully. And it does not fail on Mul operator too.
The graph after exporting does not contain ScatterND operators. 
<details>

image

</details>

Also I have a question about `Polygon_Detect._make_grid()` func
OpenCV fails on `forward()` step. I've got the same error as in https://github.com/opencv/opencv/issues/20072 
I just copied original `_make_grid()` func from `Detect` and this helped. 
Now I can use polygon model with OpenCV and this working fine (I have custom inference pipeline in c++ and opencv, so I don't use detect.py)

Also I don't know if this changes are correct, but I'll leave that question to you :shrug:

**Comment by RoudyES** [comment]
@tujh2 Careful of removing that `y[..., 8:] = y[..., 8:].sigmoid()`, it is there to make sure that all the outputs are within the [0..1] range. Without it the model might output values outside of that range which will go out of bounds of the image. You should be able to remedy that in post processing but we thought of leaving it there to include that step directly in the model and save the user from an extra step at post processing. I think it is also present in the master branch for the same reason (clamping values between 0..1), @glenn-jocher can correct me if I'm wrong.

As for the  `_make_grid()` function I'm glad that it worked fine for you! Thank you for pointing that swapping it with `Detect`'s function fixed it! We'll do some further testing to make sure that swapping the functions won't have any hidden unwanted effect, if all goes well we'll then update the PR with the original `_make_grid()`.

Also, if you're on C++ I recommend swapping your inference engine to TensorRT, your pre and post processing steps will remain almost the same and you'll get a significant speedup in your pipeline.

**Comment by sctrueew** [comment]
@RoudyES Hi,

I've converted the model to onnx and when I want to do inference in C++ I get this error:

(-2:Unspecified error) Can't create layer "416" of type "Range" in function 'cv::dnn::dnn4_v20211004::LayerData::getLayerInstance'

Do you have a sample to use in C++ on onnx or TensorRT?

Thanks

**Comment by RoudyES** [comment]
@sctrueew it seems to me that you tried to run inference using OpenCV's DNN module. If so, please refer to @tujh2's comment above. They made some slight changes and were able to run the model with OpenCV's DNN.

However, I recommend running ONNX models using ONNX Runtime. Also, if you compile onnx runtime from source with TensorRT execution provider you will be able to run the same .onnx model with TensorRT backend without changing your code (the runtime will automatically convert the onnx model to .engine). Or you can just export the .pt model into .engine using `export.py`.

As for the sample, I'm afraid we don't have a C++ snippet. We usually run everything in C#.

**Comment by sctrueew** [comment]
@RoudyES Thank you. @tujh2, Have you successfully run in C++?

**Comment by tujh2** [comment]
@sctrueew 
Yes, I have. I run it with OpenCV 4.5.4 successfully.
I think that you exported your model without `--simplify` option. Try with this option and my tips in comment above.

**Comment by sctrueew** [comment]
> @sctrueew it seems to me that you tried to run inference using OpenCV's DNN module. If so, please refer to @tujh2's comment above. They made some slight changes and were able to run the model with OpenCV's DNN.
> 
> However, I recommend running ONNX models using ONNX Runtime. Also, if you compile onnx runtime from source with TensorRT execution provider you will be able to run the same .onnx model with TensorRT backend without changing your code (the runtime will automatically convert the onnx model to .engine). Or you can just export the .pt model into .engine using `export.py`.
> 
> As for the sample, I'm afraid we don't have a C++ snippet. We usually run everything in C#.

@RoudyES Hi,
Thank you for the reply, My final goal is to run it in C# as well. It would be nice to have it in C#.

**Comment by sctrueew** [comment]
> @sctrueew Yes, I have. I run it with OpenCV 4.5.4 successfully. I think that you exported your model without `--simplify` option. Try with this option and my tips in comment above.

Thanks, I've exported successfully the model to onnx but I still get the error when I want to readNet.

OpenCV version: 4.5.4 => built with GPU
auto net = dnn::readNetFromONNX("polygon.onnx");

What changes did you in the C++ side?

**Comment by tujh2** [comment]
> What changes did you in the C++ side?

Nothing at all. Actually I use GoCV - golang bindings for OpenCV, so I didn't modify code inside OpenCV library at all

**Comment by sctrueew** [comment]
> > What changes did you in the C++ side?
> 
> Nothing at all. Actually I use GoCV - golang bindings for OpenCV, so I didn't modify code inside OpenCV library at all

I've followed your tips and finally, I could readNet but I get an error in forward():

`shape_utils.hpp:171: error: (-215:Assertion failed) start <= (int)shape.size() && end <= (int)shape.size() && start <= end in function 'cv::dnn::dnn4_v20211004::total'`

**Comment by tujh2** [comment]
> > > What changes did you in the C++ side?
> > 
> > 
> > Nothing at all. Actually I use GoCV - golang bindings for OpenCV, so I didn't modify code inside OpenCV library at all
> 
> I've followed your tips and finally, I could readNet but I get an error in forward():
> 
> `shape_utils.hpp:171: error: (-215:Assertion failed) start <= (int)shape.size() && end <= (int)shape.size() && start <= end in function 'cv::dnn::dnn4_v20211004::total'`

This is a problem with `Polygon_Detect._make_grid()` func.
<details>

```python
    def forward(self, x):
        # x = x.copy() # for profiling
        z = []  # inference output
        for i in range(self.nl):
            x[i] = self.m[i](x[i])  # conv
            bs, _, ny, nx = x[i].shape  # x(bs,267,20,20) to x(bs,3,20,20,89)
            x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

            if not self.training:  # inference
                if self.onnx_dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
                    self.grid[i] = self._make_grid(nx, ny, i)

                y = x[i].clone()
                #y[..., 8:] = y[..., 8:].sigmoid()
                # y[..., 8], y[..., 9:] = y[..., 8].sigmoid(), y[...,
                # 9:].softmax(dim=-1) # softmax loss for classes
                if self.inplace:
                    y[..., :8] = (y[..., :8] + self.grid[i].repeat((1, 1, 1, 1, 4))) * self.stride[i]  # xyxyxyxy
                else:
                    xyxyxyxy = (y[..., :8] + self.grid[i].repeat((1, 1, 1, 1, 4))) * self.stride[i]  # xyxyxyxy
                    y = torch.cat((xyxyxyxy, y[..., 8:]), -1)
                z.append(y.view(bs, -1, self.no))

        return x if self.training else (torch.cat(z, 1), x)

    def _make_grid(self, nx=20, ny=20, i=0):
        d = self.anchors[i].device
        if check_version(torch.__version__, '1.10.0'):  # torch>=1.10.0 meshgrid workaround for torch>=0.7 compatibility
            yv, xv = torch.meshgrid([torch.arange(ny, device=d), torch.arange(nx, device=d)], indexing='ij')
        else:
            yv, xv = torch.meshgrid([torch.arange(ny, device=d), torch.arange(nx, device=d)])
        return torch.stack((xv, yv), 2).expand((1, self.na, ny, nx, 2)).float()
```

</details>
Try replace code in Polygon_Detect with this. That's work for me.

**Comment by sctrueew** [comment]
@tujh2 Thank you very much. it works for me but I have to change the result of forwarding.

`
        cv::dnn::blobFromImage(input_image, blob, 1. / 255., cv::Size(INPUT_WIDTH, INPUT_HEIGHT), cv::Scalar(), true, false);

	net.setInput(blob);
	std::vector<cv::Mat> outputs;
	net.forward(outputs, net.getUnconnectedOutLayersNames());

	float x_factor = input_image.cols / INPUT_WIDTH;
	float y_factor = input_image.rows / INPUT_HEIGHT;

	float* data = (float*)outputs[0].data;

	const int dimensions = 85;
	const int rows = 25200;

	std::vector<int> class_ids;
	std::vector<float> confidences;
	std::vector<cv::Rect> boxes;

	for (int i = 0; i < rows; ++i) {
		float confidence = data[4];`  <<===== error occurred`

**Comment by sctrueew** [comment]
@tujh2 Do you have any ideas on how to resolve this issue?
Thanks

**Comment by tujh2** [comment]
> @tujh2 Do you have any ideas on how to resolve this issue? Thanks

I can publish my Go-inference code. Just modify this for C++.
<details>

```
        blob := gocv.BlobFromImage(src, 1/255.0, myNet.NetSize, myNet.netMean, true, false)
        defer blob.Close()
	myNet.net.SetInput(blob, "")

	netOutput := myNet.net.Forward(myNet.outputLayerName) // outputLayerName = "output"
	defer netOutput.Close()
	srcImgSize := src.Size()
	ratioW := float32(srcImgSize[1]) / float32(myNet.NetSize.Y) // NetSize is like --img (default 640x640)
	ratioH := float32(srcImgSize[0]) / float32(myNet.NetSize.X)
	var netWidth int = myNet.СlassesCount
	if myNet.isPolygon {
		netWidth += 9 // polygon has 8 fields for coords and 1 field for boxScore and other - class score
	} else {
		netWidth += 5
	}
	pData, _ := netOutput.DataPtrFloat32()
	var rects []image.Rectangle
	var polygonRects []PolygonOutput
	var scores []float32
	var indices []int
	var classes []int
	for i := 0; i < len(pData)-netWidth; i += netWidth {
		if myNet.isPolygon {
			fboxScore := pData[i+8]
			if fboxScore > myNet.BoxThreshold {
				x1 := pData[i] * ratioW
				y1 := pData[i+1] * ratioH
				x2 := pData[i+2] * ratioW
				y2 := pData[i+3] * ratioH
				x3 := pData[i+4] * ratioW
				y3 := pData[i+5] * ratioH
				x4 := pData[i+6] * ratioW
				y4 := pData[i+7] * ratioH

				var maxClassScore float32 = 0.0
				var classIndex = 0
				for k := i + 9; k < i+9+myNet.СlassesCount; k++ {
					classScore := pData[k]
					if classScore > maxClassScore {
						classIndex = k
						maxClassScore = classScore
					}
				}
			        // save result
			        // classId := classIndex - i - 9
			        //...
			}
		} else { 
		        // non-polygon yolo
		        //...
		}
	}

```
</details>

**Comment by sctrueew** [comment]
> > @tujh2 Do you have any ideas on how to resolve this issue? Thanks
> 
> I can publish my Go-inference code. Just modify this for C++.
> 
> ```
>         blob := gocv.BlobFromImage(src, 1/255.0, myNet.NetSize, myNet.netMean, true, false)
>         defer blob.Close()
> 	myNet.net.SetInput(blob, "")
> 
> 	netOutput := myNet.net.Forward(myNet.outputLayerName) // outputLayerName = "output"
> 	defer netOutput.Close()
> 	srcImgSize := src.Size()
> 	ratioW := float32(srcImgSize[1]) / float32(myNet.NetSize.Y) // NetSize is like --img (default 640x640)
> 	ratioH := float32(srcImgSize[0]) / float32(myNet.NetSize.X)
> 	var netWidth int = myNet.СlassesCount
> 	if myNet.isPolygon {
> 		netWidth += 9 // polygon has 8 fields for coords and 1 field for boxScore and other - class score
> 	} else {
> 		netWidth += 5
> 	}
> 	pData, _ := netOutput.DataPtrFloat32()
> 	var rects []image.Rectangle
> 	var polygonRects []PolygonOutput
> 	var scores []float32
> 	var indices []int
> 	var classes []int
> 	for i := 0; i < len(pData)-netWidth; i += netWidth {
> 		if myNet.isPolygon {
> 			fboxScore := pData[i+8]
> 			if fboxScore > myNet.BoxThreshold {
> 				x1 := pData[i] * ratioW
> 				y1 := pData[i+1] * ratioH
> 				x2 := pData[i+2] * ratioW
> 				y2 := pData[i+3] * ratioH
> 				x3 := pData[i+4] * ratioW
> 				y3 := pData[i+5] * ratioH
> 				x4 := pData[i+6] * ratioW
> 				y4 := pData[i+7] * ratioH
> 
> 				var maxClassScore float32 = 0.0
> 				var classIndex = 0
> 				for k := i + 9; k < i+9+myNet.СlassesCount; k++ {
> 					classScore := pData[k]
> 					if classScore > maxClassScore {
> 						classIndex = k
> 						maxClassScore = classScore
> 					}
> 				}
> 			        // save result
> 			        // classId := classIndex - i - 9
> 			        //...
> 			}
> 		} else { 
> 		        // non-polygon yolo
> 		        //...
> 		}
> 	}
> ```

Thanks for sharing, If we have points more than 4 points how can we set (netWidth += 9). I don't know how many points are there? for example, one detection has 4 (x,y) and another one has 12(x,y)

**Comment by sctrueew** [comment]
> 
This is my code but not working.
`

		Mat blob;
            int col = SrcImg.cols;
		int row = SrcImg.rows;
		int maxLen = MAX(col, row);
		Mat netInputImg = SrcImg.clone();
		if (maxLen > 1.2 * col || maxLen > 1.2 * row) {
			Mat resizeImg = Mat::zeros(maxLen, maxLen, CV_8UC3);
			SrcImg.copyTo(resizeImg(Rect(0, 0, col, row)));
			netInputImg = resizeImg;
		}
		blobFromImage(netInputImg, blob, 1 / 255.0, cv::Size(netWidth, netHeight), cv::Scalar(104, 117, 123), true, false);
		net.setInput(blob);
		std::vector<cv::Mat> netOutputImg;
		net.forward(netOutputImg, net.getUnconnectedOutLayersNames());
		std::vector<int> classIds;
		std::vector<float> confidences;
		std::vector<cv::Rect> boxes;
		float ratio_h = (float)netInputImg.rows / netHeight;
		float ratio_w = (float)netInputImg.cols / netWidth;
		//int net_width = className.size() + 5;
		int net_width = className.size() + 9;
		float* pdata = (float*)netOutputImg[0].data;



		std::vector<polygon> pol;

		float classScore = 0;
		for (int i = 0; i < sizeof(pdata) - net_width; i += net_width) {

			float confidence = pdata[i + 8];
			if (confidence >= 0.5) {

				float x1 = pdata[i] * ratio_w;
				float y1 = pdata[i + 1] * ratio_h;
				float x2 = pdata[i + 2] * ratio_w;
				float y2 = pdata[i + 3] * ratio_h;
				float x3 = pdata[i + 4] * ratio_w;
				float y3 = pdata[i + 5] * ratio_h;
				float x4 = pdata[i + 6] * ratio_w;
				float y4 = pdata[i + 7] * ratio_h;
				auto maxClassScore = 0.0;
				auto classIndex = 0;
				for (int k = i + 9; k < i + 9 + className.size(); k++) {
					classScore = pdata[k];
					if (classScore > maxClassScore) {
						classIndex = k;
						maxClassScore = classScore;
					}
				}
				classIds.push_back(classIndex);
				confidences.push_back(maxClassScore);
				//boxes.push_back(Rect(x1, y1, x2, y2));
				pol.push_back({ x1,y1,x2,y2,x3,y3,x4,y4 });
			}
		}
`

**Comment by RoudyES** [comment]
@sctrueew Please note that the model can only predict 4 points polygons. You will never have a result with more than 4 points (if you did your post processing isn't correct).

**Comment by sctrueew** [comment]
> 

Yes, I know. what about this example?

image

There are more than four points for each object in the example above

**Comment by RoudyES** [comment]
@sctrueew This can't be achieved in this PR. The repo can only detect bounding boxes (such as the rotated boxes of the persons in this example). The image you shared seems to me the result of an Instance Segmentation model, where you get an object's bounding box along with it's contour polygon, this is not yet supported in this PR (although we might look into it in the future if this PR gets merged with master branch).

**Comment by GivanTsai** [comment]
There is a bug when I want to save the predicted text.  If I run the inference command
`python detect.py --polygon True --data '/content/yolov5/yolov5/data/polygon.ymal' --weights '/content/gdrive/MyDrive/Polygon_Yolo/yolov5/lpr/s/exp/weights/polygon_best.pt' --img 320 --source '/content/yolov5/polygon_all/images/val/' --hide-labels`
It is Successful, but it is failed when I add the option --save-txt and --save-crop
`!python detect.py --polygon True --data '/content/yolov5/yolov5/data/polygon.ymal' --weights '/content/gdrive/MyDrive/Polygon_Yolo/yolov5/lpr/s/exp/weights/polygon_best.pt' --img 320 --source '/content/yolov5/polygon_all/images/val/' --hide-labels --save-txt --save-conf --save-crop`
image
How to deal with this bug? @ahmad4633

**Comment by GivanTsai** [comment]
> There is a bug when I want to save the predicted text. If I run the inference command `python detect.py --polygon True --data '/content/yolov5/yolov5/data/polygon.ymal' --weights '/content/gdrive/MyDrive/Polygon_Yolo/yolov5/lpr/s/exp/weights/polygon_best.pt' --img 320 --source '/content/yolov5/polygon_all/images/val/' --hide-labels` It is Successful, but it is failed when I add the option --save-txt and --save-crop `!python detect.py --polygon True --data '/content/yolov5/yolov5/data/polygon.ymal' --weights '/content/gdrive/MyDrive/Polygon_Yolo/yolov5/lpr/s/exp/weights/polygon_best.pt' --img 320 --source '/content/yolov5/polygon_all/images/val/' --hide-labels --save-txt --save-conf --save-crop` image How to deal with this bug? @ahmad4633

It seems that the size of `gn` is torch.Size([4]) and `torch.tensor(xyxyxyxy).view(1, 8)` is torch.Size([1,8]), how to fix it?

**Comment by ryouchinsa** [comment]
With RectLabel, you can read/write/export polygons and keypoints in the YOLO format.
https://rectlabel.com/help#xml_to_yolo

Please give us your feedback about the combination of YOLOv5 and RectLabel.

yolo_polygon

**Comment by Aun0124** [comment]
@sctrueew  @tujh2  I have also convert my model to onnx and the output shape will be (batch, x, 12) for polygon . Can i know did you all implement own nms or using other solution to solve this ? Anyway I wanted to implement in java for android apps.

**Comment by tujh2** [comment]
> @sctrueew @tujh2 I have also convert my model to onnx and the output shape will be (batch, x, 12) for polygon . Can i know did you all implement own nms or using other solution to solve this ? Anyway I wanted to implement in java for android apps.

Hi, no, i have missed nms step cause my photo context contains only 1 object. So i just choose polygon by max score. Also, as i know, polygon nms is an expensive step

**Comment by Aun0124** [comment]
> > @sctrueew @tujh2 I have also convert my model to onnx and the output shape will be (batch, x, 12) for polygon . Can i know did you all implement own nms or using other solution to solve this ? Anyway I wanted to implement in java for android apps.
> 
> Hi, no, i have missed nms step cause my photo context contains only 1 object. So i just choose polygon by max score. Also, as i know, polygon nms is an expensive step
 
@tujh2  how about the preprocessing letterbox resize? can i have look on your code anyway , will be greatful.

**Pull request closed without merging**
