### PR TITLE
Fix infer yolov5-seg.onnx with opencv-dnn error

### PR DESCRIPTION
**Pull request by UNeedCryDear**
```
python ./segment/predict.py --weights yolov5s-seg.onnx --dnn
```
image

after fixed:<br>
image

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This Pull Request seems to be a placeholder or an error — no code changes detected.

### 📊 Key Changes
- N/A (No changes to summarize)

### 🎯 Purpose & Impact
- N/A (No impact to users or the software as the PR contains no actual content)

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@UNeedCryDear PR is not working for me. I'm getting this error:

> Node [Identity@ai.onnx]:(onnx_node!Identity_0) parse error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/layer.cpp:246: error: (-215:Assertion failed) inputs.size() in function 'getMemoryShapes'

Screenshot 2022-09-29 at 23 17 10

**Comment by UNeedCryDear** [comment]
@glenn-jocher opencv does not support dymanic onnx,you should export onnx without flag '--dymanic'

**Comment by glenn-jocher** [comment]
@UNeedCryDear I'm using the default export command. To reproduce my error just run PR in a Colab notebook:

```python
!git clone https://github.com/UNeedCryDear/yolov5 -b master # clone
%cd yolov5
%pip install -qr requirements.txt  # install

!python export.py --weights yolov5s.pt --include onnx
!python segment/predict.py --weights yolov5s-seg.onnx --dnn
```

Screenshot 2022-10-01 at 16 40 36

**Comment by UNeedCryDear** [comment]
```
!pip3 install torch==1.8.2 torchvision==0.9.2 torchaudio===0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu111
! pip uninstall torchtext
!python export.py --weights yolov5s-seg.pt --include onnx
!python segment/predict.py --weights yolov5s-seg.onnx --dnn
```
image<br>

So, this may be caused by the pytorch version 1.12?

**Comment by glenn-jocher** [comment]
@UNeedCryDear yes seems like a torch issue. That's strange, since the file is an ONNX file and the inference is run with OpenCV. Not sure what to do now, what do you think?

**Comment by UNeedCryDear** [comment]
@glenn-jocher 
https://github.com/ultralytics/yolov5/blob/c98128fe71a8676037a0605ab389c7473c743d07/export.py#L155
it works by setting  "do_constant_folding=False" when torch==1.12.x,
At the same time, I disabled dynamic when exporting onnx for opencv-dnn.
Now use:
```
python export.py --weights yolov5s-seg.pt --include onnx --dnn
python segment/predict.py --weights yolov5s-seg.onnx --dnn
```

image

**Comment by glenn-jocher** [comment]
@UNeedCryDear Thanks for sharing the solution! I'm glad to hear that setting "do_constant_folding=False" in torch==1.12.x and disabling dynamic when exporting ONNX for opencv-dnn resolved the issue. I appreciate your efforts in troubleshooting and finding the workaround. This will definitely help others who might encounter a similar problem. If you have any further questions or need assistance with anything else, feel free to ask.

**Pull request closed without merging**
