### PR TITLE
Update export.py

### PR DESCRIPTION
**Pull request by zzz3bbb3**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR appears to be either an empty or placeholder PR, with no code changes included.

### 📊 Key Changes
- There are no code changes to highlight as the PR diff is empty.

### 🎯 Purpose & Impact
- Without code changes, there's no direct impact on the software or users.
- It could be a PR for discussion, planning, or an error that needs to be closed without merging.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@nanmi hi there. What is the bug you are trying to fix with this? For ONNX dynamic models the correct export command is:
```bash
python export.py --include onnx --dynamic
```

**Comment by zzz3bbb3** [comment]
> @nanmi你好。您要修复的错误是什么？对于 ONNX 动态模型，正确的导出命令是：
> 
> ```shell
> python export.py --include onnx --dynamic
> ```

@glenn-jocher Hi, when I fine tune the model and save onnx directly, it is easy to generate output the processing after the detection head, if I export the pre training model onnx separately, there will be no error 😀

**Comment by glenn-jocher** [comment]
@nanmi I'm sorry I'm not understanding. The Detect layer onnx_dynamic attribute is already set correctly here:
https://github.com/ultralytics/yolov5/blob/ac2c49a2bb34aa4524d89d888760c0742384550f/export.py#L293-L295

If you are seeing an error in YOLOv5 that this PR is fixing, please raise a bug report first and then link this PR to it as a solution. As is I don't understand the problem this PR is fixing.

**Pull request merged**
