### PR TITLE
Implementing New Generalized Intersection Over Union (NGIoU) Loss 

### PR DESCRIPTION
**Pull request by maurya-ashutosh**
I have implemented the New Generalized Intersection Over Union (NGIoU) Loss described in the paper _NGIoU Loss: Generalized Intersection over Union Loss Based on a New Bounding Box Regression_ (https://www.mdpi.com/2076-3417/12/24/12785).

Changes are made to the ```bbox_iou()``` function in the ```utils/metrics.py``` file by adding the NGIoU loss as an extra parameter for the function.

### Summary
📄🔄➕

This pull request introduces the NGIoU metric for bounding box evaluation and loss computation in `yolov5`. It updates the `bbox_iou` function in `utils/metrics.py` and the `ComputeLoss` class in `utils/loss.py` to use NGIoU instead of CIoU. It also adds a new configuration file for the fire detection dataset in `data/fire.yaml`.

> _New config file for_
> _`fire detection` dataset_
> _Autumn leaves are red_

### Walkthrough
* Use NGIoU metric for bounding box loss and evaluation ([link](https://github.com/ultralytics/yolov5/pull/11507/files?diff=unified&w=0#diff-afc9c0f856a1fa54a2d35dfcd375a176b7b736953195238a3a51870eef4314bbL141-R141), [link](https://github.com/ultralytics/yolov5/pull/11507/files?diff=unified&w=0#diff-b4ad8049203cd9bbf0c3f3a4edb37f8b72780228334d55fab31c4c555f942bd6L222-R225), [link](https://github.com/ultralytics/yolov5/pull/11507/files?diff=unified&w=0#diff-b4ad8049203cd9bbf0c3f3a4edb37f8b72780228334d55fab31c4c555f942bd6L246-R251), [link](https://github.com/ultralytics/yolov5/pull/11507/files?diff=unified&w=0#diff-b4ad8049203cd9bbf0c3f3a4edb37f8b72780228334d55fab31c4c555f942bd6L258-R317))
* Add configuration file for fire detection dataset ([link](https://github.com/ultralytics/yolov5/pull/11507/files?diff=unified&w=0#diff-d3ff164849166a2f54d4759f1d9906ca67f9a91365ca1875124b0fd7d52ea5ecL1-R8))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Implementation of a new Intersection over Union (IoU) metric, NGIoU, for better bounding box predictions.

### 📊 Key Changes
- Changed the IoU calculation in `loss.py` to support NGIoU (Next Generation IoU).
- Updated `bbox_iou` function in `metrics.py` to include the NGIoU implementation along with existing IoU variants.

### 🎯 Purpose & Impact
- 🎯 NGIoU aims to provide a more precise measurement of overlap between predicted and ground truth bounding boxes, potentially leading to better object localization in detection models.
- 📈 The new metric could improve the performance of YOLOv5 models, resulting in more accurate object detection outputs for users.
- 🧪 Users can expect more refined loss calculations during training, which may enhance model convergence and accuracy.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@maurya-ashutosh thanks for the PR! Can you quantify any performance difference on COCO or VOC using the new loss vs current baseline?

@AyushExel interesting

**Comment by maurya-ashutosh** [comment]
Thanks for the response, @glenn-jocher! I'm currently running low on compute resources to carry out the benchmarking. I'll update as soon as I can.

**Comment by glenn-jocher** [comment]
@maurya-ashutosh I took a look at your implementation. Shouldn't it have an `if else` statement for the 3 cases shown in the paper here?

https://www.mdpi.com/2076-3417/12/24/12785
Screenshot 2023-05-13 at 22 25 20

**Comment by maurya-ashutosh** [comment]
@glenn-jocher Since the input to this function is the tensor with all bounding boxes in an image, directly comparing (A in B or B in A) the conditions doesn't work. Instead, I make a boolean tensor for each case, and then take the sum of products of each boolean tensor with its corresponding loss value tensor (line 306).

**Comment by glenn-jocher** [comment]
@maurya-ashutosh thanks for your response. I understand your approach of creating boolean tensors and summing their products with corresponding loss value tensors. This seems like a reasonable solution to handle the three cases of the NGIoU loss function. Keep up the good work!

**Comment by glenn-jocher** [comment]
@maurya-ashutosh any update on this? Have you been able to quantify performance improvements in the PR branch vs master branch?

**Comment by masc-it** [comment]
any updates? @maurya-ashutosh really interesting job!

**Comment by glenn-jocher** [comment]
@masc-it thanks for your interest in this PR. @maurya-ashutosh is currently running low on compute resources to carry out the benchmarking and performance evaluation. We appreciate your patience and are looking forward to seeing the results as soon as possible.

**Pull request closed without merging**
