### PR TITLE
W&B log epoch

### PR DESCRIPTION
**Pull request by glenn-jocher**
May allow W&B results logging with epoch x axis.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvement in Weight & Biases logging within YOLOv5's testing and training routines.

### 📊 Key Changes
- Modified `wandb.log` calls in `test.py` and `train.py` to use `commit=False` option.
- Updated `wandb.log` in `utils/plots.py` with `commit=False`.

### 🎯 Purpose & Impact
- 👍 **Purpose**: These changes allow for more efficient logging to Weight & Biases by grouping multiple logs into a single network call.
- 🚀 **Impact**: Reduces the number of calls to Weights & Biases API during training and testing, potentially speeding up these processes and improving resource usage. Users of the YOLOv5 framework with integrated Weights & Biases logging will benefit from these optimizations.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel after our meeting I checked the docs and updated the logging here to allow epoch x axes.

**Comment by glenn-jocher** [comment]
Implemented from https://docs.wandb.ai/library/log

**Comment by glenn-jocher** [comment]
Mixed results here. I tried `wandb.log({tag: x, 'epoch': epoch})`, and saw that it simply adds 'epoch' to the data like any other value and even plots it (see example below). I tried `wandb.log({tag: x, 'Epoch': epoch})` and `wandb.log({tag: x, 'Step': epoch})` also but can not produce the desired effect with either, desired effect being that the x axis of all charts defaults to Epoch, and Epoch itself is not assigned a chart, which is nonsensical.

Screen Shot 2021-01-14 at 9 04 43 PM

**Comment by glenn-jocher** [comment]
To compound my confusion I still have no idea what a 'step' is, nor how W&B determines that 9 epochs somehow corresponds to 200-something steps.

**Comment by AyushExel** [comment]
Hey @glenn-jocher. Each wandb.log statement is treated as it's own step. So, in my dsviz demo branch, I created a wandbLogger class that stores all of the metrics and images in a log dict and logs them together at the same step when epoch ends. 
Here's an example run from my branch -> [https://wandb.ai/cayush/yolo_wandb/runs/26tjpi7r?workspace=user-cayush](https://wandb.ai/cayush/yolo_wandb/runs/26tjpi7r?workspace=user-cayush) . Notice how there are only 50 steps for 50 epochs.  I have already mailed my branch to you with all the details. Let me know if something's not clear.

**Comment by glenn-jocher** [comment]
@AyushExel ok understood. Let's chat about this coming week. I would say this seems to be our highest priority logging update at the moment.

Some people say that the general concept of an epoch is a little antiquated these days (i.e. especially with the mosaic loader), but its something basic that everyone can understand. A secondary x axis unit would be batches, and a third optimizer updates, though these last two create challenges comparing runs with different model sizes (smaller models like v5s can be trained with larger batch sizes than larger models like v5x), so I think an epoch x axis is really the gold standard we want to default to.

**Comment by AyushExel** [comment]
> @AyushExel ok understood. Let's chat about this coming week. I would say this seems to be our highest priority logging update at the moment.
> 
> Some people say that the general concept of an epoch is a little antiquated these days (i.e. especially with the mosaic loader), but its something basic that everyone can understand. A secondary x axis unit would be batches, and a third optimizer updates, though these last two create challenges comparing runs with different model sizes (smaller models like v5s can be trained with larger batch sizes than larger models like v5x), so I think an epoch x axis is really the gold standard we want to default to.

@glenn-jocher let's keep this up at #1948 . Basically, after that PR gets merged, we can set up the new logger, where "epochs will always be equal to steps". So, both the terms can be used interchangeably. I guess that's what we're aiming for?

**Comment by glenn-jocher** [comment]
@AyushExel actually I was going to close this one since it doesn't seem to accomplish what I wanted it. It's simply adding an extra data point that it considers a y axis value to each step, and then even worse it presents it in the dashboard by default as an epoch chart as my screenshot above shows. On the balance of things it seems to worsen the default dashboard for newcomers.

**Comment by glenn-jocher** [comment]
## BREAKING CHANGE WARNING

This PR includes a breaking change to logging workflows. The new W&B logging behavior will place each epoch's metrics and losses on the point on the x axis corresponding to epoch values (i.e. defaulting to an x axis that spans 1-300). This is how we should have implemented W&B logging originally (@AyushExel), as it is clearly better aligned with expected behavior, however **this change will make new trainings impossible to compare to old trainings** other than by comparing final metrics. Old and new overlays will no longer correspond as their x axes will no longer align.

I apologize for any difficulties this causes, and will seek to minimize these sorts of breaking workflow changes going forward.

**Comment by glenn-jocher** [comment]
Update: current implementation is the best compromise I could come up with. One other small nuisance is that training mosaics now do not upload right away after creation, they are delayed until epoch 0 trains and tests and are uploaded all togethor with epoch 0 results.

**Comment by glenn-jocher** [comment]
Update 2: @AyushExel I've done about all I can do I think. I've worked on this for half the day roughly, and unfortunately I haven't done a very good job of implementing this. I'm surprised it's so difficult to coax W&B into plotting epochs as the default. Unfortunately the current implementation, while it achieves this, sacrifices much in the process:

1. Due to some enigmatic W&B design choices, specifying `step` when logging prevents data from uploading until step is changed. The practical consequences of this are that results are now always delayed by one full epoch, as the previous epochs results will not be sent to the dashboard until the next epoch's results are logged. So if an epoch takes 30 minutes, you will not see any metrics on the dashboard for 60 minutes after starting training, and even then these first data points will correspond to epoch 0 metrics which were computed 30 minutes prior. 
2.  Initial images like labels.png, labels_correlogram.png, and the first few batches of mosaics used to upload instantly when training started, which felt responsive and was useful in quickly spotting issues. Now they are lumped in with epoch 0's log, which only uploads once two full epochs have completed, reducing responsiveness and utility due to #1 above.

If you have a better solution please let me know, I've been struggling with this for a while.

**Comment by AyushExel** [comment]
@glenn-jocher yes I agree. I think a better solution would be using the WandbLogger class to accumulate all the values to be logged throughout the epochs, and then log everything once the epoch ends. 
This will make sure that epoch is used as step, making sure that the number of epochs is equal the number of steps.

I think you should not worry a lot about this right now. Once we get the other W&B integration PR in, this solution will be pretty seamless.

**Comment by glenn-jocher** [comment]
@AyushExel oh didn't know there was a wandblogger class, sounds interesting. Thanks for the feedback, I will shelve this for the time being then with hopes for a solution integrated with our upcoming changes!

**Comment by glenn-jocher** [comment]
NOTE: Changes started in this PR finalized in #2073.

**Pull request merged**
