### PR TITLE
Enable ONNX `--half` FP16 inference

### LINKED ISSUE #5659: detect.py after converting in onnx with half precision doesn't work
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After converting .pt weights in .onnx format with half precision and running it with detect.py an error appears related to the fact that not all layers have been transferred to float16. 
 `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from yolov5l.onnx failed:Type Error: Type parameter (T) of Optype (Concat) bound to different types (tensor(float) and tensor(float16) in node (Concat_505).`

I executed export.py code with parameters: `python export.py --weights yolov5l.pt --half --device 0`
And after sucsessful convertation I ran the following command: `python detect.py --weights yolov5l.onnx  --half --device 0` and it gave me an error above. 

### Additional

There is no such error if I translate without the --half flag

### PR DESCRIPTION
**Pull request by glenn-jocher**
Enable ONNX `--half` FP16 inference. Resolves https://github.com/ultralytics/yolov5/issues/5659. Usage example:

```bash
# Export
python export.py --weights yolov5s.pt --include onnx --simplify --inplace --device 0 --half

# Inference
python detect.py --weights yolov5s.onnx --device 0 --half
```

In Colab V100 tests ONNX FP16 inference was about 1/3 faster than FP32 inference.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced FP16 (half-precision) support for ONNX backends on CUDA devices.

### 📊 Key Changes
- Updated the condition for enabling half-precision (`half`) support to include ONNX backends.
- Ensured consistency in FP16 support checks across `detect.py` and `val.py` scripts.
- Made minor non-functional changes to the Jupyter notebook tutorial.

### 🎯 Purpose & Impact
- **Purpose**: To extend FP16 support to more backends, improving performance and decreasing memory consumption on supported hardware.
- **Impact**: Users can now leverage the speed and efficiency benefits of FP16 inference when using ONNX on CUDA-capable devices. This makes the models faster and more efficient without compromising accuracy, benefiting those running object detection tasks on GPUs.

### CODE REVIEW

**Comment by MrRace** [comment]
Use the `export.py` to the float16 model,however it can not inference on Onnxruntime. When load the result onnx model, comes errors:
```
  self.session=onnxruntime.InferenceSession(onnx_path, providers=['CUDAExecutionProvider'])
  File "/usr/local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from 
/home/cv_models/politic/models/politic_m_0401_fp16_official.onnx failed:Type Error: 
Type parameter (T) of Optype (ScatterND) bound to different types (tensor(float16) and 
tensor(float) in node (ScatterND_995).
```

**Comment by glenn-jocher** [comment]
@MrRace thanks for the bug report. I see the exported model is using Cast modules to FP32 here, probaby on grid addition to the outputs. It seems the .half() cast is not affecting the grid/anchor_grid.

Screenshot 2022-04-08 at 10 25 42

**Comment by MrRace** [comment]
@glenn-jocher Thanks for your reply, and how should I do to fix it?

**Comment by glenn-jocher** [comment]
@MrRace good news 😃! Your original issue may now be fixed ✅ in PR #7346. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb">Open In Colab</a> <a href="https://www.kaggle.com/models/ultralytics/yolov5">Open In Kaggle</a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5">Docker Pulls</a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Pull request merged**
